### ISSUE TITLE
Options setting for cache location

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#10]
The cache folder is in C:\Users\xxxxx\AppData\Local\BrickStore\cache

Could you please set up an option setting to change it to somewhere else (like in my case I:\BrickStore for example), to avoid polluting C: drive, backup reasons, etc ?

Thank you!

**Comment by paramecie** [comment]
Bumping this also - right now I can't use BrickStore in Prod:

* system drive is backed up, and tens of thousands file increases A LOT the backup time,

* in one day using BrickStore you could make thousands of little files writes on an SSD (pics, pguides), which are slow and stress the SSDs

Really being able to set the cache folder would be nice, especially on Windows and older systems where Hard Links / Junctions aren't a default or easy (and could be dangerous, locking the system drive...)

Personnaly I don't need BrickStore to move the cache, that could be nice, but I can cut and paste the files.
So, just being able to specify the cache drive/folder.

**Comment by chiminirc** [comment]
Thoughts on moving the price guide data into a local database instead of multiple files?
@paramecie , why even back them up? I believe most file based backup applications allow you to exclude directories.
I believe best practices for software is to honor those "appdata" paths.  Also it is very easy for you to make a link for "C:\Users\xxxxx\AppData\Local\BrickStore\cache" to another location in your file system without a rewrite of the app.

Adding this feature would do no harm to the "regular user base" so I see no harm in adding it BTW.  I just feel there are better improvements to the app that could get development time first.

**Comment by paramecie** [comment]
> I believe most file based backup applications allow you to exclude directories.

At the contrary - files backup do this, but *drives* backup so NOT.
I'm talking about saving a disk here.

Best practices Microsft says are theirs; my best practice is "System disk = system files only".
This way you can scratch the system, you won't loose anything from you (or few, like configs...)

Note this feature was present:
* in 2006 and later BrickStore,
* in BrickStock since the beginning.

So now, it's a regression ;-)

![image](https://user-images.githubusercontent.com/32078594/105370624-0cd76780-5c04-11eb-9f2f-8dc67dfabb7b.png)

**Comment by chiminirc** [comment]
My apologies, I assumed if it was "disk block" level backups that an abundance of small files would be irrelevant.
If Robert feels like it is worth the effort, I don't think adding this would mess up the "average" user.
Until then, linking could solve you problem.

**Comment by paramecie** [comment]
Disk block backups may also save the filesystem tree - see the free and wonderful DriveImage XML.
It takes 15 minutes to backuo the blocks, and 15 minutes to save the tree :-(
The pro is that is saves clusters but can extract a single 10 bytes file if you wish.

Linking (Junction) isn't native in Win7.
I'm not fan of Win10 because I don't like a system that installs "Candy Crush", games and meteo widgets I don't care for.

If Robert can simply set up a Register entry, I'm fine to change it myself, no need for any interface.

**Comment by paramecie** [comment]
I re-installed this (wonderful) piece of software (and free) that I already used.
Now BS cache is on my I: drive, I'm happy.

https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html

See further down this hug old style web page, it's ultra powerful... example:
https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html#deloreancopy
I understood how works a Time Machine - which can keep an historical view of all files without making copies...

As nobody asks for this issue, maybe close it?

**Comment by rgriebl** [comment]
I'd rather close this. BrickStore follows platform guidelines on all of Windows, macOS and Linux on where to put cache data (which is %AppData%\Local on Windows). 17 years ago, there was no universal cache location, so I just used something "reasonable" for each platform, but I left the option to change it in case my "reasonable" wasn't that reasonable after all :)

**Comment by paramecie** [comment]
Mmmmh...
I think I've to migrate to TempleOS :-(
https://en.wikipedia.org/wiki/TempleOS
Wish me good luck!
