### ISSUE TITLE
#91 not 100% corrected, but minor

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#100]
#91
While copy/pasting and consolidating you still can get foolish quantities, see below:

![image](https://user-images.githubusercontent.com/32078594/104943201-abba5480-59b5-11eb-96fa-e1a89c03f35a.png)

**Comment by legobanker** [comment]
Are you doing this with your BrickLink store inventory file?  Or is this with a new document?  I want to see if I can recreate this as well.

**Comment by paramecie** [comment]
I use a TESTBRICKSTORE.bsx file for the majority of my tests.
Set a 99 million qty of something, then simply copy/paste this item while accepting consolidation. It goes faster if you copy again each result again ;-)

**Comment by legobanker** [comment]
I created a test file with set # 40358.  BS would only allow me to input 9,999,999 copies of the set.  Then, I opened another doc and did the same thing.  I did a cut and paste (while consolidating) and it gave me the follow totals:

![image](https://user-images.githubusercontent.com/77599267/104948421-46ea0480-598b-11eb-9525-23001cd39aa5.png)

Interesting to see that I have a negative number in the totals, but a positive number on the doc:

![image](https://user-images.githubusercontent.com/77599267/104948561-7f89de00-598b-11eb-8e27-c40bdab400b6.png)

Unless I'm doing it wrong...lol

**Comment by paramecie** [comment]
I redid it - it's 100% reproducible.

![image](https://user-images.githubusercontent.com/32078594/104948967-71a18080-59be-11eb-99ec-2ff7d0113d56.png)

Steps:

1. create a lot with the maximum qty allowed (99+ millions)
2. copy the lot, paste it, it asks "overwrite", say NO
3. accept consolidation AS IS
4. repeat from 2.

It takes approx 10 loops to go wild in the Land of the Negatives Quantities.

**Comment by rgriebl** [comment]
I mean - yes - it's a bug, but why are you doing these crazy tests in the first place??? ;)

**Comment by paramecie** [comment]
But you told me at 100 created issues I'd get gummy bears!!!

**Comment by paramecie** [comment]
Still exists as 308 - I tested. But you could consider it as insignificant ;) and close it?
