### ISSUE TITLE
Picture, no picture... Problem in Document, NOT Info

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#101]
**Case 1:**

In the document an "X" picture showing no picture.
But then, why does it show a picture on the Info Widget?

![image](https://user-images.githubusercontent.com/32078594/104945500-2042c280-59b9-11eb-83f9-74eb3191a09d.png)

**Case 2:**

In the document an empty (white?) picture showing no picture.
But a vivid one in the Info Widget - that maybe you can't resize ?

![image](https://user-images.githubusercontent.com/32078594/104945598-45373580-59b9-11eb-8420-daa8ea15d49e.png)

I'm not 100% sure of the solution, but maybe either:

* simply show "X" in both cases?

* or in above cases:
    - in Case 1, show the Medium Blue picture
    - in Case 2, show "X"?

**Comment by rgriebl** [comment]
The Info widget now shows the "large picture", which isn't tied to any color (or the colored 3D model, if possible). The list shows the "small picture" in the selected color (if available).

Just displaying the same small image from list a second time in the info widget really didn't make sense. It did make sense back in the old days, when the list itself scaled down the small image by another 50%.

At least in case #2 the "X" should be displayed in the list.

**Comment by ZZJHONS** [comment]
@rgriebl could there be an option to not to show the large picture and instead just the correct color picture but enlarged?

**Comment by rgriebl** [comment]
@ZZJHONS My wife got also confused, so I tried your suggestion. I looks like crap though at higher zoom levels ... at least it's color correct crap :)
A new build in `Actions` should be finished in a few minutes. Please have a go and let me know what you are thinking.

**Comment by ZZJHONS** [comment]
Okay... Indeed it feels a bit crappy yeah... but is color correct... Hard one.

What about taking the images from the Lego server with the PCC and if not exists get the BL one?

I think Brickset does that

https://www.lego.com/cdn/product-assets/element.img.lod5photo.192x192/4211636.jpg

**Comment by paramecie** [comment]
> At least in case #2 the "X" should be displayed in the list.

Agreed with this solution, show some consistency, man!
;-)

**Comment by paramecie** [comment]
Errrm even more confusing ?
:-)

![image](https://user-images.githubusercontent.com/32078594/104970987-952fef80-59ed-11eb-87d4-985c9fba2f6e.png)

**Comment by paramecie** [comment]
Ahhh I realize you (both?) misunderstood.

I understand the Info Widget list, and yes it's obvious.

The problem is the document's pictures and some "X" or white pictures, and not what is displayed in Info which is very fine (to me).

**Comment by rgriebl** [comment]
Please try out the new build that's cooking right now -- you'll be amazed with the 2D picture quality.
And try out my favorite new feature: seamless zoom with Ctrl+Mousewheel in the add-item and import-item dialogs.

**Comment by ZZJHONS** [comment]
@rgriebl I would like to try it, but the build failed :(

**Comment by rgriebl** [comment]
Qt's download servers are down at the moment. Mac and Windows will have to wait - the only thing building right now is Linux.

**Comment by rgriebl** [comment]
Our cloud provider managed to completely trash his storage system, so I had to switch to a download mirror for the time being. Build is ready for testing now.

**Comment by paramecie** [comment]
Everything's fine now!

![image](https://user-images.githubusercontent.com/32078594/105106218-ed322900-5ab5-11eb-8be0-9bfc74bad28b.png)

**Comment by paramecie** [comment]
Ah no - little correction please?

Because if a (volontarily) stupid color, the "Please wait... updating"... stays forever.

![image](https://user-images.githubusercontent.com/32078594/105108426-7c414000-5aba-11eb-95f9-d51007c9e347.png)

**Comment by paramecie** [comment]
Fixed in Build 211!
Thank you - and I guess it can be closed?
