### ISSUE TITLE
Minor, please add Filter in menu

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#103]
Please add a Filter menu option, showing the shortcut.
When clicked it'll simply set the focus to the filter field (top right of screen).

![image](https://user-images.githubusercontent.com/32078594/104971311-b218f280-59ee-11eb-8ed2-f98bc65d6f53.png)

**Comment by paramecie** [comment]
While on minor things...

https://github.com/rgriebl/brickstore/issues/92#issuecomment-762508972
https://github.com/rgriebl/brickstore/issues/99#issuecomment-762510858

**Comment by rgriebl** [comment]
why? to document the shortcut?
I'd rather add the "Ctrl+f" to the tooltip, like it is for all the other actions

**Comment by paramecie** [comment]
Yes, to document, and to have all actions listed in the menus, which seems a standard to me?

Anyway, a tooltip is fine - any way, but as no one read any doc, it should be shown somewhere ;-)
