### ISSUE TITLE
Retain field doesn't show anything

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#104]
Click on Retain field doesn't show any difference, and the associated menu either.

However the menu seems to know the status.
See here, the Menu says "[x] Yes":

![image](https://user-images.githubusercontent.com/32078594/104974690-0aed8880-59f9-11eb-8949-78c97d1db91e.png)

**Comment by legobanker** [comment]
Just noticed this as well...although I rarely use it.
