### ISSUE TITLE
Build 206: spacebar anywhere is a future feature?

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#105]
Nice but transparent ;-)

![image](https://user-images.githubusercontent.com/32078594/104974989-bd255000-59f9-11eb-87b5-eacde4097dd2.png)

If it'll exist, please remember to describe it in menu also:

![image](https://user-images.githubusercontent.com/32078594/104975162-32912080-59fa-11eb-9e50-b806e6454913.png)

**Comment by rgriebl** [comment]
Congratulations. You're probably the first one to notice! :)

This has been in there for 5 years now and it is actually my first experiment with OpenGL rendering of LDraw parts. I'm not really happy with it though, so I never publicly talked about it. Besides: with the new 2D + 3D Info widget, the 3D overlay is somewhat obsolete

**Comment by paramecie** [comment]
> Congratulations. You're probably the first one to notice! :)

Thank you :-)
But maybe then simply deactivate this shortcut?
