### ISSUE TITLE
BrickStore closes itself after clicking OK in Configure...

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#109]
As the title says.

It happened with the last release too, noticed before updating.

Sometimes Windows cursor changes to circle and the BS closes itself.

**Comment by ZZJHONS** [comment]
If I change the Language to french it closes itself but when restarting, BS is in French now.

I changed it to English and it changed without closing itself. So I closed and tried again the same steps.. And this time it didn't work, it closed itself again...

**Comment by rgriebl** [comment]
I can't reproduce this here. Maybe some old setting is interfering somehow? Could you please run `regedit`, then go to the `Computer\HKEY_CURRENT_USER\SOFTWARE\Brickstore` key, right-click and select `Export` and save that .reg file.
Please remove your BL credentials using a text editor first and then attach it here or send it directly to me.

**Comment by paramecie** [comment]
I agree with the proposal - BrickStore is better in French, please enforce this for everyone :O)

I'll test this later on...

**Comment by SteveTheBrick** [comment]
Happening here as well.

I uninstalled Brickstore, deleted the registry key,deleted the appdata folder and re-installed - still crashing.

**Comment by paramecie** [comment]
For now can't make this happen, I'm trying...

Maybe something in the LDraw detection as Robert changed this - and which might be triggered on "OK"?
Maybe you both don't have LDraw installed? Here it is installed and working.

**Comment by paramecie** [comment]
You're all on Build 220 or 2021.1.15?

**Comment by rgriebl** [comment]
At least I can trigger this crash on my wife's PC now. Debugging...

**Comment by paramecie** [comment]
How? No way here. Stable as a rock.

**Comment by ZZJHONS** [comment]
Happens to other user: https://www.bricklink.com/message.asp?ID=1247210

This happened with the dev builds after the image change too, Where I asked if the buttons should be working in issue 
https://github.com/rgriebl/brickstore/issues/101#issuecomment-762500079

I know a couple of versions earlier it didn't crashed when changing settings.

I went on and installed LDraw with the full list in the installer options. BS would not detect the folder, but if I selected Documents/LDraw folder manually it showed a green checkmark. But pressing Ok would crash BS and when reopening it the folder says again Auto detect, but it shows the error X.

Build 220 now yes.

Reg:
`Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\BrickStore]

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore]

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\BrickLink]
"LastDBUpdate"=dword:5ff89eed

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\BrickLink\Login]
"Password"=
"Username"=

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\BrickLink\UpdateInterval]
"Pictures"=dword:01da9c00
"PriceGuides"=dword:0007e900

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\ColumnLayouts]

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\ColumnLayouts\{24b23c54-41fa-47c5-ba31-7dd07684a21e}]
"Layout"=hex:40,00,42,00,79,00,74,00,65,00,41,00,72,00,72,00,61,00,79,00,28,00,\
  3b,00,28,00,59,00,31,00,00,00,00,00,00,00,02,00,00,00,00,00,00,00,20,00,00,\
  00,00,00,00,00,0d,00,01,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,01,00,00,00,00,00,00,00,00,\
  00,4d,00,00,00,00,00,00,00,07,00,00,00,00,00,00,00,00,00,72,00,00,00,00,00,\
  00,00,08,00,00,00,00,00,00,00,00,00,e1,00,00,00,00,00,00,00,09,00,00,00,00,\
  00,00,00,00,00,3a,00,00,00,00,00,00,00,03,00,00,00,00,00,00,00,00,00,71,00,\
  00,00,00,00,00,00,0a,00,00,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,06,\
  00,00,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,0d,00,00,00,00,00,00,00,\
  00,00,43,00,00,00,00,00,00,00,0e,00,00,00,00,00,00,00,00,00,3a,00,00,00,00,\
  00,00,00,0f,00,01,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,10,00,01,00,\
  00,00,00,00,00,00,40,00,00,00,00,00,00,00,13,00,00,00,00,00,00,00,01,00,b6,\
  00,00,00,00,00,00,00,02,00,00,00,00,00,00,00,00,00,5c,00,00,00,00,00,00,00,\
  11,00,00,00,00,00,00,00,00,00,5c,00,00,00,00,00,00,00,12,00,00,00,00,00,00,\
  00,00,00,3a,00,00,00,00,00,00,00,14,00,00,00,00,00,00,00,00,00,40,00,00,00,\
  00,00,00,00,15,00,00,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,16,00,00,\
  00,00,00,00,00,00,00,40,00,00,00,00,00,00,00,18,00,00,00,00,00,00,00,00,00,\
  3a,00,00,00,00,00,00,00,19,00,00,00,00,00,00,00,00,00,40,00,00,00,00,00,00,\
  00,1a,00,00,00,00,00,00,00,00,00,40,00,00,00,00,00,00,00,1b,00,01,00,00,00,\
  00,00,00,00,40,00,00,00,00,00,00,00,1c,00,01,00,00,00,00,00,00,00,40,00,00,\
  00,00,00,00,00,1d,00,01,00,00,00,00,00,00,00,40,00,00,00,00,00,00,00,1e,00,\
  01,00,00,00,00,00,00,00,4e,00,00,00,00,00,00,00,17,00,00,00,00,00,00,00,00,\
  00,3a,00,00,00,00,00,00,00,1f,00,01,00,00,00,00,00,00,00,3a,00,00,00,00,00,\
  00,00,04,00,00,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,05,00,00,00,00,\
  00,00,00,00,00,3a,00,00,00,00,00,00,00,0b,00,00,00,00,00,00,00,00,00,43,00,\
  00,00,00,00,00,00,0c,00,00,00,29,00
"Name"="BS Layout 2"

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\ColumnLayouts\{56e64be8-3838-424e-b178-01de30926729}]
"Layout"=hex:40,00,42,00,79,00,74,00,65,00,41,00,72,00,72,00,61,00,79,00,28,00,\
  3b,00,28,00,59,00,31,00,00,00,00,00,00,00,02,00,00,00,00,00,00,00,20,00,00,\
  00,00,00,00,00,06,00,01,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,01,00,00,00,00,00,00,00,00,\
  00,4e,00,00,00,00,00,00,00,07,00,00,00,00,00,00,00,00,00,76,00,00,00,00,00,\
  00,00,08,00,00,00,00,00,00,00,01,00,0d,00,00,00,00,00,00,00,10,00,00,00,00,\
  00,00,00,00,00,3a,00,00,00,00,00,00,00,03,00,00,00,00,00,00,00,00,00,71,00,\
  00,00,00,00,00,00,09,00,00,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,06,\
  00,00,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,0c,00,00,00,00,00,00,00,\
  00,00,43,00,00,00,00,00,00,00,0d,00,00,00,00,00,00,00,00,00,3a,00,00,00,00,\
  00,00,00,0e,00,01,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,0f,00,01,00,\
  00,00,00,00,00,00,75,00,00,00,00,00,00,00,11,00,00,00,00,00,00,00,01,00,86,\
  00,00,00,00,00,00,00,02,00,00,00,00,00,00,00,00,00,5c,00,00,00,00,00,00,00,\
  13,00,00,00,00,00,00,00,00,00,5c,00,00,00,00,00,00,00,14,00,00,00,00,00,00,\
  00,00,00,3a,00,00,00,00,00,00,00,15,00,00,00,00,00,00,00,00,00,40,00,00,00,\
  00,00,00,00,16,00,00,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,17,00,00,\
  00,00,00,00,00,00,00,40,00,00,00,00,00,00,00,18,00,00,00,00,00,00,00,00,00,\
  3a,00,00,00,00,00,00,00,19,00,00,00,00,00,00,00,00,00,40,00,00,00,00,00,00,\
  00,1a,00,00,00,00,00,00,00,00,00,40,00,00,00,00,00,00,00,1b,00,01,00,00,00,\
  00,00,00,00,40,00,00,00,00,00,00,00,1c,00,01,00,00,00,00,00,00,00,40,00,00,\
  00,00,00,00,00,1d,00,01,00,00,00,00,00,00,00,40,00,00,00,00,00,00,00,1e,00,\
  01,00,00,00,00,00,00,00,4e,00,00,00,00,00,00,00,12,00,00,00,00,00,00,00,00,\
  00,3a,00,00,00,00,00,00,00,1f,00,01,00,00,00,00,00,00,00,3a,00,00,00,00,00,\
  00,00,04,00,00,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,05,00,00,00,00,\
  00,00,00,00,00,3a,00,00,00,00,00,00,00,0a,00,00,00,00,00,00,00,00,00,3a,00,\
  00,00,00,00,00,00,0b,00,00,00,29,00
"Order"=dword:00000002
"Name"="Working 1"

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\ColumnLayouts\{740f81a2-28e8-4e98-a106-80d3327c6cbf}]
"Layout"=hex:40,00,42,00,79,00,74,00,65,00,41,00,72,00,72,00,61,00,79,00,28,00,\
  3b,00,28,00,59,00,31,00,00,00,00,00,00,00,02,00,00,00,00,00,00,00,20,00,00,\
  00,00,00,00,00,0d,00,01,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,01,00,00,00,00,00,00,00,00,\
  00,4d,00,00,00,00,00,00,00,07,00,00,00,00,00,00,00,00,00,72,00,00,00,00,00,\
  00,00,08,00,00,00,00,00,00,00,00,00,e1,00,00,00,00,00,00,00,09,00,00,00,00,\
  00,00,00,00,00,3a,00,00,00,00,00,00,00,03,00,00,00,00,00,00,00,00,00,71,00,\
  00,00,00,00,00,00,0a,00,00,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,06,\
  00,00,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,0d,00,00,00,00,00,00,00,\
  00,00,43,00,00,00,00,00,00,00,0e,00,00,00,00,00,00,00,00,00,3a,00,00,00,00,\
  00,00,00,0f,00,01,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,10,00,01,00,\
  00,00,00,00,00,00,40,00,00,00,00,00,00,00,14,00,00,00,00,00,00,00,01,00,b6,\
  00,00,00,00,00,00,00,02,00,00,00,00,00,00,00,00,00,5c,00,00,00,00,00,00,00,\
  11,00,00,00,00,00,00,00,00,00,5c,00,00,00,00,00,00,00,12,00,00,00,00,00,00,\
  00,00,00,3a,00,00,00,00,00,00,00,15,00,00,00,00,00,00,00,00,00,40,00,00,00,\
  00,00,00,00,16,00,00,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,17,00,00,\
  00,00,00,00,00,00,00,40,00,00,00,00,00,00,00,18,00,00,00,00,00,00,00,00,00,\
  3a,00,00,00,00,00,00,00,19,00,00,00,00,00,00,00,00,00,40,00,00,00,00,00,00,\
  00,1a,00,00,00,00,00,00,00,00,00,40,00,00,00,00,00,00,00,1b,00,01,00,00,00,\
  00,00,00,00,40,00,00,00,00,00,00,00,1c,00,01,00,00,00,00,00,00,00,40,00,00,\
  00,00,00,00,00,1d,00,01,00,00,00,00,00,00,00,40,00,00,00,00,00,00,00,1e,00,\
  01,00,00,00,00,00,00,00,4e,00,00,00,00,00,00,00,13,00,00,00,00,00,00,00,00,\
  00,3a,00,00,00,00,00,00,00,1f,00,01,00,00,00,00,00,00,00,3a,00,00,00,00,00,\
  00,00,04,00,00,00,00,00,00,00,00,00,3a,00,00,00,00,00,00,00,05,00,00,00,00,\
  00,00,00,00,00,3a,00,00,00,00,00,00,00,0b,00,00,00,00,00,00,00,00,00,3a,00,\
  00,00,00,00,00,00,0c,00,00,00,29,00
"Name"="BrickStore Layout 1"

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\Currency]
@="USD"

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\Defaults]

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\Defaults\AddItems]
"Condition"="new"
"ItemType"=dword:00000050

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\Defaults\ImportInventory]
"ItemType"=dword:00000053

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\Defaults\SetToPG]
"Price"=dword:00000001
"Time"=dword:00000000

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\Files]
"Recent"=hex(7):43,00,3a,00,5c,00,55,00,73,00,65,00,72,00,73,00,5c,00,7a,00,7a,\
  00,6a,00,68,00,6f,00,5c,00,47,00,6f,00,6f,00,67,00,6c,00,65,00,20,00,44,00,\
  72,00,69,00,76,00,65,00,5c,00,53,00,74,00,65,00,6c,00,6c,00,61,00,72,00,20,\
  00,42,00,72,00,69,00,63,00,6b,00,73,00,5c,00,42,00,72,00,69,00,63,00,6b,00,\
  73,00,79,00,6e,00,63,00,5c,00,6d,00,65,00,72,00,67,00,65,00,5f,00,74,00,65,\
  00,73,00,74,00,2e,00,62,00,73,00,78,00,00,00,43,00,3a,00,5c,00,55,00,73,00,\
  65,00,72,00,73,00,5c,00,7a,00,7a,00,6a,00,68,00,6f,00,5c,00,44,00,6f,00,77,\
  00,6e,00,6c,00,6f,00,61,00,64,00,73,00,5c,00,32,00,30,00,32,00,31,00,2e,00,\
  62,00,73,00,78,00,00,00,43,00,3a,00,5c,00,55,00,73,00,65,00,72,00,73,00,5c,\
  00,7a,00,7a,00,6a,00,68,00,6f,00,5c,00,47,00,6f,00,6f,00,67,00,6c,00,65,00,\
  20,00,44,00,72,00,69,00,76,00,65,00,5c,00,53,00,74,00,65,00,6c,00,6c,00,61,\
  00,72,00,20,00,42,00,72,00,69,00,63,00,6b,00,73,00,5c,00,42,00,72,00,69,00,\
  63,00,6b,00,53,00,74,00,6f,00,72,00,65,00,5c,00,53,00,65,00,76,00,65,00,5f,\
  00,50,00,61,00,42,00,2e,00,62,00,73,00,78,00,00,00,43,00,3a,00,5c,00,55,00,\
  73,00,65,00,72,00,73,00,5c,00,7a,00,7a,00,6a,00,68,00,6f,00,5c,00,47,00,6f,\
  00,6f,00,67,00,6c,00,65,00,20,00,44,00,72,00,69,00,76,00,65,00,5c,00,53,00,\
  74,00,65,00,6c,00,6c,00,61,00,72,00,20,00,42,00,72,00,69,00,63,00,6b,00,73,\
  00,5c,00,42,00,72,00,69,00,63,00,6b,00,73,00,79,00,6e,00,63,00,5c,00,6d,00,\
  65,00,72,00,67,00,65,00,32,00,2e,00,62,00,73,00,78,00,00,00,43,00,3a,00,5c,\
  00,55,00,73,00,65,00,72,00,73,00,5c,00,7a,00,7a,00,6a,00,68,00,6f,00,5c,00,\
  44,00,6f,00,77,00,6e,00,6c,00,6f,00,61,00,64,00,73,00,5c,00,74,00,65,00,73,\
  00,74,00,2e,00,62,00,73,00,78,00,00,00,43,00,3a,00,5c,00,55,00,73,00,65,00,\
  72,00,73,00,5c,00,7a,00,7a,00,6a,00,68,00,6f,00,5c,00,47,00,6f,00,6f,00,67,\
  00,6c,00,65,00,20,00,44,00,72,00,69,00,76,00,65,00,5c,00,53,00,74,00,65,00,\
  6c,00,6c,00,61,00,72,00,20,00,42,00,72,00,69,00,63,00,6b,00,73,00,5c,00,42,\
  00,72,00,69,00,63,00,6b,00,73,00,79,00,6e,00,63,00,5c,00,6d,00,65,00,72,00,\
  67,00,65,00,2e,00,62,00,73,00,78,00,00,00,43,00,3a,00,5c,00,55,00,73,00,65,\
  00,72,00,73,00,5c,00,7a,00,7a,00,6a,00,68,00,6f,00,5c,00,44,00,6f,00,77,00,\
  6e,00,6c,00,6f,00,61,00,64,00,73,00,5c,00,64,00,6f,00,67,00,2e,00,62,00,73,\
  00,78,00,00,00,43,00,3a,00,5c,00,55,00,73,00,65,00,72,00,73,00,5c,00,7a,00,\
  7a,00,6a,00,68,00,6f,00,5c,00,47,00,6f,00,6f,00,67,00,6c,00,65,00,20,00,44,\
  00,72,00,69,00,76,00,65,00,5c,00,53,00,74,00,65,00,6c,00,6c,00,61,00,72,00,\
  20,00,42,00,72,00,69,00,63,00,6b,00,73,00,5c,00,42,00,72,00,69,00,63,00,6b,\
  00,73,00,79,00,6e,00,63,00,5c,00,73,00,65,00,74,00,73,00,2e,00,62,00,73,00,\
  78,00,00,00,43,00,3a,00,5c,00,55,00,73,00,65,00,72,00,73,00,5c,00,7a,00,7a,\
  00,6a,00,68,00,6f,00,5c,00,47,00,6f,00,6f,00,67,00,6c,00,65,00,20,00,44,00,\
  72,00,69,00,76,00,65,00,5c,00,53,00,74,00,65,00,6c,00,6c,00,61,00,72,00,20,\
  00,42,00,72,00,69,00,63,00,6b,00,73,00,5c,00,42,00,72,00,69,00,63,00,6b,00,\
  73,00,79,00,6e,00,63,00,5c,00,73,00,70,00,6c,00,69,00,74,00,2e,00,62,00,73,\
  00,78,00,00,00,00,00

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\General]
"ConfigVersion"=dword:07e50100
"CloseEmptyDocs"="false"
"DocDir"="C:/Users/zzjho/Documents"
"Locale"="en"
"ImportedV12xSettings"=dword:00000001
"SimpleMode"="false"

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\General\Export]
"OpenBrowser"="true"

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\General\Money]
"Localized"="true"

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\Interface]
"FontSizePercent"=dword:00000064
"ItemImageSizePercent"=dword:00000050
"IconSize"=dword:00000000

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\ItemView]

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\ItemView\List]
"ColumnOrder"="0,6,7,13,2,8,5,11,12,18,19,17,1,14,15,20,21,22,23,24,25,26,27,28,29,16,30,3,4,9,10"
"ColumnWidths"="47,56,96,525,29,132,42,70,81,0,0,81,305,89,89,63,61,63,61,63,61,0,0,0,0,82,0,40,40,61,61"
"ColumnWidthsHidden"="0,0,0,0,0,0,0,0,0,40,45,0,0,0,0,0,0,0,0,0,0,61,61,61,61,0,40,40,40,61,61"
"SortColumn"="5"
"SortDirection"="D"

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\MainWindow]

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\MainWindow\AddItemDialog]
"Geometry"=hex:40,00,42,00,79,00,74,00,65,00,41,00,72,00,72,00,61,00,79,00,28,\
  00,01,00,d9,00,d0,00,cb,00,00,00,03,00,00,00,00,00,00,00,00,00,02,00,6c,00,\
  00,00,00,00,01,00,1e,00,00,00,00,00,09,00,63,00,00,00,00,00,05,00,e6,00,00,\
  00,00,00,02,00,6c,00,00,00,00,00,01,00,1e,00,00,00,00,00,09,00,63,00,00,00,\
  00,00,05,00,e6,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,0a,00,b0,\
  00,00,00,00,00,02,00,6c,00,00,00,00,00,01,00,1e,00,00,00,00,00,09,00,63,00,\
  00,00,00,00,05,00,e6,00,29,00
"VSplitter"=hex:40,00,42,00,79,00,74,00,65,00,41,00,72,00,72,00,61,00,79,00,28,\
  00,00,00,00,00,00,00,ff,00,00,00,00,00,00,00,01,00,00,00,00,00,00,00,02,00,\
  00,00,00,00,01,00,a2,00,00,00,00,00,00,00,f2,00,00,00,ff,00,ff,00,ff,00,ff,\
  00,01,00,00,00,00,00,00,00,02,00,00,00,29,00
"HSplitter"=hex:40,00,42,00,79,00,74,00,65,00,41,00,72,00,72,00,61,00,79,00,28,\
  00,00,00,00,00,00,00,00,00,ff,00,00,00,00,00,00,00,01,00,00,00,00,00,00,00,\
  04,00,00,00,00,00,01,00,0c,00,00,00,00,00,01,00,40,00,00,00,00,00,02,00,60,\
  00,00,00,00,00,02,00,86,00,00,00,ff,00,ff,00,ff,00,ff,00,01,00,00,00,00,00,\
  00,00,01,00,00,00,29,00
"ItemZoom"="0.5"

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\MainWindow\ImportInventoryDialog]
"Geometry"=hex:40,00,42,00,79,00,74,00,65,00,41,00,72,00,72,00,61,00,79,00,28,\
  00,01,00,d9,00,d0,00,cb,00,00,00,03,00,00,00,00,00,00,00,00,00,02,00,36,00,\
  00,00,00,00,02,00,5c,00,00,00,00,00,08,00,c7,00,00,00,00,00,04,00,c3,00,00,\
  00,00,00,02,00,37,00,00,00,00,00,02,00,89,00,00,00,00,00,08,00,c6,00,00,00,\
  00,00,04,00,c2,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,0a,00,b0,\
  00,00,00,00,00,02,00,37,00,00,00,00,00,02,00,89,00,00,00,00,00,08,00,c6,00,\
  00,00,00,00,04,00,c2,00,29,00

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\MainWindow\Layout]
"State"=hex:40,00,42,00,79,00,74,00,65,00,41,00,72,00,72,00,61,00,79,00,28,00,\
  00,00,00,00,00,00,ff,00,00,00,00,00,00,00,01,00,fd,00,00,00,00,00,00,00,02,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,01,00,6b,00,00,00,00,00,06,00,8d,00,\
  fc,00,02,00,00,00,00,00,00,00,03,00,fb,00,00,00,00,00,00,00,1a,00,00,00,44,\
  00,00,00,6f,00,00,00,63,00,00,00,6b,00,00,00,2d,00,00,00,54,00,00,00,61,00,\
  00,00,73,00,00,00,6b,00,00,00,49,00,00,00,6e,00,00,00,66,00,00,00,6f,00,01,\
  00,00,00,00,00,00,00,4d,00,00,00,00,00,01,00,14,00,00,00,00,00,00,00,c9,00,\
  00,00,ff,00,ff,00,ff,00,fb,00,00,00,00,00,00,00,26,00,00,00,44,00,00,00,6f,\
  00,00,00,63,00,00,00,6b,00,00,00,2d,00,00,00,54,00,00,00,61,00,00,00,73,00,\
  00,00,6b,00,00,00,50,00,00,00,72,00,00,00,69,00,00,00,63,00,00,00,65,00,00,\
  00,47,00,00,00,75,00,00,00,69,00,00,00,64,00,00,00,65,00,01,00,00,00,00,00,\
  01,00,67,00,00,00,00,00,01,00,b1,00,00,00,00,00,01,00,b1,00,00,00,00,00,01,\
  00,b1,00,fb,00,00,00,00,00,00,00,20,00,00,00,44,00,00,00,6f,00,00,00,63,00,\
  00,00,6b,00,00,00,2d,00,00,00,54,00,00,00,61,00,00,00,73,00,00,00,6b,00,00,\
  00,41,00,00,00,70,00,00,00,70,00,00,00,65,00,00,00,61,00,00,00,72,00,00,00,\
  73,00,01,00,00,00,00,00,03,00,1e,00,00,00,00,00,03,00,bc,00,00,00,00,00,01,\
  00,16,00,00,00,ff,00,ff,00,ff,00,00,00,00,00,00,00,03,00,00,00,00,00,09,00,\
  0a,00,00,00,00,00,00,00,dc,00,fc,00,01,00,00,00,00,00,00,00,01,00,fb,00,00,\
  00,00,00,00,00,1c,00,00,00,44,00,00,00,6f,00,00,00,63,00,00,00,6b,00,00,00,\
  2d,00,00,00,4c,00,00,00,6f,00,00,00,67,00,00,00,57,00,00,00,69,00,00,00,64,\
  00,00,00,67,00,00,00,65,00,00,00,74,00,00,00,00,00,00,00,01,00,46,00,00,00,\
  00,00,09,00,0a,00,00,00,00,00,00,00,6b,00,00,00,ff,00,ff,00,ff,00,00,00,00,\
  00,08,00,df,00,00,00,00,00,06,00,8d,00,00,00,00,00,00,00,01,00,00,00,00,00,\
  00,00,02,00,00,00,00,00,00,00,01,00,00,00,00,00,00,00,02,00,fc,00,00,00,00,\
  00,00,00,01,00,00,00,00,00,00,00,02,00,00,00,00,00,00,00,01,00,00,00,00,00,\
  00,00,0e,00,00,00,74,00,00,00,6f,00,00,00,6f,00,00,00,6c,00,00,00,62,00,00,\
  00,61,00,00,00,72,00,01,00,00,00,00,00,00,00,00,00,ff,00,ff,00,ff,00,ff,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,29,00
"Geometry"=hex:40,00,42,00,79,00,74,00,65,00,41,00,72,00,72,00,61,00,79,00,28,\
  00,01,00,d9,00,d0,00,cb,00,00,00,03,00,00,00,00,00,00,00,00,00,00,00,60,00,\
  00,00,00,00,00,00,22,00,00,00,00,00,0a,00,af,00,00,00,00,00,07,00,1f,00,00,\
  00,00,00,01,00,11,00,00,00,00,00,00,00,b6,00,00,00,00,00,09,00,9c,00,00,00,\
  00,00,06,00,f7,00,00,00,00,00,00,00,00,00,02,00,00,00,00,00,00,00,0a,00,b0,\
  00,00,00,00,00,00,00,60,00,00,00,00,00,00,00,22,00,00,00,00,00,0a,00,af,00,\
  00,00,00,00,07,00,1f,00,29,00

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\MainWindow\Statusbar]
"Visible"="true"

[HKEY_CURRENT_USER\SOFTWARE\BrickStore\BrickStore\Rates]
"LastUpdate"=hex:40,00,44,00,61,00,74,00,65,00,54,00,69,00,6d,00,65,00,28,00,\
  00,00,00,00,00,00,10,00,00,00,00,00,00,00,00,00,00,00,00,00,25,00,86,00,64,\
  00,04,00,8b,00,a4,00,3f,00,00,00,29,00
"Normal"="AUD|1.28598,BGN|1.60865,BRL|5.27003,CAD|1.26213,CHF|0.886083,CNY|6.46093,CZK|21.4624,DKK|6.11902,EUR|0.822504,GBP|0.728944,HKD|7.75169,HRK|6.22224,HUF|293.946,IDR|13990,ILS|3.27151,INR|72.9742,ISK|128.969,JPY|103.405,KRW|1099.78,MXN|19.612,MYR|4.03002,NOK|8.43173,NZD|1.38617,PHP|48.0392,PLN|3.72463,RON|4.00888,RUB|73.7267,SEK|8.29289,SGD|1.32267,THB|29.9301,TRY|7.36593,USD|1,ZAR|14.8041"
"Custom"=""

`

**Comment by paramecie** [comment]
Still nothing here.
Do you have the time to see some extra added line in the Error log?

Right now mine contains:

![image](https://user-images.githubusercontent.com/32078594/105424721-2f8b6f80-5c48-11eb-914c-f93a4dc1510a.png)

**Comment by ZZJHONS** [comment]
<img width="581" alt="Captura de pantalla 2021-01-22 002941" src="https://user-images.githubusercontent.com/1063368/105425070-f273ad00-5c48-11eb-80a1-f3a745e75cf3.png">

Nothing, I just opened options, click ok and it crashed without printing anything there

**Comment by rgriebl** [comment]
OMG ... found it. It crashes in a piece of code that does nothing, but that I forgot to delete.
It will always crash if it couldn't auto-detect a LDraw installation at startup. I'll push start a dev build in a minute and if this works, I'll do a .6 release

**Comment by rgriebl** [comment]
Would be nice if someone could verify whether https://github.com/rgriebl/brickstore/actions/runs/502444463 works (when it has finished building)

**Comment by paramecie** [comment]
> It will always crash if it couldn't auto-detect a LDraw installation at startup

https://github.com/rgriebl/brickstore/issues/109#issuecomment-764999128

I guessed it!
Now you've to send me extra gummy bears.

**Comment by ZZJHONS** [comment]
@rgriebl Working! 

BTW it didn't auto detect my my LDraw installation (I didn't change any default) but in BS setting selecting the correct path manually showed the check mark, I press OK and BS tells me I needed to restart, did it and now 3D view is working too!

**Comment by SteveTheBrick** [comment]
Working here as well.

LDraw was not auto-detected but now working with manual path entry.

**Comment by rgriebl** [comment]
2021.1.6 is released now with this fix
