### ISSUE TITLE
Change / modernize then program Icon?

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#11]
I know it's initially your icon, but as BrickStock used the same, now it may be a bit confusing, especially for those who'll have both BrickStore and BrickStock for some time ;-)

**Comment by chiminirc** [comment]
Agreed.  As a transition from brickstock to brickstore, it would be nice if the icon was updated so I can tell which is which is my tasktray.

**Comment by paramecie** [comment]
My Win 7 top menu, yes, still :-)

![image](https://user-images.githubusercontent.com/32078594/103594931-60566f80-4efa-11eb-94f7-0430a0fb2196.png)

**Comment by paramecie** [comment]
Don't worry about your Orange. We do remember who did this application ;-) The Maersk Blue one is VERY classy!

**Comment by chiminirc** [comment]
Honestly, just a slightly different looking icon would be sufficient if you want to keep it orange :)

**Comment by paramecie** [comment]
PS: please put a Maersk Blue Helmet there also:

![image](https://user-images.githubusercontent.com/32078594/103836592-d63d1100-5089-11eb-8835-d2857b921bcd.png)

;-)
