### ISSUE TITLE
Consolidate should consolidate ONCE or VERY differently

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#112]
Create a list with 3 identical items.
**Put Qty as 1, 2, 3 so you can recognize the lot with its quantity.**
Select them (or all), click Consolidate, always click on "No".

It asks to consolidate 3 times:

![image](https://user-images.githubusercontent.com/32078594/105430822-b8100d00-5c54-11eb-95c7-61da4baf0517.png)

![image](https://user-images.githubusercontent.com/32078594/105430847-c4946580-5c54-11eb-9255-99d564acf0be.png)

![image](https://user-images.githubusercontent.com/32078594/105430864-cb22dd00-5c54-11eb-9069-12ad6112a130.png)

But -

1) It asks to consolidate item 2 with 1

2) It then asks to consolidate item 1 with 2 (**but we already replied to this**)

3) It then asks consolidate item 1 with 3 (**wrong order, it should be 3 then 1**).

4) **Right now, it never propose to consolidate 2 with 3: bug.**

There are 4 solutions to this nightmare :-)

1) If you consolidate a group of identical items, it should ask you 1 time ONLY, even if there are 27 identical lots.
Any "No" will finish this group consolidation.

2) If you consider the different couples 2 by 2, then it's FAR more you've to propose.
With 5 items, that makes 12 different couples:
1 with 2, 3, 4, 5, then 2 with 3,4,5, then 3 with 4, 5, then 4 with 5 = 12 couples, 12 questions.

3) You can consider every couple from top to bottom of the list, so for 3 identical items you should propose 1 vs 2 and 2 vs 3.
So that's only 2 couples, 2 questions, not 3.

4) Display all the identical items and ask the question once: we're supposed to select which one is "the master" ?
So here, show 3, but ask 1 question.
**After having thought at this, I guess this would be the perfect and easiest solution.**

This is about 1 group of identical items.
Of course, there could be 10 groups of 2 or 3 identical items...
Which is why I now recommend the 4) solution above.

**Right now more than 2 identical lots is actually buggy.** Sorry.

**Comment by paramecie** [comment]
And to remove a bit of confusion, the proper index should be shown (same as in the Document):

Here 5 and 10, not 1 and 2:

![image](https://user-images.githubusercontent.com/32078594/105431863-c6f7bf00-5c56-11eb-8549-4effccf2fca3.png)

**Comment by rgriebl** [comment]
Just checked the old code in BrickStore 1 / BrickStock ... it has always been this way, so let's just call it "tradition" :)

Seriously ... that merging code is VERY old and VERY ugly. Guess I'll have to re-implement that part...

**Comment by paramecie** [comment]
You didn't know what to do during lock down?
;-)
Sincerely sorry.

And yes, I guess it worked like this; I did noticed sometimes some strange prices and always thought I had selection the wrong choice... Which is also possible, but I'm sure it was rarely the case; it was more probably the Traditional Consolidation :)

**Comment by rgriebl** [comment]
Please give the current dev build a try. Please be aware that this one is REALLY a dev build and may crash :)

**Comment by paramecie** [comment]
Wow!

Try Build 228.

Not yet the consolidation but I notice:

* multiple identical items in the same window, schön !
* order seems respected, perfekt !
* much wider window, wunderbach !!!
* ESC key works, gut !

But unfortunately :-( the window is opened wherever it wants, somewhere on the right, going outside the app (and my screen)

![image](https://user-images.githubusercontent.com/32078594/105650942-bc873080-5eb5-11eb-8738-7666e92672d6.png)

**Comment by paramecie** [comment]
Little UNDO bug.

I consolidate those 3:

![image](https://user-images.githubusercontent.com/32078594/105651126-34edf180-5eb6-11eb-844e-18b4acb5a43f.png)

I choose the 2nd item (lot) - this is correct:

![image](https://user-images.githubusercontent.com/32078594/105651172-58b13780-5eb6-11eb-992b-4a51bd86836a.png)

But if I CTRL+Z (undo), the first item goes to the right place, but the 3rd one is rejected at the end of document:

![image](https://user-images.githubusercontent.com/32078594/105651217-88603f80-5eb6-11eb-83ec-4eb3151c52c8.png)

**Comment by paramecie** [comment]
Apart this annoyance, this is GREAT how it works - sooooooo easy!

Ah and a note, those "to all" buttons doesn't mean anything, do they?

![image](https://user-images.githubusercontent.com/32078594/105651339-e3923200-5eb6-11eb-8be5-bcf38cc6402f.png)

In this case, simply put Yes/Cancel buttons?

**Comment by rgriebl** [comment]
1) The little Undo bug
This is actually correct: I don't re-sort the list dynamically, because you would go nuts otherwise with items jumping around while you edit them. If you have the list sorted by color and you change an item's color, it doesn't move until you re-sort on color. The same thing is happening here. It looks weird, but it is correct (the index numbers match) - it just a bit unexpected on the visual side :)

2) the "to ALL" buttons:
If you consolidate more than 1 type of item in one go, you can select the "to all" option for everything but the last one (obviously). At first, I hid the "for all" buttons on the last one, but then the "Yes" button is suddenly at the same position where the "No" button was before -- that's might dangerous :)
It would however make sense to hide them, if you only consolidate only one type.

**Comment by paramecie** [comment]
The little Undo bug - ohhh I see. And yes it does the same if you delete some random items and undo... No problemo amigo.

The "to ALL" buttons - I really don't agree with this, see next post.

**Comment by paramecie** [comment]
If I do CTRL+A (for ex) and consolidate multi lots of identical items:

![image](https://user-images.githubusercontent.com/32078594/105656624-edba2d80-5ec2-11eb-9bff-bca82377e0f0.png)

There shouldn't be an "to ALL" button, especially for the Yes, because it's almost impossible to guess what happened.

In the above case, I want the 2nd Lot of the 6091, and the 2nd Lot of the 3070b to be "the masters".
There is no "to ALL" possible choice (you propose some choices but none correspond):

![image](https://user-images.githubusercontent.com/32078594/105656816-5bfef000-5ec3-11eb-9e39-81a2fa51f9e3.png)

So then I'll do it group by group.

The "Yes to all" seems to me very confusing and dangerous.
Or at least propose only those choices:

.... prefer:
* the first in your sort order
* the last in your sort order

Of course, I don't know about what you think and the others...

**Comment by rgriebl** [comment]
"Yes to all" doesn't work for a lot of use-cases. In reality, most would need a "Read my brainwaves" option. 
Yes to all is there for the simple cases, where you pasted a bunch of parts and want them consolidated quickly and "prefer Index" works great in this case.
It gives you more flexibility than we had before, but you still need to know what you are doing. If not, then just go manually through the merges with Yes/No.

**Comment by rgriebl** [comment]
I'll close this one for now, since the new implementation seems to work quite well. 
Please open new reports about more specific issues that still persist.

**Comment by paramecie** [comment]
Right now it works pretty well - as of the interface, I didn't check everything.
I dislike (personnaly) the Yes to All (already said), but who knows, maybe I'll use it?

GG - thanks Robert!
