### ISSUE TITLE
Please harmonize and simplify the English naming

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#113]
I've understood the English naming is in the code.

I wouls be happy to have this change - if you accept it - ASAP, as the translations depend of it.

And the English (the vast majority) of users of BrickStore may appreciate also ;-)

**In very short**
• have short(er) fundamental names, everywhere, and the same (harmonization)
• clarify the mixed usage of items and lots in items (except 3 specific places)

**Purpose**
• save room in Documents Columns (we may save 20 chars width!)
• make Filter easier to type and without doubt or error
• save to be distracted by multiple dots everywhere ("Qty.")

**Col names**
• abbreviated names are obviously abbreviated, so “Qty” is as good as “Qty.”
• especially in all document's column titles, use single word abbreviations (no space) to simplify Filter also
• use the shorter name possible, but keep them long if abbreviated would be rare or confusing
• Comm for Comment isn't desired, as it could mean Communication or whatever else, Remark could be Rem, but anyway Remark is a short name.

**In the Document Columns Titles - and in ALL the column titles in all windows (but see further down):**

Index => #
Part # => Ref
Description => Descr
Qty. => Qty
Qty.Orig => OrigQ
Qty.Diff => DiffQ
Price => Price _(remains the same)_
Pr.Orig => OrigP
Pr.Diff => DiffP
Tier Q1 => TierQ1
Tier P1 => TierP1
(etc)
Item Type => Type
Category	 => Cat
Remark => Remark _(remains the same)_
Comment => Comment _(remains the same)_
Lot ID => ID

**In the Modify Item Window (as an example of a window)**

Item type => Type
Category	 => Cat
Part # => Ref
Description => Descr

**In the Price Guide Widget**

Min. => Min
Avg. => Avg
Q.Avg => QAvg
Max. => Max

**Please as Issue #15  also consider using item(s) everywhere and not lot(s)**

**Lots should be used only in specific places (lots in PGuide, ID and Cart)**
Examples of where Lots could be fine:
• Show Lots for Sale on BrickLink...
• Lot ID _(messages containing Lot ID, but not the column, which is ID, see above)_
• %1 lots of your Shopping Cart could not be imported.

**The Info Widget should show**

• Multiple items selected
• Items _(and not lots)_
• Qty
• Price _(and not Value)_
• Weight

Thank you!

Hoping this is accepted and supported by others, I'd be happy if this could be a bit cleaner ;-) Thanks all!

**Comment by ZZJHONS** [comment]
+1 to this

<img width="1124" alt="Captura de pantalla 2021-01-25 185756" src="https://user-images.githubusercontent.com/1063368/105746068-44fde380-5f3f-11eb-880a-33303dc97494.png">

**Comment by rgriebl** [comment]
Just going through old issues:
 - the item vs. lot naming inconsistency has been fixed a long time ago
 - the column names are are now left aligned to make them as readable as possible
 - the actual names will stay as they are ... I don't want to have cryptic 3 letter names there, that only power users really understand. It also would look ugly as hell. 
 - plus: if your column is too small to decipher the name, you still have the tool-tip
 - spaces and dots in the filter: you have to either deal with it or use the graphical filter editor. I'm not adding (and maintaining) a second set of column ids just for the text filter.
 - the only thing that I will change is the "Value" in the info widget: it really is the "Total", not the "Price" (again be consistent internally, we're adding up the "Total" column here)

**Comment by paramecie** [comment]
Agreed with almost everything.
Thanks for the "Value" change.

I just find not logical to have "Orig. " and "Diff. " names while the full names woud be the same (you'll see anyway "Orig" or such due to the default width), and as you said, the tool tip gives the full information.
