### ISSUE TITLE
Saved Layout is moving columns

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#115]
Image of the Layout I want, just after saving it:

<img width="1129" alt="Captura de pantalla 2021-01-23 174925" src="https://user-images.githubusercontent.com/1063368/105608343-bd2fa200-5da3-11eb-8426-fd7fff846754.png">

Image of the same file after closing BS and opening it and I notice it is not quite the same:

<img width="1137" alt="Captura de pantalla 2021-01-23 175020" src="https://user-images.githubusercontent.com/1063368/105608595-21eafc80-5da4-11eb-9415-9a099608677c.png">

Seems a couple of columns order is not saved correctly.

Applying my custom layout moves the 2 columns to the correct place. But closing and opening the file moves them again...

The problem should be when saving the Layout in the file because the Layout saved in BS is correct.

**Comment by rgriebl** [comment]
Most likely it is the same problem as #90. 
Changing anything regarding the columns or sorting doesn't set the "modified" flag on the document, so you can't save it.
Try to apply your layout, change e.g. the condition on any item and save. On reload the layout should be the same.

**Comment by ZZJHONS** [comment]
That is not it!

Try it yourself, put the order as the one in the first image, edit any item, save layout, save file and close it. Then open the file, you will see the Image and Bulk Columns moved. Apply the saved layout and they will be moved where they should, modify and item, save file, close it, open it and they are moved again...

**Comment by paramecie** [comment]
> 
> 
> Most likely it is the same problem as #90.
> Changing anything regarding the columns or sorting doesn't set the "modified" flag on the document, so you can't save it.
> Try to apply your layout, change e.g. the condition on any item and save. On reload the layout should be the same.

Strongly agree: as layout of a document is supposed to be document specific (and saved), make ANY change in a layout to be an Edition, forcing to save the document (or abandon).

**Comment by paramecie** [comment]
About the original post - I don't know, didn't check yet.

But I've also a remark about columns: I make a separate issue of it.

**Comment by ZZJHONS** [comment]
Seems to be fixed in latest build, thanks.
