### ISSUE TITLE
Items uploaded out of order when reverse sorted

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#116]
I've had a lot of problems today using a column layout that had 'descending' sorting by remark pre-enabled. Items on Bricklink's upload page were appearing in a different order to how they were shown in Brickstore. The problems seem to start if the remark fields are all empty when the column layout (and the sorting) is applied.

To reproduce:

Create new file, insert some items, set to price guide, leave all the remarks blank but click the 'remark' column header twice to reverse sort (little arrow pointing downwards), upload to Bricklink - items appear in Bricklink in the reverse order to how they appear in Brickstore.

**Comment by paramecie** [comment]
Hi -

There's no relation between order of the items in a BrickStore Column and a BrickLink Shop.

I'm not even sure BrickStore respects the order column to upload.
And we can't be sure how BrickLink will read and create the lots, in which order - top to bottom, inverse, something else?

Much more, items in a shop CAN'T be ordered strictly by Lot ID, but more often by color, quantity or name...

So, maybe I don't understand what you mean, **but it's normal it's not in the "same order" and it cannot be.**

HTH -

**Comment by SteveTheBrick** [comment]
Hi

Sorry, I don't think I explained myself properly, I was talking about what happens BEFORE items are uploaded to a shop. The problem in the situation I described is that the XML exported by Brickstore has the items in a different order to how they appear in the Brickstore window.

When I go to Bricklink's 'mass inventory upload' page to see which items are going to consolidate they appear in the wrong order which makes life very difficult.

Steve

![uploadorder](https://user-images.githubusercontent.com/77812338/105617895-24684900-5dda-11eb-9842-0648e7876493.jpg)

**Comment by paramecie** [comment]
Yes, BrickStore will upload following its order (probably the Index column or an entry counter).
It apparently doesn't follow any user sorting.

IMO it doesn't matter, and doesn't mean anything: there's no "bug to notice" (or BrickLink will show you a big red box you can't miss), and you shouldn't have to check anything.
Of course the consolidation options on BrickLink should be set properly, once for all (I set them in 2006 and never touched anything).

Personnaly I let them do their job, never had any problem (apart the bid red box once a year if I forget something).

Hoping it helps?

**Comment by rgriebl** [comment]
Nope - that's a bug. I just hadn't adjusted that part to the new view architecture. BS should export in the exact same order as you see on screen and BL currently verifies in exactly that order.

**Comment by paramecie** [comment]
Oh I learnt something (never checked the upload), thank you and for fixing it!
