### ISSUE TITLE
Some Total prices changes +/- after Ctrl + G but Price stays the same...

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#117]
This is before:

<img width="865" alt="Captura de pantalla 2021-01-23 222019" src="https://user-images.githubusercontent.com/1063368/105614374-4b6a4f00-5dc9-11eb-8042-1c8b8c4cba85.png">

This is after:

<img width="859" alt="Captura de pantalla 2021-01-23 221911" src="https://user-images.githubusercontent.com/1063368/105614381-5a510180-5dc9-11eb-934c-d2a24a601c31.png">

0.034 * 102 = 3.468 not 3.458
0.037 * 136 = 5.032 not 5.073

Sometimes up, sometimes down.

Seems it varies around 0.01 per 100 pieces.

Currency is USD

Build 221

**Comment by rgriebl** [comment]
BrickStore retrieves the PG data with 4 decimals, but only displays 3. If you multiply that with enough of a quantity, you'll end up noticing.
I guess it would make sense to round all PG data to 3 decimals to avoid this confusion?

**Comment by ZZJHONS** [comment]
Yeah, it might be better to top it at 3

**Comment by paramecie** [comment]
WYSIWYG!

**Comment by rgriebl** [comment]
This was implicitly fixed when switching from the old CSV to the current AJAX price guide source.

**Comment by paramecie** [comment]
![image](https://user-images.githubusercontent.com/32078594/108099543-0a422380-7085-11eb-9f42-160bdb3d0b0d.png)
