### ISSUE TITLE
Satin colors category

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#118]
There are "Satin Colors" now on BrickLink:
https://www.bricklink.com/catalogColors.asp?utm_content=subnav

![image](https://user-images.githubusercontent.com/32078594/105616851-0ac70180-5dda-11eb-9953-e7aa03128c88.png)

I updated the DB but I couldn't see them in BrickStore - maybe we've to wait for the DB to be updated?

**Comment by ZZJHONS** [comment]
@paramecie they are in BL since beginning of last year. And I see then in BS too:
<img width="155" alt="Captura de pantalla 2021-01-24 010520" src="https://user-images.githubusercontent.com/1063368/105617675-64322f00-5de0-11eb-8764-82595c010cc3.png">

**Comment by rgriebl** [comment]
Should we add a "Satin" color category?

**Comment by paramecie** [comment]
Yep @rgriebl , that what I mean of course, a "Satin colors" category.

**Comment by paramecie** [comment]
> @paramecie they are in BL since beginning of last year. And I see then in BS too:

Didn't know sorry, we part-out Friends once a year approx ;-)
Even if some Sets are awesome, I must admit.
But in general, no I don't follow closely new colors appearance.

Then I searched them in categories, and couldn't find the Satin one.

**Comment by ZZJHONS** [comment]
Now they are showing under solid. And I see that there exist Transparent and Glitter categories.

What about combining these 3 types of colors together as they are all kind of transparent?

**Comment by paramecie** [comment]
Sincerely, why not having the same exact color categories as BrickLink ?

It could be automated while parsing (yes, I know, argh) this page:
https://www.bricklink.com/catalogColors.asp?utm_content=subnav

**Comment by paramecie** [comment]
I made you the list:

Solid Colors
Transparent Colors
Chrome Colors
Pearl Colors
Satin Colors
Metallic Colors
Milky Colors
Glitter Colors
Speckle Colors
Modulex Colors

Hoping it helps the lazy developers (all developpers are lazy) ;O)

**Comment by ZZJHONS** [comment]
To not have 14 categories in BrickStore? But yeah, following Bricklink format maybe is the best.

But I think with these can be enough to keep it tidy:

Know Colors
All Colors
Popular Colors
Most Popular Colors
Solid Colors
Trans Colors: Transparent Colors, Satin Colors, Milky Colors, Glitter Colors
Metallic Colors: Chrome Colors, Pearl Colors, Metallic Colors, Speckle Colors
Modulex Colors

**Comment by paramecie** [comment]
(Personnaly) I like the idea just to see Metallic Colors **only**, and not mixed up with the others, even similar, or worst, being similar, like Flat Silver!

**Comment by ZZJHONS** [comment]
<img width="148" alt="Captura de pantalla 2021-01-24 171733" src="https://user-images.githubusercontent.com/1063368/105636309-17923680-5e68-11eb-8f68-e838b1bf3780.png">
 
They might be feeling lonely...

**Comment by paramecie** [comment]
@rgriebl Hint if you don't know about it, this simple GET gives you many "const" info, like the colors and their subcolor:
https://www.bricklink.com/js/allVars.js

Extract:
_varColorList.push( { idColor: 95, strColorName: 'Flat Silver', group: 4, rgb: '8D949C' } );

**Comment by paramecie** [comment]
> They might be feeling lonely...

Better lonely than in bad company :-)
