### ISSUE TITLE
Feature request: Add Cost column

### ISSUE THREAD

**Issue by frahugo** [rgriebl/brickstore#121]
This is a big one, and I volunteer to help. Here are the changes I foresee:

- [ ] Add Cost column
- [ ] Include Cost field when saving as BSX file
- [ ] Read Cost field from BSX file
- [ ] Import Cost from XML file
- [ ] Add Cost field to all XML exports that support the MYCOST field
- [ ] Document somewhere that the user has to enable the MYCOST feature in Bricklink
- [ ] Add "Cost" submenu (similar to Price submenu)
    - [ ] Set...
    - [ ] Inc- or Decrease...
    - [ ] Round to 2 Decimals Places
- [ ] Filter by cost
- [ ] Sort by cost
- [ ] Handle Cost column in column layouts

And eventually, add a "Distribute Purchase Cost" submenu item. But that will be a different feature request :smile:. First we need the Cost in the document.

![image](https://user-images.githubusercontent.com/14030/105643690-47890c00-5e5f-11eb-941d-3ed429426927.png)

**Comment by paramecie** [comment]
Why not also showing the difference in % between the cost and the price - the margin - (including eventual Sale?)

Ex:
* Price == 1.00, Cost == 0.50, Margin == 100%
* Price == 1.00, Cost == 0.60, Margin == 66%

;-)

But oh yes, all this is a big project.

**Comment by legobanker** [comment]
I think having a "mycost" column would be a great idea.  Considering that it seems that BL is never going to roll out seller tools, this would be a nice touch.

**Comment by rgriebl** [comment]
"big" is relative, if you know the code base inside out :)

Took me 40mins and that included figuring out why the filter was broken for currency values, plus finally fixing it.

Next up:
1) ideas about what we could do with this field
2) Add a checkbox to the consolidation dialog to not simply merge this fields (as BL has)

**Comment by frahugo** [comment]
@rgriebl Holy moly! Thanks. Wow you're quick. I will have a look right now, just downloaded the latest version.
