### ISSUE TITLE
Build 228, no more Settings / Defaults?

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#123]
Guys, am I crazy or we had a Defaults tab here?

![image](https://user-images.githubusercontent.com/32078594/105653008-f870c480-5eba-11eb-9e2c-b5bf22640242.png)

Maybe you removed it for this build for the default subcondition, @rgriebl ?

**Comment by rgriebl** [comment]
Commit 1ab22f7eb removes that on purpose: everything is saved and restored from now on, so you'll always be where you left of. Doesn't matter if you just closed and re-opened the add-item dialog (this was already working) or if you restarted BrickStore (this is new)

**Comment by paramecie** [comment]
Wow - such new nice features - so smart!
;-)

Naaa sincerely thank you!
