### ISSUE TITLE
Consolidate Popup

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#128]
It displays starting at the middle of the screen, but if it is too wide you don't see the buttons.

<img width="1321" alt="Captura de pantalla 2021-01-25 183831" src="https://user-images.githubusercontent.com/1063368/105743071-92c51c80-5f3c-11eb-9d7c-73a17d047020.png">

Even moving it, and clicking, Yes or No or X or Esc doesn't save it's position. It appears always starting in the middle.

Also, I had 1 item with the remark "2" and comment "1". When adding an item that is already in the file, the popup appears, and the default selected is the new one, not the current one in the file.

Another problem is that even thought you confirm selection of the new one (bottom one, without Comment/Remark) and click yes, the item is merged with the one in the file, and keeps the Remark and Comment but is correctly moved to the bottom. If you select merging with the current in the file, the qty updates without moving it to the bottom.

Also, can we implement doble click in this screen to accept with which one merge?

**Comment by paramecie** [comment]
About the position, signaled here:
https://github.com/rgriebl/brickstore/issues/112#issuecomment-766485095
