### ISSUE TITLE
Build 232, Cost, missing in Add Item?

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#129]
Title says

![image](https://user-images.githubusercontent.com/32078594/105744759-d5d3bf80-5f3d-11eb-86cc-a6883cf0ed65.png)

**Comment by rgriebl** [comment]
Do we need the `Total` field or can we re-purpose that position for the `Cost` field?

That being said: is anyone actually using the `Tiered prices` fields in this dialog? Just curious...

**Comment by paramecie** [comment]
IMO, Total isn't important.

You sell your part 0.034: that's important.

The total makeing 1.068 or 22.124 depending the quantity isn't informative (in this window)...

I never use Tiered, as a seller I better avoid a Lot being depleted; I prefer to sell to many people than to one big buyer ;-)
HTH?

**Comment by ZZJHONS** [comment]
Yeah, I think Cost is better there than Tier or Total. I just add items in qty 1, then in the file I update later as necessary.

**Comment by paramecie** [comment]
2021.1.17 nice!
