### ISSUE TITLE
Graphical details

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#13]
See below, could the picture column be FULLY of the BackGround color, or White ?
I think it's disturbing to have 2 colors in the same collumn...

Also the "Inv" is a nice feature, but could it:

* be MORE visible (like dark)

* not having a "shadow" style, but a why not delimited with a plain 1/4 circle?

* ideally, clicking on it would open the part-out question: "Should the selected items be parted out into the current document, replacing the selected items?"

![image](https://user-images.githubusercontent.com/32078594/103487602-f01af180-4e06-11eb-8cc5-d57b5a13c98f.png)

Ah, and finally, when there's no picture because it needs to be downloaded, then the background is Black - could it be a very light grey or simply White ?
The black ones are very contrasting and ugly when your full list is to be updated... (IMHO)

![image](https://user-images.githubusercontent.com/32078594/103487732-d0d09400-4e07-11eb-8919-7c6a7e9b0a1e.png)

Thank you!

**Comment by chiminirc** [comment]
I also like the inclusion of the INV circle.  It would be great if clicking on it triggered a part out.

**Comment by ZZJHONS** [comment]
Having the no image icon being noticeable is good as probably you made a mistake selecting the color of that item, BL recently deleted render image colors for parts not existing.

**Comment by paramecie** [comment]
> Having the no image icon being noticeable is good as probably you made a mistake selecting the color of that item, BL recently deleted render image colors for parts not existing.

No no - all items are valid and have pictures, but I took a quick screen copy just before it updated the pictures.
The black background is here for just a fraction of second (that's why it's a bit hard / contrasted)...

**Comment by paramecie** [comment]
Ah it has already changed in 2021.1.1, it's not black anymore, it's:
![image](https://user-images.githubusercontent.com/32078594/103498116-eebbea00-4e43-11eb-9097-59afa56f77c7.png)

Thank you!!

**Comment by paramecie** [comment]
I don't know for the others, but I'd prefer smaller icons for the Status.

Right now it's almost as big as the item's picture, and it's disturbing - like here where you see better the status than the parts...

![image](https://user-images.githubusercontent.com/32078594/103590765-fd131000-4eee-11eb-8f98-c11c6514b5a5.png)

And maybe something flat, like:
https://primer.style/octicons/check-24
https://primer.style/octicons/x-24
(in color of course)

Being flat/boring may less captivate the eye?

**Comment by chiminirc** [comment]
They are a bit "vivid".  I have a mixed opinion on size. I started picking orders with my phone using remote desktop tools.  So the larger box makes it easier to TAP to mark it as pulled.
I think you'll see a variety of opinions on this one. Now that the images have gotten bigger we are seeing larger row spacing.  I think the "less rows" is part of the reaction. 

Those that want bigger images won't find the status icons as intrusive.  Those that want smaller images will find them to be too big.

I don't think there will be a majority agreement on this one.  If you had to make a change I think you'd have to allow scaling or a "small, Medium, Large" under options for the size of the status icon.

**Comment by paramecie** [comment]
It could be smaller but still have the same column width (you're right, great for tap).

But yes, too vivid for my taste...

While we're at the icons, the Copy and Paste always seem to be disabled.
In this picture they're enabled but doesn't seem to.

![image](https://user-images.githubusercontent.com/32078594/103592854-7103e700-4ef4-11eb-9c30-2276bbdaa1d7.png)

**Comment by paramecie** [comment]
Appreciate build 203 fixes the background of the pics (see first post), very nice!

**Comment by paramecie** [comment]
Bumping: https://github.com/rgriebl/brickstore/issues/13#issuecomment-754298260

Really those "V", "X", "+" are too vivid and too big, especially if like here you use a smaller picture size (to have more items in your screen), ex:

![image](https://user-images.githubusercontent.com/32078594/105365753-e4993a00-5bfe-11eb-9d7b-6e4798fe2cbd.png)

:-)

**Comment by rgriebl** [comment]
Finally changed to a more modern icon set, so the last of the problems here should be solved.
