### ISSUE TITLE
Build 232, Satin colors empty

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#130]
Title says

![image](https://user-images.githubusercontent.com/32078594/105744961-0b78a880-5f3e-11eb-9d68-a3f7c61085b4.png)

**Comment by ZZJHONS** [comment]
Maybe this need a DB update?

**Comment by paramecie** [comment]
No, did this.

**Comment by ZZJHONS** [comment]
I mean, not download DB but for the server generated DB to be updated

**Comment by rgriebl** [comment]
Yes and I don't trust the current dev build enough to run the daily update. So you'll have wait a few days.

**Comment by paramecie** [comment]
![image](https://user-images.githubusercontent.com/32078594/105747351-f6e9df80-5f40-11eb-819b-b7a26579426a.png)

Isn't the last comma in excess here?

**Comment by rgriebl** [comment]
Allowed since C++11. Makes adding values less error-prone and diffs easier to read
