### ISSUE TITLE
Not consolidated but document is edited

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#132]
**Build 234**

This document is not edited, see the top arrow.

I consolidate a lot:

![image](https://user-images.githubusercontent.com/32078594/105873550-e480ac00-5ffb-11eb-9760-8fd0c3482ed5.png)

... then I click "No", it should haven't done anything, but in fact it has edited something (see the "*" after the filename):

![image](https://user-images.githubusercontent.com/32078594/105873665-037f3e00-5ffc-11eb-87a7-8b1daa4f6d1f.png)

**Comment by rgriebl** [comment]
Might have something to do with this code comment: `// TODO: we may end up with an empty macro` (macro being an undo/redo action). Thanks for confirming that Qt really doesn't like empty macro actions ;)

**Comment by paramecie** [comment]
People generally don't know the difference between a Class and a Comment, and those who write code are too tired to read more code ;-)

**Comment by paramecie** [comment]
2021.1.17 fixed!
