### ISSUE TITLE
Printing not possible

### ISSUE THREAD

**Issue by TReichling** [rgriebl/brickstore#139]
Win10 64bit
![grafik](https://user-images.githubusercontent.com/78096539/106017259-8ff33480-60c0-11eb-945e-48cb00b1dcf2.png)
![grafik](https://user-images.githubusercontent.com/78096539/106017187-8073eb80-60c0-11eb-821c-c3ea1e39326e.png)

**Comment by paramecie** [comment]
Thomas? :-)

I think it's "normal" as the printing templates have completely changed and it's more or less a prototype?
Robert will tell us ;-)

**Comment by TReichling** [comment]
Hey Sylvain, 
Tobias here :-) Printing was possible with Version 2021.1.4 ... Since my update today I got this error.

**Comment by paramecie** [comment]
Tobias - yes, I meant this, VERY sorry. We still have one of your pigs here :-)
Yes I think it was about 1.4 that Robert changed this...

**Comment by TReichling** [comment]
Every Lego Fan should have one :-)
Ah ok. I did not check the release notes properly. Thanks for telling. So I will wait for the next Version.

**Comment by paramecie** [comment]
v2021.1.4

Performance improvements across the board, especially in the table rendering.
Added

    _First implementation of a generic JavaScript extension interface, not public yet.
    As a side effect, the old JavaScript printing was replaced with the new one. Any old printing
    scripts for BrickStore 1.x are not compatible anymore, but porting will be simple once the new
    API is stable and documented._

Yes, we've to wait for Robert - but you know developpers, they are lazy.
This one takes a few hours between every build; it's shameful, scandalous!
