### ISSUE TITLE
File currency vs Options setting currency? Exchange update?

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#14]
BrickStore has a Currency setting in the Options, but when you set up a different one then USD (like EUR), it still opens files showing USD at the bottom right?
I'm not sure if it's intentional, if there's a file currency and an app currency?
I wouldn't use it, personnaly, and would prefer a general/app currency...

It should also automatically refresh the exchange rate every time your launch the application for example.

With maybe a warning if it can't get the rate like "Warning, using the previous rate, BrickStore couldn't refresh to the current one..."

Thank you!

**Comment by rgriebl** [comment]
Every document can have its own currency (that's what you see in the bottom right corner).
The currency in the settings dialog is your **default** currency for when you open or import a new document.

What I should do however, is to pop up an information box when you load a document that has a different currency as your currently selected default one.

**Comment by paramecie** [comment]
I see.

I'm not sure about tthe "different currency" question, but when opening a "currencied" document, it may ask "Would you like to update the currency rate for this doc?"

**Comment by rgriebl** [comment]
Cleanup time ... a document does not have an exchange rate, it only has price/cost values with a specific currency symbol attached.
Rates only come into play, if you convert the document to another currency (you can set the rate yourself here to cater for old documents) and when showing the price guide in any other currency besides USD (using today's ECB rate).

**Comment by paramecie** [comment]
OK fine!
