### ISSUE TITLE
BS not enforcing Not applicable color where it's needed (build #244)

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#140]
Any item selected in Add items shows all the price guide values a `-`

PG widget for selected items in file works.
<img width="888" alt="Captura de pantalla 2021-01-27 175418" src="https://user-images.githubusercontent.com/1063368/106025164-c634b200-60c8-11eb-9b31-c758278e68dd.png">

**Comment by paramecie** [comment]
This Minifig in Orange???

**Comment by paramecie** [comment]
Here it works:

![image](https://user-images.githubusercontent.com/32078594/106030055-0e0a0800-60ce-11eb-8636-398119b7a12a.png)

**Comment by ZZJHONS** [comment]
I had the orange selected from a part I added before. Just checked and selecting parts with a color is showing PG.

But In previous builds in sets and minifigs color was disabled and PG was showing correctly for them. BS should autochange to N/A as seems its not...

**Comment by paramecie** [comment]
So this is the real problem, not the Price Guide :)

I confirm.

You nshould change the issue title, the problems is BS to enforce Not applicable for the colors where it's needed.

![image](https://user-images.githubusercontent.com/32078594/106031413-8ae9b180-60cf-11eb-84c0-092d97081269.png)
