### ISSUE TITLE
Print (and Settings) button(s) ?

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#143]
While I support the less printing I can, for planetary reasons, a Print button and a Settings buttons would be fine:
_Not exactly here, but on this bar._

![image](https://user-images.githubusercontent.com/32078594/106046525-aa3e0a00-60e2-11eb-9063-fb5392f563c4.png)

Please also rename Configure... to Settings (as Settings is the window title?)
Or Preferences, or Options, but Configure is pretty rare nowayds ;-)

![image](https://user-images.githubusercontent.com/32078594/106046443-909cc280-60e2-11eb-8fe3-da21cdb5d59f.png)

A Settings button especially since you can't access the Settings from the "Splash page" as it was possible at the beginning...

**Comment by rgriebl** [comment]
The toolbar can be customize now.
