### ISSUE TITLE
Recent files, Privacy

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#145]
Say I want to make a Youtube showing your application, or my shop, or simply to show something to a buyer who visits us, or my banker...

Then I saved files named like "My extraordinary store value", "How much I make profit on this Spanish Seller" ;-) or such (stupid) names and or folders "/Secret Deals with LEGO/Order 12345.bsx"...

Please allow a way to erase this list.

![image](https://user-images.githubusercontent.com/32078594/106049034-f2aaf700-60e5-11eb-8fc1-8299c64e301b.png)

See Notepad++ for ex:

![image](https://user-images.githubusercontent.com/32078594/106048614-6c8eb080-60e5-11eb-825c-f9acc93b790a.png)

Of you course, one still can save 10 files named "Untitled1", "Untitled2", but what a pain.

**Comment by paramecie** [comment]
@ZZJOHNS very strange your reaction... maybe to _"How much I make profit on this Spanish Seller"_ ?
But now I know you really read the Issues :-)

**Comment by ZZJHONS** [comment]
I do read them all yeah, I have activated the notifications in GitHub =)

This is an awesome software with an awesome developer!

@paramecie Thumbs up is for the Issue itself, the rest might, or might not, be related to that phrase ;)

**Comment by paramecie** [comment]
Hey thanks all!
