### ISSUE TITLE
Add a "Spread Purchase Amount" function in Cost submenu

### ISSUE THREAD

**Issue by frahugo** [rgriebl/brickstore#146]
Thanks @rgriebl for adding support for MYCOST. This is huge for me because I had to use a small script on the side to add costs to my part-out files.

This is one way to assign a cost to a part: pro-rated cost using the price.

Scenario:

1. User select "Spread Purchase Amount"
2. A form shows up and user enters the purchase cost
3. System assign costs to selected items

**Formula**

```
R = Purchase amount for the selected items in the document (i.e. 149.75$ I paid for the sets)
Q = Item quantity
P = Item unit price
T = Total for an item (= Q * P)
GT = Grand Total (sum of Ts)
C = Item unit cost (new cost column)

C = (T ÷ GT x R) ÷ Q
```

By reducing the terms in the formula, we end up with a simpler formula:

```
PR = R ÷ GT (I.e. purchase ratio)

C = P x PR
```

**Example**

Given I paid 1.25$ for those 2 items
And I have a quantity and unit price for each
Then the unit costs are

Item | Qty | Unit price | Unit cost |
--- | --- | --- | --- | 
Item 1 | 5| 0.10 | 0.05 |
Item 2 | 10 | 0.20 | 0.10 ||
Total | | 2.50 | 1.25 | 

Feedbacks and suggestions are welcome. Some people may calculate costs differently. But this is the simplest way I found and better then assigning the same cost to all items.

**Comment by legobanker** [comment]
Is this function intended to "spread" the cost of the set/kit based on the parts based on the individual parts average?  It may not sound right, but my mind is thinking it LOL.

**Comment by chiminirc** [comment]
I'm thinking if set has a cost of $10 and part out of $20. Then a $4 minifig is 20% of the value of the kit and "cost" should be 20% of the COST for the kit. What I can't wrap my head around is what happens if the cost is $10 for this set, and $8 the next time I part it out.  Today values like this are Keep old, or use new.
The easy way would be NOT to consolidate lots but man how crappy.

**Comment by frahugo** [comment]
@chiminirc when consolidating lots during the import process on BL, you can choose the « By Qty Avg Cost » option, this will adjust the cost using the quantity and cost already in the store, the quantity and cost being uploaded. This is king of how the book value is managed in the stock market. So when I upload my part out files, I choose to use the new price I have in BrickStore, and update the cost using the « By Qty Avg Cost ». Works great!

**Comment by paramecie** [comment]
Ermmm related to #55 ?

**Comment by frahugo** [comment]
> Ermmm related to #55 ?

@paramecie I think you are right. I simplified the formula above and it looks very similar to what you describe in #55. The difference seems to be which field is populated. Here, it would be the cost field.
