### ISSUE TITLE
Add the total cost in the Info panel

### ISSUE THREAD

**Issue by frahugo** [rgriebl/brickstore#147]
Sum of (qty * cost) for selected lots.

Example:

<img width="262" alt="image" src="https://user-images.githubusercontent.com/14030/106076609-e622a080-60dd-11eb-9476-1cfd7273230a.png">

**Comment by paramecie** [comment]
Yes, and please Robert, this is a Price, not a Value... (and only/lonely occurence of "Value" I think)
