### ISSUE TITLE
Home and documents tabs a bit confusing

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#151]
Open/create a few tabs, activate one:

![image](https://user-images.githubusercontent.com/32078594/106146809-6f39e600-6177-11eb-8cc0-2a91581e8ff7.png)

The tab is highlighted, fine.

Now click "Home":

![image](https://user-images.githubusercontent.com/32078594/106146929-909ad200-6177-11eb-9cf5-88e59cea6274.png)

... you see the Home (Recent files) but the document tab is still in foreground and still highlighted, that's a bit confusing.

Could Home be a Tab (but of course it wouldn't have the "x" close feature)?
Or something like this?

**Comment by ZZJHONS** [comment]
Hey, I was going to comment the exact de thing this morning!

**Comment by rgriebl** [comment]
Please give the latest build a try and tell me if you like it

**Comment by paramecie** [comment]
Build 252, wunderbach !
