### ISSUE TITLE
2D / 3D choice isn't saved when quit

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#152]
Open any document, set to 3D view:

![image](https://user-images.githubusercontent.com/32078594/106147988-d0ae8480-6178-11eb-9540-db88a74a62fd.png)

Now close BrickStore, reopen it, open the document.

The view is now in 2D:

![image](https://user-images.githubusercontent.com/32078594/106148166-018eb980-6179-11eb-826f-c987ba00a9c9.png)

The 2D/3D choice isn't saved.

**Comment by rgriebl** [comment]
Already implemented, just not cross-referenced from the commit message.
