### ISSUE TITLE
Minor, Price Guide rows height

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#153]
Now in 2021 we've all better than 600px height ;-)

Please increase the height of all the Price Guide Widget rows, as the chars "g" and "y" are cut and it's ugly...
Maybe use the same height as other titles?

See:

![image](https://user-images.githubusercontent.com/32078594/106156220-90073900-6181-11eb-83ba-c6dd3a7630c3.png)

And all rows, including the "New/Used" one, Last 6 Months, Current Inventory...

**Comment by SteveTheBrick** [comment]
Interesting. I agree that the rows on your price guide should be higher but my price guide has higher rows (maybe too high!)
This is on Windows 10 with the interface set to 100%.

![Price guide](https://user-images.githubusercontent.com/77812338/106171643-b4ffaa00-6189-11eb-8e39-9fdc92494177.jpg)

**Comment by paramecie** [comment]
Yep, maybe System/Fonts dependant?
100% Font size here also.

![image](https://user-images.githubusercontent.com/32078594/106174924-cd75c180-6195-11eb-8c53-8281e88e38ef.png)

**Comment by rgriebl** [comment]
Should be fixed in the latest dev build. I cannot test on Windows 7 though - that's way too ancient.

**Comment by ZZJHONS** [comment]
It's showing nice to me now too in Windows 10

**Comment by paramecie** [comment]
> that's way too ancient.

Ha ha :) I'm still maintaining our first stock management app (still partially in usage) in my Windows XP VM machine, written in 2006 when I started the shop :)

BTW - I'll install BrickStore in XP and will tell you how it works!

**Comment by paramecie** [comment]
Build 245, it didn't change, unfortunately :-(

The "g" are cut.

Even the PG title row has less height than the document's title one.
Compare also the PG title row to the "Appears in set" one, it's smaller.

![image](https://user-images.githubusercontent.com/32078594/106477771-c954e700-64a8-11eb-8ab8-df38711e368b.png)

**Comment by paramecie** [comment]
Wow I didn't refresh the page... let me check latest build :-(

**Comment by paramecie** [comment]
Woooooooooooooooooow !

Fixed and much NICER icons.
How I see it:

![image](https://user-images.githubusercontent.com/32078594/106479176-5187bc00-64aa-11eb-85e4-fa347b252f9c.png)
