### ISSUE TITLE
Most PG is just 2 decimals instead of 3

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#154]
Most of the prices for parts and sets just show 2 decimals instead of 3... I tried downloading again the Prices and manually update 1 by one, but nothing...

<img width="661" alt="Captura de pantalla 2021-01-28 180005" src="https://user-images.githubusercontent.com/1063368/106172451-22640880-6193-11eb-9b7b-ef1a485aff11.png">

PD: In the picture issue #153 can be seen

**Comment by paramecie** [comment]
I'm not sure what you mean, here both from cache or forcing download, I get 3 decimals for 3010 White:

![image](https://user-images.githubusercontent.com/32078594/106303819-ded4d180-625a-11eb-9246-0256ebcc1b0f.png)

**Comment by rgriebl** [comment]
Please read https://github.com/rgriebl/brickstore/issues/80#issuecomment-766758577

Right now we can't have both VAT included and 3 decimals. For the time being, I decided on VAT included, 2 decimals

**Comment by paramecie** [comment]
Ah yes, currency, forgot... OK then!

**Comment by ZZJHONS** [comment]
Okay, I didn't notice that!

But, then why some have 3 decimals?
