### ISSUE TITLE
Add items search remove from list with -word

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#155]
Most times, the results are cluttered with stickered and printed parts...

So being able to write -pattern when you are looking for standard parts or -sticker when you are only looking for parts with a print pattern.

Or maybe add these 2 as a checkbox near the zoom option.

**Comment by paramecie** [comment]
This is silly! In 2021 we're all supposed to regex everyday, pfff!

**Comment by ZZJHONS** [comment]
@paramecie This is about the Add items filter, not the filter in the document... 😉 

Contain, okay, learning never ends 😜 

PD: I just learnt to put :emojis in GitHub too

**Comment by rgriebl** [comment]
> However, note it's _real_ English (c)(tm), so it's "contains" and "does not contain" (no s)...

Are you insinuating that you are surprised a German was able to come up with "real English"? :wink:

**Comment by ZZJHONS** [comment]
@rgriebl If I write `-` BrickStore crashes

**Comment by rgriebl** [comment]
should be fixed in 252

**Comment by ZZJHONS** [comment]
Works perfect now! Thx

**Comment by ZZJHONS** [comment]
@rgriebl is there a way for this to not show parts with pattern?

I couldn't made it work with Reg Ex

<img width="850" alt="Captura de pantalla 2021-02-01 163438" src="https://user-images.githubusercontent.com/1063368/106480351-99f3a980-64ab-11eb-8e00-e24bc1ec6f96.png">

**Comment by paramecie** [comment]
Like an Icon as in Studio ?

![image](https://user-images.githubusercontent.com/32078594/106481914-366a7b80-64ad-11eb-8c7e-bb4dd227e53c.png)

**Comment by ZZJHONS** [comment]
I meant exactly excluding the word `Pattern` because almost all decorated parts in Bricklink have it in the tittle.

**Comment by paramecie** [comment]
> Are you insinuating that you are surprised a German was able to come up with "real English"? wink

Exactly!
But I think the same about French people - so, don't worry.

**Comment by paramecie** [comment]
> I meant exactly excluding the word `Pattern` because almost all decorated parts in Bricklink have it in the tittle.

Then I don't agree to make a specific exclusion on one word - why not "Minifig" as I'm personnaly not interested in Minifig and their parts (for example)?

But I would support to have a quick exclusion on Decorated categories, just like Studio does.
Even this is pretty specific to building in 3D where you're often not interesting - at the beginning at least - in decorated parts.
While in BrickStore I'm not even sure what it would be helpful for...

**Comment by rgriebl** [comment]
The problem with `-pattern` is that it results in an empty filter text plus one exclusion. The bug is that I don't filter at all if the filter text is empty. Need to add the exclusion list as an additional condition.
And I fully agree with Sylvain here: I will not add functionality that's too specific for a certain workflow.

**Comment by ZZJHONS** [comment]
Now it works! Thanks

Yeah, I understand not adding a button just for that
