### ISSUE TITLE
Question regarding: "Spread Purchase Amount" function in Cost submenu

### ISSUE THREAD

**Issue by legobanker** [rgriebl/brickstore#158]
First, I love this new function!  I did have a question regarding how the correct way would be to use it.  When it comes to parting out a set/kit, would the best option be to "part out" all assemblies (such as minifigures) and then use the "spread" option?  That way you should get a more accurate figure (unless the "spread" option already does this)?  I'm playing around with the option now to see if the amounts for the "parted out" minifigures equals the original amount (before part out).  Keep up the excellent work!

Brian

**Comment by legobanker** [comment]
So here's what I have:

I parted out set #40358 x10

I parted out all of the sub assemblies: mini figures, bicycle etc.  I then copied the minifigure parts into a new tab.  I went back and did a "spread" across the complete figures, parts etc.  The spread that I got for minifigure #twn344 is $0.71 (as assembled).  When I did it using a part of out of the minifigure I get a spread of $0.87.  Am I doing something wrong?  In my head, the thought makes sense...on paper...er program, maybe not lol.

Brian

**Comment by legobanker** [comment]
When I did the bicycle...it's coming up with a $0.16 difference:

Loose Parts:
Tires: x2 = $0.328
Bike Chassis: x1  = $0.315
Total = **$0.643**

Sold assembled: **$0.861** 

There is a price difference of $0.16 as well - just like the minifigure above?

**Comment by rgriebl** [comment]
The spread function just uses the parts as they are in the current document. It doesn't automatically part-out minifigs for you. If you want to do that, then select them and part them out in-place first before running the spread-cost function.
It's basically the exact same algorithm as proposed by Hugo in #146

**Comment by legobanker** [comment]
Gotcha.  That's what I'm going with.  Thanks for the input.  I'm going to close this one out.
