### ISSUE TITLE
10+ last Filters in a dropdown list

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#160]
Following #155 this could be solved with having a list of 10 recent Filters for example here :+1: 

![image](https://user-images.githubusercontent.com/32078594/106486584-17221d00-64b2-11eb-8ea7-46a3fe162310.png)

Just with the same triangular thing to open it, as in Add item:

![image](https://user-images.githubusercontent.com/32078594/106486700-36b94580-64b2-11eb-8cbf-b33bcb18cc9d.png)

This way you could have your favorite filters quickly available.

To be able to set and manage favorites filters is a bit more complex - but already the 10 or more last would help everyone I think...

**Comment by rgriebl** [comment]
I'm playing around with this and was wondering if regular-expressions and/or case sensitivity are really needed now that the filter has support for exclude words ("brick -pattern"). This would simplify the UI a lot, because I would need to save the regexp/case-sensitive flag into the history and it all becomes a bit weird.
Opinions?

**Comment by rgriebl** [comment]
Have a look at the preliminary release note https://github.com/rgriebl/brickstore/blob/master/CHANGELOG.md and let me know if this works you.

**Comment by paramecie** [comment]
Thank you! Very convenient!
Tested Build 254.

I've difficulties to make the typed filter saved, anyway in the Add Item window.

You select Parts, type 3023 and it shows the result (Plate 1x2): you can add this item to the document.
But the filter isn't saved.

It seems to be saved only when you type then hit ENTER in the filter box.
Maybe add a save at lost focus or something like this?

**Comment by ZZJHONS** [comment]
@paramecie Its meant to save only the filters you hit enter:

From the changelog:
`You can save your favorite filters now by pressing Return in an filter edit field. Recall them by pressing Cursor Down or by clicking the filter icon on the left. The X in pop-up list lets you delete unwanted filters.`

**Comment by paramecie** [comment]
Yes, but (IMO) it's a pain.

I never hit ENTER when I find the part in front of me in the list.
I could be worried to add this Lot just after hitting ENTER and before I had the opportunity to choose the solor or set the price...

But OK, I know now, of course. I'm not sure about the other users...

**Comment by rgriebl** [comment]
This boils down to a basic question: should this be a history (what Sylvain describes) or should it be a list of favorite filters that should be kept long-term. I opted for favorite list and that's why you have to add filter terms manually via Return.
Both are valid use-cases, but we can't have both at the same time.

**Comment by paramecie** [comment]
Ah Favorites has better features, like a Manage favorites, change their order maybe...
In this case, OK to keep the ENTER validation.

A simple history is more simple for you; but then I would accept any entry without ENTER.

HTH?

**Comment by chiminirc** [comment]
I like the idea of favorites more though both are useful.

**Comment by rgriebl** [comment]
I've just pushed a change that lets you set the mode for filter edits to either
- history mode (the default, the filter is saved whenever the filter edit looses focus or you press Return) 
- or favorites mode (the filter is saved only when you press Return)

**Comment by paramecie** [comment]
Wow, both?
I'll test all this - thank you!

**Comment by paramecie** [comment]
In History mode, I'm not sure **when** it's saved.

Apparently not on lost focus event or something as "simple".

Because I tried to click a bit everywhere and it wasn't saving:

![image](https://user-images.githubusercontent.com/32078594/106968680-9c732f00-6749-11eb-810e-a2786770baaa.png)

One thing seems to be sure:
* it's saving if you click somewhere inside the document window (not the tab)
* it does NOT save when clicking on the document tab itself
* but it seems to save when the App loses the focus... (using ALT+TAB on Win for exemple)

Maybe it's QT focus events which are bizarre?

**Comment by rgriebl** [comment]
I have disabled "history" mode for now. It doesn't really work too well in practice.
Also all other apps that have a similar history functionality require a button press to execute the find/filter command (which is the same as pressing return) ... this means they are effectively in what I call "favorites" mode.
