### ISSUE TITLE
Cannot Download entire Bricklink Store Inventory Get Transfer Error?

### ISSUE THREAD

**Issue by Brick-Slayer** [rgriebl/brickstore#162]
The last 2 days I have not been able to download my entire inventory and reprice it I keep getting an error. If you want the error message me on discord and I will send a screen shot as it has my password and sign in info in the url. Thanks

**Comment by ZZJHONS** [comment]
It is working from time to time. The problem is BL servers the last couple days.
Just tried now and it downloaded in BS and BL.

**Comment by rgriebl** [comment]
See also https://www.bricklink.com/message.asp?ID=1250001
The Bricklink servers are having problems at the moment and there's nothing I could do on Brickstore's side.
