### ISSUE TITLE
Support PCC search in the Add Items window.

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#165]
It would be great if we could search with PCC directly in BS and it will show the part with the color selected (but showing too all known colors available).

Bricklink search is a bit slow, you out the PCC and it directs you to the part in that color, then you can add it to inv or to WL. 

So making a bsx file directly with a list of PCC at hand would be better!

**Comment by paramecie** [comment]
Again talking about Known Colors? #164 #94

**Comment by ZZJHONS** [comment]
Yeah, it's data that can be further used 😉

**Comment by rgriebl** [comment]
Where would this PCC import functionality live?
- A button in the add-item dialog?
  Two clicks, but you can change all the other data (quantity, price, ...) before adding
- A menu/toolbar action in the document that'll open a simple input dialog to enter the PCC?
  Faster to enter a lot of items at once, but they'll be added with qty=1 and price=0, so this has to be adjusted afterwards.

**Comment by ZZJHONS** [comment]
I thought about something like this:
<img width="849" alt="mockup" src="https://user-images.githubusercontent.com/1063368/107503884-c9d13a00-6b9a-11eb-901a-e1f6293031fd.png">

Treat the PCC as a hidden field searchable in the Add items that autoselects the part and color.


PD: Not changing to brick category, keep it at all items, but made it so for the mockup...

**Comment by rgriebl** [comment]
Would `pcc:39482903` also work? I just added `consists-of:<part-id>` and `appears-in:<part-id>` to the filter algorithm to make it easier to look up minifigs (we had the pleasure to find ~130 different minifigs while restocking our shop), so this would fit in nicely there.
BTW: give the right-click menu on a minifig in the add-item dialog a try a let me know what you think. For us this was a real time saver.

**Comment by ZZJHONS** [comment]
Wow wow wow, all of that is gold for time saving!

`pcc:` would be good!

**Comment by paramecie** [comment]
PS: didn't check but this should be documented in the balloon help...

**Comment by rgriebl** [comment]
The `pcc:` filter didn't work out too hot in practice, so I scraped that idea. There's a search icon next to the filter edit now that'll let you enter PCCs / Element numbers (or Ctrl+E)

**Comment by rgriebl** [comment]
But read the tooltip anyhow -- it's been updated with the latest features :)

**Comment by ZZJHONS** [comment]
PCC works perfect, even if you have copied the code with a space before or later it works!

Also, the filters works for all inventoried items in the catalog, not just sets or minifigs, maybe redact different the tooltip?
