### ISSUE TITLE
Importing BL Wanted list converting MINQTY to QTY

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#166]
Now, when you import XML of a BL wanted list download BS doesn't recognise the MINQTY attribute as QTY, so it importing it results in all items as 0 qty.

People need to manually edit the xml and replace all MINQTY to QTY in order for BS to recognise it.

If would be great if BS could do this by himself.

**Comment by paramecie** [comment]
Notepad, CTRL+H... people are soooo lazy :-(
But I agree, a new Import > BL Wanted List would be nice.

**Comment by rgriebl** [comment]
Dev build 261 should be able to import this correctly now: if there's a MINQTY, but no QTY field, it will import that. The same goes for MAXPRICE and PRICE.
Please give it a try and let me know.

**Comment by ZZJHONS** [comment]
Seems to be working perfectly!

There is also the `{QTYFILLED}1{/QTYFILLED}` that is the HAVE qty in your BL WL.

Maybe this can be imported too as the same lot again but with negative qty. So if you consolidate the file the total qty is updated.

**Comment by rgriebl** [comment]
Duplicating lots with neg. quantity sound a lot like black magic to me and probably confuses new user...
Maybe open a new issue about this and see what others think about this.
I'll close this for now, as the original issue is fixed.
