### ISSUE TITLE
Downloading BL Store Inventory, getting error message

### ISSUE THREAD

**Issue by legobanker** [rgriebl/brickstore#169]
Afternoon/Evening All,

I'm trying to download my store inventory, but keep getting the following message:

![image](https://user-images.githubusercontent.com/77599267/107157373-c8f99780-6951-11eb-9642-c52def38330f.png)

I did a reboot, and then started up BS.  Got the update notification and did that.  Was looking at this issue, and was wondering if everyone else is having the same thing.  I know there have been issues with the BL servers, but that issue appears to have been fixed?  Maybe not?

https://github.com/rgriebl/brickstore/issues/162

Thanks!

**Comment by paramecie** [comment]
It's BrickLink - again signaled a few hours ago, and happened to me here also.

**Comment by legobanker** [comment]
Thanks for the link and update!

**Comment by legobanker** [comment]
This function appears to be working...for now.  I'll close out this issue.
