### ISSUE TITLE
Running brickstore on linux w/ chromebook

### ISSUE THREAD

**Issue by davidwestt** [rgriebl/brickstore#170]
Has anyone been able to get brickstore to run on their chromebook? I have never used linux before, and can't seem  to figure it out. I would be very appreciative if someone could walk me through step by step to get it on chromebook Thanks!

**Comment by rgriebl** [comment]
Haven't used a Chromebook before and not planning on touching one anytime soon ... sorry about that. Maybe someone else stumbles over this issue and is able to help you.

**Comment by rgriebl** [comment]
I'm closing this for now, as this isn't really an issue that will be worked on.
There was a discussion however on how to compile BrickStore yourself: 
https://github.com/rgriebl/brickstore/discussions/543

**Comment by ZZJHONS** [comment]
Now that there is an Android app it might run well on Chromebooks:

https://play.google.com/store/apps/details?id=de.brickforge.brickstore
