### ISSUE TITLE
Can't remove a filter in some conditions

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#171]
I reproduce this bug 100% in my Shop Inventory, in memory, not saved.

1) In Filters, type something you will NOT find, like "aaa" or "any contains aaa"
It shows an empty list: correct.
Do not type ENTER key.
Click on the black "x" on the right to remove the filter (or remove the filter field using backspace or any other edition).
Filter is removed, list is displayed: correct.

2) Now instead type something you WILL find, like "brick" or "any contains brick"
It shows a partial list containing "bricks": correct.
You can compare the list number of items with the original list; it should be different because filtered.
Click on the black "x" on the right to remove the filter...

BUG: filter is NOT removed, the list doesn't change.
In fact, there is no way to remove the filter (apart setting a filter which doesn't find anything).

I couldn't reproduce this bug in a short test list for example.

Maybe it's an optimization problem, or linked to the recent history/favorite?

Forgot: Build 259.

**Comment by rgriebl** [comment]
Weird ... works for me using *your* shop contents for testing

**Comment by paramecie** [comment]
Na na na - conditions : download a shop order in memory, not saved.

(Not sure if that changes, I'll try)

**Comment by ZZJHONS** [comment]
Seems that what happens is that the filter results are fixed at the top, so when removing the filter it stays the same view, the only thing you see change is the scroll bar that gets smaller after removing the filter.
<img width="968" alt="Captura de pantalla 2021-02-07 234618" src="https://user-images.githubusercontent.com/1063368/107161713-db4df280-699e-11eb-936e-83f9ee9e8c1d.png">
<img width="974" alt="Captura de pantalla 2021-02-07 234649" src="https://user-images.githubusercontent.com/1063368/107161712-db4df280-699e-11eb-9b3f-de8ebe246b7e.png">
<img width="970" alt="Captura de pantalla 2021-02-07 234717" src="https://user-images.githubusercontent.com/1063368/107161711-d9842f00-699e-11eb-95d8-152443f16307.png">

**Comment by paramecie** [comment]
No no - the total items on left don't change. I'll post pics.

**Comment by paramecie** [comment]
Haaaa I see, the list changes, but not the selection, so the total on left remains the same.

Apologizes.
