### ISSUE TITLE
Opening a BSX file without currency shows USD instead of the Default in settings.

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#172]
When you open a bsx file generated with the old BrickStore, BrickStock or any other program. Even though in your BrickStore settings you have another currency as default it opens the file as USD currency that you have to change manually.

**Comment by ZZJHONS** [comment]
Also, if you change the currency to EUR as 1=1

<img width="266" alt="Captura de pantalla 2021-02-08 210811" src="https://user-images.githubusercontent.com/1063368/107275308-dd24be00-6a51-11eb-8216-d804cf8533b9.png">

The file still displays as USD, but if you click to change again to EUR it shows it is in EUR:
<img width="271" alt="Captura de pantalla 2021-02-08 210846" src="https://user-images.githubusercontent.com/1063368/107275321-e0b84500-6a51-11eb-977a-053555734be4.png">

Checked the PG and it is indeed changed to EUR but still displaying as USD at bottom right. If you save, close and open the file, it then shows EUR correctly.

**Comment by rgriebl** [comment]
The second part is fixed and the first part is correct: old BSX files are in USD implicitly. The currency setting in old BrickStore/BrickStock would only affect the display - the XML has the raw USD values.
One could argue that opening an old file could maybe prompt a dialog like "would you like to convert this file to your default currency?"

**Comment by ZZJHONS** [comment]
That prompt would be okay, but with the option to keep the change as 1=1 as the popup attached before

**Comment by rgriebl** [comment]
Have you been running with a 1 EUR =1 USD ratio in the old BrickStock/Store? Because really it would make sense to get the old conversion factor from the registry and propose that ratio.

**Comment by ZZJHONS** [comment]
I my case, mostly yes, it was closer to the BL PG... I have a lot of bsx files from MOCs and other data I wanted to save with X Price in EUR updated manually to some things. Didn't know the conversion factor was saved in the files.

The thing too is there are other apps (Rebrickable, BrickSync, BLS Manager...) that generate bsx files, and mostly the price printed is in the currency configured in that app/website but not saved with the new format of BS 2021.
