### ISSUE TITLE
Add Items, All Items disappear and won't come back

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#173]
I'm not sure how eaxctly to provoque it, but I did it 2 or 3 times at least.

It seems to happen if you:
* open the Add Items window,
* select All Items, type any Filter, like "plant",
* then select one item in the result.

From now one, even if you clear the Filter, there is no way to show "All items" anymore in the Category, and the previous Category found is "sticky":

![image](https://user-images.githubusercontent.com/32078594/107414562-787d6800-6b12-11eb-9592-30d095c26f44.png)

(see, no All Items anymore)

It's annoying as the only way the find back All Items is to quit BrickStore and run it again.

**Comment by SteveTheBrick** [comment]
I have seen this as well and agree that it is annoying.

If you want 'all items' to come back without quitting Brickstore try clicking on the category list and pressing the 'Home' key - it works for me.

**Comment by paramecie** [comment]
Ahh yes, the All Items is hidden "under" the current category:

![image](https://user-images.githubusercontent.com/32078594/107426737-e761bd80-6b20-11eb-83ca-de0a4b58de12.png)

See here, there are 2 "Others" :)
