### ISSUE TITLE
Sorting is re-applied when multiple items are deleted

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#174]
Since 2021.2.0 Brickstore is doing a type of 'auto-sort' that can be problematical.

Suppose I have some items that are sorted by colour and I then paste some new items at the bottom of the window. Whilst setting the price & quantity for these new items I decide to delete 2 of them. Brickstore re-applies the 'sort by colour' and the rest of the pasted items are scattered throughout the list making it very difficult to find them. Strangely, if I only delete 1 item no sorting is done.

Not sure if this is a bug or intentional but it didn't happen before 2021.2.0

**Comment by rgriebl** [comment]
I know why it happens ... now I "just" need to find a way to fix that while still keeping the performance optimizations that led to this weird behavior
