### ISSUE TITLE
Lot/Price/Totals at bottom of screen

### ISSUE THREAD

**Issue by legobanker** [rgriebl/brickstore#176]
I downloaded the newest build, #266, and I noticed that Lot/Item/Price totals at the bottom are missing?  Is there a setting to change on this, or just not included in this build?

**Comment by paramecie** [comment]
I noticed that too - maybe I'd now like it to be on the top right, close to:

![image](https://user-images.githubusercontent.com/32078594/107676870-e86a2a80-6c99-11eb-897d-b2717290a19d.png)

**Comment by legobanker** [comment]
Works for me. It'll take some getting used to since its always been at thr bottom lol

**Comment by rgriebl** [comment]
I wanted to unclutter the UI a bit. The totals are actually redundant, so I thought not calculating them twice on each edit would be a good idea: if you select none (Ctrl+Shift+A) or select all (Ctrl+A) you get the totals in a (IMHO) much nicer display in the info widget.
I could see the value of having your price total visible at all the times, but what about lots/items? why would you need that?

**Comment by paramecie** [comment]
> I could see the value of having your price total visible at all the times, but what about lots/items? why would you need that?

It's VERY useful - say I open a file from a buyer, or an Inventory, whatever, I can immediately see if it's correct (ex: 274 lots and I know this), or that it contains 1234 parts, etc.
Having to focus and CTRL+A is possible, but was better before.

About the UI, you're right, it's far better now.
I would see those numbers on top right, just like the "Errors".

like 
| Lots: 123 Items: 12345 Price: 234€ | Errors: 1 | Currency...

**Comment by ZZJHONS** [comment]
I find those values really useful, commented about them missing in #68 

If you want to condense the info is it okay but I would vote to have them back.

`| Errors: 1 | 12.345 (123) | 456,789 EUR^ | 987,65 g |`

**Comment by rgriebl** [comment]
> It's VERY useful - say I open a file from a buyer, or an Inventory, whatever, I can immediately see if it's correct (ex: 274 lots and I know this), or that it contains 1234 parts, etc.
> Having to focus and CTRL+A is possible, but was better before.

That's EXACTLY what I have done! Try it out: open a document and you immediately get the document totals in the info widget

**Comment by paramecie** [comment]
> That's EXACTLY what I have done!

Sorry, too much work, can't follow right now. But anyway to have the total **permanently** is better, IMO.

**Comment by paramecie** [comment]
> 
> 
> I find those values really useful, commented about them missing in #68
> 
> If you want to condense the info is it okay but I would vote to have them back.
> 
> `| Errors: 1 | 12.345 (123) | 456,789 EUR^ | 987,65 g |`

Yep, as above, agreed!

**Comment by legobanker** [comment]
I see...it's now moved in the corner.  

![image](https://user-images.githubusercontent.com/77599267/107685104-9ca38b00-6c71-11eb-9fa6-e5e0aee5df92.png)

**Comment by SteveTheBrick** [comment]
No problem with it being at the top, but I'd also vote to have the info there permanently.

**Comment by paramecie** [comment]
Wow we've got a consensus here - now Robert is forced to work on this, I'm so sorry :-(

**Comment by paramecie** [comment]
Arf thank YOU Robert!
