### ISSUE TITLE
"Show in My Store / CTRL+B+I" shortcut

### ISSUE THREAD

**Issue by legobanker** [rgriebl/brickstore#177]
The option to view my store inventory is grayed out.  Is the function: CTRL+B. CTRL+I no longer working?

**Comment by rgriebl** [comment]
It should work if you have a lot-id (import your store to verify).
If you want to it work even without a lot-id, then it's a duplicate of #43

**Comment by paramecie** [comment]
Oh yes, 100% of all the ones living in me wish #43 :-)

Note that could be another option, like "Search in my Store Inventory" (this one would never have to be disabled, if there's an item of course)

**Comment by rgriebl** [comment]
> Oh yes, 100% of all the ones living in me wish #43 :-)

I just had to fix #43 now ... don't need more Sylvains popping out and increasing the issue count exponentially ;)

**Comment by paramecie** [comment]
Oh oh - I'm spotted, I'll stay low profile for now on...

**Comment by paramecie** [comment]
Build 268, it works well - seems a nice feature.
