### ISSUE TITLE
Could it keep windows size and position?

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#178]
It's especially a pain for the Modify Item Window, that you may open and close often.
Every time it reverses to its default size and position, and you've to move and change it manually, like:

**From this:**
![image](https://user-images.githubusercontent.com/32078594/107712464-c12b5180-6cc9-11eb-85b7-d83c0039a635.png)

**To this:**
![image](https://user-images.githubusercontent.com/32078594/107712530-da340280-6cc9-11eb-82a6-eeec00dfb3e6.png)

And then it's lost if you click Cancel or "x"...

And in a general meaning ALL windows (except system ones of course like CTRL+O)?

**Comment by rgriebl** [comment]
The idea is/was to have this window work like a combo-box: when you open it, it will always open below (or above) the current item, so you actually see what you are editing.
I get your point though. Let me think about how I could do both without messing up the UI

**Comment by paramecie** [comment]
I understand, I didn't notice this (good, don't get me wrong) behaviour.

Tested.
Ah maybe as long as it's not changed by the user (for this session?) then open it with this behaviour, then when changed (moved resized) open it to the same place/size?

**Comment by paramecie** [comment]
Build 336 - it works, it's wonderful !
