### ISSUE TITLE
Sort feature is out of control nowadays

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#180]
Build 268.
Take a list, sort it by color, fine:

![image](https://user-images.githubusercontent.com/32078594/107719901-8d582800-6cd9-11eb-99f8-c950d3a557cc.png)

Filter for a part:

![image](https://user-images.githubusercontent.com/32078594/107719937-a82a9c80-6cd9-11eb-845c-c1add3fc469a.png)

Remove the Filter:

![image](https://user-images.githubusercontent.com/32078594/107720002-c7292e80-6cd9-11eb-9b5f-ff155bc2051c.png)

The part is now on the top, but the Sort is still by Color ascending.

Worse, it could arrive ANY place, here on this file, it arrived in the middle of nowhere:

![image](https://user-images.githubusercontent.com/32078594/107720125-fd66ae00-6cd9-11eb-827a-cac1228d789a.png)

I want to be refunded! This software is broken :-(

Arf :O)

Re #174 ?

PS: Now I'm really afraid to see what CTRL+Z does...

**Comment by rgriebl** [comment]
Not just "nowadays" ... I just tested 2021.1.5 and it has the same weird behavior.
Seems like the standard Qt model-view setup is unsuitable for our use-case of only sorting/filtering "sometimes".
Time to rewrite some stuff...

**Comment by paramecie** [comment]
Glad to see you find something to do this weekend :)
Have a good one, people!

**Comment by rgriebl** [comment]
Now it's your turn: this weekend is for testing BrickStore!

**Comment by paramecie** [comment]
Argh :-(

Will do!
