### ISSUE TITLE
Update consist-of: filter to select color

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#182]
When looking where a part is used, you usually have that part in just 1 color and want to know where it appears.

So if you use the filter, update the known colors list on the right to show the colors of that part, and if you select one, update the filter search so it will only show inventories containing that part in that color. The known color list would update to a part selected known colors if you click anything in the results, but if you search something again, it changes back to the filtered part known color.

![image](https://user-images.githubusercontent.com/1063368/107760361-e51e7f80-6d29-11eb-8572-963036f4efe2.png)

**Comment by paramecie** [comment]
Remember Known Colors doesn't work #94 ...

**Comment by ZZJHONS** [comment]
Known colors would be just the default list showing there (or last user used list) but the functionality of doing the filtering is what I meant.
