### ISSUE TITLE
How zoom % is calculated?

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#183]
I might be a little picky here, but could we have "round" numbers on zoom? 

I mean, I wold prefer 90...95...100...105 etc instead of 91...97...102... whatever

Or just double click to put it manually to XX% that I feels the better for my display.

**Comment by paramecie** [comment]
We don't need more Sylvains here said Robert!
:-)

Mmmmh another solution would be to show a zoom rate rounded, like "1" (for 100%), 0.9, 0.7 or 2...

**Comment by rgriebl** [comment]
I added these buttons specifically for my wife ... I thought the rest of the world would use Ctrl+Mousewheel or a Zoom gesture on a touchpad without paying attention to those buttons and the % value.
Guess I was wrong :)

**Comment by ZZJHONS** [comment]
> I added these buttons specifically for my wife ... I thought the rest of the world would use Ctrl+Mousewheel or a Zoom gesture on a touchpad without paying attention to those buttons and the % value.
> Guess I was wrong :)

I do use the ctrl+mousewheel to zoom, but I get those random numbers, it doesn't let you get to 100% exact
