### ISSUE TITLE
Filter, no simple search available?

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#184]
After #180 , build 269

If I type a partial or a full reference, the Filter doesn't work anymore, this is very a pain.

![image](https://user-images.githubusercontent.com/32078594/107856644-d4553300-6e29-11eb-9eb9-792999bd077b.png)

... as you've to type "Part # = 6091" including the proper space in "Part #"...

By default, with no argument, the Filter should work as "Any" I think (and I would like to)?

But I guess this isn't intentional from the Developpers Team?
:O)

**Comment by rgriebl** [comment]
The simple filter still works. It seems like you can get it into a weird state though: just managed to do it once, but I don't know yet how :)

**Comment by ZZJHONS** [comment]
For me simple filter doesn't work either, just exact filtering with expressions

**Comment by paramecie** [comment]
It works sometimes when playing with saved search in favorites... rarely though...

**Comment by rgriebl** [comment]
I think was a side effect from the model refactoring. I can't reproduce it anymore with build 247

**Comment by ZZJHONS** [comment]
It is working fine now for me, and sorting editing fixed too!

**Comment by paramecie** [comment]
It does NOT in build 273.

Open a file, type a reference that exists:

![image](https://user-images.githubusercontent.com/32078594/107867137-66842800-6e78-11eb-9a26-edc0652d2709.png)

It doesn't filter, ENTER key or not hit.

**Comment by rgriebl** [comment]
I can't reproduce this in 274. If you still can, then please give me the exact steps to trigger this.

**Comment by paramecie** [comment]
I wrote:

> It does NOT in build 273.

Then today I switched to 275, and it's fixed, so it seems I just missed a build :-) ?
