### ISSUE TITLE
Filter, can't select favorite with mouse

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#186]
I can't mouse click to select a filter :-(
Obliged to use the arrow keys.

![image](https://user-images.githubusercontent.com/32078594/107856801-fef3bb80-6e2a-11eb-9c2c-5504f457bd2e.png)

(but of course it should NOT apply the filter if you click on the right "x" to remove the filter )

**Comment by ZZJHONS** [comment]
This was happening too with the Add items filters saved some builds ago.

**Comment by paramecie** [comment]
No one should work on weekends :)

**Comment by paramecie** [comment]
Build 272 confirm works now. Thank you!
