### ISSUE TITLE
Allow a quick Filter on errors (a new command)

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#187]
One clicking or double clicking on "Errors" (in the top bar) could automatically apply a Filter on Errors - so you can see them immediatly in a long document...

![image](https://user-images.githubusercontent.com/32078594/107856960-f485f180-6e2b-11eb-9410-4fb9c9fe8357.png)

**Comment by rgriebl** [comment]
This is not possible with the current architecture, but I have another idea to make spotting errors easier.

**Comment by paramecie** [comment]
Ahhh great, tested in 273, that helps a lot!
