### ISSUE TITLE
Filter, max confusionning with CTRL+Z

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#188]
Sometimes cancelling (the Filter) brings to a confusing situation, no Filter but nothing is displayed either in the List.
In short, an empty document list.

![image](https://user-images.githubusercontent.com/32078594/107857127-c9e86880-6e2c-11eb-971f-dd2b04cd25a6.png)

I guess the Filter text isn't restored with CTRL+Z?

I also think CTRL+Z should be disallowed AS AN EDITION command in the Filter window: it cancels the edit, while CTRL+Z is cancelling in the document... may be source of the problem?

**Comment by paramecie** [comment]
I confirm the Filter text isn't cancelled.

If I select a Filter and then cancel the action (filtering), then the Filter is still shown, while no Filter is applied:

![image](https://user-images.githubusercontent.com/32078594/107857470-c48c1d80-6e2e-11eb-9beb-704002a1f375.png)

**Comment by rgriebl** [comment]
I'm a bit confused too :)

What do you mean exactly with "If I select a Filter and then cancel the action (filtering)". I'm not quite sure what you means with "cancel" in this context...

**Comment by paramecie** [comment]
I meant:
* apply a Filter in favorites
* hit CTRL+Z

But let me check again...

**Comment by paramecie** [comment]
No, not this... but it happens, see the first post picture.

One thing is sure, the Filter field itself isn't cleared when you CTRL+Z a Filter set. See above.
