### ISSUE TITLE
Error count is wrong

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#189]
Check the attached image of a download of inventory:

There are 7 items empty in my store as stockroom (done by faulty BL Instant Checkout)

But there is only 1 error showing:

![image](https://user-images.githubusercontent.com/1063368/107857183-18960280-6e2d-11eb-8e05-d381685ba0ec.png)

Also, it would be useful if we had a couple of arrows besides the error numbers to focus each in without need to re-sort any column.

Build 269

**Comment by paramecie** [comment]
> Also, it would be useful if we had a couple of arrows besides

#187 ?

**Comment by paramecie** [comment]
> But there is only 1 error showing:

Maybe it detected it's you the only error?
grin grin

**Comment by paramecie** [comment]
Wow now more testing's required :(
