### ISSUE TITLE
Combining orders into one list for multiorder picking

### ISSUE THREAD

**Issue by BrickSouth** [rgriebl/brickstore#19]
I don't know how feasible it is to implement this, but one enhancement I would like to see is a more refined way to create a picklist of multiple orders into one tab. Currently, you have to open an individual tab for each order, add a unique designation to a column (such as comments) to differentiate the orders and then cut and paste the contents of each tab into a single tab. This process can be very time consuming.

So this enhancement request is actually two-fold. First would be a way to auto populate an "order identifier" field that would differentiate the parts that belong to each order. Bricksync has the order number in the xml filename for Bricklink and Brickowl orders, so it would seem the data is there somewhere. Second would be a way to merge all the order tabs for one picklist. Or perhaps have an option to automatically merge them when you import multiple order xml files at once.

Thank you for all your work on this project!

Jacob
BrickSouth

**Comment by chiminirc** [comment]
Having joined brickfreedom and also using BLS Manager, this multi order picking would be nice.
My preference is the color band on the left.

![image](https://user-images.githubusercontent.com/76887746/103561922-e1bcec00-4e7f-11eb-9117-e8b28e7cf20c.png)

**Comment by paramecie** [comment]
When I have/wish to do this:

* I import the first order
* CTRL+A, Set Remark, I type 4 last digits (or paste the full order number)
* CTRL+X, paste all this in a bigger list, close this order
* import the next order and so on...

It makes something like this - you can sort, search, and sort again by remark (so, by order):
![image](https://user-images.githubusercontent.com/32078594/103564191-62024200-4ebe-11eb-85f9-d2bef3ec2642.png)

In fact, I programmed a macro key when I type CTRL+R then it does CTRL+A and Edition/Remark/Set...

**Comment by rgriebl** [comment]
I have added experimental support for a `Marker` column in the latest dev build. In addition, the order import dialog gained an `Import combined` button that does exactly what is described above.
Please give it a try and let me know what you think.
Keep in mind that the marker value is currently not saved!

**Comment by paramecie** [comment]
Nice, with colors :)

The order number is much important - you can have 4 orders from/to the same buyer/seller...
"Shop_name / 12345678"

Or an option insettings of which fields used as a Marker?

As you think!

**Comment by paramecie** [comment]
With the same name the color changes, nice. But order number (also?) would be a must ;-)

**Comment by paramecie** [comment]
Experimental ?

![image](https://user-images.githubusercontent.com/32078594/110527802-b1136000-8117-11eb-907d-b0fa96416311.png)

:)

**Comment by rgriebl** [comment]
The alternative would have been a crash due to null pointer... which one would you have preferred? ;)

**Comment by paramecie** [comment]
We don't prefer, we don't think - we're the guinea pigs here.

...

But be warned, we're more numerous than you!

**Comment by rgriebl** [comment]
Implemented in 2021.3.2
