### ISSUE TITLE
The app crashes everytime I click on this icon

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#192]
![image](https://user-images.githubusercontent.com/32078594/107858155-ff905000-6e32-11eb-9960-5f276a2827ae.png)

Much more, I don't understand what the tooltip means :-(

**Comment by rgriebl** [comment]
This will change the tooltip into something readable: https://answers.microsoft.com/en-us/windows/forum/windows_7-desktop/change-windows-7-language-from-french-to-english/2c9c9fd2-11be-4442-9a45-7ec61483e7b9?auth=1

**Comment by paramecie** [comment]
Ah that's an easy fix for the tooltip!

About the "x" red button, I'll have further testing - as it seems it happens to me on Firefox too... so unlucky I am :-(
