### ISSUE TITLE
Something wrong happens when editing any field, it changes another instead

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#193]
Latest build:

I added a remark to latest item and it changed this one:

![image](https://user-images.githubusercontent.com/1063368/107858582-3c5d4680-6e35-11eb-860f-b5bc374d6970.png)

Then I modified qty of the second and changed the third:

![image](https://user-images.githubusercontent.com/1063368/107858596-51d27080-6e35-11eb-8eef-5983c9cda0d6.png)

**Comment by ZZJHONS** [comment]
Mmmm, closed and opened BS again and I can't reproduce.

**Comment by paramecie** [comment]
Weird... Build 272:

I type in Comments of an item, and it creates a duplicate lot

Before:
![image](https://user-images.githubusercontent.com/32078594/107859271-adeac400-6e38-11eb-9cb6-822d414fb472.png)

After, when I typed "qty=7" on "aaa"

![image](https://user-images.githubusercontent.com/32078594/107859287-d4106400-6e38-11eb-91f5-2991d5b58777.png)

... it has created a new lot.

**Comment by paramecie** [comment]
We can all stop testing now - not only Robert has work for this weekend, but maybe also for the whole next week :-)
