### ISSUE TITLE
Creates a dup lot when editing a lot comment (at least) in diff mode

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#195]
Maybe related to #193 

Weird... Build 272:

I type in Comments of an item, and it creates a duplicate lot

Before:
![image](https://user-images.githubusercontent.com/32078594/107859271-adeac400-6e38-11eb-9cb6-822d414fb472.png)

After, when I typed "qty=7" on "aaa"

![image](https://user-images.githubusercontent.com/32078594/107859287-d4106400-6e38-11eb-91f5-2991d5b58777.png)

... it has created a new lot.

**Comment by ZZJHONS** [comment]
It doesn't create a lot, it changed your index 1 lot with the data of your current editing item.

**Comment by paramecie** [comment]
Uh, I don't get it - there's a duplicate lot, see 2 items 3070b in Blue, while there was one only.

**Comment by ZZJHONS** [comment]
@paramecie don't you see white 3069b missing? 😉 

The bug is #193,  if you resort the file, the row you are editing changes instead the equivalent index # line

**Comment by paramecie** [comment]
Yep - weird - anyway seems Robert fixed it. I'll check this also.
