### ISSUE TITLE
Sorting inverted is not the same order as sorted.

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#196]
Check the attached images, sorted by color vs sorted by color inverted:

![image](https://user-images.githubusercontent.com/1063368/107864475-b1904200-6e5c-11eb-8423-bc253f2e2604.png)

![image](https://user-images.githubusercontent.com/1063368/107864477-b94fe680-6e5c-11eb-8e9b-89ca94921a5b.png)

I don't know what is the criteria, but it not the same as it should...

**Comment by paramecie** [comment]
It cumulates the sort orders, and the Index is the sort order by default, so it's sorted by Color THEN by Index (same direction as color)?
