### ISSUE TITLE
Filter creates an edition

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#197]
Build 272 (it may be already fixed)?

If you pick (with mouse, thanks!) a Filter, like here:

![image](https://user-images.githubusercontent.com/32078594/107866521-2621ab80-6e72-11eb-9152-aafa515d3aec.png)

Then the file becomes edited:

![image](https://user-images.githubusercontent.com/32078594/107866538-49e4f180-6e72-11eb-8fca-b39c9369aa12.png)

And it asks to be saved when closing, but this is normal in the bug context.

**Comment by paramecie** [comment]
Typing something like "aaa" makes the same effect (without even ENTER key pressed).

**Comment by paramecie** [comment]
Build 273 same behaviour.

**Comment by rgriebl** [comment]
Everything that is on the undo/redo stack flags the document as modified. Right now I'm not saving the filtering/sorting state, but that is on my todo list.
BTW: Excel does the same thing on sorting/filtering

**Comment by paramecie** [comment]
Yes, I agree - but when you've cancel ALL the editions, the file shouldn't remain edited.

This already works:
* open a saved document
* delete 1 lot => edited
* CTRL+Z => NOT edited

It should work the same with filtering - IMO.

**Comment by rgriebl** [comment]
Yes - it should. The problem is that difference mode also changes the column layout by (de)activating the diff/orig columns and this is just recorded as "something changed" in the same way as loading a column layout does.
Ideally these actions should also be part of the undo stack, but that's not so straightforward to integrate, because architecture wise, it's in a different abstraction layer.

**Comment by paramecie** [comment]
Gee... why then simply NOT record a change when filtering?

After all, when I filter in a DB, in Notepad or Word, it doesn't edit it.
Doing a CTRL+F shouldn't.

Except maybe if you save (ENTER key) the filter, then yes.

I don't know, I'm writing what I'm just thinking :)

**Comment by paramecie** [comment]
Same for #199 - as long as you don't type/change anything, from difference or not difference mode could NOT edit it.

**Comment by rgriebl** [comment]
Everything that is undo-able will mark the document modified. You can't have one without the other.
And again: this is exactly what Excel is doing ... not saying that Microsoft does the right thing here, but it is a standard after all.

**Comment by paramecie** [comment]
They're just lazy, just like as in NTFS where you need to defrag files, where in all Linux FS there's no need for defrag.
Just a poor and lazy decision.

In short: if you can cancel something, it should revert to the initial state before cancellation.

Right now you can cancel a Filter, then it should 100% reverse - or don't allow cancel.
#214 ?

IMHO, of course.
And yes, I'm a pain :)
