### ISSUE TITLE
Problem loading orders by date range.

### ISSUE THREAD

**Issue by chiminirc** [rgriebl/brickstore#2]
I am able to load individual orders but was unable to import via a date range.  I chose RECEIVED as well as ANY status. I also tried just DEC and just JAN in case crossing over the 2020/2021 year was an issue but it didn't matter.

Briefly I saw status for 302K download but then ended up with the error dialog "caused by three things".

**Comment by rgriebl** [comment]
BL's download API is acting really weird all of the sudden and is not returning XML, if the order of the parameter changes.
Tried to work around this with b352c1b4369ca201e08177c5b2809ec86d770c2c and it seems to work for me.
Please re-open, if the next BrickStore release still has issues.
