### ISSUE TITLE
Upload clipboard select all items in document instead of just the rows I had highlighted.

### ISSUE THREAD

**Issue by chiminirc** [rgriebl/brickstore#20]
I went to upload some new inventory.  I selected 9 of the 32 total rows and dialog confirmed it was 9 items.  However, the XML copied into the clipboard was all items in the document. Unfortunately the issue is intermittent or perhaps has to do with using the CTRL+E / CTRL+U shortcut keys.  The first time I did shortcut keys and it didn't filter.  Then drop down menus and it was ok.  Again with shortcut keys and it worked.  

![image](https://user-images.githubusercontent.com/76887746/103586456-bdc2d000-4eaa-11eb-90d8-08af35595103.png)

**Comment by rgriebl** [comment]
I can't see this happening in the code. What could have happened on your end, was that you accidentally hit `Escape`, `Return` or `Space` on that dialog. All these keys act as *No*.

Looking at the code, I also think the *Yes* button should actually be the default here, so that `Return` and `Space` result in *Yes* and `Escape` results in *No*. Opinions?

**Comment by chiminirc** [comment]
Ahh, that is what happened.  I'm set on muscle memory with brickstock.
CTRL+E / CTRL+U / ENTER
In brickstore I see I would need to do CTRL+E / CTRL+U / Y / ENTER

If I'm given the option, I'm thinking YES is the default I'd prefer.

**Comment by paramecie** [comment]
> Looking at the code, I also think the _Yes_ button should actually be the default here

Sorry no, it's "No" by default here, with CTRL+E and U, and the same with the menu.

Note: you may also have an extra question "Contains errors, are you sure you want to upload?" and here also the default is No.

But I tried and couldn't reproduce the OP bug here.

**Comment by paramecie** [comment]
> In brickstore I see I would need to do CTRL+E / CTRL+U / Y / ENTER
> If I'm given the option, I'm thinking YES is the default I'd prefer.

Yep, agreed to all this.
