### ISSUE TITLE
User default layout sort not working correctly when importing inventory

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#201]
![image](https://user-images.githubusercontent.com/1063368/107875309-7ecb6580-6ebf-11eb-9e17-4aad008e6d54.png)

![image](https://user-images.githubusercontent.com/1063368/107875323-8559dd00-6ebf-11eb-9b0a-0ce4d925bc45.png)

PD: sorting manually again corrects it

**Comment by rgriebl** [comment]
This is a duplicate of #39, but we didn't have user configurable Lay-outs back then.
