### ISSUE TITLE
Filter, strange results filtering on 1 char

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#202]
Build 275

One could use filter on 1 char - like tying "z" for Medium Azure, or any other case...

But right now it finds sometimes strange results.

This is fine with "z":

![image](https://user-images.githubusercontent.com/32078594/107883480-78ed7880-6eef-11eb-81a5-6f21c9db9c3f.png)

This is weird with "x" (it finds 8 results without obvious "x" in 8 lots of a 10 lots document):

![image](https://user-images.githubusercontent.com/32078594/107883490-94588380-6eef-11eb-83c4-1a4d618dd2c3.png)

**Comment by ZZJHONS** [comment]
1 `x` 2 in the description

**Comment by paramecie** [comment]
F^^^^ck!
