### ISSUE TITLE
Export menu options needs a case fixed, and less messages if possible

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#204]
Could we have all conditions fixed in enable/disable Export menu options ?

Like here, it's correct, as the doc is empty:

![image](https://user-images.githubusercontent.com/32078594/107884029-d0d9ae80-6ef2-11eb-875c-2e53249d14b6.png)

But here it's not, as it's not in difference mode (should be disabled):

![image](https://user-images.githubusercontent.com/32078594/107884083-15654a00-6ef3-11eb-9732-672945c1269c.png)

I didn't check all the other cases, maybe it's the only one...

This may allow you to get rid of those nasty multiple message boxes which are really painful...

But we all like you very much, Robert!!! :-)

**Comment by legobanker** [comment]
Not sure if I'm thinking of the same thing, but I am trying to update prices using my master inventory file.  I've downloaded the from BL and attempted to update a price via the "XML Update" function, but keep getting this error?  I can't find where to enable the "difference mode":

![image](https://user-images.githubusercontent.com/77599267/107892246-df739600-6ef1-11eb-9b53-903c944ce0e5.png)

**Comment by legobanker** [comment]
> Not sure if I'm thinking of the same thing, but I am trying to update prices using my master inventory file. I've downloaded the from BL and attempted to update a price via the "XML Update" function, but keep getting this error? I can't find where to enable the "difference mode":
> 
> ![image](https://user-images.githubusercontent.com/77599267/107892246-df739600-6ef1-11eb-9b53-903c944ce0e5.png)

I found it.....duh.....

![image](https://user-images.githubusercontent.com/77599267/107892379-b273b300-6ef2-11eb-887e-f3fdb6743976.png)

**Comment by rgriebl** [comment]
Those "multiple message boxes" - apart from the "you're not in difference mode" are exactly 1 nowadays ... just saying
I can't just disable the export though. How would people know that Mass-Update exports only work if they activate Difference Mode first?

**Comment by paramecie** [comment]
> ... just saying.

Sorry Robert - I mean, you do wonderful job here, and I'm sure anywhere.

In fact, I don't like the Diff mode since the beginning, not sure why. Bugs when saved had a role (could never remove it)...

Maybe time to review this mode? I'll think at it...

**Comment by paramecie** [comment]
Ah I've found a message that can disappear :-))

If you click twice on "Enable Diff Mode", it shouldn't warn you if there has been no change at all.

**Comment by rgriebl** [comment]
Closing, because there is no explicit diff mode anymore.
