### ISSUE TITLE
Import Cart, allow a different URL format/source

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#205]
Following #17, it seems to depend where you're getting this URL, but where I use it - in the shop where I am, when I click on show Cart - the URL is different and is right now not accepted:

Example:
https://store.bricklink.com/_name_of_seller_?sID=_id_of_the_shop_&itemID=_id_of_the_cart_#/cart

Could you allow this format?

**Comment by legobanker** [comment]
Got this:

![image](https://user-images.githubusercontent.com/77599267/107893086-20ba7480-6ef7-11eb-8c98-ce22f8a7b1e6.png)

**Comment by paramecie** [comment]
Of course, I edited the URL, it can't work :)

Open a cart you've made in a shop (just for testing), and see the URL, it'll be this one.
