### ISSUE TITLE
Saving inventory file with "remarks" ascending/descending

### ISSUE THREAD

**Issue by legobanker** [rgriebl/brickstore#206]
I tried looking at the other issue #'s, but didn't see this.  If it's there, please let me know.

Is there a way to save a file (say your master BL inventory) so that the file opens using the "remarks" as the default?  I want to have my inventory loaded so that drawer #0001 populates on the list first.  When I save the column layout as my default (ie Master) it doesn't save the settings and I have to adjust the "remarks" column so that the remarks are in ascending order, as you scroll down....0001, 0002, 0003 etc.  

![image](https://user-images.githubusercontent.com/77599267/107893604-1a79c780-6efa-11eb-8500-c43b8786551b.png)

It looks like it's defaulting to the "index" column as the primary sort, but in descending order?

![image](https://user-images.githubusercontent.com/77599267/107893717-c7ecdb00-6efa-11eb-9e2c-e5b1c37ab2a3.png)

**Comment by paramecie** [comment]
I'm afraid is concerns too few, or, what about those who better wish to open the file sorted by Price?

One solution would be an Option setting like "Open my documents sorted by [order] and [Ascending/Descending].

But then what about the docs that in the future that will have their Sort order saved with the file?

Some brainstorming needed here...

**Comment by legobanker** [comment]
I guess it could go in any format: index, price, quantity.  Maybe the option to save each file the way the user wanted (as in a specific setting)?  It looks like the "index" is primary, but my "remarks" show the arrow going up, but it doesn't save to that format.

![image](https://user-images.githubusercontent.com/77599267/107895090-1486e500-6f00-11eb-8873-ff9ed35cbc49.png)

**Comment by legobanker** [comment]
I was just playing around with the "Save/Manage" column layouts:

![image](https://user-images.githubusercontent.com/77599267/107896602-bad4e980-6f04-11eb-866a-5dbb03e798fb.png)

It appears to save the setting for the remarks from "ascending/descending".  I use ctrl+home to carry me to the top.  I'll play around with other files to see how it works out.

**Comment by rgriebl** [comment]
Sort order is saved per file and should also be restored on load. This is a bug with the new model handling.
