### ISSUE TITLE
Proposal for an *automatic* Diff mode, with no Diff mode button, no forget before Mass Update

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#209]
Right now (IMHO) Diff mode is really too obscure.
Especially you edit many things with it disabled, try to Mass Update, and all what you did is to redo, if you remember what you did :-(

Let's try an easier one?

Making the Diff mode automatic and removing its enable/disable button.

**1) Columns where the Diff mode is not presented in column, but as an icon and a tooltip.**
Typically, almost all fields except Price and Quantity.

To simplify: the Diff mode silently activates.

What you change automatically saves the initial value.
It shows the tooltip with the previous value.
This is permanently kept and will be saved in the file.

You can keep it as info, or not, nothing is asked you.
You can mass update because internally it's in Diff mode.

But we need a menu option (like it was before - or, better as a button in the toolbar) something like "Forget the initial values"

Meaning: consolidate and definitely set the new value, the Diff to nothing, and automatically get out the Diff mode (which doesn't exist for the user, remember).

**2) Columns where the Diff mode is in columns (Price/Qty).**

If you type something new here, simply ask ONCE (until the document is closed):
"Do you want to see the difference columns?" yes/no

If Yes, display the corresponding column for THIS field - not all of them.

Same as above, this automatically sets internally in Diff mode, saved in the file, which will provoque the column appearance.

The new button "Forget the initial values" will clear all this, and sets no-Diff mode.

We could have a "Show the difference columns" menu option, in case you replied "No" to the question.
Note that if you display them but there's no difference in fact, when it's saved the columns aren't saved, they won't appear next time.
Again, those cols appear only and automatically if there's a difference in the concerned column.

**In short:**
* Comments, Remark... are automatically "diffed"
* Price, Qty ask you to show/not their diff column
* User CANNOT choose the appearance of the diff columns: if there is one diff, it's displayed, if not, hidden.
* We have an menu option "Forget the initial values"
* We have also "Show the difference columns"
* We can Mass UPDATE after any change, because the Diff mode has been automatically set for ANY change.

**Internally:**
* There's no apparent diff mode
* If there's a difference it's in this Diff mode
* On open, if there are initial values, there are diffs, so it's in diff mode
* If it's in diff mode with changes on Price/Qty, display automatically the corresponding column
* Save the eventual initial/differences, you don't need to save the mode itself (it's automatic)
* Don't allow user (don't show him as a choice) to show/hide the diff columns, they're automatically displayed (but they can be moved or resized)

It's late, hoping it's clear :-(

**Comment by rgriebl** [comment]
This is more or less what I've implemented now.
Only the Orig/Diff columns are not special anymore - use custom layouts if you want to enable/disable them dynamically. 
This, plus getting rid of the "buyer/collector" mode made the column handling code so much simpler and also made it possible to hook up column handling to undo/redo in the first place.

**Comment by ZZJHONS** [comment]
Niceee!
