### ISSUE TITLE
Can "COMMENT" be added to the context menu?

### ISSUE THREAD

**Issue by chiminirc** [rgriebl/brickstore#21]
I'm still trying to figure out how to filter on the Status column (filter out red X).  Until I can what I do when uploading a set is select all the rows I've uploaded, RIGHT CLICK, COMMENT, ADD TO, "UPLOADED".

Then in my search bar I have a COMMENT does not contain UPLOADED.  This leaves me with a list of rows I have left to upload to inventory.

![image](https://user-images.githubusercontent.com/76887746/103591181-02ebff80-4eb5-11eb-8588-7b682d21f88b.png)

**Comment by paramecie** [comment]
Agreed, I can't see the Comment in the context menu, and it's VERY useful.

It was there in BrickStore 2006+ and BrickStock.

Robert probably forgot/missed it when rewriting :)
