### ISSUE TITLE
BrickStore crashes

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#210]
Importing any inv. and doing Ctrl + L or clicking on Consolidate makes BS close it self

Selecting all and Ctrl+X takes a few seconds... and pasting it in a document frozens BS an it restarts itself showing:

![image](https://user-images.githubusercontent.com/1063368/107928111-32902c00-6f78-11eb-962e-7e7ba76e35ba.png)

Build 277

**Comment by legobanker** [comment]
I got this same error message.  I believe its build 278?

**Comment by paramecie** [comment]
Ah AFAIK we're only at Build 277 :-)
