### ISSUE TITLE
Nice Cart feature, but only Domestic show up

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#211]
VERY nice, but I've 99 Carts, so it seems some are missing ;-)

![image](https://user-images.githubusercontent.com/32078594/107960949-8d8c4800-6fa5-11eb-94a1-1f10cf3ec2c6.png)

After checking, yes, it misses all International ones - the domestic ones are all here.

**Comment by ZZJHONS** [comment]
It just shows domestic ones for me too

**Comment by paramecie** [comment]
Please allow ALSO a search field at the bottom so we can paste either:
* seller's shop name, or country maybe,
* any URL, like Global Cart URL or the one I gave you...

Because with this interface, in my case for example, I'd have to search the Cart I wish to open in a big list..

**Comment by paramecie** [comment]
Build 278: working!

I miss the search field anyway :-(
;-)
