### ISSUE TITLE
Settings/Interface/Picture size edits the document

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#213]
Any change in Picture size makes the document Edited:

![image](https://user-images.githubusercontent.com/32078594/108144899-d7228300-70ca-11eb-830b-74a0e75b5ead.png)

But NOT in the Font size.

Build 286, but appears before...

**Comment by rgriebl** [comment]
Same as this comment: https://github.com/rgriebl/brickstore/issues/197#issuecomment-778807077
Changes to the column layout currently still just set a "modified" flag. The undo stack lives in a differnt SW layer.

**Comment by paramecie** [comment]
Yes/No - then why doesn't the font size, as it does change the layout - now I'm puzzled :-(

Anyway, if you could fix this behaviour...

**Comment by paramecie** [comment]
Same: if you resize a column, it marks it "modified".
But you can't CTRL+Z the resizing!

Note that in Excel 2013 (yes) you can CTRL+Z a column resizing, but the document stays "edited" :-(

I hate it when it's not logical:
* you do something, it says the state has changed, that's right
* you fully cancel this action, it should revert to the initial state (at least, no change due to this action)
