### ISSUE TITLE
Enable/disable Diff Mode with no change edits the document

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#214]
If you click twice on "Enable Diff Mode", it shouldn't warn you if there has been no change at all.

**Comment by rgriebl** [comment]
It doesn't warn me in 2021.2.1. This was explicitly fixed in 47b221dd9dbdde402c26f10314d6a4297539ff72

**Comment by paramecie** [comment]
I'm tired :-(

The title of the issue was right, not the text that I cut/pasted...

It doesn't warn (thank you!) but it marks it "modified", edited.

I know it's another abstraction layer etc - but it's just a pain, sorry.

**Comment by rgriebl** [comment]
The marker is still correct, since difference mode is an undo-able action. There is a bug that undoing it will leave the document modified, but that is going to be fixed soon

**Comment by paramecie** [comment]
So either:
* it CAN be cancelled, then cancellation should remove ANY trace of it,
* or it can't be cancelled, then disable CTRL+Z (button, commande, shortcut...)
_(just like resizing a column)_

Right now you can cancel it, but partially.
No offense hey Robert ;-)

**Comment by ZZJHONS** [comment]
Just thinking... What if difference mode was always there? And you could enable/disable each diff. column the same as the others in the layout, and reset any logged changes with a button or right click?

As I said, just thinking out loud...

**Comment by paramecie** [comment]
> As I said, just thinking out loud...

You mean, like in #209?

Yes I think there should not be any Diff mode, or at least an automatic one: as soon you edit you see the initial value.

My guess is 90% of BS users don't use this, or worse, don't understand it. That's my opinion hey, and I'm not blaming people here. I just think this mode to actually set is too obscure.

**Comment by paramecie** [comment]
Wow - I asked you a lot of work, I've seen.

 Undo/redo enhancements:

- sort and filter are decoupled
- adding/removing/changing an item will remove the sort indicator from
  the header bar. Clicking on the section where the indicator was last
  will now re-sort in the original order
- the filter edit gained a "refresh" icon to re-filter
- column resizes and moves are undoable

And MANY changes.
Ohhh thank you for this, really!
