### ISSUE TITLE
Is there any working way to print a file to PDF?

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#215]
I wanted to share a PDF of a file, but can't make it work even with the standard template?

Is there a way to do so? I get this error: 

![image](https://user-images.githubusercontent.com/1063368/108245902-1b586680-7151-11eb-92b3-378a19b1102b.png)

I suppose is something to do with the JS implementation that it is not released yet, but the print buttons are still in the file menu...

**Comment by rgriebl** [comment]
There is a way ... remind me to test printing before doing a release :)

**Comment by ZZJHONS** [comment]
@rgriebl seems to be another error now, BS is frozen and not responding after selecting the standard template in the popup.

**Comment by paramecie** [comment]
Tired? Aging? Me both here :)
