### ISSUE TITLE
Add items, maybe remove Unsorted Lot?

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#22]
As title says.

![image](https://user-images.githubusercontent.com/32078594/103674300-e0261d80-4f7e-11eb-8efc-dfcb42c848f4.png)

**Comment by rgriebl** [comment]
Is anybody really using the "Unsorted Lot" type nowadays? Would it make sense to completely ignore it everywhere in BrickStore?

**Comment by paramecie** [comment]
Just kill it everywhere.
You can't manage this in here.

**Comment by rgriebl** [comment]
Seems like I accidentally already killed the 'U' type when I switched from CSV to XML downloads :)
