### ISSUE TITLE
Cart Filter opens wrong Cart

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#221]
Build 290
I'm searching for bruno (ja ja) and when clicking OK or double-clicking it opens another cart ;-)

![image](https://user-images.githubusercontent.com/32078594/108429759-ae23fe80-7240-11eb-8763-8d25118583fb.png)

Same with searching another shop's name...
But NICE feature thanks Robert.

**Comment by paramecie** [comment]
Oh it's not the Filter, even with no Filter, clicking on any Cart opens another one :-)

**Comment by rgriebl** [comment]
Found this myself already ... took me a while to figure out what was going on :)

**Comment by paramecie** [comment]
Wow - great you found.

BTW, a button on this window "Open this cart on BrickLink" could be nice... What do you think?

**Comment by paramecie** [comment]
Much changes just for this. Thank you!
