### ISSUE TITLE
XML-Import fails for items with no ccolor

### ISSUE THREAD

**Issue by AllesMeins** [rgriebl/brickstore#222]
When a Bricklink-XML contains an item with no color-tag (for example a minifigure) the import fails.

"Could not parse the XML data. Parse Error: Expected a single color tag but found 0".

Steps to reproduce:

1. Create a Bricklink-Wishlist containing at least one minifigure
2. Download wishlist as XML
3. Try to import into Brickstore

I'm using Brickstore 2021.2.2 on Ubuntu Linux.

**Comment by rgriebl** [comment]
I just modernized the XML parser and made the parsing a bit stricter ... too strict in this case
