### ISSUE TITLE
Enable/disable Diff mode; The Return of the Son

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#225]
Build 292 - I reopen one Issue, you said it's fixed but uhh, not fully?
#214 

* Click Enable diff mode, then cancel: fine, nothings to be saved.

* Click Enable then click again to diasble: it's to be saved :-(

Could it be as "cancelled"? Please? So sorry.

**Comment by rgriebl** [comment]
Closing, since diff mode works differently now (no pun intended)
