### ISSUE TITLE
Propose the Document folder (in Settings) only if the user didn't use another one

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#227]
Right now if I start to work for a specific project I create a specific folder.
But for every file I save, it always bring me back to the Document folder which is far away where I want to save (as)... It's a real pain.

Please propose the Document folder (in Settings) only if the user didn't use another drive/folder.

In other words, if the last open, import or save folder was somewhere else, please use the very last used folder.
Thank you!

**Comment by paramecie** [comment]
Thanks! Will be even happier when the build will be available :)
No hurry, it's weekend ;-)

**Comment by rgriebl** [comment]
I thought you were a stone-age Windows guy? only the Ubuntu build failed

**Comment by paramecie** [comment]
I'm even older than this! My first programs were games on Bull Mitra 15, saved on perforated ribbon paper, the language was then LSE.
I quit that for ASM on 6502 on my first computer:
https://i.ytimg.com/vi/YRssOjxbyaY/maxresdefault.jpg

So... I've programmed in many many languages and computers (including SCO Unix 4 and 5 on production servers), I've seen a lot and a lot of techs.

Frankly, for my day to day use, I'm comfortable with my Windows 1000% stable (still in Win 7, though).

And I've a good Steam library (100% still gamer here); you simply can't fight :)

**Comment by paramecie** [comment]
Apart this, I'm to happily try this build :)

**Comment by paramecie** [comment]
Ah great, this issue is fixed, and please admit, it's far easier now ;-) Thank you!!
