### ISSUE TITLE
Please add shortcut to every Set command for the main editions at least

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#229]
For every day users, please add shortcuts to every "Set" command for the main editions, as (proposal) :

* quantity: CTRL+Q

* price: CTRL+E

* cost: CTRL+O

* comment: CTRL+M

* remark: CTRL+R

So then you can select a few items, and boom, CTRL+R to set the same Remark, etc.

![image](https://user-images.githubusercontent.com/32078594/108551459-462cf100-72f0-11eb-8f0f-bcad152a81af.png)

**Comment by rgriebl** [comment]
If it only was that easy...
Ctrl+Q is quit on macOS
Ctrl+E is already in use for Export
Ctrl+O is open file

I have list of still available single letter shortcuts here on my desk -- currently we are down to:

`D F H J K M R T U`

**Comment by ZZJHONS** [comment]
Qty = U (Units) 
Cost = T

Maybe?

The F is not used for focus search/filter?

**Comment by paramecie** [comment]
Those given were just examples...

A double CTRL, like CTRL+I, CTRL+S ?

Ex: CTRL+T (like SET), CTRL+R ?

**Comment by rgriebl** [comment]
Instead of using up all the (still) available shortcuts, you can now change all values within the selection with `Ctrl+Return`. Also, for mouse users, the context menu has a "Set value" action for every column

**Comment by paramecie** [comment]
I don't get this one.
I can see no change with CTRL+RETURN.

If I type a new price and CTRL+RETURN it doesn't change the price on the selected items:
![image](https://user-images.githubusercontent.com/32078594/109310072-5db22f80-7844-11eb-9cf9-5671f429893d.png)

?
How/when is it suppose to work?

**Comment by ZZJHONS** [comment]
@paramecie check #253

**Comment by paramecie** [comment]
Arf !

**Comment by paramecie** [comment]
I've a comment...

Why not simply with RETURN?

Edition is direct while typing. We don't need to strike RETURN.

And normally you do NOT select multiple columns when you change a price for example.

So you need to do 2 things: select multiple rows AND type RETURN before editing.

I think that's far enough, and CTRL is just a pain...

**Comment by rgriebl** [comment]
And how would you disambiguate return on Status, Item, Color, Condition, Retain and Stockroom?

**Comment by paramecie** [comment]
Good question.

Even easier: maybe multiple selection could imply multiple edition, even withOUT any RETURN?

**Comment by paramecie** [comment]
BTW, in all cases the Undo should show the proper change.

Here I guess:
Modified 'Bulk' on 3 items

![image](https://user-images.githubusercontent.com/32078594/109315401-cb615a00-784a-11eb-84d8-1b0316e526af.png)

Like here:

![image](https://user-images.githubusercontent.com/32078594/109315447-d916df80-784a-11eb-801d-df0be64cf4ac.png)

**Comment by paramecie** [comment]
BTW, that could be an option in settings, like: 

Multi-edition [ x ] When multiple items are selected, any edition to ONE of those items will be applied to ALL of those in selection.

![image](https://user-images.githubusercontent.com/32078594/109361324-0aae9b80-7889-11eb-9e70-962e568375f3.png)

Or something like this?

**Comment by paramecie** [comment]
I've seen you implemented the automatic multi-edition in Build 308 - wow, you're always surprising Robert (in a good way)!
https://github.com/rgriebl/brickstore/issues/229#issuecomment-786686764

I like it, but people what do you think?

_Please just remember the Undo/Redo that has to change (see above)._
