### ISSUE TITLE
Consolidating in copy/paste bug and the way it works

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#233]
I have this reference file with prices volontarily set to 0.3 0.4 and 0.5

![image](https://user-images.githubusercontent.com/32078594/108606532-d9325d80-73ba-11eb-88b4-1de43da8ee97.png)

Quantity is zero because I wanted to reply to a question asked in another issue...
But that shouldn't be a problem.

Then select ALL, Copy.

Open your working including the same items, prices aren't the same:

![image](https://user-images.githubusercontent.com/32078594/108606566-0f6fdd00-73bb-11eb-81f0-f17c1fc6ed92.png)

**There are 2 problems depending the way you're consolidate.**

**Bug : paste from clipboard, it opens consolidation, select "New items" and click "Yes to all"**

![image](https://user-images.githubusercontent.com/32078594/108606625-55c53c00-73bb-11eb-9908-bc9160d0ca16.png)

**Price of the first item is incorrect (but the 2 next are OK):**

![image](https://user-images.githubusercontent.com/32078594/108606651-742b3780-73bb-11eb-9ba3-78dfc8e9f4b3.png)

What ever means "Prefer the new" (prefer to preserve ? Or prefer the new attribute will overwrite?), in all case there's a bug because the first price has been differently treated than the others.

**Problem 2: do it manually, item per item, select the item you want (with the new prices 0.3 04 and 0.5)**

![image](https://user-images.githubusercontent.com/32078594/108606685-b48ab580-73bb-11eb-8d4d-c327d17f5b03.png)

If you do it this way, the 3 prices are wrong, because you didn't understand "select the one to be preserved".

![image](https://user-images.githubusercontent.com/32078594/108606701-d5530b00-73bb-11eb-8c43-ca572d1c9ce2.png)

**Maybe the description should and the way it works should be reversed?**

Right now you're saying "Select the attributes that are to be preserved"
If I overwrite an old price (or not), to preserve the new price doesn't mean anything: you won't change the clipboard contents or the original file.

Maybe it would be easier to say **"Select the attributes you want for this item"**
If it's the old item, the person doesn't want the new attributes.
If it's the new item which is selected, he/she wants the attributes of the new item.

Same, please precise what means **"Prefer the new"** or such in this case.
Maybe, something like 
* Update with the attributes of the new
* Keep the attributes of the old

Thank you.

**Comment by rgriebl** [comment]
I'm closing this as the consolidate dialog was completely revamped and should now support everything you asked for.
