### ISSUE TITLE
Database Connectivity Issues

### ISSUE THREAD

**Issue by DMBrickCo** [rgriebl/brickstore#235]
Whenever I try to install the app and open it. A window pops up titled "Update Database" With a progress bar titled "Updating Bricklink Database", and below the progress bar it says "Error: Download failed: SOCKS version 5 protocol error". It lets me get to some of the data, but there are no thumbnail images of anything. And it can't import my store inventory, or anything from Bricklink really.

If you need any more info. Let me know.

**Comment by rgriebl** [comment]
Never heard of that before, but a quick google search for that error message tells me that you are using a Mac and there's a (broken) SOCKS5 proxy set in the global network preferences.
Why you would be using a SOCKS proxy in 2021 outside of a locked-down corporate network is beyond me though... 
In any case: this is a configuration error in your network. Just google for this error message and then follow the instructions to disable it.

**Comment by DMBrickCo** [comment]
Thank you! I have no idea why I would be using a SOCKS proxy either. I have
had to configure a few settings on my computer for school so I wonder if
that changed something.

Thanks for your help! Have a great day!
