### ISSUE TITLE
Consistancy Currency and Currency symbol

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#24]
I'd show EUR as the currency is shown as EUR - just for consistancy.
Here and anywhere else...

![image](https://user-images.githubusercontent.com/32078594/103682699-7eb77c00-4f89-11eb-8d64-3e4ba030d303.png)

Ah I see, then there's this problem:
![image](https://user-images.githubusercontent.com/32078594/103682849-b45c6500-4f89-11eb-9689-95a1caac45e0.png)

Maybe simply put "Pr" for Price and that's it, so it dosesn't have to be dynamical?

**Comment by rgriebl** [comment]
Fixed

**Comment by paramecie** [comment]
Niiiice !
