### ISSUE TITLE
Open 2 or more recently opened files?

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#241]
That would be a way to reopen your current work on your project.
You'd select 2 or more files here with CTRL (for 2 or more single items) or SHIFT (for multiple items selection), or both:

![image](https://user-images.githubusercontent.com/32078594/108631348-d9d5fd00-7469-11eb-97b2-0a49c52609fa.png)

If the [ ] Multiple selection isn't checked, then a single click opens the document
If it's checked, then you can select as many files with clicks, then you've to click on Open

Just as an idea...

It can avoid you, to have to implement the future request "Please add a Save my Session" management ;-)
I'm sure somebody will ask for this... (not me, I'm not so lazy)

**Comment by ZZJHONS** [comment]
Why not a setting to reopen as closed? Like any web browser, if you close the tabs they don't reopen, but if you close the program with open files restore them.

**Comment by paramecie** [comment]
Ah, see? The Session management just has been requested :-)

**Comment by paramecie** [comment]
Nice! But remember to check this setting!

![image](https://user-images.githubusercontent.com/32078594/109307825-81c04180-7841-11eb-81ee-61a8d9d1bc47.png)
