### ISSUE TITLE
'Show in my store' not working for minifigs, standard sets & cmf sets

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#242]
'Show in my store' is not working for minifigs because Bricklink doesn't recognise (not applicable) as a colour. In fact it is searching for 'not applicable' in the name of the minifig.

Searching for standard sets has the 'not applicable' problem but also the short set name needs to be used -  e.g. 4204 instead of 4204-1.

Searching for CMF sets has the 'not applicable' problem but these sets are also listed in the inventory by name so it's not possible to search for them by set number.

I wrote a greasemonkey script to add a 'show in my store' link to the Bricklink web site so I'm familiar with all these problems!

**Comment by SteveTheBrick** [comment]
And please don't forget about the 'not applicable' instructions/box/book/catalog.

**Comment by paramecie** [comment]
Agreed, for minifig, series, instructions/box/book/catalog, and stickers also!

There could be exceptions somewhere like the stickers in parts. Some search has to be made?

**Comment by ZZJHONS** [comment]
Some gear items have color, but others don't...
