### ISSUE TITLE
Installing/opening BrickStore

### ISSUE THREAD

**Issue by Brickslan** [rgriebl/brickstore#244]
Hi, 

When i try to open BrickStore as regular user or as administrator, the program does not want to open.
It launches the program but then it goes to "does not respond" and all i get is a blank box.

I have tried installing different versions and the problem persists with all versions i tried.
When i install the latest version on my laptop, the program works just fine. 

Windows 10 is up to date.

Does anybody know what the problem might be? 

Thank you in advance.

![image](https://user-images.githubusercontent.com/79459792/108716642-adc78400-751c-11eb-9a0b-a5dd8bd6662a.png)

**Comment by rgriebl** [comment]
Weird ... I'd start with disabling firewalls, anti-virus, etc. to see what is blocking the program.

**Comment by Brickslan** [comment]
Thank you for the repley.
I disabled my firewall and anti-virus but it's still not working sadly.

**Comment by paramecie** [comment]
Did you install the proper version, 64 bits I guess, and NOT the 32?

#76

**Comment by Brickslan** [comment]
Yes i did install the 64-bit version.

Op ma 22 feb. 2021 21:43 schreef paramecie <notifications@github.com>:

**Comment by rgriebl** [comment]
I have no idea what might be causing this. You could try to run Microsoft's DebugView and see if BrickStore is generating at least some debug output

https://docs.microsoft.com/en-us/sysinternals/downloads/debugview  -- click *Run now from Sysinternals Live* 
then start BrickStore.

**Comment by paramecie** [comment]
Using this tool, this is what I can see when tracking everything...

![image](https://user-images.githubusercontent.com/32078594/109178738-7578ad80-7789-11eb-9de9-0ba5bcb04cbf.png)

...and launching BrickStore:

![image](https://user-images.githubusercontent.com/32078594/109178572-482bff80-7789-11eb-8f04-fffb42efeacd.png)

If you don't see one of these, that may give some information on where the problem comes from?
Of course here it's a different system - Win 7.

**Comment by paramecie** [comment]
BTW Robert, strange it tried twice to load the database... now if I launch it it shows only once the Load database every time:

![image](https://user-images.githubusercontent.com/32078594/109179201-f172f580-7789-11eb-9973-beb3e9ffb7a1.png)

Just FYI.

**Comment by rgriebl** [comment]
You received an automatic DB update the first time: look at the "Generated at" timestamps

**Comment by paramecie** [comment]
11 hours ago... but yes, the filedate corresponds:
![image](https://user-images.githubusercontent.com/32078594/109180093-d48af200-778a-11eb-98b1-6b62b1df4df6.png)

I noticed I can delete the db v2 I Still have...
Thanks!

**Comment by Brickslan** [comment]
This is what i am getting with the tool
![image](https://user-images.githubusercontent.com/79459792/109200866-6271d780-77a1-11eb-8931-e9fd0b87ed86.png)

**Comment by Brickslan** [comment]
This is what i am getting with the tool
![image](https://user-images.githubusercontent.com/79459792/109201008-93520c80-77a1-11eb-84fb-62eba10798b2.png)

**Comment by paramecie** [comment]
This error 20 seems to come from a buggy MSI audio driver:
https://github.com/TOtto-EclipseIR/EIRC2/issues/19

... and:
https://bugreports.qt.io/browse/QTBUG-79799

QT seems related to this, has a problem with those drivers.
QT is used in BrickStore.

Maybe try to simply uninstall the last audio/system drivers you installed? Or install the more recent ones? And see if it makes a difference?

PS: of course if you know a bit what you're doing.

**Comment by Brickslan** [comment]
@paramecie I have found the problem due to your last post, it appears to have been "msi sonic radar" software that was the cause.
I have removed this program and then brickstore works just fine.
Kinde strange because i have a Asus motherboard en GFX card. I have nothing of MSI in my gaming desktop.

Thank you for the help, it is greatly apreciated :)

**Comment by rgriebl** [comment]
Thanks Sylvain for puzzling this one out. I've added comment to the Qt bug report that this bug in the MSI driver is still a thing and that it sometimes is even worse than just a few annoying lines in the debug log.

**Comment by paramecie** [comment]
You're both welcome! I always loved chasing weird machine behaviours... But about Humans I don't understand anything, though ;-)
