### ISSUE TITLE
Feature Request: API call to BL for remarks data

### ISSUE THREAD

**Issue by GreatBrickLab** [rgriebl/brickstore#245]
Would you be able to code in an API call to BL that would look for a matching lot in current inventory?  OR  Could you see if there is match to the downloaded inventory locally?

This request is to allow adds of inventory and find if the item is already in the store and then add to the "remark" location or change that location, then upload the bsx file.

CJ

**Comment by paramecie** [comment]
#191 would help?

**Comment by ZZJHONS** [comment]
I think more like #64 and #71

**Comment by rgriebl** [comment]
This should be possible with the `Copy values from document...` command. Just import your store into another document and then copy the remarks from your store document to the current one.

**Comment by RedWolves** [comment]
> This should be possible with the `Copy values from document...` command. Just import your store into another document and then copy the remarks from your store document to the current one.

OK, I'm sorry for the extra reply.  But I just wanted to comment on how cool this is!!!

**Comment by GreatBrickLab** [comment]
Yeah,   I saw the video you did yesterday.  That is really good!

**Comment by rgriebl** [comment]
Thanks Ralph! I've linked your video from https://github.com/rgriebl/brickstore/wiki/Tutorials
