### ISSUE TITLE
Import bricklink shopping cart imports wrong row (store)

### ISSUE THREAD

**Issue by chiminirc** [rgriebl/brickstore#248]
The list enumerates fine.  Store names, qty, lots, total all seem to be correct.  However, when I doubleclick a row or select IMPORT when a row is selected, the wrong store imports.  It is the SAME wrong store each time.  So if I close and reopen and attempt to import my latest cart (last update field), a different store imports.  The tab name of the store and cart contents are correct (the wrong store is imported but the items match that store's cart).

It is almost as if a different index is used for the cart listings (row number based on sort) vs another index (order carts are imported?)

**Comment by paramecie** [comment]
Solved couple of days ago, see #221 

Please download the latest build here:
https://github.com/rgriebl/brickstore/actions
