### ISSUE TITLE
Import Shop Inventory has been unsuccessful

### ISSUE THREAD

**Issue by xaraxarax** [rgriebl/brickstore#249]
On two different Installations it comes to the following error:

![grafik](https://user-images.githubusercontent.com/79638214/109143517-6cbfb180-7760-11eb-964f-e6b114c9e03f.png)

My setup

![grafik](https://user-images.githubusercontent.com/79638214/109143651-9082f780-7760-11eb-90ee-8fa69c28bfdb.png)

thx

**Comment by rgriebl** [comment]
Your Bricklink login username and or password are wrong. Fix them in Settings
And yes, the error message could be better :)

**Comment by xaraxarax** [comment]
first thing i have checked and they are correct. My shopping carts load successful with the same credentials ...

**Comment by rgriebl** [comment]
Are you using your username or email address? I guess it is the email address then and that won't work

**Comment by xaraxarax** [comment]
yes, see my edit, thank you for ultra fast reaction :)

**Comment by rgriebl** [comment]
You're welcome

I'll add a check to the settings page to prevent user from entering mail addresses.
Also, the weird error message is happening, because BL changed the error response page, so BrickStore cannot detect the problem correctly

**Comment by xaraxarax** [comment]
or maybe like this:

![grafik](https://user-images.githubusercontent.com/79638214/109147274-1dc84b00-7765-11eb-99b1-ea99072a741b.png)

thank you ;)

**Comment by rgriebl** [comment]
I think I'll make it a bit more subtle ;)

**Comment by xaraxarax** [comment]
sounds better ...

short last question? Is multi column sorting possible, something I'm missing?

**Comment by rgriebl** [comment]
Older versions remembered the last 2 "sorts" to disambiguate the current one. I had to disable this feature for now to implement the new undo/redo architecture.
I don't know if I can re-implement it like it was before, but if you open a new request here on GitHub, it would be at least documented.

**Comment by xaraxarax** [comment]
No problem, I won't miss the old way ... I'll try to put my idea into words.
