### ISSUE TITLE
Multi column sorting would be a nice addition

### ISSUE THREAD

**Issue by xaraxarax** [rgriebl/brickstore#250]
It would be nice if you could sort by multiple columns in the view and optionally save the sorting. I would spontaneously think of two areas in which this could be placed. 

1. Via the column layout, which should then also be storable there or
2. As a supplement to the filter, for example "sort <field1> asc and sort <field2> desc ..."
 
Maybe that can be implemented without much effort. What do everyone else think ...

**Comment by ZZJHONS** [comment]
This would be nice!

On Brick Owl website you can sort a second column by pressing Shift + Click

**Comment by xaraxarax** [comment]
Ha, second, third, and so on ... very cool, smoothly overlooked

**Comment by paramecie** [comment]
Hi guys - I feel stupid, tired or old - or both.
:-(

It seems resolved, but I can't find a way to sort by Color and then Part # for example.
How do you do this???

**Comment by rgriebl** [comment]
Normal click on a column header sets the primary sort column (the once with the v/^ marker). Shift-clicking afterwards will set secondary/tertiary/etc. sort columns, but I can't easily add a marker, because none of the 3 desktop platforms have a UI concept for "secondary sort column"

**Comment by paramecie** [comment]
Uhhhh sorry can't make it work?

Clicked normal on Color, then shift-left click on Part #, it gives me this:

![image](https://user-images.githubusercontent.com/32078594/113332193-25a97b00-9321-11eb-825e-b1e9478c62b9.png)

**Comment by UticaBrix** [comment]
This would be a great feature fi this can be done!

**Comment by ZZJHONS** [comment]
> Uhhhh sorry can't make it work?
> 
> Clicked normal on Color, then shift-left click on Part #, it gives me this:
> 
> ![image](https://user-images.githubusercontent.com/32078594/113332193-25a97b00-9321-11eb-825e-b1e9478c62b9.png)

Just tried the same and it is working as intended for me, sure you are in 416?

The only thing is that clicking a second time with left-click the second sorted column does not invert the sorting, can this be implemented too? @rgriebl

**Comment by UticaBrix** [comment]
When you do that it just separates by scattered.    Example:  On bricklink, when they are separated by color, then by item name.   On here, once you separate by color, then when you left click/shift the description, they become scattered color again.    BL they have plates, slopes, tiles, etc… all together in order by color.

**Comment by paramecie** [comment]
> Just tried the same and it is working as intended for me, sure you are in 416?

No, 414, but it was fixed 4 days ago, before 414.
OK I'll try 416.

**Comment by paramecie** [comment]
I confirm it works in Build 416 - no idea why it didn't in 414, too much work here sorry pals :-(

**Comment by paramecie** [comment]
@UticaBrix Download the Build 416 here, it works :)

https://github.com/rgriebl/brickstore/actions/runs/699590591

**Comment by UticaBrix** [comment]
Sorry not sure what the 416 is?

**Comment by paramecie** [comment]
Consider it as a version - a non official version, but still it's corrected.

**Comment by UticaBrix** [comment]
Sorry I don’t see one that says “416”.   Can I just do an update?

**Comment by paramecie** [comment]
No you can't - you MUST be logged on Github.

Then you go to this page:
https://github.com/rgriebl/brickstore/actions/runs/699590591

And you'll find a bit further down the installer for this Build 416.
HTH?
