### ISSUE TITLE
Remember options in Copy or merge values

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#252]
Now it is always the defaults values, it would be better to remember the last options used as in most other settings of BS.

For example, most of the times for part outs I want to Copy all fields except Qty. to ignore.

**Comment by paramecie** [comment]
The more you give them, the more they demand...

**Comment by ZZJHONS** [comment]
And a shortcut would be appreciated too, it is in a bit hard to reach position...

**Comment by rgriebl** [comment]
Fixed in 1b4a415ad329388a1a62aea60f912f359d1d074b
