### ISSUE TITLE
Editing a field with `Ctrl+Return` changes the value in all selected rows

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#253]
Ctrl+Cursor works for moving, but I couldn't get Ctrl+ Return to work, only the field in the current row is being changed, not the rest of the selection.

**Comment by rgriebl** [comment]
Are you sure you are *starting* the edit with `Ctrl+Return`?

**Comment by ZZJHONS** [comment]
Okay, that was the problem, I was ending with Ctrl+Return, not starting with it.

**Comment by rgriebl** [comment]
I also tried triggering on *ending* with `Ctrl+Return`, but this was awkward and inconsistent for the select item/color columns which generate a pop-up editor.
