### ISSUE TITLE
Wrong Filter using Create from Selection on something missing

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#256]
All those fields (absence of) contents gives a wrong Filter:

![image](https://user-images.githubusercontent.com/32078594/109392359-f5368180-791b-11eb-9308-24939baa74d9.png)

This is an example, there are other fields...

The filter is then:

![image](https://user-images.githubusercontent.com/32078594/109392412-3038b500-791c-11eb-9011-7c70b415587e.png)

And this gives zero result.

**Comment by rgriebl** [comment]
I knew there would be some problem in the filter when I refactored the document interface :)
