### ISSUE TITLE
Minor, reconsider the Inv icon/button in the Description 

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#257]
First: I don't like it:-)

Who cares - but more important, you don't know where to click:

![image](https://user-images.githubusercontent.com/32078594/109392785-53646400-791e-11eb-8d06-9659c45e0461.png)

In the "blurry" part of the circle, a double click opens the Modify Item Window.

On the plain blue part of it, it opens the Inventory Window.
In fact it opens Inventory Window ONLY in an undefined rectangle around the "Inv" text...

Please prefer something with a border and no shadow effect, so you know what you're opening **in advance**?

**Comment by rgriebl** [comment]
Now  **YOU** were the one who requested this feature in the first place: #13 
Before that, the `INV` tag was just a passive marker.

What are you proposing? replacing this tag overlay with a dedicated button? or making it passive again and rely on the (now shortened) context menu?

PS: It would be easier to hit, if you didn't set the scale factor so low ... the hitbox is (cell height/2) x (cell height/2), anchored to the lower, right corner of the cell. This works out quite nicely at 100% :)

**Comment by paramecie** [comment]
Uhhh sorry, yes a button, or a shape, a border as a line?
I don't know what you can do. It's just the shadow thing...

I changed the scale because I usually work with 25+ items on the same page, otherwise I spend my time scrolling.

Again, it's minor, no problem :)

**Comment by rgriebl** [comment]
Closing as nobody else complained about the Inv tag in the last 2 years. Plus I like it :)

**Comment by paramecie** [comment]
> Plus I like it :)

Arf, that's a killer argument :-)
No problem !
