### ISSUE TITLE
Spread Cost Amount function still broken :-(

### ISSUE THREAD

**Issue by legobanker** [rgriebl/brickstore#261]
Just downloaded #311 and the spread cost function isn't working :-(

Seems all other price related functions are working fine 👌

**Comment by paramecie** [comment]
Confirmed, even on a couple of items; it apparently doesn't do anything.
It marks the filed "modified" anyway.

I'm afraid Robert didn't like #257 and is angry now :-(

**Comment by paramecie** [comment]
Confirm, fixed :)
