### ISSUE TITLE
Detail, double click on picture opens the BL Catalog Info...

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#263]
Just to add an extra quick and easy feature ;-)

![image](https://user-images.githubusercontent.com/32078594/109427871-a1e43200-79f4-11eb-91f2-cf4a8a6ef2e7.png)

**Comment by rgriebl** [comment]
Double-clicking interferes with the 3D view unfortunately. I have however rearranged the menu, so that the catalog link is right at the top.
