### ISSUE TITLE
Detail, double click on BrickStore helmet icon opens its Github

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#264]
![image](https://user-images.githubusercontent.com/32078594/109427928-ed96db80-79f4-11eb-80c7-0c50b47c9fed.png)

Would open https://github.com/rgriebl/brickstore

**Comment by rgriebl** [comment]
Good idea, but right-clicking it gives you the option to cancel all downloads.
Having something completely unrelated would be bad UI design.
Instead, any click will now show the "cancel all downloads" option.

(BTW: I fixed the broken GitHub link in the About dialog)

**Comment by paramecie** [comment]
OK!
