### ISSUE TITLE
Pressing 'Enter' in some import dialogs creates 2 documents

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#267]
In the 'Import set inventory' dialog if I click on a set and press the 'Enter' key the set is imported twice (2 identical documents created).

Same thing happens with the 'Import order' dialog. I haven't tried the other import dialogs.

**Comment by paramecie** [comment]
Build 317 confirmed.

**Comment by paramecie** [comment]
Build 319, seems fine!
