### ISSUE TITLE
Filter, use stockroom == "" instead of stockroom == N

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#268]
Following #256 and reading the translation, this isn't obvious to me (at least):

You've to type stockroom == N to filter for "no stockroom".

This isn't documented.

Please harmonize and use stockroom == "" instead?

**Comment by rgriebl** [comment]
This *is* harmonized now: retain = Y/N, stockroom = A/B/C/N
Both show an unchecked box when unset, so both should have the same filter value

Regarding the translation: all filter values have the translator comment "Filter>[Fields]>[Value]" ... e.g. `Filter>Stockroom>None`

**Comment by paramecie** [comment]
Bob, dear Bob.

I see your logic.

Anyway - one thing is sure, as it's not written anywhere, neither Y/N or A,B,C/N I guess nobody will get this :-(

Side note, wouldn't it be (far more complicated) but more explicit like this?

![image](https://user-images.githubusercontent.com/32078594/109749197-715ded00-7bda-11eb-85e5-0e4f80f7a4b5.png)


Just my 2 cents... I'm not sure.

**Comment by rgriebl** [comment]
And on an unrelated note: never call a German named Robert "Bob" if you want to stay on his good side :)

**Comment by paramecie** [comment]
Arf - that was on purpose Robert, that was on purpose :O)

And I agree with your wife; at least column names are far too complicated to type, with spaces and dots (or sometimes not)... already written somewhere else.

**Comment by paramecie** [comment]
> Nothing is really document in BrickStore, and an empty string is the same magic as 'N' if there's no documentation.

Yes/No. An addition to the tooltop help could be simple:
_Type "" to means any empty field, eg: Retain == ""._

Now it's more complicated because that should be : 
_Type "" to means any empty field, except for Retain and Stockroom where nothing is meant by "N", eg: Retain =="N", or Reserved == ""_

Hum.

Anyway I hereby vote for ZZJHONS to write the official documentation!

He has far too much time available anyway. That's very suspect.

**Comment by ZZJHONS** [comment]
Actually I never have a lot of free time... 🤦‍♂️ 

But I was indeed thinking about helping with a Spanish translation 😉 

Oh... I said it public, now I have to do it... 😅

**Comment by paramecie** [comment]
This is disgusting. Now he's inventing he speaks Spanish not to have to write the documentation :-1: 

But please no Arnold translations...
I can see the message boxes: "! Hasta la vista Baby !" and "No problemo amigo."
Ha ha !

Great ! Bienvenida !
