### ISSUE TITLE
Menu windows hidden behind while in Full-Screen

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#269]
When in Full-Screen mode (F11) a click on a menu seem to NOT open the menu.

But in fact, I believe the menu is opened but behind the application (wrong zorder), so you don't see it.

The print screen below isn't showing it properly, as as soon as I print screen, the menu comes back to foreground:

![image](https://user-images.githubusercontent.com/32078594/109693103-8eb69b00-7b89-11eb-92ba-3a67ad511a65.png)

Win 7 - Build 317

**Comment by rgriebl** [comment]
Was this working before?

**Comment by paramecie** [comment]
Never tried... I'll install an old random version...

**Comment by paramecie** [comment]
It seems to be fixed!
