### ISSUE TITLE
Allow ESC to leave full screen mode

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#27]
After F11 you NEED to remember F11 to get out of full screen.

Maybe allow ESC to do the same like in many applications/sites?

**Comment by rgriebl** [comment]
Which apps would use ESC for that? I tested Firefox, Edge, Explorer, Notepad++, Chrome and Audacity on Windows, and none of those reacted to ESC -- every single one wanted to have another F11 to go back to normal

**Comment by paramecie** [comment]
Youtube :-)

I may be wrong (apart video in full screen mode, like Youtube - but then it's not F11...)
Let's say forget it :-)
