### ISSUE TITLE
File only opens showing 1 line of item instead of all

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#271]
Something strange happens with one file, opening it in BS 2021 only shows 1 item, and the totals equate it, no filters applied.

But opening it in BrickStock it shows everything correct...

Sadly this file I can't share it...

PD: I don't know if related, but sometimes with CTRL+G it only prices the first item and tells there is no data for pricing the rest. But if you Ctrl+G again, it prices all correctly.

**Comment by ZZJHONS** [comment]
Happens again with other file:

![image](https://user-images.githubusercontent.com/1063368/109711124-cda31b80-7b9e-11eb-8112-10b3847e4e3a.png)

![image](https://user-images.githubusercontent.com/1063368/109711362-12c74d80-7b9f-11eb-995a-8692867f069c.png)

**Comment by rgriebl** [comment]
Please attach such a file, or send it directly to me via email (click my username)

**Comment by ZZJHONS** [comment]
Sent to your email.

Also this was in the LOG repeated a lot:

WARN default: QPainter::begin: Paint device returned engine == 0, type: 3
WARN default: QPainter::setRenderHint: Painter must be active to set rendering hints
WARN default: QPainter::setPen: Painter not active
WARN default: QPainter::setPen: Painter not active
WARN default: QPainter::setPen: Painter not active
WARN default: QPainter::end: Painter not active, aborted

**Comment by ZZJHONS** [comment]
Fixed!
