### ISSUE TITLE
Feature Request: Export View to Excel/CSV/...

### ISSUE THREAD

**Issue by xaraxarax** [rgriebl/brickstore#274]
It would be a good extension to be able to export the current or selected view to Excel / CSV / Whatever, optionally directly to the predefined application

**Comment by paramecie** [comment]
Or as an Export to Clipboard that you can paste wherever you wish like:

N 3001 Brick 13x7 Red 100 0.10 10.00 €
(tabulations in between, one line per item)

There could be a setting or a choice when exporting for the delimiter, so you could have nice tabulations or ";"...

**Comment by rgriebl** [comment]
In theory you could just open in BSX file in Excel .. in practice you have to delete the second line `<!DOCTYPE...>` because Excel is trying to be overly correct. 
Since I'm using RelaxNG as an XML schema nowadays I might as well drop the DOCTYPE line completely, since it doesn't serve a technical purpose anymore.

**Comment by paramecie** [comment]
Yes, with the <!DOCTYPE...> Excel gives an error.

But when you remove it, it opens it nicely.
Simply doing a file/open but selecting *.*, it'll tell you about XML, agree everything...

![image](https://user-images.githubusercontent.com/32078594/109806186-b149c200-7c24-11eb-9ea7-cf4285f1ee1d.png)

**Comment by xaraxarax** [comment]
I think I was too short again. One click on a button to export the current view with the column configuration and line selection into the clipboard and then insert it in the favorite application, is imho not the same as to remove all unnecessary lines, save the file, and open it then in the faviored application. Yes, the opening in Excel goes, but I have to edit the columns and lines again. I think it could be easier, lets name it quick export  :)

**Comment by paramecie** [comment]
Sure, an "Export to Clipboard for Spreadsheet" would be fine, and yes, with the proper cols names (as the ones in BS document).

As this Issue was about an export to CSV/Excel and it's basically working, please simply open a new Issue asking for a clipboard export?
