### ISSUE TITLE
Detail, make "3DROT" a button and a saved status in Info Widget

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#275]
Just because why not... why can't we have a direct button to open in 3D **and** start rotation here?

This status should be saved (just like 2D and 3D), which means next time it'll automatically open in 3D rotating - hence this "3DROT" name...

![image](https://user-images.githubusercontent.com/32078594/109818210-08ef2a00-7c33-11eb-821a-00e503ee645c.png)

So the 3D button would be the same but without ROT.

That's not important, just an extra cool feature which shouldn't cost much ;-)

**Comment by rgriebl** [comment]
2D/3D is saved nowadays. The rotation did look cool, but having a constantly rotating item on the screen may not have been a good idea from a user experience point of view :)
