### ISSUE TITLE
'Set to price-guide' finishes before all prices are set

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#276]
If I part out a minifigure and want to set the parts to the price guide I normally press 'ctrl-g, enter, enter' very quickly without waiting for the confirmation dialogs to appear.

In the latest builds it appears that the last confirmation dialog appears before all the prices are set. If I hit the 'enter,enter' too quickly the last dialog is dismissed and the operation finishes before all the items have their price set.

There are no problems if I set the prices a second time ( prices cached instead of downloaded? )

This is on Win10 build 319  so maybe related to build 317 ??

**Comment by paramecie** [comment]
Confirmed here, Build 325 on Win 7.

**Comment by SteveTheBrick** [comment]
Actually, I think we are just closing the dialog quickly without reading the message that there are errors connecting to Bricklink and items have been skipped!

But, then, why does it always work the second time?

**Comment by rgriebl** [comment]
It's definitely a bug and I know where it introduced it: in order to get around the slow as molasses Window I/O, I spread the loading of the PG data files over multiple threads. I just can't trigger it consistently right now to debug it.

**Comment by rgriebl** [comment]
I think I found (and fixed) it. Could you please test the new build 326 (should be built in a few minutes)

**Comment by SteveTheBrick** [comment]
Thanks, Robert, it seems OK with the latest build.
