### ISSUE TITLE
Critical, single lot consolidation error

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#277]
Build 325.

Following #233 and some others...

Please Robert, understand we all pushing for more features and nice Gizmos, and we all know how much time it must take you, and thank you for this!!!

On the other hands, some base features are critical in BrickStore. Consolidation is one of them.

If someone's managing his Shop, there are so many Lots, Quantities and Prices and numbers that you can't be sure if BrickStore is making an error or not, and can't check manually every single change.

...

Create a document, make a lot with a specific price you can't miss, select this Lot, COPY to clipboard:

![image](https://user-images.githubusercontent.com/32078594/110007548-17187580-7d1b-11eb-93ed-f8d1916ea34a.png)

Open another document with the same lot but a different price:

![image](https://user-images.githubusercontent.com/32078594/110007605-28618200-7d1b-11eb-9676-08595bb8b820.png)

Don't select, anything, PASTE:

![image](https://user-images.githubusercontent.com/32078594/110007734-4af39b00-7d1b-11eb-9c35-d98f60b224b7.png)

You want the NEW price (1€) to be "preserved", to be the one applied. So you select (or leave selected) the first Lot.
Click Yes.

**Error: the quantity is fine but the price is the old one, not the new one.**

![image](https://user-images.githubusercontent.com/32078594/110008003-8d1cdc80-7d1b-11eb-910d-1b0792710097.png)

Please also consider changing the **"to be preserved"** caption to be changed as something like **"are to be used"** (or such meaning) because "preserve a new price to come", doesn't mean anything to me (IMHO).

Personnaly I'll try to debug Consoldation even more.
Please the others don't hesitate, that's an hot subject.

**Comment by paramecie** [comment]
BTW #233 is still valid, if I copy/paste 3 lots, and if I select "New" and "Yes to all", still 1 price is the old one and 2 prices are the new ones...

**Comment by paramecie** [comment]
I can't test more the Consolidation, as of right now I can't expect any reliable result.

Sincerely, I wouldn't release a version with this doesn't fixed.
No pressure ;-)

**Comment by rgriebl** [comment]
The problem with the wrong data is the sort order. If you change the document sort order to "Index" / Ascending (the standard) it should work as intended (minus all the obvious quirks in the system :) )
Could you please test this?

**Comment by paramecie** [comment]
Sorry was AFAIK. Yes, I'm testing...

**Comment by rgriebl** [comment]
Thanks for testing. Fix is pushed.

**Comment by paramecie** [comment]
What? Already fixed? On BrickLink it would have taken 2 years.
OK I'll check when build's ready.

**Comment by paramecie** [comment]
Maybe I tested too quickly? Or another case? Or it changed in between builds? Sorry, it's not working #278
