### ISSUE TITLE
Difference Mode, persistence, meaning and bugs

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#28]
_There were difficult problems in this mode until the very last BrickStore ;-)_
_Hoping you can fix them now._

Right now:
• save a new test file with at least 1 Lot and some qty
• View menu, set Difference Mode
• save the file, quit BS

Reopen BS and this file.

First :
• it doesn't stay in difference mode, is that normal?
• if not, the difference mode is temporary, at the contrary of View Show Inputs Errors which is permanent

In short, it's not very clear if Difference Mode is temporary, or a file thing or an application thing.

Second, more important, bugs:

• if you change a Qty (like -1) save the file, quit and reopen it, immediately set Difference Mode: the -1 change does not show anymore (Qty Diff ==0) - but the Qty is correct (changes have been validated)

• much more, if you reopen again this file and set Difference Mode, then you CANNOT edit anymore the quantity. It reverts to the original quantity. But if you open the file without the Difference Mode, then you can change the Qty.

Hoping this description is enough, if not, I'll post detailed steps for each problem. Thank you!

**Comment by ZZJHONS** [comment]
Was testing and activated the Diff mode (I like to have it always active) and closed the file and BS. When opening again BS and the file it shows the Diff mode, great, but it is not shown as enable.

<img width="1075" alt="Captura de pantalla 2021-01-08 191528" src="https://user-images.githubusercontent.com/1063368/104049910-0ef1fd00-51e6-11eb-85b7-e2dc7c4fd71a.png">

**Comment by paramecie** [comment]
For sure will test this!
