### ISSUE TITLE
Make Option "Editing a field while multiple rows are selected will change the value in all selected rows."

### ISSUE THREAD

**Issue by DenHae** [rgriebl/brickstore#285]
Can this newly introduced function be made an option?
It severely interferes with my part-out process (and perhaps of many other users) where I need to keep several lines selected while adding many _different_ remarks to the lines to enter the storage locations.
Please consider this and get back to me if there are any questions.

Cheers,
 Dennis

**Comment by paramecie** [comment]
Not saying this is not a good idea, as an option - but maybe you can use my solution?

Fix your items list, set them all to Extra (it takes 2 clicks maybe):

![image](https://user-images.githubusercontent.com/32078594/110213675-4b1da300-7ea1-11eb-9813-f4c946e2186f.png)

Then when you've finished a lot (price, remark, whatever....) just double click on the "+" to mean "Done!"
Or double click again to "X" meaning "Not good!"

![image](https://user-images.githubusercontent.com/32078594/110213723-8029f580-7ea1-11eb-99f6-c0a76412a6da.png)

This way also you're not obliged to keep the selection, you can sort or filter, do whatever lot in whatever order, etc.

HTH?

**Comment by DenHae** [comment]
Thanks for the fast reply.
I haven't thought of this use of the Status field before, this is a really good idea. Not having to keep the selection all the time reduces other possibilities for errors as well. :-)
Cheers,
 Dennis
