### ISSUE TITLE
Trademark? Danemark!

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#287]
Help/About:

All data from <a href="https://www.bricklink.com">www.bricklink.com</a> is owned by BrickLink<sup>TM</sup>, which is a trademark of Dan Jezek.

But no :-(

https://trademarks.justia.com/863/39/bricklink-86339801.html

Current Trademark Owners
LEGO JURIS A/S

Please change this before we receive registered letters from a big lawyers cabinet ;-)

Idea, you may:
* mention as BL does "Dan Jezek, the founder of BrickLink" (bottom right of BL main page), 
* or link to one of BL's pages: https://moc.bricklink.com/pages/moc/help/about3.page
* or maybe for a more personal touch to: https://www.danjezek.com/

**Comment by rgriebl** [comment]
You think I didn't know? :) I just left it in as bit of nostalgia ..

**Comment by paramecie** [comment]
Yep, guessed this - so a sad event :-( - maybe a link to Dan's page then?
