### ISSUE TITLE
Enable searching by LEGO 'element id' in Add Items dialog

### ISSUE THREAD

**Issue by theRealMCQwerty** [rgriebl/brickstore#290]
In BrickLink, if you enter the LEGO `Element Id` in the search box, BrickLink will find the correct part and pre-select the correct color code. I believe Bricklink calls this "fully-qualified-id" the `Part Color Code`.

For example:

**LEGO Element Id:** 6270003
**Matches BrickLink Part Color Code:** 6270003
**Returns BrickLink Part:** 30176
**Returns BrickLink Color:** Green

My request is to add this functionality to the search bar in the 'Add Items' dialog box in BrickStore.

Entering the LEGO Element ID (6270003 for example), would act as if the user had entered the BrickLink Part Id `30176` in the search box and selected the color `Green` in the Color Selector on the right of the Add Items dialog.

Bonus request: If the user enters a LEGO `Design Number`, (which is the element identifier without the colour code), in the Add Items dialog search, then the BrickLink part should be found but no colour selected.

I realise that there may be ambiguity between BrickLink Item Numbers, BrickLink Part Color Codes, LEGO Element IDs and LEGO Design Numbers so a small selector to the left of the search box in the Add Items dialog may be required. Obviously if this defaulted to `BrickLink Item Number` then there would be no change for users that choose not to use this feature.

Thanks!

**Comment by rgriebl** [comment]
Just click the magnifying glass icon (or press Ctrl+E)

Since PCCs also encode the color, I couldn't integrate this into the normal search field in a clean way.

**Comment by theRealMCQwerty** [comment]
@rgriebl WOW!!! The exact feature I wanted was there the whole time! 🤯 
Thank you!

**Comment by theRealMCQwerty** [comment]
@rgriebl Is there a way to go the other way? So if I have the BL Item Number and the colour, can I find out the LEGO Element ID? Obviously BL knows it but the LEGO Element ID and LEGO Design Number are not listed anywhere in BL or in BrickStore as far as I can see...

**Comment by rgriebl** [comment]
BrickStore has the information and I could display it in the picture widgets next to the item id and name.
Please open a new feature request. 
I can't simply hack it in right now, because the lookup would be too slow with the current data structure.

**Comment by ZZJHONS** [comment]
> @rgriebl Is there a way to go the other way? So if I have the BL Item Number and the colour, can I find out the LEGO Element ID? Obviously BL knows it but the LEGO Element ID and LEGO Design Number are not listed anywhere in BL or in BrickStore as far as I can see...

Bricklink displays it under Color images box on the left of the main image of the catalog item view.

**Comment by theRealMCQwerty** [comment]
@rgriebl WOW again! So it does. Fantastic, thank you so much! (Loving all the updates to BrickStore btw!)
