### ISSUE TITLE
Option to choose from saved layouts when printing. 

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#293]
As of now, the printed file is always the same, you can only change the sorting.

It would be great to be able to select one saved layout as a print template to show the fields you want in the order you want.

**Comment by paramecie** [comment]
For all the files, not file dependent?

#292 ;-)

If so, yes!

**Comment by ZZJHONS** [comment]
Okay, the new printing is awesome! 

There is still a couple of tweaks to be perfect ;)

Sorting is good, but column order is not the one in the file.

Also being able to scale down the zoom would be great to fit all in one page instead of two if the user wants.

**Comment by ZZJHONS** [comment]
Printing now is just perfect!

Minor bug: Fit to width leaves one column in the next page, changing to custom displays it correctly.

**Comment by rgriebl** [comment]
All the (obvious) bugs should be fixed. Feel free to open a new issue, if something else is broken.
