### ISSUE TITLE
Part out from item in file doesn't include instructions

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#297]
Even the box for include instructions is ticked and saved in the part out item window, if you start the part out from inside a file item it doesn't adds the instructions.

**Comment by paramecie** [comment]
> Even the box for include instructions is ticked and saved in the part out item window

Yep, they're not related: one is Import BrickLink Inventory, the other is an item part-out from the document...

IMO they should stay separate BUT all the part-out options should move from the Import Window to the general Settings options.
Then it would be global, whatever the import is.

Like this:

![image](https://user-images.githubusercontent.com/32078594/110816554-babdd480-828b-11eb-82d6-2f82f9caf4ad.png)
