### ISSUE TITLE
'Customize keyboard shortcuts' should not allow the main menu shortcuts (alt-f, alt-e, etc)

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#299]
I can currently use the main menu shortcuts such as Alt-E as customized keyboard shortcuts. This should not be allowed as they will always trigger the main menu and will not work as custom shortcuts - this is on Win10.

**Comment by paramecie** [comment]
I don't get it: ALT+E is supposed to open the Edit menu, it's one of the Windows GUI accessibility good practice.

**Comment by paramecie** [comment]
Oh that kills me: I just realized there's a new option Keyboard for shortcuts!

Oooooh that's a great move from Robert! Thanks!

**Comment by paramecie** [comment]
Very nice... anyway, Robert will do what he thinks good, but I wouldn't allow the use as customs of any system shortcuts, like those ones:

![image](https://user-images.githubusercontent.com/32078594/111011163-dc58b200-8398-11eb-8881-1428b4b4a24c.png)

In short ALT+ something should not be allowed (sorry, and IMO).
