### ISSUE TITLE
Document, Colums, minimum size?

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#30]
Please either:

* Add a View menu item to "Resize all columns to min size", which will avoid you to double click on every column top-right to save room...

* Or, maybe by default, when a file is opened, immediately resize it to the minimum width by default.

I'm not sure what you Robert and others think about this, but I'd personnaly prefer the 2nd option...

_There's a third option, but it needs a lot of work and control on opening, especially after application evolutions, which is to save the column width in each BSX file, but I guess this is too complicated for now..._

**Comment by ZZJHONS** [comment]
I would prefer not to implement your second option. It would be better if just "Save column layout" remembered it all
