### ISSUE TITLE
Minor, but why asking?

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#301]
![image](https://user-images.githubusercontent.com/32078594/111010795-da422380-8397-11eb-8bc6-a09087703297.png)

If I click "Open" will it break my GTX 42800?
Will it make me install Ubuntu instead of Windows?!

Sincerely, simply get rid of this message: errors are shown in the document in big and red.

Or at least simply show "This document contains 5 errors" - OK only.

But I don't think any message is necessary?

**Comment by ZZJHONS** [comment]
I would show a window like the one for consolidate lots with a list of these amd what BS thinks is the correct ID now

**Comment by paramecie** [comment]
Oh no - like the old BrickStore? If you have 133 errors you had to click 133 times or spam the ESC key... I remember well how painful it was.

Sincerely, show the errors in the document, and better let them change (or not!) those errors when they want!

**Comment by ZZJHONS** [comment]
You know we could request a yes/no to all button to Robert? 

But it would be nice if BrickStore didn't change any ID automatically, but for it to show me the suggested change would nicely. Leaving it just as an error item leads to user to search himself a solution that not all would know how to fix.

**Comment by rgriebl** [comment]
Making this an information only box makes sense nowadays.

@ZZJHONS The automatic fixup via the changelog is not negotiable. Fixing lots in the old BrickStore was THE most frustrating experience.

**Comment by paramecie** [comment]
@rgriebl 

> The automatic fixup via the changelog is not negotiable. Fixing lots in the old BrickStore was THE most frustrating experience.

Agreed! But then make it "modified", see #295 ...
