### ISSUE TITLE
.bsx file corrupt after shared drive can't be found

### ISSUE THREAD

**Issue by Lynxarts** [rgriebl/brickstore#302]
A bsx file on our shared drive got corrupted after leaving the file open in BrickStore on our laptop overnight.

This morning we opened the laptop and got a warning from BrickStore that the shared drive and file could not be found (although it was still connected and able to access in Windows 10 1909). We restarted BrickStore and got a circle of death until it crashed.
After a reboot and recheck of being able to acces the shared drive we fired up BrickStore again and opened the file, it then said it expected a > instead of a =.
Looking into this file it had replaced certain lines with '?' and deleted most lines on the bottom. Restoring the file was possible due to some coding but useless since it had deleted most lines when it went corrupt (now going through 2000 drawers to sync our inventory back up since we changed a lot in the new database...).

We have used this method for the last few years with BrickStores predeccesor BrickStock wiithout issue.
Until resolved we will revert to local .bsx files which works great.

**Comment by paramecie** [comment]
Wow - great you could solve this!

I guess the "over night" case meant your laptop went in sleep or some off mode, and the connexion was reset/lost at one moment?

For 20 yrs I never ever work on a distant share (for this specific reliability reason).

This PC is organized in 10 drives, all are backed up differently on 5 other PCs (and reciprocally) and on a debian NAS.
I use goodsync and syncback pro, ultra powerful and stable tools.
Never lost a bit ;-)

I'm not sure Robert can do anything in this case; again, consider not working on shares?

**Comment by Lynxarts** [comment]
Thanks! The .bsx code is just xml so pretty easy to read, I opened another OK file for comparison in VScode and looked up the line that had issues.

I totally agree it's not the best way to work with files that are somewhat business critical (file goes corrupt means inventory not right) so we are looking into solutions to solve this permanently and implement a more robust redundancy. 

Synology Drive might be an option (the hardware is already here) since the files are stored both on the PC itself and only sync with the server when changed (rules out the connection getting lost as you pointed out!). It seems it also does versioning so backups of backups!

We have the situation back under control after a few hours so no harm done.

**Comment by paramecie** [comment]
Yep on Synology! I tried the Xpenology on a VM, and it worked very fine!
We're planning to migrate to Syn one of this days, but it takes some time ;-)

Note that locally you could set up a syncback pro to save the file under a different version/name (if different) every 30 minutes for ex, or some Time Machine like:
https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html#deloreancopy

But of course that means you've to *save* the BS file from time to time... I've seen people making 100 items list manually without saving until the very end :-(

**Comment by paramecie** [comment]
Try... catch... That's the whole meaning of Life.
