### ISSUE TITLE
Visibility of 're-apply filter' button doesn't update properly when switching tabs or opening files

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#303]
Suppose I filter a document by remarks (e.g. remarks~="tub"), then I change a remark so that the circular arrow to re-apply the filter appears. When I switch tabs the circular arrow will dissappear as expected but it will not re-appear when I return to the original tab. Even changing more remarks in the document will not make it re-appear.

The same thing occurs if I close the document and then re-open it when the arrow is not visible.

Win10, build #349

**Comment by paramecie** [comment]
> the circular arrow to re-apply the filter appears

I don't see any circular arrow or any reapply filter?
Win 10 specific (Win 7 here)?

**Comment by SteveTheBrick** [comment]
Maybe it's a new feature, I've never used it before today. It's at the far right of the filter bar and doesn't appear until you make a change that is 'incompatible' with the filtering. In the photo I changed the remark of the first item from 'Squirt 3' to 'Squirt 4' so that it no longer fits the filter. The little circular arrows appear and clicking them will re-apply the filter making that item no longer visible.

![filter](https://user-images.githubusercontent.com/77812338/111208254-6d5ea180-85c2-11eb-8bd6-6c200ce03bdc.jpg)

**Comment by paramecie** [comment]
Don't have this, sorry. Build 345 here.
Can't install an update right now, working on a project, many files not saved...
Tomorrow very probably.

**Comment by paramecie** [comment]
Just installed latest build, 349, don't see this re-apply thingy, sorry :-(

**Comment by rgriebl** [comment]
Don't let Sylvain get in your head :) 
The button does exist and you're right - it isn't restored when switching documents.

(@paramecie filter for something, then change any field in one of the visible items)

**Comment by paramecie** [comment]
@rgriebl grmlbmblblbl

Question, why not an auto reapply (after a validated edition)? Just wondering - I didn't think at this much...

**Comment by rgriebl** [comment]
Same as for not sorting dynamically while editing: your item will jump around or vanish while editing.
Say you filter on "used" and then change one item's cond. from used to new -> gone. I had this behavior in at one point, but it's irritating as hell, so it got removed quickly.

**Comment by paramecie** [comment]
Yep, I guessed so.
