### ISSUE TITLE
Installation vanity ;-)

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#306]
You could show a "company" and a website:

![image](https://user-images.githubusercontent.com/32078594/111383130-19c68380-86a8-11eb-8eb5-0a1f5d76860d.png)

It's Revo Uninstaller (I recommend!) but it's the same with the Windows standard one:

![image](https://user-images.githubusercontent.com/32078594/111383433-7e81de00-86a8-11eb-958d-682244ef151d.png)

But I noticed you're already here:

![image](https://user-images.githubusercontent.com/32078594/111383257-424e7d80-86a8-11eb-944c-76ce3db9382f.png)

Great!

**Comment by rgriebl** [comment]
Accidentally committed together with the sentry changes.

**Comment by paramecie** [comment]
Yep - nice !

![image](https://user-images.githubusercontent.com/32078594/111715395-048e5800-8854-11eb-93ca-3e6a768755ed.png)
