### ISSUE TITLE
Autosave restored file, when saved produces invalid BSX

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#307]
* Open BS, create a new file with a few items
* Wait a minute or more
* Open task manager and kill BrickStore

* Reopen it, it says:

![image](https://user-images.githubusercontent.com/32078594/111383749-f51edb80-86a8-11eb-8dc7-683425290bca.png)

* OK, open, it opens fine, problem solved - but no...
* Save the file as is, give it any name, close it
* Try to reopen it:

![image](https://user-images.githubusercontent.com/32078594/111383917-2a2b2e00-86a9-11eb-9506-df411323f8e8.png)

**Comment by rgriebl** [comment]
All files saved with the last dev build have the ItemTypeId saved in the wrong format: e.g. `80` instead of `P` (80 is the ASCII code of P).
This is fixed now. I hope this didn't wreck too many files. If it did, I can add a temporary check when loading to be able to load these broken files.

**Comment by paramecie** [comment]
I wonder why anyone would code a ski?

![image](https://user-images.githubusercontent.com/32078594/111479902-b5e89d00-8731-11eb-9c08-035cf7f7263d.png)

Anyway, happy it's fixed!

**Comment by paramecie** [comment]
Ohhh seriously I now understand why some of the recent BSX aren't loaded in our process...
Same: `<ItemTypeID>80</ItemTypeID>`
