### ISSUE TITLE
Add Year release info on Info Tab

### ISSUE THREAD

**Issue by GreatBrickLab** [rgriebl/brickstore#309]
Sometimes I like to know the year of released parts.

**Comment by paramecie** [comment]
Yes but the info tab doesn't show if less than 2 items are selected.

Then what would you write ?
1980/1990?

And for 3 lots?
1980/1982/1990?

I'm not sure about this, sorry to say.

**Comment by rgriebl** [comment]
I'm with Sylvain on this one. I have no idea how to display that information in a clean way in the info tab.
Even if you don't need it all the time, you can quickly show/hide the `Year` column by right clicking the column headers. 
Or you could even save a custom column layout and quickly switch between your "normal" and the "with-year" layout.

**Comment by GreatBrickLab** [comment]
Thanks for the consideration on it.  Appreciate it.  Development has been
great so far  Wonderful in fact!   Thank you!
