### ISSUE TITLE
Feature-Request: Fast way to duplicate item

### ISSUE THREAD

**Issue by AllesMeins** [rgriebl/brickstore#311]
Hi, one action I need to perform quite often is to duplicate one item in brickstore.  I use this if I want to add a similar item with a small difference, using the already added item as a blueprint - for example while parting out I notice that one of my ten 2x4 plates has a wrong color. In these cases I like to take the existing entry, copy it and than change color and quantity accordingly. But to do this I've to do quite a few steps

1. Select the part
2. Chose copy
3. Chose paste
4. Confirm whether I want to replace or create a new entry (-> select new entry)
5. Confirm whether I want to consolidate the new entry with the old one (-> no)

Would it be a lot of work to add a "duplicate this entry" to the context-menu that does just that without any other dialogues I've to confirm?

**Comment by paramecie** [comment]
Sure would be nice!

**Comment by ZZJHONS** [comment]
I use to do this sometimes too

**Comment by paramecie** [comment]
Nicely done Robert, thanks!

**Comment by AllesMeins** [comment]
Great, thank you for the fast response/fix!

**Comment by ZZJHONS** [comment]
Works awesome! and Ctrl+D is perfect!
