### ISSUE TITLE
Build 375, Cancel edition doesn't cancel on docs having obsolete refs

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#312]
Right now (Build 375), BrickStore changes the references (thank you), but:

* open a file with an obsolete reference
* pass the message box
* edit a single Comments with "a" for example, or a qty...
* cancel the edition

The cancel should remove the "Modified" status (the "*") of the document, it doesn't.

It works for other documents where no reference has been changed.

**Comment by rgriebl** [comment]
Works as expected: there has been a change (the changelog being applied) that is not undoable. 
Why should changing some other unrelated field and undoing that reset the modified status?

**Comment by paramecie** [comment]
No no - compare to a "normal" file which hasn't obsolete ref?

**Comment by paramecie** [comment]
Sounds linked to #313 same problem modifed/not modified.

See how your work is simple now :)

**Comment by paramecie** [comment]
Build 383 for #313 solves it also.
