### ISSUE TITLE
Build 375, mark document modified when opened with a changed ref?

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#313]
Right now (Build 375), BrickStore changes the references (thank you), but:

It changes the displayed reference, but doesn't permit to save the file with the new reference.
Apart editing a comments...

This is a problem:
* as every time you'll open this file it'll complain,
* as searching in the _contents_ of your files doesn't permit to find the new reference (as the old remains in the file).

I recommended to mark the file "Edited" after a reference change, so the user can decide (or not) to update his document?

See #295 - what's the other users think?

**Comment by rgriebl** [comment]
BS does exactly what you want on my end. I open an old file, it tells me X references have been updates, the file is marked modified (*) and I can save it

**Comment by paramecie** [comment]
Not here :-(

**Comment by paramecie** [comment]
I took this one, as the others were having problems:
https://github.com/rgriebl/brickstore/actions/runs/671847724

**Comment by paramecie** [comment]
I tested: Build 382 doesn't either!

**Comment by rgriebl** [comment]
Yes - that's it.

**Comment by rgriebl** [comment]
No idea WHY though yet  ;)

**Comment by paramecie** [comment]
Happy I could helped!

**Comment by paramecie** [comment]
Build 383 works! Thanks!
