### ISSUE TITLE
Build 375, missing some catalog log changes for obsolete refs?

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#314]
BrickStore could find couldn't file the new reference of this part:

![image](https://user-images.githubusercontent.com/32078594/111890526-6a144d00-89ea-11eb-9486-5b249eac5009.png)

While a log change exists:

https://www.bricklink.com/catalogReqList.asp?viewYear=&viewMonth=&viewGeDate=&q=30225pb03&viewStatus=A&itemType=&viewAction=*

And this part is correctly listed in the Inventory of this set as:

![image](https://user-images.githubusercontent.com/32078594/111890598-18b88d80-89eb-11eb-9af7-5a82805bd6b7.png)

Maybe we would need #298 ?

**Comment by rgriebl** [comment]
https://www.bricklink.com/v2/search.page?q=30225pb03#T=A

Somebody has reused the old id for a different part. Since I don't have the information when ids were added to the catalog, I have no way  to detect this problem.

**Comment by paramecie** [comment]
Of course I HAD to fell on this case :-(

**Comment by ZZJHONS** [comment]
> https://www.bricklink.com/v2/search.page?q=30225pb03#T=A
> 
> Somebody has reused the old id for a different part. Since I don't have the information when ids were added to the catalog, I have no way  to detect this problem.

You can check the catalog page of the item ID, bottom left it is: added this item to the catalog on Feb 13, 2011

**Comment by rgriebl** [comment]
Same problem as with the "known colors": as long as this info is not available in a catalog download XML, it's not existent for BrickStore: I can't scrape 150000 HTML pages daily for updated information.

**Comment by ZZJHONS** [comment]
Ah sure, I didn't mean scrape everything, just as needed. But probably too much hassle for a few cases.

Searching I found we have https://www.bricklink.com/calendar.asp?v=C with daily item creations https://www.bricklink.com/catalogList.asp?itemDate=3/2/2021 so down to 7500+ scrapes the first time :)
Just needed to update if a merge occurs: https://www.bricklink.com/calendar.asp?v=Q&m=0&itemType=M

**Comment by rgriebl** [comment]
Sorry - I won't add any more HTML scraping code.

**Comment by rgriebl** [comment]
closing as this is a corner case BS can't handle
