### ISSUE TITLE
Import Orders combined...

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#316]
* Please make it possible for Placed orders also (very useful to list what's in arrival, for example...)
But (probably) don't allow mix of Placed and Received?

* Then the default name for the file should change, for something like:
Order Placed Multiple
Order Received Multiple

![image](https://user-images.githubusercontent.com/32078594/111938281-e92c8280-8ac9-11eb-83ee-83614ecaab33.png)

* Please set the Marker column position in the BrickStore Default columns just after the Remarks field, where it's far more useful than at the very end ;-)

![image](https://user-images.githubusercontent.com/32078594/111938074-7ae7c000-8ac9-11eb-826c-555cb9a6125f.png)

* Please finish this experimental feature, LOL - but no kidding, it's very fine!

PS: in case you wish to mix up ANY type of Order, then the Marker could differentiate them:
type/number/buyer or seller

Placed 12345678 bricskstore
Received 12345679 bricskstore

**Comment by rgriebl** [comment]
Combining placed orders does work for me... are you sure it doesn't on your side?

**Comment by paramecie** [comment]
Still not - mmmmh depends the currency?

The 2 first of this list CAN be combined.

If I add the 3rd one in the selection it CAN'T be combined.

![image](https://user-images.githubusercontent.com/32078594/112366233-d936bd80-8cd8-11eb-9244-a5f4f64e2bf5.png)

In fact, the 3rd one can't be combined to anything, it's in HUF currency, while the others are EUR.

**Comment by paramecie** [comment]
If that could help - and taking care of the different currencies - in this case you could throw a message like "All prices won't be combined as being in different currencies" [OK]

So you'd combine everything but with prices == 0 for example.

**Comment by rgriebl** [comment]
Ah - yes. Currently only orders of the same type and the same currency can be combined.
I'm running my shop in EUR-only mode, so this doesn't bother me. If it would be helpful to combine multiple currencies, I could do that relatively easily using the exchange rates from the ECB.

**Comment by paramecie** [comment]
I mean, and personnaly - I don't care for combined prices in multiple currencies. What's interesting is to make a list of what arrives (items, quantities...)
Then, when processing them, I can manage them one by one, with the proper amounts, no problem.

And I don't need this feature, but sure sure would use it if available.
I don't know what the others think?

**Comment by rgriebl** [comment]
Could you please test build 401? (should be ready any minute now)

I only have EUR orders in my account, so I can't test.

**Comment by paramecie** [comment]
Sure!
Downloading!
I must finish some task, I'll post in a moment from now...

**Comment by paramecie** [comment]
I don't have time right now to check everything, but build 401 converts it, and it seems fine!

![image](https://user-images.githubusercontent.com/32078594/112396244-1793a300-8d00-11eb-9880-c721b5719e5a.png)
