### ISSUE TITLE
Shortcut to print in PDF

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#321]
Nowadays people save more as PDF than print with a printer.

Consider adding a shortcut for it, maybe Ctrl+Shift+P?

**Comment by rgriebl** [comment]
`Ctrl+P` -> `Destination` -> `Save as PDF`

The menu item is just a shortcut for pre-selecting that destination.

**Comment by rgriebl** [comment]
You can set custom shortcuts via the Settings dialog. You could even re-map `Ctrl+P` to PDF printing (after remapping normal printing away from `Ctrl+P` to e.g. `Ctrl+Shift+P` first).
