### ISSUE TITLE
'Paste silent' is disabled when no items are selected

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#322]
I'm finding this new feature quite useful but when no items in the document are selected the 'Paste silent' menu item is disabled (greyed out).

Overwriting is obviously not an issue when no items are selected, but paste silent would still avoid consolidation.

Win10, build #409

**Comment by paramecie** [comment]
And, reminder, Paste silent should appear in contextual menu too ;-)
