### ISSUE TITLE
Feature Request: import filed orders

### ISSUE THREAD

**Issue by Lynxarts** [rgriebl/brickstore#323]
Would it be possible to have a checkbox in the 'Import> Bricklink order...' menu to also see and import filed orders?

Being able to import all past orders, without first un-filing them on BL, would be great to easily get more insight in sold stock.
We are able to do this now by unfiling orders on Bricklink and afterward refiling them but this but the addition of a one tick checkbox in BrickStore to work around this would be very welcome.

**Comment by paramecie** [comment]
On the other side, I never file placed orders, as after 6 months they disappear and until then the Received/Completed is enough... But sure that can help the ones who use it.
