### ISSUE TITLE
Tier quantities and prices not importing from store inventory

### ISSUE THREAD

**Issue by BrickSouth** [rgriebl/brickstore#324]
When I import my store inventory, items that have tiered prices have blanks in the Tier Q1, P1, etc. fields.

**Comment by rgriebl** [comment]
Seems like I broke this back in 2021.2.1 when I modernized the XML parsing code. You are the first to notice though 😁

**Comment by paramecie** [comment]
Tiered pricing is crazy anyway. I wish I could charge **more** if people buy in quantity :-)
