### ISSUE TITLE
Add "Save as" button to pictures

### ISSUE THREAD

**Issue by chedenq** [rgriebl/brickstore#325]
Is it possible to add "Save as" button to parts picture? Or "Copy" to paste it in word for example.
![image](https://user-images.githubusercontent.com/78899121/112754788-5cf8ee80-8fe6-11eb-8b45-8bb4700bfa6e.png)
I mean in this menu add one more button, that allow me to save picture as jpg, png, etc.

**Comment by paramecie** [comment]
Build 414: nice, Robert, gg!
