### ISSUE TITLE
First Time Uploading BL store inventory, gives error. 

### ISSUE THREAD

**Issue by UticaBrix** [rgriebl/brickstore#326]
Give me an error  when I try to upload my BL store inventory.  Any advice?

**Comment by rgriebl** [comment]
Please be more specific than "an error". What does it tell you?

**Comment by paramecie** [comment]
... that he should read his email for help :)

**Comment by UticaBrix** [comment]
This is my first time downloading Brick Stock and this is the error I get…

 

Error: Download failed: unsupported protocol

**Comment by paramecie** [comment]
Dave I proposed to help you directly, as you asked for...

**Comment by rgriebl** [comment]
This error message comes from *down*loading either your store inventory or the database (no *up*load). 
What's really strange is that HTTPS seems to be broken on your machine. What operating system are you running and which BrickStore download from the release page did you install?

**Comment by paramecie** [comment]
The error was he used a 2006 BrickStore, or such :)

I helped him on teamviewer, we set up the latest release, and now he's ready to rock and roll.
You can close this issue Robert.

Ah - but he'd prefer a Dark Mode, I asked him to open an issue, but anyway I just write it here...

**Comment by UticaBrix** [comment]
Thank you again!   This software is really amazing!!

I want to thank Sylvain, he was very very helpful, detailed and explained things very thoroughly.   
Thank you all again!
Dave
Utica Brix
