### ISSUE TITLE
Improve Known colors checking if image exists?

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#328]
I don't know if this is possible without a lot of scrapping, but maybe the Known colors list on BS could be increased with all the colors that have image for the item.

Part 970c00pb0495 has only 1 known color but exists in 2, you can check this page: https://www.bricklink.com/catalogColors.asp?itemType=P&itemNo=970c00pb0495&v=2

So maybe a check of the existence of the URL for this image in each colo Color ID can be done: https://www.bricklink.com/P/63/970c00pb0495.JPG

63 is the BL color ID, if the image does not exists it redirects to a 404 page.

**Comment by rgriebl** [comment]
There are 182 colors times ~150,000 parts. No way you could check that on once every X day level, that would be needed to have it properly in the BS database.
But even if I would do the checking dynamically at runtime, I would have to send 182 HTTP HEAD requests for every item you click: this takes some time, so the user experience would be terrible: I can't just block the UI while waiting, but then suddenly the list of colors would change while the download results are coming in.

Apart from the obvious problem, that BL won't be happy with everyone hammering the server with picture requests that are probably unsuccessful around 99% of the times.

No - the only way to get that information into BS properly is for BL to add that information to the catalog download XMLs. I've asked the devs and got the response "will look into this". Maybe you can try to build some pressure via the forum if enough people chime in?

**Comment by ZZJHONS** [comment]
I know this was gonna be your reply, just wrote a way this could be accomplished :)

I have tried my best with the forum suggestion...
