### ISSUE TITLE
Please sort Currencies

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#329]
This is a mess:

![image](https://user-images.githubusercontent.com/32078594/113292677-1e6c7800-92f5-11eb-9d6c-1c752ce43da3.png)

At least by ascending name, or maybe better, in 2 groups, a first group of "most used ones" (sorted) then a sorted group for the others, like:

-------------- 
Default currency USD
-------------- 
CAD
DKK
EUR
GBP
PLN
...
-------------- 
BGN
MYR
...
-------------- 

_No idea why this list shows bold in Github, anyway..._

The first group may be found on the Net as "most used currencies" or such...

**Comment by paramecie** [comment]
BTW it seems this orders changes depending something... probably as you scrape the exchange rate page?

**Comment by rgriebl** [comment]
The list WAS sorted alphabetically before I optimized the internal data structure. Guess I'll un-optimize it now ;)

**Comment by paramecie** [comment]
Please tell me it's not *always* my fault!
