### ISSUE TITLE
Appears in Set widget

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#33]
1) I think the left column title should be "Qty" and not "#" which is more meaning "number", AFAIK?

2) The default sorting order seems to be increasing qty, and I don't think it has any use?

![image](https://user-images.githubusercontent.com/32078594/103690364-e7582600-4f94-11eb-9b75-3a6afd9934b5.png)

For me and IMO, it should be sorting **decreasing Qty** by default, as it's more interesting?

![image](https://user-images.githubusercontent.com/32078594/103690459-0ce52f80-4f95-11eb-919a-d449347fe552.png)

Or set number, but increasing qty doesn't seem interesting (to me).

But I don't know for other people...

That could be an option setting too...

**Comment by paramecie** [comment]
2021.1.2 perfect, thank you!

**Comment by ZZJHONS** [comment]
I always changed it to decreasing Qty. Nice addition, thanks!
