### ISSUE TITLE
Copy Values From Document button/Remember last setting

### ISSUE THREAD

**Issue by BrickSouth** [rgriebl/brickstore#330]
Maybe I am the only one who works this way, but I thought I'd throw this out there...

When I am cataloging used parts, I begin with one element that I may have several different colors of, put them all in a BrickStore file, then click Copy Values From Document to populate the remarks for those parts. I only do a handful of lots a time so as not to have parts strewn everywhere and lose track of where they need to go. So I am frequently having to go to the Edit drop down to get to Copy Values From Document.

My first thought was a Copy Values From Document button along the top menu bar. I am using it so much, I feel it justifies having its own button. Again, maybe it's just me. I'd love to hear how other used part catalogers use this...

Another issue is that now it comes with a dialog with all kinds of copy and merge options. I really only need remarks. Right now it defaults to the same thing every time it opens and I have to click all fields ignore and then click copy for Remarks. It would be great if it would remember your last setting.

**Comment by paramecie** [comment]
> My first thought was a Copy Values From Document button along the top menu bar. I am using it so much, I feel it justifies having its own button.

I wouldn't need this button, but much more an Options button...
Some would need something else.
I guess in this case what would be VERY nice is a configuration tool for the toolbar ;-)

> Right now it defaults to the same thing every time it opens and I have to click all fields ignore and then click copy for Remarks. It would be great if it would remember your last setting.

Yes, it was already signaled in an old Issue, don't remember which one.
As BrickStore retains everything, it's a shame this window doesn't :-)

**Comment by ZZJHONS** [comment]
Indeed I use this and feel it is far away from reach, could be more high on the menu and also in the left click menu...

About the remember values, I already put the issue #252
