### ISSUE TITLE
Can't compile latest release (private/qsimd_p.h: No such file)

### ISSUE THREAD

**Issue by AllesMeins** [rgriebl/brickstore#331]
Hi,

on my system (Linux, Aarch64-Processor) the compiling of the latest version fails (2021.3.3). Are there any new dependencys I would need? The last Version I used was 2021.3.1 and it compiled fine.

The error is:

```
src/utility/q5hasfunctions.cpp:15:10: fatal error: private/qsimd_p.h: No such file or directory
15 | #include <private/qsimd_p.h>

compilation terminated
make: *** [Makefile: 2534: .obj/release/q5hashfunctions.o] Error 1
```
Do you have any idea how I could fix this?

**Comment by rgriebl** [comment]
You need the private headers for QtCore and QtGui. `apt install qtbase5-private-dev` should do the trick and that is also what is done by the GitHub CI runner (https://github.com/rgriebl/brickstore/blob/master/.github/workflows/build_qmake.yml)

Which Qt version are your trying to compile against?

**Comment by AllesMeins** [comment]
> You need the private headers for QtCore and QtGui.

Thank you, that has done it!

> Which Qt version are your trying to compile against?

Qt 5.15.2

I want to thank you again for the work you're doing here and all the time you're investing! Thank you very much! Unfortunately I don't have the skill to do some actual helping with the development, but is there a way I could send you some small donation? What you have don here saved me a lot of time, so I'd like to give something back...

**Comment by rgriebl** [comment]
Oops .. just noticed, I forgot to reply and close this bug. 
If you still want to donate, then just click the `Sponsor` button at the top the page. Thanks!
