### ISSUE TITLE
Could we have a new Document Column: "Rating" ?

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#332]
Rating or some other name, the idea is to give a "rating" value from 1 to 9 for every lot you'd like to.

Those values could reflect:
* what is important to take care of
* what is to buy, or to sell
* if, for example, a price or a lot is critical and needs attention
* a todo list showing the order...
* an emergency (time depending),
* etc.

Right now I guess people use Remarks or Comments to say this, but we could have a separate column for this!
See the column at the right here (it's an example):

![image](https://user-images.githubusercontent.com/32078594/113599511-ff485000-963e-11eb-810d-f138e292e384.png)

How it could work:
* normally it has zero (the field is empty)
* it would have different colors, **1 to 3 = red, 4 to 6 = orange, 7 to 9 = green**
* it's a bit like "x", "+", "v", when you double click on it it puts "1" then puts "2", then "3", "4"... etc
* or you can directly type 1 to 9 (ONLY 1-9 are authorized)
* you can sort using this column, or filter on it, like "Rating >= 4"
* of course this column could be moved anywhere you'd prefer, or hidden
* changes can be cancelled...

Why not continuing to use Remarks or Comments ?
They don't automatically switch from 1 to 9, there's no color, they're already often used for comments and part location, etc.

Hoping it makes sense... please other people, push this if you'd like it ;-)

**Comment by rgriebl** [comment]
I've now created a super-task issue for custom columns: #617

I will close this issue here however, as it will not be implemented in BrickStore itself and just sitting around in the bug tracker as an open bug for years doesn't help anyone.
