### ISSUE TITLE
Crash on paste and consolidate

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#334]
Please have a look at the attached bsx file, there's a 100% reproducible crash for me on Win10 with build #416.

To reproduce:

Part out the first item (the flagstand) to a new document.

Select all items in the new document and copy (ctrl-a, ctrl-c).

Go to the original document and paste (ctrl-v).

Select 'yes' to overwrite. In the consolidate dialog select 'prefer new items' and click 'yes to all'.

Brickstore crashes.

[Test.zip](https://github.com/rgriebl/brickstore/files/6267153/Test.zip)

**Comment by rgriebl** [comment]
I know already ;)  I had 3 sentry.io crash reports incoming the last days and I just figured the actual reason out a few hours ago. It's a bit tricky to fix though, so it'll take a bit.
The reason why it crashes, is if there are multiple lots in the paste that would be merged into the same existing lot.

**Comment by SteveTheBrick** [comment]
Thanks for letting me know, Robert, it looks like sentry is proving useful! I guess you'll soon have several more reports that I caused by testing this tonight.
