### ISSUE TITLE
Improve Lot Consolidation 

### ISSUE THREAD

**Issue by GreatBrickLab** [rgriebl/brickstore#337]
Could the lot consolidate be changed?   When we download our entire store and then consolidate everything, the list of lots consolidated is not easy to identify.  If a new file was created or some other flag made then we could use that data to find the multiple lots task the work out.

**Comment by cwmcd** [comment]
to clarify, are you saying you have multiple lots of the same item in your online store?

**Comment by GreatBrickLab** [comment]
That is correct.   Maybe we will regret it later, but our current strategy
does not consolidate lots as we add parts.  Allowing us to add parts much
much faster.

**Comment by cwmcd** [comment]
ok, i suspect you may have the same strategy as me. can you explain your current strategy 'in a nutshell'?

**Comment by GreatBrickLab** [comment]
Yes,   We have a backlog of cataloged parts from employees that work from
home.  They use BrickStore to create files that we store in boxes for a
later time to upload.  We are moving to a large warehouse in a few months.
Ramping up our size we agreed to increase prices and load all the bags as
new lots.  That way we don’t have to walk the isles to consolidate lots or
change a location if a drawer is now too small.  We fill drawers with lots
limited only by the size of the drawer.  Adding parts like this has sped up
the process considerably.  We thought about an employee to consolidate
lots,  if a list could be made or printed of a repeated lot
; the process could be easy.  We could also focus on the ones that have the
most repeated.  Like black legs?   Why does my daughter keep adding one or
two qty count lots every time she works!!!  Ahh!!!  Oh well
She catalogs like a champ.

One more thing,  this new strategy has open a door that we did not expect.
 1. We have lots at multiple prices,  making for interesting results from
customer orders.  2. We have a cataloging desk that has 5 new drawers that
we add parts directly to and then add them right to the store.  Making for
a improved load time for minifig adds and sets part outs.

Big nutshell!

**Comment by cwmcd** [comment]
ok so this is roughly my workflow:
-i have a box that has empty, NUMBERED containers.
-i crack open a set, sort all the colors into BLANK containers
-then i go into brickstore, part out the set and check for stuff that needs special attention (extra parts, wheels vs tires/hubs, etc)
-i then set the list to sort by color and grab the BLANK container holding that colors parts and get to it.
-dump the container into a tray and look for the first item.
-pull all the first item, make sure its got the proper amount and grab an empty NUMBERED container and make a REMARK in brickstore what number container that is.
-rinse repeat
NOTE: when i'm done with one color, i like to save the file (just in case) and if i'm done for the day i may copy those 'done' colors to another tab and export that for upload to get them online.
-when that's all done, i go to file>export>mass UPLOAD, which i have set to pop open the bricklink upload page
-at the mass inventory upload page i select <consolidate lots by using> and then either leave everything at "old" or maybe change to use the <new pricing> or whatever, not terribly important.
-but what IS important is, i check the <concatenate old and new remarks>
so what this does is, it will take the NEW remark with the NEW container number and ADD it to the EXISTING remarks in my store with existing container numbers. 

so you'd end up with something in your remarks resembling: 238, 553, 1, 22

these are all the locations that have that part.

so when i go to pick an order, i'll see that row of numbers. personally i like to start at the highest number (553 in this case) and grab what i need from that until empty. and then put that empty NUMBERED container ASIDE for the moment.

at some point when someone is idle, they can go into bricklink and do a remark search for the empty bin numbers and remove them from the remarks and then throw them in the box for reuse.

also at some point (either during order pull or idle time) you can import the store inventory in brickstock and go through and find the items that have multiple locations, pull them and consolidate, update remarks in bricklink interface to new bin number or remove other bins. at this point you can move your lots into more appropriate sized bins. i actually use multiple size bins as well.

IN ANY CASE, that's basically my flow and the point is is to keep your online store inventory clean so when people search for a part on your store they don't see multiple copies and wonder what the difference is, and also so you don't have to worry about downloading, consolidating and reuploading.

the <consolidate lots by using> and <concatenate old and new remarks> can really help keep track of multiple physical lots while keeping your store inventory clean. this will also help with multiple lot prices.

also this would cover your 'employee to consolidate lots' and also have them edit the remarks to remove the empty bins and prepare them for new parts!

who knew working assembly line/parts management jobs would prepare me for selling lego lol

hope this helps for some of your issues and congats on the store expansion!

**Comment by GreatBrickLab** [comment]
Awesome, thanks!   I do wonder what the the multiple prices abs lots has on
customer presentation.   We are just experimenting right now.  We totally
want to expand quickly and keep the # of employees down.    I will review
your comments with my team and see what we can do

**Comment by cwmcd** [comment]
anytime!

yes, when you look for a part in a store, you'll see multiple listings of the same part. so if i search for a red 2x4 brick in your store and you have 5 all with different prices, it will show me all 5 with all the different prices.

whereas if you select 'consolidate lots by using' and either leave the 'old pricing and old tier pricing' as is or change to 'new price', it will take what you are uploading, add it to the EXISTING lot in your store and update the single listing with the new quantity (existing+new) and will update the pricing.

together with the 'concatenate old and new remarks' you'll end up with a single listing in your store with updated pricing, quantity and remarks.

hah guess i could have said that earlier lol, just figured sometimes seeing other people's flows may spark new ideas.

i'm a one man operation and for me, that particular workflow helps me to be able to compartmentalize parts of the operation and move swiftly through each, while also being able to migrate between operations as needed.

**Comment by cwmcd** [comment]
looking back on your flow:

you could take the backlog of cataloged parts with (i'm assuming) the brickstore files to go with them.
put the lots away and put the location numbers in the remarks field
select 'concatenate old and new remarks on the bricklink upload page.
and done.

then at a later date, import your store into brickstore
look for the lots that have multiple locations, pull, consolidate, put empties aside.

then when you're ready, via bricklink backend search for empty bins in remarks, update and put empties back ready for use.

**Comment by GreatBrickLab** [comment]
I do also want to say thank for starting work on the tool again.  My team
has been blessed by the use of it.  It has become a integral part of day to
day operations.  I would like to make some updates to my YouTube channel
showcasing the way I use it. Especially the updates in search.  I am able
to get to many parts with no need for BL at all.     Did you ever see my
commentary on the reverse color search?   I don’t think it would work great
as the code coming back from BL does not always come in with the right
colors.  The feature of known colors was a cool add too.  Have you ever
seen FIO (figureitout.app)?   They have some great code for minifig
searching.  FIO and BrickStore could be a combo tool with even more power
to find parts.

**Comment by cwmcd** [comment]
sadly i am just a helpful community member. but i agree brickstore is a great tool. i've been using it for years.

the devs here are always glad to hear what the community has to say tho!

i had never heard of the figureitout.app. looks very interesting. i had mentioned in another thread that it would be nice if brickstore had a plugin feature for community addons and addition service api addons.

that figureitout.app looks cool! yes if they had an api and brickstore had plugin capabilites that'd be very interesting indeed!

i'll have to check out your youtube channel!

**Comment by Randallflagg0** [comment]
Ouch, any store that has multiple lots for the same item in the same condition goes on my least favorite list.  It makes for not only a chaotic store but when I am shopping by wanted lists and it shows many unique lots, then I found out it is 5 listings for the same item in the same condition, the bookmark comes out!

**Comment by GreatBrickLab** [comment]
Thanks for the feedback!  We are still getting a lot of sales with the
change.  However I was not sure of the impact to customers experience with
shopping our store.  I am satisfied that we will continue this way as we
are adding parts for quicker than ever before.  An effort later maybe taken
to consolidate them.

**Comment by Randallflagg0** [comment]
I'm sure I am in the minority when it comes to this but it is kind of like assembling new minifigures.  I figure no one is going to complain if they aren't assembled but some people might complain if they are.

**Comment by cwmcd** [comment]
> Ouch, any store that has multiple lots for the same item in the same condition goes on my least favorite list. It makes for not only a chaotic store but when I am shopping by wanted lists and it shows many unique lots, then I found out it is 5 listings for the same item in the same condition, the bookmark comes out!

@Randallflagg0 agreed, double lots are one of the major cardinal sins as a bricklink seller.

**Comment by cwmcd** [comment]
> I'm sure I am in the minority when it comes to this but it is kind of like assembling new minifigures. I figure no one is going to complain if they aren't assembled but some people might complain if they are.

@Randallflagg0 also agreed. if they are listed as 'NEW' then in my opinion they should NOT be assembled. that'd be like selling a set as NEW but prebuilt.

**Comment by GreatBrickLab** [comment]
Speaking of which,  we are able to ship our own store for parts to build
figs all the time.

**Comment by rgriebl** [comment]
Going through old reports...
The consolidation process has been completely rewritten since this issue was created and is much more user friendly now, so I'm closing this one here. I won't change anything major in the new consolidation workflow, but if you think minor tweaks would be useful, then please open a new report.
