### ISSUE TITLE
Please add Clear item menu to Remark and Comment

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#34]
I know that's lazy, but I don't think I'm alone ;-)

A Remark / Clear item menu would clear the Remark, and the same for Comment.
And also in contextual menu of course.

![image](https://user-images.githubusercontent.com/32078594/103691015-ce9c4000-4f95-11eb-9f0d-6018d6bfc8df.png)

**Comment by chiminirc** [comment]
I do regularly edit, clear field, and save. Having a CLEAR on the context menu would be helpful.

**Comment by ZZJHONS** [comment]
So the same function as click add remark and leave empty and accept?

**Comment by paramecie** [comment]
> So the same function as click add remark and leave empty and accept?

Not exactly: when you already have a Remark, the windows Set Remark shows the already filled Remark.

So to clear a remark, you've to Set Remark, empty it, validate : 3 steps instead of Clear remark (1 step).
