### ISSUE TITLE
Custom print template still not working 100% correctly

### ISSUE THREAD

**Issue by BrickSouth** [rgriebl/brickstore#342]
I followed the steps to use GreatBrickLab's print template, but it is still missing the remarks and marker columns. There are a few other differences as well. When I print using the "paper saving printing" option to put two pages per sheet, it doesn't fill up the whole sheet as well as it does when you print from BrickStock. Is there a reason the BrickStore version looks so much different than what you get out of BrickStock?

Comparison:

**BrickStore**
![printing1](https://user-images.githubusercontent.com/76957522/117008725-a35dff00-acb0-11eb-952f-bf0a87b742b6.png)

**BrickStock**
![printing2](https://user-images.githubusercontent.com/76957522/117008736-a5c05900-acb0-11eb-8965-545ba2ecc78f.png)

**Comment by rgriebl** [comment]
There are 2 print templates attached to #81 and I thought they were the same. I ported the one attached by Sylvain, but GBL's one is actually different.
I'll have a go at porting the actual GBL script.
