### ISSUE TITLE
"Appears in Sets" not working with certain parts

### ISSUE THREAD

**Issue by henriquedesousa** [rgriebl/brickstore#344]
Some parts fail to appear in the section "Appears in Sets" 

An example can be:

53562pb03 in Glow in Dark Opaque
45705 in Dark Bluish Gray
40395c01 in Sand blue

and some more. If you need printscreens/videos, I can show it to you. 

Many thanks in advance.

**Comment by rgriebl** [comment]
The database has now been regenerated.

**Comment by henriquedesousa** [comment]
Thank you very much for your help, appreciated.
