### ISSUE TITLE
BrickSync Compatibility - suggesting a separate export / save as function for BrickSync

### ISSUE THREAD

**Issue by RedWolves** [rgriebl/brickstore#345]
BrickStore saved files don't work in BrickSync due to some extra meta information being saved to the XML file and the bad XML parsing of BrickSync can't ignore the added information.  

Basically BrickStore is saving the `Currency="USD"` on the root `<Inventory>` element.  This causes BrickSync to think the file is not a bsx file and spits out an error. 

Suggestion: Can we have an export or save as command in the file menu that will save a copy of the file in the format that BrickSync expects?  Additionally, maybe some advanced preference setting to set where this file gets saved to.  Since BrickSync expects the bsx file to be in the root of the BrickSync folder we can set that path and then we can save the copy to the BrickSync folder while maintaining the original in it's current place. 

Currently there are two work arounds for this.  Open the bsx in a code editor and remove the currency property, save and run in brickSync.  Or open the file in BrickStock save as ontop of itself and run the command in bricksync.

**Comment by rgriebl** [comment]
I have fixed this upstream in BrickSync already.

You can get a fixed build here: https://github.com/ZZJHONS/Bricksync/actions/runs/712450306

@ZZJHONS just needs to click the `release` button to make this into an official release that everybody can download without being logged into GitHub. Please pester him to finally do it :)

**Comment by RedWolves** [comment]
YOU DA MAN!!!

**Comment by ZZJHONS** [comment]
@rgriebl @RedWolves something like this?

https://github.com/ZZJHONS/Bricksync/releases/tag/v1.7.2-3
