### ISSUE TITLE
Feature Request: Reset Differences

### ISSUE THREAD

**Issue by CamelCityBH** [rgriebl/brickstore#350]
On  the older package (by another name), there is a menu item under "Edit" that allows the user to "reset differences" for only items selected.  I have not found this on BrickStore.  If it is there, please point me to it.  If not, that has been a GREAT feature for updating partial inventory.

**Comment by rgriebl** [comment]
It has just been renamed: `View` > `Reset Difference Mode Base Values`

**Comment by CamelCityBH** [comment]
Every time I've tried that, it resets ALL difference mode values, not just those selected.
