### ISSUE TITLE
PG mismatch

### ISSUE THREAD

**Issue by rgriebl** [rgriebl/brickstore#351]
@ZZJHONS: I've moved your comment to a new issue, since it's not related at all

![image](https://user-images.githubusercontent.com/1063368/118138779-006f5880-b407-11eb-8a60-eef9197b6e4f.png)

@rgriebl Do you know why Ctrl+G Current Average doesn't match? Most items are off by 0,001 and some even more.

**Comment by rgriebl** [comment]
I can't reproduce this with 29115 in red .. it's 0.281 on both sides for me

**Comment by rgriebl** [comment]
Did you have this document open for a longer time (hours)? I think you got a new EUR<->USD conversion rate update from the ECB and the price guide widget doesn't update, unless the currency *code* changes. It should also update when the *rate* changes, but doesn't right now.

**Comment by ZZJHONS** [comment]
Yes, that seems to be the problem, the file was open for about 2 or 3 days. 
Just closed it and reopened, now prices match exactly.
