### ISSUE TITLE
Open orders

### ISSUE THREAD

**Issue by TGS4114** [rgriebl/brickstore#352]
When opening an order, I can only choose among "open orders". how can I load an Bricklink order with status "completed"?????

**Comment by cwmcd** [comment]
are you going to file > import > bricklink order?

**Comment by TGS4114** [comment]
Yes, and only the open orders shows up + some random ones. 
As you can see I get 5 new orders and 2 old from 01-01, but I have a lot of orders between these.


![Skærmbillede 2021-05-16 120234](https://user-images.githubusercontent.com/83815923/118393286-a35de780-b63e-11eb-8b01-2ace00a3ca38.jpg)

**Comment by cwmcd** [comment]
i'm curious, i'm assuming you are talking about orders you receive, are you actually missing ones 'between' or just earlier than 4-23-21? bricklink does purge older orders and it's my understanding that they are no longer available.

but your original question was that you wanted to be able to open orders marked 'completed' and not that you were missing orders.

if you click on, say, 4-23-21 completed order and hit import it should open it in a tab.

if you're talking about finding old orders, i'm thinking they may have already been purged from bricklink.

if you go onto your orders received page on bricklink and in the top right select summary, do you see the missing orders?

**Comment by TGS4114** [comment]
Sorry, I'm not that good at english.
I have a lot of orders between 01-01-2021 and now, some of them are listed in the 
picture. I wnat to be able to open any order no matter it's status.

![Skærmbillede 2021-05-16 200403](https://user-images.githubusercontent.com/83815923/118407629-f1480f00-b681-11eb-8d31-f6694f9c6f89.jpg)

**Comment by TGS4114** [comment]
Ordres are purged from Bricklink when they are 180 days old. If you see in my first picture I had set the "days" field to 360 days, but I only got 7 orders listed. As you can see on the this picture I have at least 10 pages with 10 orders each, that are less than 180 days old.

![Skærmbillede 2021-05-16 201119](https://user-images.githubusercontent.com/83815923/118407883-15f0b680-b683-11eb-8a52-a09049308fed.jpg)

**Comment by cwmcd** [comment]
@rgriebl @TGS4114 
hmmm, ok yes, unless i'm missing something this does seem to be an issue.

what version of the software are you using? i'm using 2021.4.1 (build 429). it seems to work for me with no missing orders

**Comment by TGS4114** [comment]
Same version as you, I have tryed the x86 version too, same problem. And it is a BIG problem.
Can there be a hidden setting somewhere??

**Comment by TGS4114** [comment]
Problem solved, the program obviously only get "unfiled" orders on Bricklink. Any way to get an "filed" order without "unfile" it first????

**Comment by cwmcd** [comment]
bah, bricklink maintenance so i can't also confirm.....

but that sounds like it would make sense. i never 'file' my orders and i see all of them in brickstore.
