### ISSUE TITLE
Outdated Items Have Been Updated

### ISSUE THREAD

**Issue by shaggyonjd** [rgriebl/brickstore#353]
Getting this warning when opening a BSX.
Is there any way to find which items have been changed?

![BrickStore Error](https://user-images.githubusercontent.com/81053064/118356254-2f530f00-b56c-11eb-83bc-bc42b4c5e334.png)

**Comment by cwmcd** [comment]
can you link your bsx file?

**Comment by shaggyonjd** [comment]
It's the inventory for 71016 The Kwik-E-Mart.

[Inventory for 71016-1.bsx.txt](https://github.com/rgriebl/brickstore/files/6489313/Inventory.for.71016-1.bsx.txt)

**Comment by cwmcd** [comment]
ok so if you go to view>view info docks and enable 'error log' you can see what failed.

in this case it was the following:

![image](https://user-images.githubusercontent.com/7256436/118407356-4dd10d00-b635-11eb-9603-e43fa046f63f.png)

**Comment by shaggyonjd** [comment]
Nice one.  Thanks for that, much appreciated.
Good to know where to find that Error Log  :)
It's because BrickLink re-numbered the decorated 2x4 tiles with an extra 0.

**Comment by rgriebl** [comment]
Duplicate of #315
