### ISSUE TITLE
right click to add from + "add items" menu

### ISSUE THREAD

**Issue by GreatBrickLab** [rgriebl/brickstore#355]
Wow!   that new lock on color has improved my speed to add parts my near 3-4 times.   I was able to add 50 heads in less that one hour.    That is HUGE!!!!!!!!!!!!!        Now for the next item to help improve speed.     I was searching for a white torso "ninjago"   Found it pretty fast.  Also found the fig from the "Show what sets it appears in" menu.    I suggest adding a right click function from that menu to add the fig to the file.  Then I don't need to change to minifig and find the fig,  just add from there.   That would help alot. 

Chris
GBL
![Screenshot 2021-05-20 143714](https://user-images.githubusercontent.com/76892578/119038580-e5f22d80-b978-11eb-98e6-88555d01bd78.png)

**Comment by GreatBrickLab** [comment]
Just another thought,   if you could add a filter capability to the menu items for adding parts that could help when I am working on minifigs only,   for example.   if I could check only the categories I am working with at a time Like  (minifig torso and headgear)  then only list those categories that would help speed also.   Perhaps a custom Item Type capability.

Chris 
GBL

**Comment by SteveTheBrick** [comment]
Yes, the colour lock is massive time saver (especially for heads!).

I would also love to be able to insert items from the 'appears in' widget - not only in the insert dialog but also in the main window. Whenever I work with minifigs I regularly see a figure in the 'appears in' list that I want to insert but I have to remember the part number and open the insert dialog.
