### ISSUE TITLE
Error Updating Database - MacOS Big Sur 11.3.1

### ISSUE THREAD

**Issue by breynolds265** [rgriebl/brickstore#357]
I am unable to update the Bricklink database on the latest version of Brickstore 2021.5.1 (build: 452) on macOS.

I get the attached error. It's worth noting that on previous build of Brickstore, 2021.4.1, it was working up until the new Brickstore release was available. I opened up Brickstore the other day and got this error, I then proceeded to open the application and I was made aware of the latest version (2021.5.1) so I updated. After updating, I got the same error. 

<img width="484" alt="Screen Shot 2021-05-21 at 4 56 30 pm" src="https://user-images.githubusercontent.com/29752785/119111473-aea57e80-ba55-11eb-9a09-8ba1162b3842.png">

I have tried removing the application and re-installing it, but it still fails.

I just tried on my Windows machine and it works fine, but generally use it on my Mac and would like some guidance on this one. 

Cheers,
Brandon

**Comment by rgriebl** [comment]
Works perfectly fine on my 11.3.1 MacBook. This must be some firewall or security setting on your Mac then. Check if you can open https://brickforge.de/brickstore/ in your browser: this is the same machine that is delivering the database updates.
Also check if your system's date is correct: https connections fail if the system time is too far off.

**Comment by breynolds265** [comment]
Thanks for the tip, however I do not believe that is the issue. I actually think it's my ISP. I am having the issue on other machines on my network now too. There is nothing being blocked on my router and my Mac firewall is off. My Unifi 'Threat Management' does not show anything being blocked from your IP (188.68.37.79). I can resolve your website, but I can't pink it. If I connect my Mac to 4G, it seems to work fine. Pinging brickforge.de is about 1-2 seconds but I can connect and download data base. From there it works fine, I can import/export from bricklink, no issues. 

I will close the case, cheers.
