### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by Bricklahoma** [rgriebl/brickstore#358]
Downloaded 2021.5.1 and keep getting this error,  Now I am attempting to re-launch Brickstore and the same error appears, where no issues were there before.  I tried to Dl and view my inventory in both .txt and .xml and there is no row with this number 100673. 

![185365247_496453934837949_8097609920057607016_n](https://user-images.githubusercontent.com/84601669/119199247-5ae46680-ba50-11eb-8cd2-c55fae69aeb8.png)

**Comment by rgriebl** [comment]
Nothing changed in BrickStore in the store import functionality.
Two things to test on your side:
1. can you import the store XML file downloaded via the browser (`Import` > `BrickLink XML`)?
2. can you view your order list and/or cart (`Import` > `Order`/`Cart`)?

If 1 works, but 2 doesn't, your username/password are set wrong in BrickStore. If 1 doesn't work (same error), then BrickLink is generating invalid XML.

**Comment by Bricklahoma** [comment]
Downloading my Bricklink inventory download creates the file invxml.txt, so trying step 1. gives me same parse error...do I need to do as a .csv file?  
I can view my order list perfectly though...even orders that have come through today.

**Comment by rgriebl** [comment]
Could you send that invxml.txt to me to analyze? Don't attach it here, but send me an email (click my user icon - my email address is on the profile page)

**Comment by Bricklahoma** [comment]
Thanks Robert, on its way now

**Comment by rgriebl** [comment]
Yep ... BrickLink is generating invalid XML nowadays. This is line 100673:

` <SUPERLOTREMARKS>Book & cover</SUPERLOTREMARKS>`

The `&` needs to be escaped as `&amp;` ... otherwise you are generating invalid XML.
Since the chances of BrickLink fixing the XML export on their side are close to zero, I would suggest to change the superlot remark via the web interface and replace `&` with `and`.

**Comment by Bricklahoma** [comment]
Fantastic. I changed the ampersand and was able to import with no issues. Thanks so much. 

Dg 

On May 21, 2021, at 5:09 PM, rgriebl ***@***.***> wrote:

﻿
Yep ... BrickLink is generating invalid XML nowadays. This is line 100673:

<SUPERLOTREMARKS>Book & cover</SUPERLOTREMARKS>

The & needs to be escaped as &amp; ... otherwise you are generating invalid XML.
Since the chances of BrickLink fixing the XML export on their side are close to zero, I would suggest to change the superlot remark via the web interface and replace & with and.
