### ISSUE TITLE
Parting out colored items loses the color

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#359]
When parting out items with color, like multipacks:

![image](https://user-images.githubusercontent.com/1063368/119478121-d5163300-bd4f-11eb-9e7f-d0cb22682e74.png)

They lose the color:
![image](https://user-images.githubusercontent.com/1063368/119478157-de070480-bd4f-11eb-84ab-b604c5380eb5.png)

This happens because the inventory of the item in BrickLink has them as (variable color), so when parting out these in BS convert the variable color to the one the item was in the file. 
But not all the inventory, as there may be just 1 part with variable color and the rest with color.

**Comment by rgriebl** [comment]
Didn't even know these existed. Looking at BrickLink's XML, the color of the items is just `0` (Not applicable). This means I would have to try to figure when a `0` means *base color* and when it just means *no color*. What would be the heuristic here?

**Comment by ZZJHONS** [comment]
> Didn't even know these existed. Looking at BrickLink's XML, the color of the items is just `0` (Not applicable). This means I would have to try to figure when a `0` means _base color_ and when it just means _no color_. What would be the heuristic here?

Well, maybe there is no Parts with inventory that have inventory items as truly n/a? Don't know for sure, but can't think of any for now.
