### ISSUE TITLE
Setting prices

### ISSUE THREAD

**Issue by Randallflagg0** [rgriebl/brickstore#361]
I have found that when I am using the down arrow to check pricing, and then setting the price to the price guide my selection then reverts to the file itself rather than the line I was just on.

**Comment by rgriebl** [comment]
Could you please describe precisely what you are doing, what you expect the outcome to be and what the outcome actually is?

**Comment by SteveTheBrick** [comment]
As a heavy keyboard user I've noticed that this happens after running many actions in Brickstore but it's only a small inconvenience. On Windows you just press shift-tab to bring the keyboard focus back to the item list and then you can use the arrow keys again, I'm not sure about other OS'es.
