### ISSUE TITLE
Top column in the file is white in the dark them

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#366]
![image](https://user-images.githubusercontent.com/1063368/119885353-05b5c280-bf32-11eb-97be-0d1957a7dff3.png)
Since the last commit the top column is with white background, the before dev release was okay.

W10

**Comment by rgriebl** [comment]
You seem to be over-motivated today 😁 
This feature isn't finished yet ... it's currently a lot of back and forth between Windows, macOS and Linux until everything works and the easiest way for me to sync the platforms is to push whenever one of them works.

**Comment by rgriebl** [comment]
Now themeing changes should work on all platforms ... happy testing :)

**Comment by ZZJHONS** [comment]
> You seem to be over-motivated today 😁

Well, the other day I saw a screenshot in black theme, but couldn't find any settings to it, and when today I saw the commit about adding it to Windows.... :)
