### ISSUE TITLE
'Colour Lock' in the Add Item dialog doesn't recognise all the known colours

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#369]
This morning I was using the 'Add Item' dialog to insert part 4461 in Red.

Brickstore shows 7 known colours for this part but the colour lock only works on 4 of those colours. If I choose Blue, Yellow or Red and click the colour lock button then the part dissapears from the list.

Another random example: part 4735 has 9 known colours but never appears when the colour lock button is clicked.

**Comment by rgriebl** [comment]
I forgot to update the server side BrickStore version that generates the DB daily.
Fixed now - just update the database and it should work.
