### ISSUE TITLE
Consolidate Items - Does not delete the item being consolidated

### ISSUE THREAD

**Issue by Brick546** [rgriebl/brickstore#375]
Version 2021.6.1
Build 472

Awesome Application and does so many cool features that are required when managing a bricklink site. The consolidation item works fine for the remanding item, the only thing it does not do is create a delete lot when doing a mass update XML. So you end up with both items remaining in your bricklink inventory. 

lot ABC  Qty 5       Consolidate from 
lot DEF  Qty 10      Consolidate to

After the xml upload you end up with :

lot ABC  Qty 5
lot DEF  Qty 15

Cheers,
Adam

**Comment by rgriebl** [comment]
I know the problem, but I haven't found an obvious way to make the user aware of a 'to be deleted' lot.
Just deleting lots on Mass-Update without the user being made aware of it (like with the blue *differences* arrows for changes) is not very user friendly.

Ideas welcome :)

**Comment by Huseriato** [comment]
My idea is a new state "trashed". So item will remain in the list after consolidation, but it's greyed. This may be useful for manual deletions, too. For example to delete items from the shop. May be a item should be trashed first. When deleting trashed items they are removed from the list.

I don't know, if the should be the default behaviour or if this should be limited for listing the shop. There is a special behaviour for orders (a button for "order information" in the toolbar).

**Comment by Huseriato** [comment]
Are there any plans on this? I really want to consolidate some lots.

**Comment by rgriebl** [comment]
The new consolidate dialog introduced in da2b2b8d has now a checkbox to either delete the merged lots, or set their quantity to 0.
Granted, it's not as fancy as a "trashed" state, but it'll work nicely for mass-updating without massive changes to BrickStore's internal data model.
