### ISSUE TITLE
Importing Bricklink Store

### ISSUE THREAD

**Issue by Udris** [rgriebl/brickstore#378]
when trying to download the BL inventory I get this **Error: Download failed: Host not found**
in previous versions program told that the username is incorect or does not match with the password

Reinstalling does not hlep.
where the username and the password is stored when the program is installed? Because Brickstore did get the username and password from previous version (orange icon).

**Comment by rgriebl** [comment]
`Host not found` means that the server https://www.bricklink.com is not reachable from your machine. If you are on Windows, make sure you can access BrickLink via Edge or Internet Explorer (Chrome and FireFox might use different DNS settings from the operating system's defaults)
This might also be a Anti-Virus or Firewall blocking the BrickStore process.

**Comment by Udris** [comment]
Bricklink is accessible via Edge and IE (IE does not open the upper links, such as login, but Edge does.)
I disabled Firewall, and tested. Still the same problem - Host not found. 

<img src="https://i.imgur.com/PPY2kFd.png" />

I did reset IE settings and checked hosts file.

**Comment by Udris** [comment]
> 
> 
> Bricklink is accessible via Edge and IE (IE does not open the upper links, such as login, but Edge does.)
> I disabled Firewall, and tested. Still the same problem - Host not found.
> 
> ![](https://camo.githubusercontent.com/a45aac900f95507eeba05b488232b0d8d455d4d968262be826de45605268c2cf/68747470733a2f2f692e696d6775722e636f6d2f505059326b46642e706e67)
> 
> I did reset IE settings and checked hosts file.

### BrickStore 2021.6.1 (build: 472)

* **brickstore.ldraw**: false
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (16.1929)
* **build.date**: 2021-06-02T10:26:35.000
* **build.host**: fv-az28-119
* **build.number**: 472
* **build.qt.version**: 5.15.2
* **hw.cpu**: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
* **hw.gpu**: Intel(R) HD Graphics 4600
* **hw.memory.gb**: 15.9
* **os.arch**: x86_64
* **os.name**: Windows 10 Version 1909
* **qt.debug**: false
* **qt.version**: 5.15.2

**Comment by rgriebl** [comment]
It's really a "Host not found", but not the reason is insane: BrickLink changed the error page you get back when trying to log in with an invalid username or password **again**.
This time, they redirect to the URL `:///oops.asp` and of course BrickStore is not able to find a host for this non standard compliant, invalid URL.
I'll add another hack to detect this situation in the next release :(

As for you immediate problem: either your username or password are wrong.

**Comment by Udris** [comment]
username and password are tripled checked, they are correct.
I even changed the username and password to check if the username or password caused problems with Brickstore.

the problem is still there.

**Comment by Huseriato** [comment]
Hello,

I can confirm, that this problem also exists for me. I've triple checked the account data. I can login from the same pc with edge, chrome and opera with the exact same data (copy pasted and also manually entered from my password manager). BrickStore refuses to connect to my store. May be it has something to do with the new "XP" Layout? Maybe some URLs changed? I use the default layout in all my browsers. Is there any logfile I can check?

**Comment by Huseriato** [comment]
I checked the URL https://www.bricklink.com/invExcelFinal.asp (specified in source code). I can open it in my browsers (when logged in to bricklink). I've currently not the development setup to debug this. I can open the orders without any problems. Can I do anything to help you finding the issue?

**Comment by rgriebl** [comment]
Since it works perfectly fine for me, I cannot reproduce it. You could send me your username/password privately via mail (click my username to get my email address) and I can have look at it with a debugger.

**Comment by Udris** [comment]
I sent you the login data. I hope it helps.

**Comment by rgriebl** [comment]
It did help! The problem is the handling of a `+` character in the username or password. I'll fix this is the next release to make BrickStore act like a browser in this regard.
To get around this problem right now, you can just change your password to *not* contain `+` characters.

For reference: https://doc.qt.io/qt-5/qurlquery.html#handling-of-spaces-and-plus

**Comment by Huseriato** [comment]
Okay, interesting. I tried to change my password to contain only A-Z, a-z and 0-9. But my username constains an underscore. May be this is misinterpreted as a space character. Thanks for fixing.

**Comment by rgriebl** [comment]
@Huseriato I do have a test account for BrickStore that also has an underscore in its name and this one works fine. If you also send me your name/password via mail I can definitely fix it.

**Comment by rgriebl** [comment]
It's 2021 an BL is truncating passwords to 15 characters, but WITHOUT telling the user! You can set a longer password, but BL only ever uses 15 characters of that.
What's even worse is that this truncation happens on the client side, so I need to add a similar truncation hack to BrickStore and hope that BL never changes that limit.

**Comment by rgriebl** [comment]
Small correction: they are doing it by limiting the number of characters in all the password input fields, but if you are using a password manager to generate your passwords you have a hard time catching the truncation...

**Comment by Huseriato** [comment]
Modern problems require modern solution. Thanks for fixing. I changed my password to 15 characters length. If they ever change the limit, users with longer password managers will not be able to login after a change.
