### ISSUE TITLE
Filtering with the term 'Orange' does not filter

### ISSUE THREAD

**Issue by RedWolves** [rgriebl/brickstore#379]
I usually put parts away by color and filter the list of parts down via color name.  This works well except when I search for 'orange' it doesn't filter anything.  

**Expected**

I should see just the orange parts.

**Comment by ZZJHONS** [comment]
Did you try searching with:

`Color ^ orange`

**Comment by rgriebl** [comment]
The filter parser is being stupid here: it parses `orange` as `<empty string>` `or` `ange`.
A simple workaround for now is to quote the word orange with double quotes: `"orange"`
