### ISSUE TITLE
Copy Values from Document does not work if ...

### ISSUE THREAD

**Issue by xaraxarax** [rgriebl/brickstore#386]
... Destination Parts come from Part Out over 'Appears In Sets'. 

To reproduce this Issue select any Part from any List and in Info Dock 'Appears In Sets' Right Click on any Set and 'Part out item'. In the newly created Inventory Document run 'Copy values from Document' and nothing happens.

If you add the set over 'Add Items ...' and part out this Set and do the same, all values are as expected except the Counterparts, these always do not work.

Used Version is 2021.6.1 B. 472, latest W10

**Comment by rgriebl** [comment]
This works perfectly fine for me. What do you mean with "nothing happens"?  Is the "Copy or merge values" dialog not showing at all?
And yes: counterparts are treated as a second class citizen all over the place ... that's to be expected ;)

**Comment by xaraxarax** [comment]
https://user-images.githubusercontent.com/79638214/129913742-a696ed3a-ab48-41a1-9165-07985560010d.mp4

**Comment by xaraxarax** [comment]
https://user-images.githubusercontent.com/79638214/129916203-14296822-0bc2-4b01-a05e-da4ef1f1060e.mp4

**Comment by xaraxarax** [comment]
https://user-images.githubusercontent.com/79638214/129916408-110ace6c-6175-4e58-b667-a0dc55585ad9.mp4

**Comment by ZZJHONS** [comment]
I can't reproduce it.

**Comment by rgriebl** [comment]
I can reproduce it now, but this is how it should work: 3475b in your source document is `Used`, but it is `New` in the part-out document. For copy/merge fields to work, all of item-id, color and condition need to match.
