### ISSUE TITLE
Ctrl + D

### ISSUE THREAD

**Issue by TGS-Brick** [rgriebl/brickstore#389]
Please look at the result when using ctrl+D to copy a line.
When using Ctril+D a new line appears, but typing new Qty the program edit the old line.

**Comment by ZZJHONS** [comment]
I can reproduce it, it duplicates the line, if you start typing it edits the old line and if you hit enter it saves the value in the new line.

**Comment by TGS-Brick** [comment]
Why not edit the new line and store value in new line. I use this and then
change the part # afterwards. Great software, thanks.


ons. 18. aug. 2021 kl. 10.34 skrev ZZJHONS ***@***.***>:
