### ISSUE TITLE
Part out of an item, please sort

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#39]
I can't find any sorting here, maybe I missed it?

![image](https://user-images.githubusercontent.com/32078594/103801756-78d79e80-504e-11eb-8ce2-bf4bbd074b08.png)

But please, if possible, by default sort by Status (the extras at then end) then by Item Type and/or Item Category and/or item ID, so it looks a bit nicer ;-)

![image](https://user-images.githubusercontent.com/32078594/103801933-b2a8a500-504e-11eb-85b2-761794215802.png)

Thank you!

**Comment by rgriebl** [comment]
There is no sorting by default in any new document until you click on a header. What you see is the original order of the items as downloaded from BrickLink's inventory.

**Comment by paramecie** [comment]
Oh I don't blame you - I would prefer any sorting. I don't know about the others, though...
