### ISSUE TITLE
Missing sets

### ISSUE THREAD

**Issue by UticaBrix** [rgriebl/brickstore#390]
Hello.   The 3 sets below are not coming up for some reason.

21327
75308
21325

Thank you
Dave

**Comment by ZZJHONS** [comment]
I see them in BrickStore, are you sure that you have the database updated, try Extras->Update DB

**Comment by UticaBrix** [comment]
Oh yes!  Thank you!!!   I was doing “update program”.      It is there.  Thank you so much!!
