### ISSUE TITLE
Part Lock

### ISSUE THREAD

**Issue by GreatBrickLab** [rgriebl/brickstore#391]
The color lock feature is incredible valuable and has increased the speed to catalog part significantly.   I think there would be the same value in a lock for the part also,  for example I have a pile of all 3003 and I want to change the color and be sure that I stay on the 3003 part,  I suppose I could just type the part # in the filter,  however when you change colors the sort changes order.   Just a thought.

**Comment by rgriebl** [comment]
Why wouldn't you stay on the 3003 part? Just changing the color does not change the part selection. At least I can't figure out how that would happen...

**Comment by GreatBrickLab** [comment]
If you pick a color that does not have that part it looses the matching.
My steps it to use the keyboard to get to the colors.  LIM for lime.  W
white.  RR for reddish brown.  L and down some for light bluish gray.  BB
for blue.  I have found a few quick key combos that can get to the color or
close by a few clicks.  If you go trough a color that 3003 was not produced
in the part selection is lost.

**Comment by ZZJHONS** [comment]
Okay, you mean that if you have the color lock enabled and you press a color the current part doesn't exists the selection is lost.

I understand It and I too would like to have the part stay selected.
