### ISSUE TITLE
Unable to add items......

### ISSUE THREAD

**Issue by DaddyOsBricks** [rgriebl/brickstore#392]
As I was in the middle of adding parts (literally switching from one part to the next), the add button now stays grayed out as if I do not have a part/color combination selected. This is now the second computer this has happened to for me (both are windows installations). I have checked for updates, updated the database, rebooted the computer, uninstalled/reinstalled, uninstalled and tried a previous version, tried in new documents and old documents, different combinations of parts colors and item types, all of which still leave me in the same place. I am able to import a set inventory but once it loads I am unable to add any additional parts. Happy to provide any additional details that may help troubleshoot this.

Any assistance would be greatly appreciated 

![Screenshot 2021-08-22 225157](https://user-images.githubusercontent.com/89368999/130383658-04772541-386f-42e0-86a5-11cf0faf2933.jpg)

**Comment by rgriebl** [comment]
You have no price, but tier pricing enabled (in a weird way I might add ;) ) and the validation fails here: the check is that each tier must result in a lower price than the preceding tier or, for the first one, lower than the actual price. In your case `0 USD * 0%` is not lower than `0 USD`

**Comment by DaddyOsBricks** [comment]
Thank you, back up and running!! Not sure how I managed to do that twice as I don't use tiered pricing and I add with my price at zero then adjust after the fact. 

Also thank you for all the work you have done, been a great update from brickstock and a game changer when it comes to inventory management for myself and I'm sure all of us that use it.

-Bill
