### ISSUE TITLE
Set #75308 (R2D2) missing

### ISSUE THREAD

**Issue by UticaBrix** [rgriebl/brickstore#393]
Could not locate this one.

**Comment by rgriebl** [comment]
You find it the same way as you would find any set...

Set `Item type` to `Set`, `Category` to `All Items` and type `75308` into the `Filter` field at top.

This works both in the `Add Item` dialog, as well as in the `Import BrickLink Set Inventory` one.

**Comment by UticaBrix** [comment]
I didn’t realize, lately it stays on the “type of set” I was last on.  It used to default back to “all” I believe.   I never had to change that.
