### ISSUE TITLE
LOG has no name

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#395]
![image](https://user-images.githubusercontent.com/1063368/131246355-1cf39b74-899f-4c8b-b01e-40e243f25607.png)
![image](https://user-images.githubusercontent.com/1063368/131246358-f0523702-2e38-4b06-8522-eb2c818a0fd4.png)

**Comment by rgriebl** [comment]
Already fixed in 70b6e27d678d4d48eb856f2991e3bec4e34551f8

**Comment by ZZJHONS** [comment]
Okay, time to download the dev builds before posting!
