### ISSUE TITLE
Connection to EZB-Servers - Error

### ISSUE THREAD

**Issue by tnbla** [rgriebl/brickstore#396]
Directly after the start of Brickstore, an error message now appears.
Brickstore seems to have issues, connecting to the servers of the european central bank for the newest currencies, changing from Dollar to EURO.

![ezb error](https://user-images.githubusercontent.com/89812011/131407882-b4753590-fee0-4e18-b242-ebe693eb456c.PNG)

Nothing related to prices works.

Using latest Version: 2021.6.1
Brickstock was installed before (Showed the same message)

Grüße aus Landshut :-)

**Comment by rgriebl** [comment]
Sorry for the late reply -- I must have missed this while I was on vacation.
This was either a temporary problem on the ECB's side or something is/was wrong with your Windows' HTTPS certificates store. In both cases, there's nothing I can do.
