### ISSUE TITLE
brickstore bsx file to big when doing mass update to bricklink

### ISSUE THREAD

**Issue by losenit** [rgriebl/brickstore#399]
i just started using brick store . when i download my inventory  to do a price update then export it to bricklink  upload page. i click verify file then come's up with an error file to large.

**Comment by ZZJHONS** [comment]
That is a problem from BL, the website can't load large lots files or even part outs started in BL, so it would be good to have like a Pop-up informing of this whenever someone tries to export more than 1000 lots to upload/update Bricklink XML.

**Comment by losenit** [comment]
Thank youSent from my Galaxy
-------- Original message --------From: ZZJHONS ***@***.***> Date: 2021-09-09  2:47 p.m.  (GMT-06:00) To: rgriebl/brickstore ***@***.***> Cc: losenit ***@***.***>, Author ***@***.***> Subject: Re: [rgriebl/brickstore] brickstore bsx file to big when doing mass update to bricklink (#399) 
That is a problem from BL, the website can't load large lots files or even part outs started in BL, so it would be good to have like a Pop-up informing of this whenever someone tries to export more than 1000 lots to upload/update Bricklink XML.

**Comment by rgriebl** [comment]
The current dev version will now inform you that exporting more than 1000 lots to the clipboard isn't a good idea.
