### ISSUE TITLE
Add Date Added and Date Last Sold columns

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#400]
When downloading the inventory in XML these 2 are there, it could be great to have this info in BrickStore in 2 new columns.

**Comment by chiminirc** [comment]
This would be beneficial for pricing adjustments.

**Comment by bgrantwilliams** [comment]
Very much agree! Adding "Date Added" and "Date Last Sold" would be incredibly helpful!

**Comment by rgriebl** [comment]
Implemented and duplicate of  #384
