### ISSUE TITLE
adding minifigs info wont come through

### ISSUE THREAD

**Issue by adbookerfhsu** [rgriebl/brickstore#401]
on the add screen under minifigure, I'm browsing through star wars and when you select one the info does not show up. You have to choose another category and then go back to minifigures. When you first open the app, it's like its expecting you to choose a color but minifigures won't allow color.

**Comment by rgriebl** [comment]
I can't reproduce this with 2022.10.1 anymore. If you still can, then please reopen this issue ... ideally with a screenshot attached
