### ISSUE TITLE
resize issue on main screen

### ISSUE THREAD

**Issue by BobShuster** [rgriebl/brickstore#404]
MacBook Pro running Big Sur 11.6.  The main screen cannot be resized vertically to be less than about 820 pixels (approximate) in height. This works fine on the default screen resolution of 1440x900, but at 1280x800 the bottom of the window is off the screen at the bottom.  I was unable to find a workaround for this without switching to Full Screen mode.

**Comment by rgriebl** [comment]
This is a recurring issue on the small MacBooks with their ridiculously small vertical resolution.
The only way around that (in the current release) is to disable at least info dock via the `View` > `View info docks`.

In the current dev version, you also have a lot more freedom on how to arrange and stack these info docks, so you could drag the *Appears-In* and *Price Guide* docks on top of each other to get a tabbed info dock that only takes up half the height.
