### ISSUE TITLE
SSL handshake failed

### ISSUE THREAD

**Issue by retailonline** [rgriebl/brickstore#409]
Everything worked fine with the program until today when it says "Error: Download failed: SSL handshake failed" on startup.
Any idea of how I can solve this?

![ssl-handshake](https://user-images.githubusercontent.com/25500812/135537383-2eb53e59-4611-49e8-a02c-be6c10812f99.jpg)

**Comment by rgriebl** [comment]
Just a temporary hiccup due to LetsEncrypt switching root certificates (https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/). For whatever reason this failure only happened on Windows, but a restart of the web server seems to have solved the problem. I guess some weird caching issue on the Windows side.

**Comment by retailonline** [comment]
Still the same problem.
Can I clear the cache on my machine in some way to?

**Comment by rgriebl** [comment]
The server is configured correctly: https://www.ssllabs.com/ssltest/analyze.html?d=brickforge.de&s=188.68.37.79

If this still doesn't work for you, then either you have a very old system (see https://letsencrypt.org/docs/certificate-compatibility/) or -- assuming you are on Windows -- you have disabled Windows' automatic root certificate update mechanism: make sure to delete the registry key `DisableRootAutoUpdate` at `HKLM\Software\Policies\Microsoft\SystemCertificates\AuthRoot`, then reboot and give Windows some time to do the update.

**Comment by retailonline** [comment]
Thanks for the tips, sadly it does not solve the problem for me.
I'm on Windows Version 10.0.19043 Build 19043 and the registry-key you referring to does not exists so nothing to delete.
I have no idea what could be the problem, I tried to reinstall the software and rebooting the machine but no success.

**Comment by retailonline** [comment]
I found this:
[https://docs.certifytheweb.com/docs/kb/kb-202109-letsencrypt/](url)

> Windows PCs#

On windows PCs, simply browsing to a website using Chrome, Edge etc with updated the client trust store with the required certificates. Browsing to https://valid-isrgrootx1.letsencrypt.org/ will prompt Windows to include ISRG Root X1 in its trust store automatically.

Now it works..
