### ISSUE TITLE
Include/Exclude Counterparts on Set Import

### ISSUE THREAD

**Issue by beaverbrick** [rgriebl/brickstore#410]
Hi :)

When importing sets, it would be great if there was an option to include/exclude counterparts.

The counterparts are regularly just the stickered parts, so when parting out sets, especially new, I find myself having to find and delete them all.

I was thinking a checkbox could be added to the 'Import BrickLink Inventory' dialog box, underneath the 'Include instructions' checkbox (see pic) with the selection remembered for next time.

![BrickStore_Counterparts](https://user-images.githubusercontent.com/81053064/135923019-05095aef-2182-4627-89b4-cc68411c63be.png)
 
Thanks very much for all your work on this program.

**Comment by msfreaks** [comment]
+1

**Comment by rgriebl** [comment]
Already implemented, just not cross-referenced from the commit message.
