### ISSUE TITLE
Price Guide Not Showing Correct Price Below .01

### ISSUE THREAD

**Issue by bartman1983** [rgriebl/brickstore#411]
on Mac OS the Price shows .000 on anything with a value below .01.  meaning if a brick cost .003 it shows .000

is there a fix to this.... if so how?

**Comment by InterruptSpeed** [comment]
Hi there,
Can you provide an example of a part please that has this issue? I can't double check on my mac.

**Comment by rgriebl** [comment]
This is a technical limitation of the BrickLink API. See the pinned issue #80
