### ISSUE TITLE
Error on Startup - zlib1.dll missing

### ISSUE THREAD

**Issue by beaverbrick** [rgriebl/brickstore#416]
Since updating to the latest version v2021.10.1 I get the following error when starting BrickStore...

![zlib1 dll](https://user-images.githubusercontent.com/81053064/136444333-7c0755c9-cd52-4947-9859-55c30bc68241.png)

BrickStore will actually open after clicking OK and seems to be working as it should.

64-bit Windows 7 Home Premium

Thanks

**Comment by rgriebl** [comment]
Please test the dev build 501 (should be compiled in about 10mins) and let me know if this fixes the problem.

https://github.com/rgriebl/brickstore/actions/runs/1317660155

**Comment by beaverbrick** [comment]
Yes that worked thank you :)
