### ISSUE TITLE
Updateded to 2021.10.1 - zlib1.dll missing?

### ISSUE THREAD

**Issue by retailonline** [rgriebl/brickstore#417]
Just updated to 2021.10.1 (Win 10), when trying to start the program crashpad_handler.exe shows up telling me "The code execution cannot proceed because zlib1.dll was not found. Reinstalling the program may fix the problem".

Reinstalled - Same problem
Reinstalled to older version - Same problem
Cleaned registry - Same problem

Any thoughts?

**Comment by mevitsbricks** [comment]
I'm getting the same zlib1.dll missing message here on Win10 Pro Ver 21H1 64 bit.

**Comment by rgriebl** [comment]
2021.10.2 should fix the issue for everyone now
