### ISSUE TITLE
New tutorial found !

### ISSUE THREAD

**Issue by iriki** [rgriebl/brickstore#418]
Hi guys,

Since forking wiki is not possible/ver cumbersome, I found a very nice tutorial that I use a lot and would like to share. I formatted the code and added the thumbnail image, as in the wiki.

```
* Tutorial on how to Part out sets with Brickstore and upload it to Bricklink.

[![ Not Just Collectibles's video on YouTube](https://i.ytimg.com/vi/Wg4sdMGDjLU/hqdefault.jpg)](https://www.youtube.com/watch?v=Wg4sdMGDjLU)`
```

**Comment by rgriebl** [comment]
Thanks! I've added it to the wiki.
