### ISSUE TITLE
Bricklink Inventory detail page being deprecated

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#419]
BL just announced that they will be removing the old inventory detail page, and as BS links to it I open this issue to see if there is a way to make it work with the new one.

I commented about this problem in the BL post:

https://www.bricklink.com/messageThread.asp?ID=310499

**Comment by ZZJHONS** [comment]
Seems BL is aware of this and old link will still work as a redirect to the new page, so you can close this as seems there is no other way around.

**Comment by rgriebl** [comment]
Closing as this is a duplicate of #570
