### ISSUE TITLE
Price inc/dec window, always focus and fully selected

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#42]
When in this window, at the opening the value has the focus and is fully selected.

![image](https://user-images.githubusercontent.com/32078594/103803584-0ddb9700-5051-11eb-8fdf-78d2db671716.png)

But as soon as you click an option like Increase / Decrease you loose the focus.

This is a pain as when you've to do many different Decreases for example, you've to click Decrease, then set the focus again, then delete the 0 value, or select it fully... So, please automatically give back focus and full selection after an option click?

**Comment by rgriebl** [comment]
Do we really need the inc/dec buttons? No idea why I did that dialog like it is (it was probably 15 years ago), but why not just enter negative numbers if you want to decrease something... feels a lot simpler to me.

**Comment by paramecie** [comment]
Ooooh please kill it - it's always been a pure pain (obliged to click "decrease" and bring focus back)!

**Comment by paramecie** [comment]
BTW, there could be the 2 little arrows up/down here also:
![image](https://user-images.githubusercontent.com/32078594/108463471-bdc23800-727e-11eb-9a1f-2264ec4c3176.png)

Or better, remove them everywhere - I wonder who use them :)
