### ISSUE TITLE
having the filter system from 2021.6 as an option

### ISSUE THREAD

**Issue by istaylor92** [rgriebl/brickstore#420]
is it possible to have the single filter bar utilizing the coding type filter system as an option?
Either in Settings -> interface, or a View -> filter mode, or both.
I like the name Uber-Bar for the 2021.6 filter

**Comment by rgriebl** [comment]
Not without someone rewriting the parser: there were just too many subtle bugs.
Plus, having to type the abbreviated column names is just awkward.

I'll leave the bug report open for now, but don't expect a comeback of the text-only filter soon :)

**Comment by Huseriato** [comment]
I don't know what https://github.com/rgriebl/brickstore/commit/d1aaf995123c7f0d64eaae8099f343474d7c878e fixed here. Are this small changes bringing us back the 2021.6 filter system?

**Comment by rgriebl** [comment]
This is just the commit that ironed out the last bugs in the filter system after the big refactoring:
```
# git diff v2021.10.2.. --shortstat
328 files changed, 37624 insertions(+), 20643 deletions(-)
```

**Comment by Huseriato** [comment]
Okay, does this mean the option is already implemented? I would be happy to hear that. Thank you for your good work.

**Comment by rgriebl** [comment]
The latest unreleased dev build is always available by clicking on "Actions" at the top (you need to be logged to download)

**Comment by xaraxarax** [comment]
Cool, thx!
