### ISSUE TITLE
Decimal places for prices

### ISSUE THREAD

**Issue by Al-Legorical** [rgriebl/brickstore#424]
Since using new (and much improved) version, prices are no longer pulled from BrickLink as three decimal places, all prices are getting rounded to two decimal places. This may appear minor, however, for example, I price technic pins at $0.009/ea
Also $0.001 can make a difference in winning the customer!
Thanks!

**Comment by rgriebl** [comment]
I'd like to do this, but it is technically not possible at the moment. See the pinned issue #80
