### ISSUE TITLE
MacOS build instructions

### ISSUE THREAD

**Issue by InterruptSpeed** [rgriebl/brickstore#425]
### MacOS
* ensure Homebrew and xcode command line tools are installed and then:
```
$ brew install qt5
$ brew link qt5 --force
$ mkdir build && cd build
$ qmake ..
$ make
```
* note you can use qt6 instead of qt5 above now...if you do you can skip the brew link step

**Comment by rgriebl** [comment]
Closing, as this is not really a "issue". Plus building instructions are available in the Wiki: https://github.com/rgriebl/brickstore/wiki/Building-from-Source
