### ISSUE TITLE
Search in Store Inventory menu option

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#43]
In this case, there's no Lot ID, but those Plates are for sale in my shop.
I guess it's why the "Show in my store on BrickLink" is disabled.

![image](https://user-images.githubusercontent.com/32078594/103818989-dc22fa00-5069-11eb-808f-04bf35ad2a0e.png)

We could have another menu option here (and in main menu) like "Search in my Store Inventory"

It's very straight forward, it could send the GET:
https://www.bricklink.com/inventory_detail.asp?catType=P&q=white%203666
_(this works for ten+ years even if I'm not sure it's documented)_

There's only Type, Color and Reference to change, and to make the proper URL formatting (%20...)

It would open this page:
![image](https://user-images.githubusercontent.com/32078594/103820590-ee526780-506c-11eb-82cf-d3c1e0b08012.png)

It can stay always enabled as you don't need the lot ID to work.

**Comment by legobanker** [comment]
I downloaded my store inventory and attempted to update a single lot.  It did update the lot using the "lot ID".

**Comment by paramecie** [comment]
See #68 and #96 - update wasn't working on historical BrickStore if you didn't edit either price or quantity (or new lot).
In short, any other change didn't provoque the update.
For now it seems working as before; but that's to change I guess (and hope!)
