### ISSUE TITLE
Multiple Item Number Filter

### ISSUE THREAD

**Issue by jdcofficial** [rgriebl/brickstore#431]
In previous versions, I was able to select multiple items from a document, copy all of their item numbers and paste them into the search of a different document to filter multiple items. Seems that the new filter takes away this method of quickly filtering many items by simply typing "|" or "or" between them? Or do I now have to create a new filter for each item number - however then I can't mass paste the list of item numbers.

Many thanks!

**Comment by rgriebl** [comment]
Should be available in the latest dev build by switching to "text-only filters"
