### ISSUE TITLE
Windows, installation folder

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#44]
I had a doubt, so I cleanly uninstall BrickStore before, removing all Register infos and local cache files also.

I just then installed 2021.1.2, and confirm, apparently the 64 bits version installs in (x86) folder.

![image](https://user-images.githubusercontent.com/32078594/103824667-afc0ab00-5074-11eb-8ae1-f66163f59258.png)

Shouldn't it to be installed in the C:\Program Files folder for the 64 bits versions?

**Comment by rgriebl** [comment]
That's how it **should** be, but this is a bit of gray area in Windows and nobody really plays by the rules ... me included :)
This 32/64bit "separation" in Windows is a mess and I couldn't easily find a clear way to create 2 separate installers based on the same Inno Setup source file. I might revisit this later, but for now, this is really only a cosmetic issue.

**Comment by chiminirc** [comment]
I agree it's cosmetic but does innosetup honor CSIDL_PROGRAM_FILES  and CSIDL_PROGRAM_FILESX86?

Or perhaps it's build internally when setup for 64bit install mode? - https://jrsoftware.org/ishelp/index.php?topic=32vs64bitinstalls
in .iss config file
[Setup]: ArchitecturesInstallIn64BitMode

Totally not worth it if it causes other things to break.  But it may just need the addition an innosetup will do the rest.

**Comment by paramecie** [comment]
That was just a remark, I don't **need** this, don't worry ;-)
