### ISSUE TITLE
Align figures in columns

### ISSUE THREAD

**Issue by BKuNL** [rgriebl/brickstore#441]
The figures in the columns like part#, Qty, weight etc, are not always lined up equally. This makes them sometimes hard to read, as they are too close together. Some are aligned to the left, others to the right side of the column.
Is it possible to align the columns with figures to center of the columns, or to give the possibility to choose yourself for each column how to align the data in that column, just as it's possible in a Excel Spreadsheet?

**Comment by rgriebl** [comment]
I don't see why the values within one column wouldn't be aligned the same way? If you can still reproduce this with 2022.10.1 then please add a screenshot here.
In general, all numbers are right-aligned (as numbers should be), all text based columns are left-aligned. This leaves just the odd-ball icons/check-boxes which get centered.
Making this configurable would be too much work for little gain.

**Comment by BKuNL** [comment]
With your explanation I understand now why text and numbers are not aligned the same way.
However, it would be good then if both of them are aligned the same way.
See underneath why.
In the column remarks I put the number of the location where I can find the piece in my drawer system. Although it’s a figure, it’s handled as text, as it is in the remarks column.
Next to the remarks position I want to know the quantity, now you see that quantity and position are next to each other, which makes it harder to read, as it might be seen as one figure. I could put another column in between, I know, but that is not what want.
That’s why I came with the suggestion to choose yourself how to position it. When it would be equal for text and figures by default, it would also be good, as long as they don’t get close too much.
 

 
Best regards/m.vr.gr.
Bert Kuyper
