### ISSUE TITLE
Extension Documentation

### ISSUE THREAD

**Issue by jrobinson-uk** [rgriebl/brickstore#443]
Hi,

I was looking into building a simple extension to populate Remarks column from a lookup table. Is there any documentation on building a ExtensionScriptAction (specifically an actionFunction rather than printFunction)

thanks

James

**Comment by jrobinson-uk** [comment]
@rgriebl I figured more of this out and  had a working extension script but then lost the code during a re-install and now can't figure it out.

Can you help me with how I can access the current doc from an actionFunction, a printFunction has a reference to doc, how do I do the same for actionFunction. After that I can do the rest

**Comment by jrobinson-uk** [comment]
Thanks @rgriebl, that's really helpful.
Do you mean that the UI extensions themselves aren't finished yet or that the documentation isn't?

If I'm reading that right I should be able to use something like:

`var thisDoc = BrickStore.activeDocument`

within my extension function to retrieve an object representing the current document (from which I can examine items etc)

I've tried this with no success:

```
Script {
    name: "Set Remarks"
    author: "LegoJames"
    version: "0.1"
    type: Script.ExtensionScript

    ExtensionScriptAction {
        text: "Sets Remarks based on item category"
        actionFunction: setRemarks
    }

    function setRemarks()
    {
        var thisDoc = BrickStore.activeDocument
        var version = BrickStore.about
        console.log(version)
        console.log(thisDoc)
    }

    }
```

my output is:

```
DBG  qml: [object Object] at set-comments.bs.qml, line 20
DBG  qml: undefined at set-comments.bs.qml, line 21
```

**Comment by rgriebl** [comment]
I just don't want to commit to a stable API right now. The API should be usable, but I might change functionality and move stuff around while I work on the new mobile apps.
That being said, your example should work ... however I don't see the `import BrickStore 1.0` import at the top of the file. Is this missing, or did you just not copy it?

**Comment by jrobinson-uk** [comment]
I just didn't copy full script:

```
import BrickStore 1.0
import QtQuick 2.12


Script {
    name: "Set Remarks"
    author: "LegoJames"
    version: "0.1"
    type: Script.ExtensionScript

    ExtensionScriptAction {
        text: "Sets Remarks based on item category"
        actionFunction: setRemarks
    }

    function setRemarks()
    {
        var thisDoc = BrickStore.activeDocument
        var version = BrickStore.about
        console.log(version)
        console.log(thisDoc)
    }

    }
```

What constitutes the activeDocument, is it just whichever file is open and in focus (not welcome page obvs), does the file need to be saved?

**Comment by rgriebl** [comment]
This script works perfectly fine for me against the latest dev build (578) on Windows.
Opened a new document, clicked your script menu item and it says:
`DBG  qml: Document(0x2a0dde8cf00) at set-remarks.bs.qml, line 21`

And yes the `activeDocument` is the one that currently has user input focus. Doesn't matter if it's saved or not. The activeDocument should be `null` when you're on the welcome page (at least I hope it is ;) ) and if there's no document open at all.

**Comment by jrobinson-uk** [comment]
Ah!

Doh! I think I'm running a build based off of my fork. I'll download 578 and test.

**Comment by rgriebl** [comment]
If you have an active fork, then please be aware that I retired the `master` branch. The development is now happening on the `main` branch.
(Not because of the usual reason that the word "master" is considered bad nowadays, but because I screwed up :) ... 34ab3bdb7)

**Comment by jrobinson-uk** [comment]
Thanks, I'd stupidly built from my fork following my pull request.

Final question, I've got a Document object now for the active Doc. How do I reference the items inside, essentially I want to iterate over each item, check the item type and set the remarks based on it's value.

As I say I have written this extension previously cannot remember how I did this bit.

**Comment by nicobubulle** [comment]
Hello @rgriebl I have the same question as @jrobinson-uk I would like to set remarks for each lot from rebrickable API to get "num_parts" of the set.

Thank you, Nicolas
