### ISSUE TITLE
add column for % difference

### ISSUE THREAD

**Issue by GreatBrickLab** [rgriebl/brickstore#444]
It would be nice to know the % cost difference from the original cost when I make a change the cost to some other amount.   Then I would know how much higher than the 6mon avg my prices are for example.

**Comment by rgriebl** [comment]
I've now created a super-task issue for custom columns: #617

I will close this issue here however, as it will not be implemented in BrickStore itself and just sitting around in the bug tracker as an open bug for years doesn't help anyone.
