### ISSUE TITLE
Force Info widget picture size

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#46]
I use Document picture size at 50% to get with many items on the same screen, but then the Info widget picture size is ridiculously small ;-)

Could you not change the Info widget picture size? Set it to 100%?

_(or even make it bigger depending available space, but that's another story)_

![image](https://user-images.githubusercontent.com/32078594/103840086-223f8400-5091-11eb-8720-eb4bd5f89b2a.png)

It's a detail ;-)

**Comment by ZZJHONS** [comment]
Similar to Issue #6

**Comment by paramecie** [comment]
Ooops - sorry. Then I agree #6 - this one can be closed as dup.
