### ISSUE TITLE
The 'Modify Item' and 'Modify Color' dialogs have lost their close button

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#461]
As the title says, these two dialogs no longer have an 'X' in the top right hand corner to close them. Obviously there are other ways to close them but my mouse just naturally goes up to the top right hand corner.

Win 10, build 540

**Comment by rgriebl** [comment]
"Lost" is relative .. the (x) has been deliberately removed back in March (!)
The idea was that these dialogs are really just complex combo-box popups and not normal dialogs. Plus I remember that there were some issues with positioning that got solved by treating them as so-called "Tool Windows".

**Comment by SteveTheBrick** [comment]
OK, that makes sense, I'll close the issue.
