### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by offtel** [rgriebl/brickstore#464]
please open a translation starting point for Portuguese

**Comment by offtel** [comment]
Why?

**Comment by rgriebl** [comment]
"Why" what? 
If it's about me closing this issue, then it's because I've added a blank `pt` translation in the commit referenced above. You can now start translating following these instructions: https://github.com/rgriebl/brickstore/wiki/Translating-BrickStore

**Comment by ZZJHONS** [comment]
@rgriebl just checked that software for translating and its very nice, more than I thought! So if you add Spanish too I will start doing it as I promised sometime ago :)

**Comment by rgriebl** [comment]
Thanks Sergio, I've add a blank `es` translation file as well.
