### ISSUE TITLE
Price sync

### ISSUE THREAD

**Issue by cajunik** [rgriebl/brickstore#467]
Hello,

There is an error with the price sync of the item 76192-1.
The Bricklink 6 month average is 67.673 EUR but in BrickStore is 36.494 EUR.
I tried to re-sync several times with the same result. I have checket the sync mode is "Last 6 month sales" and "Average"

I work with MacOs versión BrickStore 2021.10.2 (build: 503)

Thanks

**Comment by cajunik** [comment]
Here I attach some screenshots
<img width="441" alt="Captura de pantalla 2021-12-11 a las 0 47 08" src="https://user-images.githubusercontent.com/70350012/145654734-1dc143b2-a655-403f-a919-aac8040c2b64.png">
<img width="685" alt="Captura de pantalla 2021-12-11 a las 0 46 49" src="https://user-images.githubusercontent.com/70350012/145654737-29bf695d-6b94-4c3c-ae0c-4e66d02497a2.png">

**Comment by rgriebl** [comment]
Seems like BrickLink added an `[x] Exclude Incomplete` switch, which you have activated. BrickStore however retrieves the default "All sets price guide".
I guess it would make sense to change this in BrickStore, since a PG for incomplete sets is nonsensical in my opinion.
