### ISSUE TITLE
'Appears in sets' incorrect when multiple items selected

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#469]
It looks like 'appears in sets' is broken - here's one random example (win10, build#546):

These 5 items don't appear together in any sets (this is correct):

![5 items](https://user-images.githubusercontent.com/77812338/145678587-d7c7e35f-0f59-4a2b-95a3-433a6722c99d.jpg)

but adding a 6th item they do appear together in one set (this is wrong - 60599 is not in this set):

![6 items](https://user-images.githubusercontent.com/77812338/145678602-fde28a22-13cf-4d31-9cd3-3d34e803e520.jpg)

**Comment by rgriebl** [comment]
Weird - I haven't changed that algorithm in a long time and it also works perfectly fine for me. Maybe try updating the database, in case there was an error in BL's inventories (I just tested against the DB from today).

**Comment by SteveTheBrick** [comment]
I've updated to today's database but it doesn't fix it.

Looking into it a bit further it seems to only be a problem with this file and in particular with 60599 not being in that set.
Here's my file, see if you can reproduce it.


[temp.zip](https://github.com/rgriebl/brickstore/files/7697261/temp.zip)

**Comment by rgriebl** [comment]
I found the cause for this: all the extra items, especially on 98138 mess up my algorithm. I think I have to change the DB generation to ignore extra parts when calculating the "appears in" data. This might take a bit of time until I have fixed and verified this, deployed to the server generating the DB and have that server run the daily DB gen.
