### ISSUE TITLE
Updating database - Could not load the new database

### ISSUE THREAD

**Issue by Randallflagg0** [rgriebl/brickstore#472]
This is odd as nothing has changed on my end.  Cleared out the appdata\local\BS\cache directory too to see if that would help.

Maybe the database it is download is corrupted?  Fresh install does the same thing.

![error](https://user-images.githubusercontent.com/74560323/145725943-8abdcd84-b527-47b7-a6c6-317b8e04c89d.JPG)

**Comment by beasville** [comment]
ya same for me. can't use the program with this error

**Comment by Argmentum** [comment]
can confirm for me as well , looks to be potentially a corrupt file downloaded. (uk based if that means anything)

**Comment by Davidiio** [comment]
Same here error log:

```
WARN default: Error reading database: could not open database for reading (C:/Users/David/AppData/Local/BrickStore/cache/database-v4): Le fichier sp�cifi� est introuvable.
WARN default: Error reading database: failed to read from database (C:/Users/David/AppData/Local/BrickStore/cache/database-v4) at position 0
```

Maybe it could be a feature request to make the app works with outdated database in case the update fails?

**Comment by ZZJHONS** [comment]
I think @rgriebl changed today how the DB gets generated to fix an issue, it works in the latest dev build here:

https://github.com/rgriebl/brickstore/actions

But yeah, having BrickStore still save the previous db in case the new downloaded one doesn't work would be great, if not you can't work...

**Comment by rgriebl** [comment]
I've messed up the old (v4) DB generator while adding a new v5 feature. The fix needs a bit of time until it's fully deployed and a new DB is generated.

**Comment by Argmentum** [comment]
I'm gonna ask the question everyone else is thinking but dares not ask...

what kinda time frame are we looking at a few hours, a day.. possibly a week? 

This'll stop me at least hitting the update database button for a while.

**Comment by rgriebl** [comment]
Try now.

**Comment by Udris** [comment]
It works now. fhew!

**Comment by Randallflagg0** [comment]
Thank you Robert, that was a quick response!

**Comment by Argmentum** [comment]
thumbs up from me
