### ISSUE TITLE
Copy values from document only working from clipboard

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#478]
It's the first time I've used this feature so it could be user error, but I can't copy values from an open document. If I copy that same document to the clipboard and then choose 'items from clipboard' as the source it works correctly.

Win10, build#558

**Comment by ZZJHONS** [comment]
I can replicate this

**Comment by rgriebl** [comment]
Fixed in the latest dev build. Was accidentally committed as part of another fix.
