### ISSUE TITLE
Removing Stockroom A,B,C

### ISSUE THREAD

**Issue by GreatBrickLab** [rgriebl/brickstore#484]
Issue:  As a customer I download my BL store and add a flag to stockroom a LOT,    Mass Update the lots and the Stockroom is added.   Removing the same stockroom on those lots is only possible when you download the store in BrickStore again and starting the process over.

I would like to be able to add the stockroom flag for a group of lots,   verify the inventory for them and make changes as needed,  then remove the stockroom in the same file.

**Comment by rgriebl** [comment]
I think I finally understood your problem now :) 
Just do a `View` > `Reset Difference Mode Base Values` after your first mass-update.
If I still misunderstood, then please re-open and try to explain it differently ;)
