### ISSUE TITLE
importing store carts not updating

### ISSUE THREAD

**Issue by newfie675** [rgriebl/brickstore#485]
Hi, First I think you have done an amazing job with Brickstore. The issue I am having is after I import a store cart Brickstore cannot import any updated cart until I exit the program and restart it. Essentially import BL cart, updated cart in BL, refresh import carts window, all carts remain the same values as first import, nothing else will import, close BS, open BS, import BL cart, refresh, the cart imports.
Thanks
Chris

**Comment by rgriebl** [comment]
You forgot the "wait ~1 hour between imports" part :) Seems like BL times out the login state, but doesn't tell anyone in the reply... BrickStore just gets back an empty lot list together with a "everything went ok" flag. Very helpful indeed 😞 
I'll have to find an heuristic to detect when a login is considered expired by the BL servers...
