### ISSUE TITLE
Please add a Quick Filter contextual/menu option

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#49]
Please add a Quick filter menu option like here somewhere, especially in the contextual but also the menu:

![image](https://user-images.githubusercontent.com/32078594/103912686-e267b380-5107-11eb-95e5-387af36483ef.png)

Filter textbox is fine but complicated, needs a lot of typing without error, especially for column titles (Part#, Part #, Qty, Qty.?)...

We could have a Quick Filter option, applied based on the current lign AND column selected or right clicked:

Quick Filter

- Same (would work for every column, like Part #, Description, Color, Price, Qty...), and would set a Filter “Part # 6091” (for example)
- Different (same as above, but the opposite)
- Less than (would not work for Part # or Description, but for Qty, Price...)
- More than (same as above, but the opposite)
- Clear filter (would clear any filter, if any)

**That would give a very handy filter WITHOUT typing ANYTHING and changing focus, and would solve maybe 80% of the basic everyday filter cases!**

Icon could be something like this 
![image](https://user-images.githubusercontent.com/32078594/103914114-a3d2f880-5109-11eb-9fb6-d9731746e035.png)

**Comment by BrickSouth** [comment]
A filter would be especially helpful when you import your store inventory and are looking for particular parts in a huge list. I suggest making it similar to the filters in Excel.

**Comment by paramecie** [comment]
Thanks for your support, that's very important ;-)
But maybe not like Excel, or not now - I guess it would be far more complicated...

If we'd have a simple right click, select Quick Filter / Same, left quick... that's already VERY nice (IMHO).

**Comment by paramecie** [comment]
Apparently, we now have a straight Filter on selection (selected column == selected value).

Thank you!
