### ISSUE TITLE
Downloaded store is marked as modified if a modified document is open

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#491]
If I have a modified document open and then I download my store the main window title contains an asterisk as if the store is modified - 'Store * — BrickStore'. There's no asterisk in the 'open documents' widget or the 'windows' menu. This doesn't happen if I have an unmodified document open.

Win10, build #579

**Comment by rgriebl** [comment]
Manually closing, because I had a typo in a `Closes:` commit header.
