### ISSUE TITLE
Pressing 'Enter'  on the 'Appears in' widget in the insert dialog

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#493]
If I'm in the insert dialog I can select a set from the 'appears in' widget and part it out by selecting 'part out' in the context menu.

But if I press 'enter' instead of opening the context menu then the set is parted out and the selected part from the main item list is added to the end of the set inventory creating an incorrect part-out.

Win 10, build #584

**Comment by rgriebl** [comment]
Well, the bug is that there shouldn't be a "Part Out" menu item available in the "Insert" dialog to begin with. Good thing it didn't just crash 😃

**Comment by SteveTheBrick** [comment]
Oh well, it's actually quite useful, but no problem if you need to remove it.

**Comment by ZZJHONS** [comment]
Parting out from there works well when you want to locate a strange part to find out which set it is from so you can piece it together from a bulk lot.
