### ISSUE TITLE
Font size text not working properly

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#495]
Not all text is scaled up:

![image](https://user-images.githubusercontent.com/1063368/150340784-7fa9f0a1-bf82-4982-aa61-30ad79b95573.png)

![image](https://user-images.githubusercontent.com/1063368/150340798-37f06e7e-69b4-49dd-9812-65c2553e4c5f.png)

![image](https://user-images.githubusercontent.com/1063368/150341208-54f45812-cfb6-4ca3-8e4f-bfb69f73e4a1.png)

It is not much noticeable in screenshoots but some text remains really small

**Comment by rgriebl** [comment]
Does it work if you restart BrickStore?

**Comment by ZZJHONS** [comment]
Nope

![image](https://user-images.githubusercontent.com/1063368/150361875-9a78f0ef-ec61-4bfe-860a-70083aa745c9.png)
