### ISSUE TITLE
Import "Bricklink Store Inventory" fails

### ISSUE THREAD

**Issue by outbreaker8** [rgriebl/brickstore#500]
Using newest version (2022.1.1 build 596).

When importing the inventory from my bricklink store I get:
![image](https://user-images.githubusercontent.com/17637836/150648054-d1839bf0-2132-4c1d-abd0-c287f9788c87.png)

In the previous version it worked with my very similar inventory of yesterday.
In the old version of BrickStock it still does (just tried to exclude a problem with the data).

Unfortunately, I didn't find a way to grab the XML to provide more info on the source file.

**Comment by rgriebl** [comment]
I guess this is yet another malformed XML produced by BrickLink. Wouldn't be the first :(

Please download the XML manually here: https://www.bricklink.com/invExcel.asp

Then either open it in a text editor and paste the area around line 31794 here, are just zip up the XML file and send it to me via mail (click on my name).

**Comment by outbreaker8** [comment]
Thanks for the speedy response 👍 

![image](https://user-images.githubusercontent.com/17637836/150649101-0452af44-8ddc-425d-9f39-0ac03364654d.png)
At first: looks like it is not my lovely character escaping in the description ;)
If this is not sufficient, I'm happy to send you the file.

**Comment by rgriebl** [comment]
Yes, the escaping seems valid (things like that were often a problem in the past).
Please send me that file - seems like I have to load it up in the debugger.

**Comment by outbreaker8** [comment]
Solved - error/incorrect escaping in inventory file
