### ISSUE TITLE
File not found - Crash

### ISSUE THREAD

**Issue by mevitsbricks** [rgriebl/brickstore#501]
I closed brickstore with a .bsx file opened.  I then moved that .bsx file to a completed area.  When I opened Brickstore it complained about not being able to find a file and then closed.  It did that over and over.  I finally moved the file back to the original location and the program started right up.  If someone deletes the file and can't restore it then they won't be able to open the app.

Thanks,

Mevit (Kevin)

**Comment by beaverbrick** [comment]
What version are you running?
I've just tested this on the latest release 2022.1.1 (build: 596) and it works OK.

It does throw a warning about not being able to find the file, but after clicking OK the program does not close/crash and you can carry on using the program as normal.

**Comment by mevitsbricks** [comment]
[image: image.png]
Interestingly it is happening on only one of my workstations. My other
workstation is working as you mentioned.   I'll try uninstalling and
reinstalling on my other workstation tomorrow.

Thank you,

Mevit (Kevin)

**Comment by rgriebl** [comment]
I see quite a few weird crashes via sentry when displaying message boxes, but I don't have a problem on any of my machines.

@mevitsbricks could you please test the newest dev build 601 on the workstation where you are having problems? https://github.com/rgriebl/brickstore/actions/runs/1734128848

**Comment by rgriebl** [comment]
@mevitsbricks Any chance you could test the dev build? Thanks!

**Comment by mevitsbricks** [comment]
Just tried now and the new build is working fine on my system.

Thank you,

Kevin

**Comment by rgriebl** [comment]
Thanks for testing
Fixed by bbee01ec
