### ISSUE TITLE
Failed to download the store inventory: Host not found

### ISSUE THREAD

**Issue by RedWolves** [rgriebl/brickstore#502]
![image](https://user-images.githubusercontent.com/129322/150659515-2aefd7b7-df4d-4704-a143-77cee49cd4f9.png)

I get this error randomly when trying to download my store inventory.  However it seems like I get it when I try to download my store inventory for a second time after the program has been open for a while. 

Restarting BrickStore and trying to import store inventory after it loads works.

**Comment by ZZJHONS** [comment]
Working fine here, maybe you were trying during daily mantenience?
