### ISSUE TITLE
Add a bit more info to the Order details.

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#503]
![image](https://user-images.githubusercontent.com/1063368/150676202-a96e4a36-1e8d-4fc3-b5f2-57fe346606a7.png)

![image](https://user-images.githubusercontent.com/1063368/150676295-a75757b2-f50b-408c-bc8a-3f1693d3f48e.png)

Yellow: Order Shipping Method name
Orange: Order Payment Method and  maybe the status of payment too.
Green: The same country flag that appears in the order details, so we have a bit of color in that screen ;)

**Comment by rgriebl** [comment]
The shipping method would be nice, but it's not available in the XML.
