### ISSUE TITLE
files won't close properly

### ISSUE THREAD

**Issue by newfie675** [rgriebl/brickstore#505]
Hi, with the new version 2022.1.1 build 596 files will not close using command + w or the close command under the file. Brickstore asks if you want to save, but the file remains open in the list. If I quit Brickstore and reopen it asks if I want to recover the files that were open when Brickstore crashed. Those files are the ones that did not close prior to quitting. The other files that were open when quitting does not open like the previous version.

Thanks
Chris

**Comment by rgriebl** [comment]
Could you please try if the dev build 603 fixes the problem: https://github.com/rgriebl/brickstore/actions/runs/1742037695 (scroll down for the download links).
Thanks!

**Comment by BrickArena** [comment]
I also am unable to close documents (I'm on MacOS). Pressing the close icon clears the window but leaves the document in the dropdown and in the open documents window and clicking on it immediately shows the document again. I have tried the developer release mentioned in your response and this does not resolve the issue.
