### ISSUE TITLE
Issues typing in search area of "Add Items to..." 

### ISSUE THREAD

**Issue by mevitsbricks** [rgriebl/brickstore#507]
As I am typing a number into the search bar of "Add items to" the number jumps around and never completes what I am typing.  In the screen video, I'm trying to type "2458".
Please see video: https://www.screencast.com/t/VCGrMTvH

Thanks,

Kevin

**Comment by mevitsbricks** [comment]
Using version 2022.1.2 (build: 608)

**Comment by ZZJHONS** [comment]
I can replicate.

**Comment by rgriebl** [comment]
A quick workaround, if you want to stay on the released version: Press `Cursor down` in the empty filter field and remove all the saved favorite filters.
Also, don't save any new ones ... the list opening and closing is what messes with the selection.
