### ISSUE TITLE
Build 608 - Add items screen

### ISSUE THREAD

**Issue by jsandawg** [rgriebl/brickstore#508]
When entering numbers in Add items screen filter, the text highlights and you type over already entered text.  For example trying to to type in part 6180.  I type 61, it highlights and then the 80 shows up as final entry, unless I stop after the 61 entry and hit the right arrow key to clear the highlighted text before entering the 80.  

![image](https://user-images.githubusercontent.com/61241208/151066576-9af72fdd-2735-4229-bfec-61fc3cd0b360.png)

**Comment by mevitsbricks** [comment]
Check this closed issue: https://github.com/rgriebl/brickstore/issues/507#issuecomment-1021619423

**Comment by jsandawg** [comment]
Thanks!  Is there a setting to prevent it from saving the filters?
