### ISSUE TITLE
Copy values from Document

### ISSUE THREAD

**Issue by UticaBrix** [rgriebl/brickstore#509]
The new update, selecting "Copy values from Document" is not working.

**Comment by rgriebl** [comment]
You have to be a bit more specific on what you are trying to do, because a quick test on Windows shows that copying the price between 2 documents works perfectly fine for me.

**Comment by UticaBrix** [comment]
Nevermind, I restarted computer after the update and it worked.  Must have just been a glitch.
Thank you for your time.

**Comment by Threewit** [comment]
> You have to be a bit more specific on what you are trying to do, because a quick test on Windows shows that copying the price between 2 documents works perfectly fine for me.

Does it have to be color specific to work or just item number? i have not been able to get this feature to work.

**Comment by rgriebl** [comment]
All of item-id + color + condition have to match. The same way as BrickLink is doing its consolidation on upload.
