### ISSUE TITLE
import order is pulling different item ids

### ISSUE THREAD

**Issue by RedWolves** [rgriebl/brickstore#510]
When importing an order (received or placed) everything is correct except the item id the color, quanty, price and are all correct but the items id/description are coming from I don't know where they are completely wrong.  

Imported order
![image](https://user-images.githubusercontent.com/129322/151636890-98542145-fc7f-44b1-a9f4-a5f7532b9d2e.png)

Actual order
![image](https://user-images.githubusercontent.com/129322/151636919-a29f7f5c-1547-436d-8fca-264b3339d9c1.png)

**Comment by rgriebl** [comment]
Did you update the database manually while BrickStore was running? Does it work again after re-starting BrickStore?
I forgot to clear the cached orders when updating the database, so that would explain it (although on my machine, it just plain crashes ;) )
