### ISSUE TITLE
Case sensitivty of xml tags?

### ISSUE THREAD

**Issue by amordicus** [rgriebl/brickstore#515]
When importing xml file, it seems that the XML tags must be CAPITAL letters?

I think that as long as the opening tag is the same as the closing tag it should have worked, but it didn't?

i.e.  
```<Inventory>
  <Item>
    <ItemType>P</ItemType>
    <ItemID>x486</ItemID>
    <Color>11</Color>
    <MinQty>1</MinQty>
  </Item>
</Inventory>
```

should work as well as 

```<INVENTORY>
  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>x486</ITEMID>
    <COLOR>11</COLOR>
    <MINQTY>1</MINQTY>
  </ITEM>
</INVENTORY>
```

[rg: added backticks to make the XML readable]

**Comment by amordicus** [comment]
Sorry, maybe I wasn’t clear enough.  Wikipedia says the same thing as me in my issue report  "Tag names are case-sensitive; the start-tag and end-tag must match exactly”.  The problem is that if I try to import a file that is not all CAPITAL letters it doesn’t work, see my example in my issue #515.

If you try this it is not going to work although the start and ending tags are the same as per Wikipedia.

<Inventory>
    <Item>
    <ItemType>P</ItemType>
    <ItemID>x486</ItemID>
    <Color>11</Color>
    <MinQty>1</MinQty>
  </Item>
</Inventory>

Somehow <Inventory> is missing in my issue, I’ll edit it!

Joseph

**Comment by rgriebl** [comment]
Still nope:

http://xml.silmaril.ie/case.html

This is XML not HTML. 
 * BSX is defined in an official schema here: https://github.com/rgriebl/brickstore/blob/main/BrickStoreXML.rnc and uses CamelCase
 * BrickLink's XML has no official DTD/schema, but it's well documented here: https://www.bricklink.com/help.asp?helpID=207 and uses UPPER case

**Comment by ZZJHONS** [comment]
@rgriebl seems the BrickstoreXML schema page needs to be updated with some of the column additions?

Also seems BL started updating their page this year.
