### ISSUE TITLE
Missing Item 23306 

### ISSUE THREAD

**Issue by DNKpp** [rgriebl/brickstore#517]
Hey, I manually updated the db, but the item ``23306 Weapon Lightsaber Hilt without Bottom Ring`` still can't be found. Is that a mistake of mine or actually an oversight?
https://rebrickable.com/parts/23306/weapon-lightsaber-hilt-without-bottom-ring/

**Comment by ZZJHONS** [comment]
That one is an alternate of this: https://www.bricklink.com/v2/catalog/catalogitem.page?P=64567

**Comment by DNKpp** [comment]
Yeah, I saw that on the page, too. Sry, I'm not too deep into the lego brick business, I just want to catalog my parts :D
My parts actually don't have that ring, thus they should be the ``23306``?

**Comment by rgriebl** [comment]
Alternate item numbers are not available via BL's catalog download API. I really would like to have this in BrickStore, but without substantial changes to BL's development process this is sadly never going to happen.
