### ISSUE TITLE
Cannot Add parts

### ISSUE THREAD

**Issue by bekel85** [rgriebl/brickstore#518]
I am trying to update and add parts to my inventory, but when i click Add, nothing gets added to my inventory. This is an intermittent issue that i have experienced in the past, but for some reason this time i cannot seem to add any more 1 x 1 tiles to my inventory. If i switch to a different part i can add that part, but as soon as i try to add a 1x1 tile again, Brickstore will show that it was added on the add part page, but my inventory will not show the part being added. I have tried re-downloading Brickstore again to see if that would fix the issue, but it still exists. Please contact me if you have questions or can explain why this is happening. I am a new user and am not overly familiar with Brickstore yet.

**Comment by bekel85** [comment]
I did have consolidate selected, but the problem was that I could not find the part that I just added. I could search for the number and nothing would show up in my inventory. However, if I started a new BSX file I could add parts without issue. It happens maybe once every 1000 lots, but I don’t know why it happens. 

Regards,
Nick Bekeleski

**Comment by rgriebl** [comment]
Nobody else ever had this problem before and since this is a core functionality, I'm sure others would have reported this as well... I'll keep this bug report open for now to see if other people chime in.

**Comment by rgriebl** [comment]
Closing for now, as nobody else seems to have this problem. Please re-open if it happens again.
Ideally add a screenshot of the add-item dialog in this state.
