### ISSUE TITLE
Add integration with Rebrickable

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#519]
This is just to leave the idea here.

Rebrickable is the de facto website to share MOCs and it is connected to BrickLink pretty well.

The principal motive would be to get alternate IDs of parts easily.

For example the piece 64567 on BL it is also: 577, 15556, 23306, 86132, 22232 

So a call like: https://rebrickable.com/api/v3/lego/parts/?search=23306

Would return:

> {
>   "count": 2,
>   "next": null,
>   "previous": null,
>   "results": [
>     {
>       "part_num": "23306",
>       "name": "Weapon Lightsaber Hilt without Bottom Ring",
>       "part_cat_id": 27,
>       "part_url": "https://rebrickable.com/parts/23306/weapon-lightsaber-hilt-without-bottom-ring/",
>       "part_img_url": "https://cdn.rebrickable.com/media/parts/ldraw/383/23306.png",
>       "external_ids": {
>         "BrickLink": [
>           "64567"
>         ],
>         "BrickOwl": [
>           "459306"
>         ],
>         "Brickset": [
>           "22232",
>           "23306"
>         ],
>         "LDraw": [
>           "23306",
>           "577a"
>         ],
>         "LEGO": [
>           "22232",
>           "23306"
>         ],
>         "Peeron": [
>           "577"
>         ]
>       },
>       "print_of": null
>     },
>     {
>       "part_num": "64567",
>       "name": "Weapon Lightsaber Hilt with Bottom Ring",
>       "part_cat_id": 27,
>       "part_url": "https://rebrickable.com/parts/64567/weapon-lightsaber-hilt-with-bottom-ring/",
>       "part_img_url": "https://cdn.rebrickable.com/media/parts/elements/4539482.jpg",
>       "external_ids": {
>         "BrickOwl": [
>           "459306"
>         ],
>         "Brickset": [
>           "15556",
>           "64567",
>           "86132"
>         ],
>         "LDraw": [
>           "577b",
>           "64567a"
>         ],
>         "LEGO": [
>           "15556",
>           "64567",
>           "86132"
>         ],
>         "Peeron": [
>           "577"
>         ]
>       },
>       "print_of": null
>     }
>   ]
> }

So the search for parts inside BrickStore can return the actual BL ID

Link: https://rebrickable.com/api/v3/docs/

PD: Or If you can download the parts db from them and use the data to fill the BS db, but seems the parts_rel csv only contains separated entries in the DB not the actual alternate IDs, so 23306 is listed for64657 but the rest are not.
https://rebrickable.com/downloads/

**Comment by rgriebl** [comment]
I looked at that back when you opened this issue, but totally forgot to comment afterwards:
as you already found out, not all alternate ids are available via the CSV downloads and running ~100K API calls daily is not a viable option: 
a) performance wise and 
b) rebrickable explicitly states: _"If you need more details, you can use the [API](https://rebrickable.com/api/) which provides real-time data, but has rate limits that prevent bulk downloading of data."_

**Comment by ZZJHONS** [comment]
Well... Maybe Nathan or TobyMac can update the download files with those or to talk something between both of you behind the scenes ;)

https://forum.rebrickable.com/t/rebrickable-api-data-usage-restrictions/83178/19

https://rebrickable.com/users/TobyMac/profile/

**Comment by ZZJHONS** [comment]
Since Bricklink added the Alternate ID field to its download this issue is no longer needed!
