### ISSUE TITLE
English and all languages, simplify Column names for Filter

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#52]
As Filters can be long and painful to write (even if very powerful!), could we decide to simplify in all languages the column titles?

![image](https://user-images.githubusercontent.com/32078594/103924307-219d0100-5116-11eb-8d55-c904b6049b0b.png)

By:
- removing all dots "."
- using always single words, abbreviated
- maybe shorter names, like Descr instead of Description

That would give:
- Qty instead of Qty.
- Part# instead of Part # (and I would even prefer Ref)
- QtyDiff instead of Qty.Diff.
- PrDiff
- Type instead of Item Type
- Descr, Cat, Comment, Remark...

Etc.

Filters would be far easier to type.

**Comment by chiminirc** [comment]
If the direction is not including the multi line searching, I agree some of the column names could use improvement.
I think the benefit of what brickstock did is the column names would dynamically update to the language you are using.
![image](https://user-images.githubusercontent.com/76887746/103925290-eaf6c480-50dc-11eb-91b5-ef663a033505.png)

**Comment by paramecie** [comment]
Oh - columns names ARE translated, at least they should be, if translators do their job ;-)
