### ISSUE TITLE
right click to add figs and collapsible tree view buy attribute

### ISSUE THREAD

**Issue by GreatBrickLab** [rgriebl/brickstore#520]
Feature add request,

1.  It would be nice to be able to right click > add part / set from the "Appears in Sets" toolbar,  not just double click to partout.

2.  It would be nice to create a tree view by an attribute,   i.e.  from remarks,  then I could see all my store, but expand the drawer or location I am working on only,  OR from the part# I could see all the location where that part is located at.   If this is possible then I could start to consolidate a part that is located in multiple location with an improvement in the consolidate items,   with the tree view I could focus on the one part and then consolidate give me a report where they are all located at,  and from the full store download create the changes to the qty in the LOT# to make an update XML to move all those parts,   not sure if this was clear, 

Thank you, thank you, thank you for the tool update,  Game Changer!!!!

**Comment by BrickSouth** [comment]
I had a similar request back on #406. Currently I am finding minfigures by searching based on decorated torsos, double clicking on the figure down at the bottom that has that torso to part it out and see what other parts I need to look for. If I find all the parts and complete the figure, right clicking on the "figures that have this torso" section should give you the option to include the whole figure. I would include a screenshot, but for some reason I can never get Github to attach an image.

**Comment by rgriebl** [comment]
Going through old reports...

1. is already implemented and much more powerful thanks to all the new relationships
1. I played around with a tree-view, but it's a nightmare implementation wise. What you can do to simulate the grouping tree, is to right-click the value you want to "group" on and do a `Create filter from the selection`. Clicking `x` on the filter gets you back to full view.

There also #442, so I'm closing this one.
