### ISSUE TITLE
Crash on paste and consolidate

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#521]
I had several crashes today when trying to paste and consolidate one particular item in one specific file.

I can upload a sample file with instructions to reproduce if the sentry reports are not sufficient to track down the problem.

**Comment by rgriebl** [comment]
Please upload that file plus the instructions. This would be much easier for me to debug than trying to figure out crashes after the fact with mostly only stack traces to work with.

**Comment by SteveTheBrick** [comment]
To reproduce:

Open the attached file and select the top item (hinge brick with top plate).

Select 'part out item' and part it out into a new document.

Select both items in the new document and copy them to the clipboard.

Go back to the original document (with the top item still selected) and select 'paste' - choose 'overwrite currently selected items'.

The 'consolidate' dialog appears - select the hinge brick at the bottom and click on 'yes'.

Brickstore crashes.

Win10, build #634


[Inventory for 8129 Walker2.zip](https://github.com/rgriebl/brickstore/files/8005890/Inventory.for.8129.Walker2.zip)

**Comment by SteveTheBrick** [comment]
Also please leave the filter in place - the crash doesn't happen without the filter

**Comment by rgriebl** [comment]
Thanks! I can reproduce the crash.
