### ISSUE TITLE
BrickLink names sometimes have extra spaces to sort alphabetically, but BS displays them differently depending where.

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#522]
<img width="749" alt="image" src="https://user-images.githubusercontent.com/1063368/152963913-2b65a344-1e78-4321-9c46-02430206d9d8.png">

As noticed by a BL user: https://www.bricklink.com/messageThread.asp?ID=316883&nID=1326529

But seems BS renders the spaces correctly in the list and document, but on the boxes with images is stripped down.

So all or just 1 but everywhere the same?

**Comment by rgriebl** [comment]
It's the same as with BrickLink itself: as soon as a double-space is passed to a HTML renderer (the tooltip and the info box are just small HTML documents), it gets squished into a single one.
I guess it makes sense to trim out all the double spaces for the BrickStore database: BrickStore already sorts correctly without the need for those weird spaces, plus it makes filtering documents awkward.
