### ISSUE TITLE
Instrucctions image shows the Set one instead

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#523]
<img width="344" alt="image" src="https://user-images.githubusercontent.com/1063368/153069376-53dcd90d-83ac-4c11-a0ff-c286f5b1c7a5.png">
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/1063368/153069442-c6262adc-4d69-4061-8f0b-bc6fdf5b315a.png">

Also notice its item type if not a part in the Info tab?

**Comment by rgriebl** [comment]
Oh well ... seems like I can remove another hack then :) In the good old times there were no pictures for instructions, so I had to add a hack to redirect those to the corresponding set picture.
