### ISSUE TITLE
Double Clicking Item in "Appears in Set" No Longer "Parts Out" to Inventory

### ISSUE THREAD

**Issue by Chrillusionist** [rgriebl/brickstore#526]
Hello,

The screenshot shows the "Add Items to Inventory" window and a minifig's torso and to the right of that it shows the complete minifig. In BrickStore version 2022.1.3 when double clicking the complete minifig, it would part out the complete minifig into an Inventory List (or new item list). That no longer happens after updating to Version 2022.2.1. It is a big time saver to be able to part out the set by double clicking.

We greatly appreciate the past updates, but we downdated to the previous version and hope that the function is able to be reincorporated in a future update.

Thank you! :-)

![Version 2022 2 1 Bug](https://user-images.githubusercontent.com/99374634/153322737-bea782bf-e5d8-479f-b532-95b816e8d6da.jpg)

**Comment by ZZJHONS** [comment]
It is still working on the "Appears in" info doc but having the option with right-click there would be good too:

<img width="299" alt="image" src="https://user-images.githubusercontent.com/1063368/153378525-c4eb5e6b-2db7-4c50-bfe6-1bb0adf0dff6.png">

+Add to current file
+Part out in new file

Similar to the Appears In info dock:

<img width="344" alt="image" src="https://user-images.githubusercontent.com/1063368/153378799-010d6a29-1b1e-4c78-8a28-403c00029c18.png">
