### ISSUE TITLE
New pane to help with building minifigures

### ISSUE THREAD

**Issue by BrickSouth** [rgriebl/brickstore#527]
Let me begin by saying I realize this is probably a long term addition, but I wanted to start the conversation about adding functionality that would aid in minifigure assembly.

I understand everybody's process might be a little different regarding assembling used minifigs, but I would assume almost everyone begins with a decorated torso. What I've been doing is color locking on the torso color to narrow down the selection and then in the search bar typing in the "arm color" and "hand color" to narrow down even further. A lot of times, I don't even need any other search terms to find the torso I am looking for. This aspect of the program is awesome. After that, it becomes a little more cumbersome at putting together minifigs and I feel could be improved. 

So I've found the torso using the process I described above and I've got a handful of different minifigs that use that torso. How do I find the minifigure(s) that I have all the parts for? Currently, you have to hover the mouse over the "Appears In" section and the full fig image pops up. What would be better is if you could look at all of them at the same time. Having a new pane that you could toggle would be my suggestion. It could also show you the price guide data for the minifigures.

Here's a mockup of what I think it could look like:

![minifig add screen(1)](https://user-images.githubusercontent.com/76957522/153618605-e1f2c81b-f1d5-436a-9718-35dd2769af26.png)

![minifig add screen(2)](https://user-images.githubusercontent.com/76957522/153617031-94099b0d-2314-4808-8f90-da57c6340a63.png)

![minifig add screen(3)](https://user-images.githubusercontent.com/76957522/153618739-8b31e7ad-d386-47bf-9ce6-81bed63e2f41.png)

![minifig add screen(4)](https://user-images.githubusercontent.com/76957522/153619235-b133c6ea-3de5-4ed5-abb4-70c0526ce34f.png)

![minifig add screen(5)](https://user-images.githubusercontent.com/76957522/153620751-c06aded7-01a8-4b22-a629-3b36f858f831.png)

**Comment by rgriebl** [comment]
Going through old reports...
This is already available now: just use the `appears-in` view and zoom in to enlarge the images
