### ISSUE TITLE
Baseplate category is blank on Add items to upload dialog

### ISSUE THREAD

**Issue by RedWolves** [rgriebl/brickstore#533]
When I try to add an item in the Parts > Baseplate category, no items load in for me. 

![image](https://user-images.githubusercontent.com/129322/153933938-440f47d7-671f-4cbf-afae-930b2993b16f.png)

**Comment by ZZJHONS** [comment]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/1063368/153941253-592276d2-2189-4176-bec9-c2e076e7a846.png">

I too experience this problem, also the right click doesn't work in the search results for the expected Baseplate category items

**Comment by rgriebl** [comment]
Finding this took me way longer than it should have :)
