### ISSUE TITLE
Comments Field in Add Item Dialog missing

### ISSUE THREAD

**Issue by xaraxarax** [rgriebl/brickstore#534]
Add item Dialog has no longer the Comments Field visible. 

The Add Item Dialog no longer has the input field for comments visible. I don't know since when, but I miss it so much ... maybe others do too.

![grafik](https://user-images.githubusercontent.com/79638214/154968825-126d9c50-3640-47a7-9d3a-2c332606e740.png)

**Comment by rgriebl** [comment]
Just re-enable the "Show Additional Input Fields" toggle in the lower left corner (4th button).

**Comment by xaraxarax** [comment]
omg, sorry, thanks
