### ISSUE TITLE
Request: Add more docks

### ISSUE THREAD

**Issue by areolysz** [rgriebl/brickstore#536]
Since version 2022.1.1 - 2022-01-21 I'm unable to see the price guide and the "appears in..." list/dock.
It would be great to be able to add a third dock and have the ability to move docks from one spot to the other.

**Comment by rgriebl** [comment]
Just grab the title bar (not the tab!) of the dock in question and drag it around: it'll show where it will snap in, when you let go of the mouse button. If it's not visible yet, click any one of the vertical three-dot menus and activate the dock you need.
If you drag one dock directly over another one, if will create a stack (tabs). If you drag it towards the top or bottom edge it will position the dragged dock on top or below the other one. This also works on the right side.

**Comment by areolysz** [comment]
Perfect! Thanks for the quick reply. 😸  👍
