### ISSUE TITLE
Document, big selection with SHIFT+HOME/END/PAGE UP/DOWN

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#54]
Please make it possible to use the "traditionals" shortcut to select big ranges with the keyboard.
An old-school guy like me uses this every day :-)

I mean, when say you're in the middle of a big list, have selected 1 item, then you'd use SHIFT+HOME or SHIT+PAGE UP to select everything from here up to the end of page, or the beginning of the list.

I doesn't have the old BrickStore installed, but BrickStock implements this - the new BrickStore doesn't.

**Comment by rgriebl** [comment]
Shift+PageUp/Down works, Shift+Home/End selects start/end of line. I'll see if I can tell Qt to change from line to column in this case.

**Comment by paramecie** [comment]
Ooops - agreed on PageUp/Down!

And CTRL H/E PU/PD also would be nice :-)

**Comment by rgriebl** [comment]
All the movement commands are hardcoded in Qt's TableView component. This isn't a quick fix.

**Comment by paramecie** [comment]
https://doc.qt.io/qt-5/qshortcut.html
?

From:
https://stackoverflow.com/questions/51823289/pyqt-qtableview-capture-keydown-keypress-event

**Comment by paramecie** [comment]
BUMP!

I hope with the new QT and such that traditional selection with the keyboard is possible!

I miss this A LOT personnaly, and as I've taken the habit to use it, it messes my list (scrolling to the right part of it for example).

**Comment by xaraxarax** [comment]
Any news to this? (We) continue to miss this ...

**Comment by paramecie** [comment]
Thank you!
