### ISSUE TITLE
Is there a way to add a column for date in current inventory?

### ISSUE THREAD

**Issue by GreatBrickLab** [rgriebl/brickstore#541]
The concept of sell through is something worth looking into.   The data from the current inventory "QTY(Stores)" and the ratio of how many have sold vrs how many are available could be quite valuable to know as you list parts that have sold more that are currently available.  Either way, being able to add a column for this data would prove valuble.

Chris
GBL

**Comment by rgriebl** [comment]
I've now created a super-task issue for custom columns: #617

I will close this issue here however, as it will not be implemented in BrickStore itself and just sitting around in the bug tracker as an open bug for years doesn't help anyone.
