### ISSUE TITLE
Suggestion: Sell through % column

### ISSUE THREAD

**Issue by davidwestt** [rgriebl/brickstore#544]
Would be great to have a column that compares lots available vs lots sold in the last 6 months represented by a percentage. 
Eg if 300 lots have sold in the last 6 months and only 150 lots are available the column reads 200%

Thanks for all you do!

David

**Comment by rgriebl** [comment]
I've now created a super-task issue for custom columns: #617

I will close this issue here however, as it will not be implemented in BrickStore itself and just sitting around in the bug tracker as an open bug for years doesn't help anyone.
