### ISSUE TITLE
Pricing update freezes

### ISSUE THREAD

**Issue by newfie675** [rgriebl/brickstore#548]
When I try to add prices to an item (command+G) I get a window asking what price, I click ok and I get a 2nd window "downloading price guide..." and it will not complete the task. I can cancel that window, command+G immediately after and it works.
![image](https://user-images.githubusercontent.com/96376889/164040918-8f388563-acd3-4c3b-a802-a45c94bb2b6c.png)

**Comment by rgriebl** [comment]
Oops ... I totally missed this one. Sorry about that.
Does this still happen in the current 2022.10.1 version?

**Comment by newfie675** [comment]
No it seems to be fixed. I figured out it happened when there was a
database update. If i closed brickstore and reopen the database updates and
the update current prices worked again.
