### ISSUE TITLE
New "Price Set to value" menu option

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#55]
Say I have this list of parts with Avg prices for a total of 2723 USD.
I know that I paid this 1000 USD.
I would like the individual items to now proportionnaly reflect this buying price.
_Later on, I can affect my selling price based on this, but it's another story._

Right now you've to get your calculator for something like this:
(shown price - buying price)/shown price => gives you a percent, here 0.633 or 63.3% less.

Now you can use CTRL+A  then Price / Set and pick Decrease (or CTRL+"+"), and type 63.3 %, hoping you didn't miss a digit.
The total list is now 1000 USD

A new option menu would be far better : a simple field, you enter the desired target value, and BrickStore calculates the individual prices :-)

![image](https://user-images.githubusercontent.com/32078594/103950360-07c2e480-513d-11eb-8030-ed649b1bbc28.png)

**Comment by rgriebl** [comment]
Can we close this, now that support for the cost field and the "spread purchase amount" functionality is in?

**Comment by paramecie** [comment]
If you wish, but no for me :)

I mean, this feature Spread does set a Cost, NOT a Price.

Ahhh don't move, I've a simple idea people will like :)

**Comment by paramecie** [comment]
Done, see #203

**Comment by rgriebl** [comment]
Closing this one, but keeping #203 open

**Comment by paramecie** [comment]
OK, I'll put a comment there.
