### ISSUE TITLE
Swedish translation of Brickstore

### ISSUE THREAD

**Issue by jjcchh754** [rgriebl/brickstore#551]
Hey

I would love to help with translating to Swedish.
Best regards
Johan

**Comment by rgriebl** [comment]
Hi Johan,
And I would like to have one :) Please be aware that BrickStore gains new features all the time, so the translations have to be adapted for each new release to keep the UI consistent.

I've created a wiki page that should get you going with the translation: https://github.com/rgriebl/brickstore/wiki/Translating-BrickStore

As for the needed `.ts` file: please download the `brickstore_se.zip` attached to this message, open the ZIP and copy the `brickstore_se.ts` from the ZIP out into the `translations` folder after downloading BrickStore's sources.

(GitHub wouldn't let me attach a `.ts` file directly, so I had to ZIP it)

@ZZJHONS just did the Spanish translation recently, so he might also be able to help if you have questions


[brickstore_se.zip](https://github.com/rgriebl/brickstore/files/8691482/brickstore_se.zip)
.

**Comment by jjcchh754** [comment]
Hello thereI have started the translation work now. I have a plan that first version of the translation would be done within may month.Best regards,JohanDen 13 maj 2022 kl. 23:45 skrev rgriebl ***@***.***>:Hi Johan, And I would like to have one :) Please be aware that BrickStore gains new features all the time, so the translations have to be adapted for each new release to keep the UI consistent.I've created a wiki page that should get you going with the translation: https://github.com/rgriebl/brickstore/wiki/Translating-BrickStoreAs for the needed .ts file: please download the brickstore_se.zip attached to this message, open the ZIP and copy the brickstore_se.ts from the ZIP out into the translations folder after downloading BrickStore's sources.(GitHub wouldn't let me attach a .ts file directly, so I had to ZIP ***@***.*** just did the Spanish translation recently, so he might also be able to help if you have questionsbrickstore_se.zip .—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by jjcchh754** [comment]
HeyI am sorry if I havent been in contact with you last month. I just wanna say I am still gettin a first translation to swedish. I think I have around 1/4 left to do.There is alot of specific words Like lots, batch and so on that I am struggling with. I want thoose words be as good as possible and Same translation all over :)Best regards,JOhanDen 13 maj 2022 kl. 23:45 skrev rgriebl ***@***.***>:Hi Johan, And I would like to have one :) Please be aware that BrickStore gains new features all the time, so the translations have to be adapted for each new release to keep the UI consistent.I've created a wiki page that should get you going with the translation: https://github.com/rgriebl/brickstore/wiki/Translating-BrickStoreAs for the needed .ts file: please download the brickstore_se.zip attached to this message, open the ZIP and copy the brickstore_se.ts from the ZIP out into the translations folder after downloading BrickStore's sources.(GitHub wouldn't let me attach a .ts file directly, so I had to ZIP ***@***.*** just did the Spanish translation recently, so he might also be able to help if you have questionsbrickstore_se.zip .—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by rgriebl** [comment]
Just take your time!

**Comment by jjcchh754** [comment]
HeyThis took alot more time then I was thinking. But actually I am done.My question is, do I need to finalize the translation with the new version? if so are you able to put up a new .ts file for me?Best regards,JohanDen 14 juni 2022 kl. 15:17 skrev rgriebl ***@***.***>:Just take your time!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by rgriebl** [comment]
Hi Johan,
Thanks for your work! The easiest way would be to send the .ts file to me via mail (click my name) and I'll merge it into the current code base. From then on, you can re-download the merged .ts directly from GitHub to work on it further.

**Comment by jjcchh754** [comment]
Here it comes :)Can I ask, is it a very huge effort to make the priceguide local... I mean like I can say in settings I want my priceguide information to be for sweden. And all Priceguide information would be after that.I really love your program and use it More then daily. But I work ALOT with setting prices and it takes alot of time. I think if the prices shown in priceguide would spare me MANY hours.Best Regards,JohanDen 10 nov. 2022 kl. 15:29 skrev rgriebl ***@***.***>:Hi Johan, Thanks for your work! The easiest way would be to send the .ts file to me via mail (click my name) and I'll merge it into the current code base. From then on, you can re-download the merged .ts directly from GitHub to work on it further.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by rgriebl** [comment]
In case you attached the .ts file to your last reply: this doesn't work as GitHub filters out anything it doesn't know about. You have to either ZIP it, or send it directly to my private mail address.

**Comment by jjcchh754** [comment]
Mat I have your email :)

Johan

Skickat från min iPhone

**Comment by rgriebl** [comment]
As I wrote - if you read this message on GitHub web site, you can click my name to get it. I don't feel like inviting more spam than necessary by posting it to a public forum.

**Comment by jjcchh754** [comment]
Ooo sorry, I am writing from my mail and didn’t think about that, sorry. 

Johan

Skickat från min iPhone
