### ISSUE TITLE
Million separator not shown on the PG when <10M

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#555]
<img width="246" alt="image" src="https://user-images.githubusercontent.com/1063368/172050921-a972c9d8-a7f7-4259-9cdc-f2fc34444ec7.png">

**Comment by rgriebl** [comment]
Works for me! But there's more: in a Qt blog post about adding support for more localization features (https://www.qt.io/blog/teaching-qlocale-more-about-number-formats), I found this:

> For example, Spanish leaves 1000 ungrouped, only adding a comma when there are at least two digits before it, as at 10,000;

So it's your own fault, being Spanish and all that :)

**Comment by ZZJHONS** [comment]
Oh... Learnt something new!

Thanks for checking, I suppose localization is based on computer settings and not on the language settings [inside](https://www.youtube.com/user/boburnham/) BrickStore.

**Comment by rgriebl** [comment]
Yes - translation and localization are separate. Basing the whole localization on the language alone would force anybody using BrickStore in English to also deal with the weird US date formats. That's not something you want to wish upon your worst enemy, even if their first language was English :)
