### ISSUE TITLE
Importing Order does not work: XML error

### ISSUE THREAD

**Issue by Caryntjen** [rgriebl/brickstore#560]
Hi Robert,

importing my orders did work in the past but now it doesn't. I get the following order on Windows 11:
![image](https://user-images.githubusercontent.com/3481691/174482664-62d358af-24f0-4c5c-ba64-8a5150294601.png)

Using version 2022.4.1 build 663 in English

Tried several times, rebooted pc, lowered the or made the days higher, new login... I can import my store inventory.

**Comment by rgriebl** [comment]
Have you checked if your system drive (or the one with your user directory on it) is full or close to full?

Also check the Error Log (enable via `View` > `View Info Docks` > `ErrorLog`) if you see lines that say `Orders::orderSaveFile failed to open` after trying to update the orders.
If you do, please copy&paste the whole line here.

**Comment by Caryntjen** [comment]
FYI: I got the problem resolved with the following workaround:

Changed the username so the credentials were incorrect. The order screen then showed a different error. Corrected the username and I could properly import the orders again.
