### ISSUE TITLE
Shift + Sort doesn't work correctly on Diff. Price Column

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#561]
![image](https://user-images.githubusercontent.com/1063368/174785290-eaae04ca-e0bf-49a9-ae63-630871eb858a.png)

**Comment by rgriebl** [comment]
What do you expect would happen? The additional sort columns only come into play, if the values in the primary sort column are equal. In your case all values in "Remarks" are unique though...
