### ISSUE TITLE
Copy values from document default button

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#563]
When the Copy values from document window appears it is highlighted the button Next but if you just press Return/Space the window closes as if you clicked Cancel or Close. Shouldn't Return/Space just be as clicking Next?

**Comment by rgriebl** [comment]
I guess you meant the "Copy values from document" dialog? In that case the focus should always be on the first radio button `(o) Items from clipboard`, but it's hard to see in the dark theme. If you use the standard Windows theme you can see that is has a dotted rectangle around it.
The blue rectangle around `Next` is the so called "default" button on Windows, which gets triggered by pressing `Return`, regardless of what other element has focus.
In any case - Space never cancels the dialog for me ... which version are you using to test this?

**Comment by ZZJHONS** [comment]
You guessed right, I called it that because I had binded Ctrl+I, Ctrl+V for this...

Okay, understood the focus and blue rectangle difference.

Happens the same in all builds since I remember, currently 703 and 708, all on Windows 11.

Opening the dialog:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/1063368/176882418-ecb46692-3723-4674-87b0-232dda7ab4a5.png">

If I click the `[TAB]` key once:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/1063368/176882606-f48f5345-6aa5-4ed8-89ea-5e28fbb81c1c.png">

If then I press `Shift + Tab`:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/1063368/176882677-1b806067-55da-43b1-b61f-b49662ea4f73.png">

Seems the focus is on the Cancel button.
