### ISSUE TITLE
Mass-Update XML Contains More than 3 Decimal Places

### ISSUE THREAD

**Issue by serens2** [rgriebl/brickstore#57]
I'm trying to update my inventory using BrickStore. I imported my inventory into BrickStore and set all of the prices equal to the last 6 months quantity average. In BrickStore, the prices are shown to three decimal places; however, when I export my inventory as a BrickLink mass-update XML to clipboard, the prices in the XML vary from two to five decimal places and BrickLink throws an error. I tried rounding all of the prices to two decimal places, but the issue persists.

Here is a sample of my inventory in BrickStore, with the prices shown to three decimal places:

<img width="1186" alt="Screen Shot 2021-01-07 at 5 52 18 PM" src="https://user-images.githubusercontent.com/47232656/103957982-915cbd00-5111-11eb-8371-9ee822d21410.png">

And here is the BrickLink mass-update XML that is generated from it, with prices varying from two to five decimal places:

<img width="196" alt="Screen Shot 2021-01-07 at 5 54 20 PM" src="https://user-images.githubusercontent.com/47232656/103958072-c49f4c00-5111-11eb-8cda-0f04fbefc382.png">

I am using Brickstore 2021.1.2 on a 2018 Intel-based MacBook Pro running macOS Catalina 10.15.7.

**Comment by paramecie** [comment]
Confirmed here also:

![image](https://user-images.githubusercontent.com/32078594/103960137-c852c300-5151-11eb-8eca-95159f4360f1.png)

Someone just forgot a rounding somewhere :O)

**Comment by paramecie** [comment]
Boom! Corrected!

I wish BrickLink would have Robert as developper...
