### ISSUE TITLE
Fix "Show in My Store on Bricklink" link

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#570]
For a black 1 x 2 brick with ID 3004

Currently the link generated is: https://www.bricklink.com/inventory_detail.page?catType=P&q=3004&ColorID=11
It redirects to: https://www.bricklink.com/v2/inventory_detail.page?catType=P&q=3004&ColorID=11#/
But the result show all colors as only the query 3004 is processed by BL.

I checked Bricklink inventory page and it uses the itemID instead to show a part in a particular color with a link like this:

https://www.bricklink.com/v2/inventory_detail.page?itemID=280&colorID=11#/

So, does the BrickStore DB has the itemID that BL uses for each item number in the catalog and can use it to fix this link?

**Comment by SteveTheBrick** [comment]
Yes, this has been broken for a while and it may not be possible to get the redirect to work for colours.

On the plus side this link works works for me without needing the ItemID:

https://www.bricklink.com/v2/inventory_detail.page?q=Black%203004#/
