### ISSUE TITLE
New Item Ids not correct or available on BL

### ISSUE THREAD

**Issue by Caryntjen** [rgriebl/brickstore#571]
Hi,

I have uploaded the parts with the óld'(in red ids). No issues until recently and now BrickStore mentions they are incorrect in my inventory. The new IDs do not exists in BrickLink.

![image](https://user-images.githubusercontent.com/3481691/182047662-c655ebac-6ff9-4e5c-826d-235e26b140d2.png)

Any suggestions on how to fix this?

**Comment by rgriebl** [comment]
One of these items was changed yesterday, so the BrickStore database was not up-to-date yet (it's only regenerated once per day at 05:00 CET)

https://www.bricklink.com/catalogReqList.asp?nID=&viewDate=Y&viewType=E&viewStatus=A&viewYear=2022&viewMonth=7&q=66962c01

Save the file, update the database manually and reload the file. BrickStore should then update the items in question and notify you.

**Comment by Caryntjen** [comment]
Okay good to know. I'll wait at least 24h to try again. Thanks!
