### ISSUE TITLE
Cant add anything to the document

### ISSUE THREAD

**Issue by Schoen98** [rgriebl/brickstore#572]
When i'm in the menu picking a set or a part, i can't add the thing i want to. the add button is simply not available.

**Comment by rgriebl** [comment]
There is no "menu" to pick a part. You have to be a more specific on what you are trying to do and what doesn't work. Adding screenshots helps, as well as stating the version you are using.

If you are in the "Add Items" dialog and the "Add" button is disabled, check that the tiered prices and quantities make sense.

**Comment by Schoen98** [comment]
![IMG_20220805_105744](https://user-images.githubusercontent.com/110640548/183042680-cd56703f-98f5-4368-968e-910b91962b37.jpg)
![IMG_20220805_105801](https://user-images.githubusercontent.com/110640548/183042706-65851f65-abe3-451d-941b-a8af1110d74b.jpg)
![IMG_20220805_105826](https://user-images.githubusercontent.com/110640548/183042717-09836ef2-cfb5-4aec-abc8-905a2a4215dc.jpg)

I'm in th add items dialog and the add button is disabled. there are no prices and quantities where they are supposed to be shown.

I have tried to update bricklink database, and update brickstore. nothing helps

**Comment by Schoen98** [comment]
Nvm I found out. I just forgot to pick the colour😊

**Comment by twoloosebricks** [comment]
oddly enough it fixed itself, must have been a temporary glitch. works again,  my issue was in the screen where you pick the item and add it. the button was greyed out, sometimes when you dont pick color it does that, but it was all the time,  but ok now. huum must have been a software fart.
