### ISSUE TITLE
Help, please - Fail to import... XML parse error at line...

### ISSUE THREAD

**Issue by bricksbytheriver** [rgriebl/brickstore#573]
Hello
I am trying to use Brickstore for months, but every time I tried to access the Bricklink store inventory at Brickstore it shows this box.

![Failed to import](https://user-images.githubusercontent.com/110954463/183800316-354105b0-2581-4ef5-96f5-bfef7d2d26bf.png)

I opened the XML file in the Windows Note Pad, but I cannot find that line...

I do not know what to do to solve this issue. Can you please help me?
Thank you in advance.
Best

**Comment by rgriebl** [comment]
BrickLink is known to sometimes generate invalid XML if you have HTML formatting in the extended descriptions.
You can download your store as XML from BrickLink manually and run the downloaded XML through a validator: google for `online xml validator` and pick one.
This should give you more context on where the error occurs.

**Comment by bricksbytheriver** [comment]
Thank you for your fast reply. I will try to follow your instructions

**Comment by bricksbytheriver** [comment]
I did it! Finally! Thank you!
The remarks included many HTML issues.
