### ISSUE TITLE
Add status row to show summary of columns

### ISSUE THREAD

**Issue by dirkolbrich** [rgriebl/brickstore#574]
Feature request: Add an (optional) extra status row to the end of an inventory table, which can show a summary for each column, e.g. total sum of qty or number of rows. Like one can do in an Excel table.

Use Case: I use BrickStore inventory files to track which pieces of a set I already have. For that I import the set inventory, set the `Quantity` column to 0 for all pieces and make the column `Orig. Quantity` and `Diff. Quantity` visible. For each piece I found in my collection I update the number in the column `Quantity`. 

With the extra status row I can easily see how many pieces a set originally has, how many pieces I already got and how many pieces are still missing. 
Currently the status info at the top only shows the summ of all pieces in the column `Quantity`.

**Comment by ZZJHONS** [comment]
Maybe if on the info window a new line is added showing Total qty. Diff. and Total Qty O. for the items selected would do the trick, and only show them if each of those columns are visible on the document.

**Comment by dirkolbrich** [comment]
Yeah, this would work as a quick fix/workaround.

BUT:
This would add a hard coded statistic to the info panel. Isn't it better to have a more flexible way of showing some statistic about a specific column?

AND (another idea):
Add the possibility to add custom columns to the list, which can hold filters and simple calculations of other columns for this specific row - like the filter functionality already does.
E.g. in the image below I would add an extra column named [Estimated Price] with the filter/calculation "if [Diff. Quantity] not 0 then absolute[Diff.Quantity] x [Price] else 0". For this additional column I would set the summary row to show the sum of all calculated fields. This way I would know what would be the estimated cost for all missing parts of this set (based on the average price).

<img width="2117" alt="Bildschirmfoto 2022-08-26 um 13 12 22" src="https://user-images.githubusercontent.com/3765119/187081628-0971ac28-7b41-40d7-8d8f-5bfc28d65773.png">

**Comment by rgriebl** [comment]
Sorry but BrickStore is a very specialized app, not a generic spreadsheet like Excel.

One cannot just add columns without adding a lot of code (see also https://github.com/rgriebl/brickstore/issues/576#issuecomment-1273920908)

Adding a "totals" row would even be more work, as this would be a totally new concept.

That being said: I still have plans to allow custom columns via JavaScript extensions, but getting this right is very tricky, so I cannot promise you anything in this regard.

**Comment by rgriebl** [comment]
I've now created a super-task issue for custom columns: #617

I will close this issue here however, as it will not be implemented in BrickStore itself and just sitting around in the bug tracker as an open bug for years doesn't help anyone.
