### ISSUE TITLE
Items for collection management

### ISSUE THREAD

**Issue by gualandd** [rgriebl/brickstore#576]
Hi, I love Your software but I'm not a BL seller but a Lego collector and I like if is possible to add some features to the sw.

Please add some column for collection management, for example:
- Lego original price
- Shelf position
- Paid price (cost)
- Set quotation (price)
- Box condition remark

Other than that the possibility to add unsorted or custom set to the catalog with custom images (for example promotional sets that aren't categorized in BL database as official but only as custom).

Last but not least, the possibility do access to Brick Economy database for set quotations other than Bricklink

**Comment by rgriebl** [comment]
Adding columns is not as easy as you think: all backend classes need to be extended to handle the new fields, the display, edit and filter code needs to be updated for both the desktop and mobile versions, then the loading and saving code needs to be extended and last but not least the BSX file format has to be amended (this format is stable for 17 years now and used by a lot of other apps and services, so no experiments allowed there)

Having said that: 
- why don't you use the "Remarks", "Description" and "Reserved" fields for arbitrary text like the shelf position and the box condition? 
- there already is a cost column available.
- as for all your prices: you could just re-purpose the "Tier P1-P3" fields for that

As for custom sets and images: this won't happen
- I personally don't have a need for it, so someone else would have to implement and maintain it. This would be huge task, most likely rewriting a large chunk of BrickStore.
- having one consistent read-only database for all items is what allows BrickStore to work as fast as it does. 

And lastly, Brick Economy doesn't even offer an API.

**Comment by rgriebl** [comment]
I've now created a super-task issue for custom columns: #617
