### ISSUE TITLE
Ability to pin colours

### ISSUE THREAD

**Issue by quotingmc** [rgriebl/brickstore#577]
The ability to pin and unpin colours to the top of the list would be very helpful when working with lots of parts from just a few colours or colour groups. While sorting the list by hue often helps you still sometimes end up scrolling backwards and forwards.

To pin a colour, a pin button could appear when the colour is selected or on hover. To unpin, a pin icon next to the colour in the pinned section could be clicked.

Mockup:
![image](https://user-images.githubusercontent.com/26186100/187910584-b6e95c66-a35b-4946-ba7d-a7bd51612321.png)

**Comment by paramecie** [comment]
Would be nice!
