### ISSUE TITLE
Save Store import filename could be better

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#58]
The document title is "Store DD/MM/YYYY" which is fine, but the proposed filename isn't.

I propose you the same name format, but replacing "/" or "\" by "-" for example ?
That would give here "Store 08-01-2021" (.bsx)

![image](https://user-images.githubusercontent.com/32078594/104025199-8c0c7a80-51c4-11eb-8dcd-eb26f736d5f5.png)

**Comment by rgriebl** [comment]
That's why Germans use "." as the date separator: we have no problems with stray directory separators over here :)

**Comment by paramecie** [comment]
Ja ja du bist perfekt :-)

**Comment by paramecie** [comment]
Danke sehr!
