### ISSUE TITLE
Dialog boxes and menus open on secondary screen

### ISSUE THREAD

**Issue by BrickSouth** [rgriebl/brickstore#580]
Just upgraded to the latest version and noticed that if I have the main program window on my primary screen and open a dialog box, it opens on my secondary screen. For example, if I right click on an item, the right click menu shows up on my other screen. If the window is on the secondary screen the dialog boxes/menus perform as expected.

**Comment by xaraxarax** [comment]
Same here, but it is also if it starts on the secondary screen amd the program is moved to the secondary screen.

**Comment by rgriebl** [comment]
Are we talking about Windows here? (10 or 11?)
Do you have High-DPI scaling settings (> 100%) on one or both monitors?
Can you make sure you are really running 2022.9.1 via Help > About ... there are some hiccups right now if BrickStore is running during the upgrade.

Please also note that BrickStore saves and restores a lot of Dialog position and sizes, but this has been the case for a long time. From the top of my head this includes the Add Item and all the Import dialogs, but there are more. These dialogs will always popup exactly where you closed them last.

As for popup-menus: all of the ones it tested work perfectly fine in my multiple monitor setup. Can you please give me a specific example that doesn't work for you.

**Comment by rgriebl** [comment]
Got it ... I have 2 totally different monitors, but the bug in Qt only triggers if you have 2 similar ones:
https://bugreports.qt.io/browse/QTBUG-102122

Guess I'll have to move to Qt 6.3.2 for Windows as well then.

**Comment by rgriebl** [comment]
Could someone please double check if build 774 fixes the issue: it's currently building and should be ready in approx. 20 mins: https://github.com/rgriebl/brickstore/actions/runs/3054699124

**Comment by xaraxarax** [comment]
problem solved, now the others... (coming soon)
