### ISSUE TITLE
can't choose printer after update to v2022.9.1

### ISSUE THREAD

**Issue by qf3RPOpPOjfx** [rgriebl/brickstore#581]
after update to v2022.9.1 I can't choose any printers after selecting File > Print... , the only available option is save as PDF. Also the button left of 'Cancel' (Ok?) has no text an doesn't seem to do anything. The Printing using system dialog option also doesn't work.
I also tried File > Print to PDF but this has the same issue. 
I'm using Windows 10 Home.

**Comment by qf3RPOpPOjfx** [comment]
also see issue #582 not sure if they are related...

**Comment by rgriebl** [comment]
Are you sure your system has printers available? Looking at the code, the only way to trigger such an behavior in BrickStore would be if no printers are defined in Windows (this will be fixed).
I will however not remove all my printer definitions to test this :)

**Comment by qf3RPOpPOjfx** [comment]
Tested on another PC with W10. New install as admin with latest release and I can print :O
Now on my main pc I downloaded the latest release and also no problems.
So the problem was auto updating in the app instead of manually updating, for me this seems to have broken something.

**Comment by rgriebl** [comment]
Closing for now, as nobody else seems to have this problem. Please re-open if it happens again.
