### ISSUE TITLE
update to v2022.9.1 not working?

### ISSUE THREAD

**Issue by qf3RPOpPOjfx** [rgriebl/brickstore#582]
I have chosen to update to v2022.9.1, after the installation is finished the Help > About still says I'm on v2022.4.1 (build 663)
When I restart the application, I'm again asked to update.
Restarting my PC didn't fix it. I'm using Windows 10

**Comment by ZZJHONS** [comment]
Seems some code didn't update, in mine it says 2022.6.2 (762) on the about screen and on the homepage
