### ISSUE TITLE
Mac 12.6 not working

### ISSUE THREAD

**Issue by lynnbehrens** [rgriebl/brickstore#583]
I tried updating new version but I get immediately that the product must close and it will not open. Anybody else have issues with Mac?

**Comment by newfie675** [comment]
I have the same problem

**Comment by ZZJHONS** [comment]
Mentioned in #579 too.

**Comment by msudawgs56** [comment]
Not working for me either.

**Comment by rgriebl** [comment]
Could someone please double check if build 774 fixes the issue: it's currently building and should be ready in approx. 20 mins: https://github.com/rgriebl/brickstore/actions/runs/3054699124

**Comment by newfie675** [comment]
It works for me!
Thanks so much
Chris
