### ISSUE TITLE
Got a virus warning on new version Brickstore install

### ISSUE THREAD

**Issue by rv6abob** [rgriebl/brickstore#584]
This may be bogus but Windows Security didn't like the new install:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/2474200/189974417-1ac21c6f-8ee4-4f1c-af4e-b55f38ea679e.png">
 
Trojan: Win32/Spursint.F!cl

**Comment by rgriebl** [comment]
VirusTotal begs to differ:

https://www.virustotal.com/gui/file/00d2b3a5af806063619ed2be575708a1e8c185877fdbe7407f70078629582a14/detection

Please check your local copy in the mentioned path on virustotal.com and see if the hash (00d2b3...) matches. If not, then something on your machine manipulated the download.
