### ISSUE TITLE
No sound when it finishes pricing a document

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#589]
In earlier versions BS made a small notification sound when the pricing was done and I think in a few more scenarios.

Now it is not making any... Running W11 here. Release 2022.9.2 (777)

**Comment by rgriebl** [comment]
Still the same annoying ding here for me. This sound is triggered by the OS itself, so check your Windows sound settings if you (a) have the ding enabled at all and (b) are unmuted.

Also interesting: https://www.ctrl.blog/entry/windows-alert-sounds.html

**Comment by ZZJHONS** [comment]
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/1063368/190390405-9510723e-25ae-4c41-b116-2065326159a5.png">

I tried the sound and it works, also when I do a screenshot with Win + Shift left + S the notification sound works and is shown moving in the sounds settings, but when doing the pricing it shows nothing there. Maybe Qt had a windows audio file defined instead of the default? Don't know really, rebooted and troubleshoot audio but nothing changed.

**Comment by rgriebl** [comment]
Just checked - This is an 'information' dialog, so Windows is playing the `Asterisk` sound, not the `Notification` one ... I guess it's been like that since Windows 3.1, so why change it, right? ;)

**Comment by ZZJHONS** [comment]
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/1063368/190402138-aa22346c-973d-4a68-b65d-b8de3d7421d0.png">

That one works too and yes it is that one I instantly recognized it. Distinct from the screenshot one though.

But no luck for BS making the sound... 

Screenshot at the time the bar completed, no movement.
<img width="532" alt="image" src="https://user-images.githubusercontent.com/1063368/190402310-78ea97e4-c3bc-42de-a29b-06559b117f8a.png">

**Comment by ZZJHONS** [comment]
Tried in another PC with W11 (both received an update last week, but this one is Inside Preview and the other is standard) and on this one the sound works as expected when finishing pricing. I will see what I can find online...

**Comment by ZZJHONS** [comment]
Today I started BS and after pricing it sounded again, the PC was not even rebooted since 2 days ago when I was testing... strange...
