### ISSUE TITLE
Windows, multiple install of MS C/C++ runtime

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#59]
![image](https://user-images.githubusercontent.com/32078594/104030495-ca596800-51cb-11eb-9f82-9d6a50e9dd48.png)

I alread noticed but could verify today with 2021.1.3 that:

1) I'm not sure this redist is necessary on my PC, as it's a Dev PC with Visual Studio, Visual Studio Code and many apps - so, I've a doubt this was necessary (but I may be wrong)

2) This is installed / reinstalled every time I install BrickStore, which is not appropriate (IMHO). Normally it should first check if already installed and wouldn't do it again.

See today it reinstalled it:

![image](https://user-images.githubusercontent.com/32078594/104030679-0b517c80-51cc-11eb-8e62-6bb64053a500.png)

**Comment by rgriebl** [comment]
Blame Microsoft ... I just run the Visual Studio vc_redist installer in silent mode. This definitely IS required and this is exactly the way Microsoft intended the vc_redist packages to be used. 

But why it re-installs itself (or just updates the install date, who knows?) is out of my reach.

**Comment by paramecie** [comment]
Ah sorry, I don't agree on this.

When I used InstallShield you could check if already installed, and you wouldn't; it was bad practice at this time.

In Inno setup:

https://bell0bytes.eu/inno-setup-vc/

"Unique IDs

As we learned way back in a previous tutorial, each Windows program has a unique ID, thus to check whether the Visual C++ 2017 Redistributables are installed or not, we simply query whether software with a given ID is registered in the registry or not." 

(etc)

**Comment by paramecie** [comment]
A bit trickier maybe in this Inno setup, is - AFAIK - it should be checked if those are necessary to be installed, or not.

In a general meaning no extra (not needed) should be installed.

The first time I ran your new set up, a few days ago, it asked me to reboot.
I cannot (machine hosts servers, a bit long), but ran the application with no problem.
But BrickStore works fine for a few days without a reboot.

That *could* mean that the installation installed unnecessary files.
Again, IMO.

**Comment by rgriebl** [comment]
The restart issue is gone - or at least - suppressed since .1 or .2. I'm running the vc_redist with `/norestart` now. 

The problem is - again - with Microsoft, who, in their infinite wisdom are distributing Windows updates as part of the MSVC 2019 C-runtime. I have one machine here that really required that reboot before BrickStore would even start ... this is just madness.

Since this is not really an issue, apart from the installation taking a few seconds longer, I will stick to just installing whatever Microsoft thinks is necessary. There are bigger fish to fry :)

**Comment by paramecie** [comment]
> There are bigger fish to fry :)

Absolutely!
