### ISSUE TITLE
parting out collt-12 gives collt11 minifigure instead of collt12

### ISSUE THREAD

**Issue by baraakamal** [rgriebl/brickstore#590]
Not sure if this is a bug or just something with my installation, but I tried multiple times with the same result.

Parting out collt-12 set brings out correct parts but with collt11 minifigure instead of collt12.

**Comment by ZZJHONS** [comment]
https://www.bricklink.com/catalogReqList.asp?nID=&viewDate=Y&viewType=E&viewStatus=A&itemID=200587

https://www.bricklink.com/catalogReqList.asp?nID=&viewDate=Y&viewType=E&viewStatus=A&itemID=200586

Those figures got the ID changed between them last year, maybe BrickStore has some king of cache for its database creation that didn't notice this change?

**Comment by rgriebl** [comment]
This is much more involved than anticipated: if an item-id changes, the affected inventories will not get an "updated" marker, even though the inventory download will now obviously return something different.
I'm quite sure that this wasn't a problem in the past (given that nobody reported such a problem in the last 18 years). I'm currently working on a an update to the BrickStore database generator to detect these cases. This needs some more testing though before running this on the production database.

**Comment by rgriebl** [comment]
Fixed by f9e0a700d73ecc4accc400d75af48a95528fce41
Just update the database.
