### ISSUE TITLE
Not working for Mac 

### ISSUE THREAD

**Issue by mortrist** [rgriebl/brickstore#591]
Currently can't use on my Mac, please see details below.  Thanks!  - Tristan

Translated Report (Full Report Below)
-------------------------------------

Process:               BrickStore [1391]
Path:                  /Applications/BrickStore.app/Contents/MacOS/BrickStore
Identifier:            de.brickforge.brickstore
Version:               2022.9.1 (767)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2022-09-15 20:56:13.8996 -0400
OS Version:            macOS 12.6 (21G115)
Report Version:        12

**Comment by ZZJHONS** [comment]
Robert the author made a Legacy branch of BrickStore that still works for older Macs and Windows but that will stay at update 2022.4.2, you can download it here:

https://github.com/rgriebl/brickstore/actions/runs/3056502815
