### ISSUE TITLE
Add item window.

### ISSUE THREAD

**Issue by TGS-Brick** [rgriebl/brickstore#596]
Hi
First thanks for this fantastic piece of software, I'm using it 6-8 hours a day.
I work a lot in the add item window, and it would be great for me, if I have an option to switch the view window and the color window. Then only the items of a certain color is displayed in the view window like searching on Bricklink.

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/85295976/191079755-2c036de2-714b-4882-a4b3-be32ff4a96e3.png">

**Comment by ZZJHONS** [comment]
Click the lock icon next to the Colors categories picker ;)

<img width="558" alt="image" src="https://user-images.githubusercontent.com/1063368/191091443-ee23c0aa-2b0d-4285-9aa7-5624588592cd.png">

**Comment by TGS-Brick** [comment]
Fantastic, thanks!
And I'm still asking for the option to turn on +1 and -1 with arrows in the quantity field. Can I look forward to this?????
Regards

**Comment by paramecie** [comment]
But that works also. Click the Qty field and use up or down?

**Comment by TGS-Brick** [comment]
Yes in the add item window, but I would like it in the main window.

<img width="383" alt="image" src="https://user-images.githubusercontent.com/85295976/191245786-30f13227-06fa-428e-b01f-f9fd873a5eb6.png">

**Comment by rgriebl** [comment]
You already opened an issue for this: #348 
I gave you my reasoning for the status quo there: https://github.com/rgriebl/brickstore/issues/348#issuecomment-839787055

**Comment by rgriebl** [comment]
Closing here, as the color issue has been answered.
