### ISSUE TITLE
Doesn't ask to save an edited file on part-out to another file

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#597]
Legacy version.

100% reproductible:
* Make a blank new list, add 1 Minifig
* Click "Inv" right bottom to part it out
* Choose "No" to part this out in a new window
* Now you see a new file with a content, the part out of this minifig
* Click the Close button

BrickStore will NOT ask if you wish to save this file or not, it closes it.

**Comment by ZZJHONS** [comment]
You can close this issue yourself with the Close with Comment button instead of the Comment alone button.

Also I see this okay as is just like a view inventory screen (similar to the Add items one) until you edit something.

**Comment by paramecie** [comment]
Yep - OK!
