### ISSUE TITLE
Prompt for relaunch after end of upgrade?

### ISSUE THREAD

**Issue by chiminirc** [rgriebl/brickstore#60]
This is minor but didn't want to share that 2021.1.2 did successfully see 2021.1.3 available.  I clicked DOWNLOAD which took me to the site. I downloaded and ran the installer.  I elected to leave brickstore running on purpose.  The installer did prompt to close the app to proceed.  The upgrade ran smoothly.  All great.  Only feedback I could offer would be to prompt to launch at the end.

**Comment by rgriebl** [comment]
The installer tried to. It's just that the 'RestartApplication=yes' option in the installer isn't enough, if BrickStore doesn't implement Windows' `RegisterApplicationRestart` API.
