### ISSUE TITLE
'Ctrl-C' copies data to the clipboard when no items are selected

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#600]
When there is no item selected in a document the Edit/Copy menu is disabled but 'ctrl-c' is still active. It looks like it copies the contents of the last selected cell to the clipboard:

Click on the 'item description' of an item in the document.
Deselect it and then press 'ctrl-c'.
Double click the remarks field of the item to open it for editing and press 'ctrl-v'.
The item description is pasted as remarks.

Win 10, build#786

**Comment by paramecie** [comment]
Yep, confirmed on Legacy too.
