### ISSUE TITLE
Stockstore crashes when trying to add part

### ISSUE THREAD

**Issue by bricknit** [rgriebl/brickstore#601]
Since the latest update (v2022.9.3) I am unable to use brickstore. It crashes when trying to add a part. I have checked my integrated intel graphics drivers and they are up to date.

**Comment by rgriebl** [comment]
You have to a bit more specific on what you are trying to do before it crashes.
Also, it seems you have not enabled Sentry crash reports: I have only one reported 2022.9.3 crash (9 hours ago) and this one is totally unrelated to what you are describing.

**Comment by bricknit** [comment]
Not too sure whats happened, its working fine now. I uninstalled V2022.9.3 and installed V2022.9.2 to try and fix but had the same issue last night. To allow the crash report to go through just now I did the update to 9.3 and it seems to be fixed. Thanks for the quick reply though.

**Comment by rgriebl** [comment]
Closing for now, as nobody else seems to have this problem. Please re-open if it happens again.
