### ISSUE TITLE
Cannot upgrade to 2022.9.3

### ISSUE THREAD

**Issue by stecre72** [rgriebl/brickstore#606]
![image](https://user-images.githubusercontent.com/114445354/192384027-146cd5bb-77c7-40f4-8088-867897ac8de1.png)
Windows-x64-BrickStore-2022.9.3.exe

**Comment by rgriebl** [comment]
Google for this error message and the first link gives you instructions on how to solve this: https://www.thewindowsclub.com/ipersistfile-save-failed-error
This has nothing to do with BrickStore at all.
