### ISSUE TITLE
Please restore the checkbox to force download current prices

### ISSUE THREAD

**Issue by chiminirc** [rgriebl/brickstore#61]
It can remain unchecked but please bring back the ability to force current price data to load.  I'm not sure removing an option for the user benefits them.

**Comment by paramecie** [comment]
https://github.com/rgriebl/brickstore/issues/50#issuecomment-756852864

**Comment by rgriebl** [comment]
Done, but hidden  behind an "Advanced Option" disclosure button

**Comment by chiminirc** [comment]
Thank you!
