### ISSUE TITLE
Can add sets, minifigs, etc. but not parts

### ISSUE THREAD

**Issue by polstarbl** [rgriebl/brickstore#610]
No prior issues until this fresh install on a new computer. I can now add sets, minifigs, gear, instructions, etc from the catalog but I cannot add any parts. The "add" button remains translucent for "parts" and pushing the enter button does not help. The "consolidate" option is not active when I try to add parts and I can add multiple sets, minifigs, etc from the catalog as normal. This does not appear to be a known issue so any help will be greatly appreciated.

**Comment by rgriebl** [comment]
That code did not change in a long time. Make sure you have a color selected and that the price (and tiered prices, if enabled) are sensible. Also any tiered price must be higher than the actual price and higher than the lower level tiers. The opposite is true for the tiered quantities: they need to decrease with each tier level.
If that still does not help, then please make a screenshot of that window and attach it here.

**Comment by rgriebl** [comment]
Closing due to missing feedback. Please reopen if the problem still persist.
