### ISSUE TITLE
Fehlermeldungen Brickstore

### ISSUE THREAD

**Issue by RainerWeiss** [rgriebl/brickstore#611]
Hallo,
ich bekomme bei Brickstore Fehlermeldungen.
![FehlermeldungBrickstore](https://user-images.githubusercontent.com/114877029/193468987-a638ecf1-bd51-4a9a-9739-c58c2dc5e766.jpg)
Da sowohl Brickstock als auch Brickstore nun nicht einwandfrei arbeiten und ich weder Inventar noch Bestellungen runterladen kann, ist das äußerst problematisch.
Eine Gewerbeanmeldung kann ich dann erst mal knicken...

Gruß
Rainer Weiß

**Comment by rgriebl** [comment]
Das ist eine Fehlermeldung aus den Untiefen des Windows Network stacks. Das kann jetzt daran liegen, dass die BrickLink Server gerade rumzicken oder - viel wahrscheinlicher - dass eine Firewall auf deinem Rechner die Verbindung blockiert.
Funktioniert denn `Extras` > `Datenbank aktualisieren`?

**Comment by rgriebl** [comment]
Eindeutig ein Anti-virus/Firewall Problem. Der komplette BrickStore Prozess wird daran gehindert Verbindungen ins Internet aufzubauen. Das Problem musst du auf deinem Rechner, bzw. in deinem Netzwerk finden und lösen.

Siehe auch: https://github.com/rgriebl/brickstore/issues/604#issuecomment-1256952746  (BrickStore.exe liegt jetzt woanders im Dateisystem - das muss evtl. auch im Anti-Virus angepasst werden)

Teilelisten importieren geht, weil BrickStore anscheinend noch die letzte Version der Datenbank von BrickStock importieren konnte. Die Daten sollten aber ziemlich veraltet sein.

Brick **Stock** ist hoffnungslos veraltet und kann nur SSL (Verschlüsselung) Versionen sprechen, die als geknackt gelten und somit von keinem anderen Rechner im Internet mehr akzeptiert werden. Immerhin kommt BrickStock laut dieser Fehlermeldung an Deiner Firewall/Anti-virus vorbei ins Internet: es will dann nur niemand mit ihm reden ;)
