### ISSUE TITLE
Import Bricklink Order Placed failure

### ISSUE THREAD

**Issue by froqzy** [rgriebl/brickstore#615]
If we try to update our Bricklink Orders Placed to import we consistently get the following error:
"Last update failed: Could not parse the received order XML data: XML parse error at line ###, column ##; Expected ';', but got ':'.

Last but not least: thanks for all a the great work :-)

**Comment by froqzy** [comment]
BTW: error only occurs for Orders Placed, Orders Received are still imported

**Comment by froqzy** [comment]
If I try to synchronize the orders in the last 1 days: no error and Orders Placed are imported. If I try to synchronize 2 days or more I receive the error message above.

**Comment by froqzy** [comment]
Wow, that's a fast response. And incredible that you're willing to give this kind of support. You're awesome!
I'm a little familiar with the WDT but may need a little help:

1. I suppose you need the "orderDetail.asp?ID=xxxxxxxx" portions and I just save this as .xml instead of .asp?
2. How do I know which is the broken order, or do I just send all orders that won't import?
3. Do I just attach the order files (which feels a little unprivate) or can I send the files or a Dropbox link to you?

Thanks again!

**Comment by ZZJHONS** [comment]
> Seems like BrickLink is now also generating broken XML for orders. Up to now they only did it for store inventory. I suspect an extended item description with a non-latin character coming from the seller of the "broken" order. There is no easy way to debug this, especially as BrickLink has removed the Download link for placed orders.
> 
> * if you are familiar with the Web Developer Tools (F12) in your browser, then you could get me the XML files to debug.
> * if not, the only option would be to change your BL PW and send it to me privately via mail. Then I can download the orders, and you immediately reset your PW back. You have to trust a stranger (me) for this though.

I see the Download link if I click to see the filed ones:

https://www.bricklink.com/orderExcel.asp?orderType=placed

Seems it is only removed if you don't have any placed orders in the last 6 months, but the page is accesible.

**Comment by froqzy** [comment]
Ah OK, didn't check but you're right - it's still there. Here's the order file with the broken order in it.
[orderxml issues.txt](https://github.com/rgriebl/brickstore/files/9745921/orderxml.issues.txt)

Thanks again!

**Comment by rgriebl** [comment]
Thanks Sergio -- I don't buy much nowadays, so I don't have this link visible!

That aside: the problem order is from the shop Macdoom, who set the tracking number to `Recommended letter: T&T:` and BrickLink (once again) is not escaping the `&`, resulting in invalid XML.

Nothing I can do about, but I will report it to BrickLink.

**Comment by rgriebl** [comment]
https://www.bricklink.com/message.asp?ID=1369060

**Comment by froqzy** [comment]
Awesome!
But do I understand well that there is no way to correct the xml and update it into Brickstore manually?

**Comment by froqzy** [comment]
Ai, don't have high hopes on Bricklink IT. One thing for sure they're not as fast as you are ;-)
Since the ability to import orders seems quite crucial to working with Brickstore, would it be feasible to have the option to import order XMLs directly into Brickstore so we're not 100% dependent on the Bricklink XML generator?

Thanks again!

**Comment by froqzy** [comment]
Found a workaround: asked seller to update the record with the tracking number. Problem solved for me. But cause obviously remains.

Keep up the good work. Can't tell you how happy we are with BrickStore.

**Comment by rgriebl** [comment]
> Since the ability to import orders seems quite crucial to working with Brickstore, would it be feasible to have the option to import order XMLs directly into Brickstore so we're not 100% dependent on the Bricklink XML generator?

I thought about this as well: you could in theory just inject the order XML into BrickStore's cache directory, but in the end this wouldn't help you, as the next update would download the faulty order again and choke on it.
Also: in these cases NO order can be imported at all, because the whole XML file (containing all orders) can not be parsed.

**Comment by froqzy** [comment]
Then let's hope Bricklink team gets their act together...

**Comment by Brick-Top** [comment]
Now haunted by this unfortunate bug, thank you for the workaround.

Fot future people that come: **if the tracking number field for an order includes the character '&', you need to ask the seller to remove it.**

Now fingers crossed the seller helps us removing it... :D
