### ISSUE TITLE
Include alternate item number in item search

### ISSUE THREAD

**Issue by habex-ch** [rgriebl/brickstore#616]
Some item numbers are not found when I search them in the search box in the "add item" window.

This is due to some items have multiple numbers like 6155 has the alternative number 28829 (see [https://www.bricklink.com/v2/catalog/catalogitem.page?P=6155](https://www.bricklink.com/v2/catalog/catalogitem.page?P=6155) "Alternate Item No").

It would be great if the search box also looking for alternative number because my normal search procedure looks like:
1. Look at a lego piece for its item number
2. Search this number under "add item"

Currently, I have to add the following steps, if I don't find the item

3. Go to the bricklink homepage, search the number and get "main" number
4. Enter the main number under "add item"

**Comment by habex-ch** [comment]
That's a bummer. 

What happens, if you search for an alternative item number, does the API return them?

I created a suggestion (see [https://www.bricklink.com/message.asp?ID=1369100](https://www.bricklink.com/message.asp?ID=1369100))

PS: Wow, you are quick...

**Comment by rgriebl** [comment]
The numbers are probably available via the new JSON API. But this API is not suitable for BrickStore (much too slow, only 5000 calls per day). BrickStore has its own database that gets rebuilt daily by downloading the catalog and pre-processing it. (https://www.bricklink.com/catalogDownload.asp)

**Comment by habex-ch** [comment]
yes, the Json-Api has a property "alternate_no" ([https://www.bricklink.com/v3/api.page?page=resource-representations-catalog](https://www.bricklink.com/v3/api.page?page=resource-representations-catalog))

How about using the best of both ways?
Fetching each day some of the additional information using the Json-API and saving them in a different database. (Looping through those information in about a month.)
Then creating the daily BrickStore-Database from both sources?

Or is this somehow against the term of use?

**Comment by rgriebl** [comment]
Surely one could implement this: we're at ~160000 unique items in the BL database, so with the 5000 requests per day limit it'll be around 30 days.
If you are willing to implement that download mechanism (including all the necessary bookkeeping to deal with errors and temporary network problems) and have some server cycles and HDD space to spare to run this job each day every day, be my guest.
If you then also make sure that the complete dataset is available for download 24/7, I'll gladly download an XML/JSON/whatever file from your server and integrate that into the BrickStore DB creation process.

**Comment by habex-ch** [comment]
I just read the [API Terms of Use](https://www.bricklink.com/help.asp?helpID=2216) of BrickLink. It would probably also be against their terms. 
I think I will not risk it beside all the other work and issues I would face. 

So let's close this issue.

Thank you anyway for your time and all your work for BrickStore. I just started to use it and it is really a good software!

**Comment by ZZJHONS** [comment]
I suggested an alternative way a while back: https://github.com/rgriebl/brickstore/issues/519
