### ISSUE TITLE
View - Manage Column layouts not doing anything.

### ISSUE THREAD

**Issue by chiminirc** [rgriebl/brickstore#62]
Saving layouts is great new feature.
Autoresize Once.  Works great. Nice addition.
I was able to save my own column layout.  The managed column layouts menu item, I'm assuming, would be to delete or possible reorder my user views?  I added one view and the option didn't work.  I added a 2nd view thinking it may only trigger when there is more than 1 view and it didn't work.

Until the view manager is working, where are these view entries stored?

**Comment by rgriebl** [comment]
Yes - this will be an UI to reorder and delete. See the comment on the commit: 03e2e12a7dc4d25d01f0c0515973f1ff29c8716d

If you want to mess with them now: on Windows, they are in the Registry at `Computer\HKEY_CURRENT_USER\SOFTWARE\Brickstore\Brickstore\ColumnLayouts`

**Comment by paramecie** [comment]
Arf, now users are supposed to read code and know what a comment is, and understand what meant the dev!
Things have changed since 2000 :)

**Comment by rgriebl** [comment]
Fixed in 3a1c6963c5c9465f079d9b0b745267fec5d72172

**Comment by paramecie** [comment]
Great!
