### ISSUE TITLE
"Add complete minifigure" option when adding minifig parts

### ISSUE THREAD

**Issue by steverus99** [rgriebl/brickstore#620]
When searching minifigure parts Brickstore shows the complete Minifigures that include the part you are searching. If you click on a minifigure shown you can view it in BL or part ot out into a new file, would it be possible to have a "add" the complete minifigure to file option as well as the part out option?

Would make it smoother to add complete minifigs to a file when sorting a mixed minifig lot that have complete but disassembled/mixed up parts, rather than having to remember the BL id, change the search to minifigs and search the figure to add, then return back to parts and re-enter your filtered search terms.

Cheers

**Comment by ZZJHONS** [comment]
I think that is what I suggested here too: #530
