### ISSUE TITLE
V2022.10.2 crashing on add item window

### ISSUE THREAD

**Issue by TechnicBuilt** [rgriebl/brickstore#621]
Hello

Just updated to 2022.10.2 and when I open the add item window Brickstore crashes. I have uninstalled and reinstalled, restarted computer a few times. Same issue. 

### BrickStore 2022.10.2 (build: 818)

* **brickstore.ldraw**: 17 Sep 2022 18:21:20 -0600
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930146)
* **build.date**: 2022-10-13T22:25:27.000
* **build.host**: fv-az211-858
* **build.number**: 818
* **build.qt.version**: 6.4.0
* **hw.cpu**: Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: NVIDIA Quadro 1000M
* **hw.gpu.arch**: nvidia
* **hw.memory.gb**: 7.9
* **os.arch**: x86_64
* **os.productname**: Windows 10 Version 21H1
* **qt.debug**: false
* **qt.version**: 6.4.0
* **windows.tabletmode**: false

**Comment by rgriebl** [comment]
This is similar to https://github.com/rgriebl/brickstore/issues/587

The crash comes from your graphics card and/or its drivers being very old (~11 years). Your 1000M is already blacklisted as "not 3D capable" in BrickStore though, so I'm a bit puzzled why you are still crashing.

Could you please try to update your drivers and report back if that helps?
Here's a quick link to the "latest" driver: https://www.nvidia.com/Download/driverResults.aspx/120734/en-us/

If the driver update doesn't help, then the way I'm blacklisting old GPUs doesn't work for NVIDIA, while it works perfectly fine for Intel and AMD, and I need to come up with a different strategy.

**Comment by TechnicBuilt** [comment]
Updating the driver did not solve the issue unfortunately.

**Comment by rgriebl** [comment]
Could you please check if this build really fixes your problem?
https://github.com/rgriebl/brickstore/actions/runs/3358507681

(you need to be logged into GitHub; just scroll down, download the installer and install as usual)

**Comment by TechnicBuilt** [comment]
The version above does the same thing, crashes on add item window.

**Comment by rgriebl** [comment]
Would have helped, if I had removed the testing code that inverted the black-listing check 🤦  Could you please test once more with https://github.com/rgriebl/brickstore/actions/runs/3365712369 ? Thanks.

**Comment by TechnicBuilt** [comment]
That last one seems to have done the trick!!. 
Thank you so much for helping solve this issue and all the work you have put into making this a great program for us Lego sellers!
