### ISSUE TITLE
File/Save as leads to 2 different versions of the same document

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#623]
Suppose I have 2 documents open - a.bsx & b.bsx.
I select the a.bsx window and choose File/Save as - I then save it as b.bsx.
I now have b.bsx open twice but with 2 completely different contents - this probably shouldn't be allowed.

**Comment by rgriebl** [comment]
Just checked in other apps: Excel will not allow you to save under the same name, while Notepad++ will allow it (and essentially does the same thing as BrickStore).
