### ISSUE TITLE
3D view for parts in assembly with variable color

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#624]
<img width="432" alt="image" src="https://user-images.githubusercontent.com/1063368/199235446-2a135c70-ad7e-42aa-a28b-566cc6779261.png">

Can the variable color be changed in the render?

Also this one seems the tyre is wrong

**Comment by rgriebl** [comment]
The tire is the same in LeoCAD, so it's either a bug in the LDraw library or an item id mismatch. Please ask on the LDraw forums what's up with this part id.

I'll have a look at the color issue.

**Comment by ZZJHONS** [comment]
it was v823 but installed v865 and now it renders Pearl Gold correctly, maybe a temporary bug there.

Seems the Ldraw indeed is different:

https://www.ldraw.org/parts/official-part-lookup.html?folder=parts&partid=56145c01

**Comment by rgriebl** [comment]
I'm closing this bug report for now. I think those item id inconsistencies should be reported to both LDraw and the BL catalog admins, because this will not just confuse BrickStore users.
