### ISSUE TITLE
Consists of (new feature)

### ISSUE THREAD

**Issue by GreatBrickLab** [rgriebl/brickstore#627]
At time when right clicking to add + item from the new consists of menu,  the item is category is displayed,  and then a second time add + item will then advance to the item selected.

**Comment by SteveTheBrick** [comment]
Same problem with the browsing history. It's intermittent but sometimes the category is selected but no item is selected. Choosing the same item from the history a second time selects the item.

**Comment by rgriebl** [comment]
I can reproduce this problem, if (and only if) either a text filter or a color-lock is active when trying to switch to a new item. I have that fixed already locally.
Could you please verify that this is the problem on your side too?

**Comment by GreatBrickLab** [comment]
Confirmed.

**Comment by SteveTheBrick** [comment]
Confimed here as well but it's not only if the filter is active when switching.  It also happens with no filter if the browsing history item has been stored with an active text filter.

**Comment by rgriebl** [comment]
Could you please confirm that https://github.com/rgriebl/brickstore/actions/runs/3433219489 fixes the problem? It should be fixed, but there were 3 separate bugs that led to the broken behavior...
