### ISSUE TITLE
Jump from part to MF sometimes doesn't work

### ISSUE THREAD

**Issue by xaraxarax** [rgriebl/brickstore#629]
https://user-images.githubusercontent.com/79638214/203350956-8fcc3ff7-a2aa-495e-bbec-8b342be91e4e.mp4

**Comment by rgriebl** [comment]
I think this is a duplicate of #627. Could you please try the latest dev build to see if it fixes the problem?
https://github.com/rgriebl/brickstore/actions/runs/3493282271

**Comment by xaraxarax** [comment]
same behavior in #882, seems to affect all heads without having tried all

**Comment by xaraxarax** [comment]
works like charm ;) without filtering, just select the part from the list and jump works like charm

**Comment by xaraxarax** [comment]
👍
