### ISSUE TITLE
Inherit status when parting out an item

### ISSUE THREAD

**Issue by AllesMeins** [rgriebl/brickstore#634]
I'm not sure if there is a reason for that, but the fact that brickstore automatically marks items as "include" when parting out regardless of the status of the original item always gets my pulse up a bit :-) 
In my workflow I only mark items as include which I've confirmed. But parting out a minifigure or a set adds items marked as "include" that I haven't checked yet and I'm always afraid that I might overlook one row and end up with missing parts in my inventory. So I would propose the following change: Upon parting out the new items should inherit the status of the original item from which I've parted out. So that if I part out an set or minifigure that I don't have marked as "include" I don't end up with missing parts marked as "include".

**Comment by rgriebl** [comment]
How would you handle Extra parts in the parted-out inventory? Or parting out extra parts? 
Is `Excluded` containing `Extra` = `Excluded` or `Extra`?
Is `Extra` containing  `Included` = `Included` or `Extra`?
In any case, you loose one status flag ... right now you do that too, but at least it's deterministic.

**Comment by AllesMeins** [comment]
But there already is a dialogue how to handle extra parts when parting out sets, if I'm not mistaken. I can already chose whether to include, exclude or mark them as extra. So there wouldn't be any need to change anything there.

**Comment by rgriebl** [comment]
You are right regarding the first example - I forgot that the newer BrickStore versions will now always show the dialog if the part-ed out item contains anything besides standard parts.
This still leaves the second one: Parting out a lot that has an `Extra` status, but I think in this case we can simply inherit the `Extra` status as well for all the normal parts and let the user decide on the weird `Extra-Extra` parts.

**Comment by rgriebl** [comment]
BTW: Would you rather have this inheritance only work when parting out in-place, or should the status also transfer when parting out into a new document?
