### ISSUE TITLE
Error: Updating the BrickLink database failed

### ISSUE THREAD

**Issue by GlebVarVar** [rgriebl/brickstore#636]
Wi-Fi is working correctly. Also Tried on mobile internet. Used 2 computers Windows 10 and Windows 11. Tried previous versions. Nothing works. A year ago everything worked fine. Maybe it depends on my location (I'm from Russia). Thanks for any help.
![image](https://user-images.githubusercontent.com/87074772/204086213-72f03c5f-c5e9-4285-a0c0-706196a73560.png)

**Comment by rgriebl** [comment]
A year ago, Russia also wasn't invading their neighbor... and yes, you are blocked.
