### ISSUE TITLE
Populate remarks from inventory feature?

### ISSUE THREAD

**Issue by BrickSouth** [rgriebl/brickstore#64]
It would be great if BrickStore had a way to populate the remarks for lots already in your Bricklink store inventory similar to Bricksync's Sort command. Is this possible to implement at some point?

**Comment by paramecie** [comment]
Not sure what you mean, but if you Import your Store you will get your Remarks.

**Comment by ZZJHONS** [comment]
What about an option in Remarks -> Set... From file/window XXXX

If the same item in the same condition is matched fill the remarks?

But more than just remarks, an option to fill all data (price, bulk, comments etc) from another file would be best.

<img width="438" alt="Captura de pantalla 2021-01-08 193809" src="https://user-images.githubusercontent.com/1063368/104051849-18c92f80-51e9-11eb-8964-7fcd93d807e1.png">

**Comment by chiminirc** [comment]
This would be handy.  I use this to load a new set, and copy remarks and pricing from existing inventory. Then I also see what will become NEW lots before ever doing the upload to bricklink.

Today I do this by
-Import store inventory
-Set QTY to 0
-Open file I want to "copy remarks and prices" for
-Copy all those items
-Paste into ZEROed out store inventory
-delete "Qty. = 0"

the remainder is that set, with my prices and remarks, and blank remark fields are new lots.

**Comment by BrickSouth** [comment]
> Not sure what you mean, but if you Import your Store you will get your Remarks.

I'm talking about when I add parts. Right now, after I've added a bunch of parts to a file, I have to go to Bricksync and run a sort command, bring it back into BrickStore and see which ones are already in the store. Seems like this could be done in BrickStore itself.

**Comment by chiminirc** [comment]
Brickstock tried to do this.  I had to revert to the workflow above and as it didn't honor exact part-color combos.  It would sometimes copy in remarks and prices for different colors of the same part
![image](https://user-images.githubusercontent.com/76887746/104052858-eea74b80-51af-11eb-82d7-5ea54fbc10b6.png)

**Comment by paramecie** [comment]
If you wish a simple function please describe **precisely** what it should do?

But stock management using BrickStore...
I'm not sure BrickStore is ready for this, right now?

**Comment by chiminirc** [comment]
For me it would work like this.
I have a list of items with no LOTID loaded.  These were loaded from a set or manually entered by me to prep for upload.
I select rows (or all) that I want to update
I invoke the action to copy remarks from a document, select the document I want, and it will populate remarks from the source document providing the part and color are an exact match.

**Comment by paramecie** [comment]
Copy Remarks from another (opened) Document.
First problem, how do you determine the match?
If you're adding parts, you have a Lot ID in your shop, but not in your addition.
Then if I compare using condition-type-ref-color, what should be done if you've 2 lots online with 2 different remarks?
etc.

**Comment by BrickSouth** [comment]
Haha, sorry I'm not familiar with coding.... But I did say "like Bricksync's sort command". So I was initially just asking if something like that was possible in BrickStore.

**Comment by paramecie** [comment]
Bricksync's sort command: many (a majority?) of us doesn't know what that means.

BTW - the Copy from (or populate with?) idea is interesting.
But not only for Remarks.
You could also copy Comments, Price, etc.

How it copies needs to be described precisely in all cases.

**Comment by chiminirc** [comment]
> Copy Remarks from another (opened) Document.
> First problem, how do you determine the match?
> If you're adding parts, you have a Lot ID in your shop, but not in your addition.
> Then if I compare using condition-type-ref-color, what should be done if you've 2 lots online with 2 different remarks?
> What if there are lot IDs in your addition (because you copied/pasted from an old document) - and which may be different than the current ones in shop?
> etc.
> 
> Hee hee - we're relpying simultaneously :-) Don't worry, think at it, I'm off for now.

In my use case, the LOT ID is irrelevant.  I wouldn't pay attention to it on either side.  This is because I don't need to copy it. The resulting file is going to be uploaded to bricklink using bricklink's options for consolidation options. What I decide to do for new lots, replace or append remarks/comments, I decide during the bricklink upload. I don't need LOT ID in the XML for this operation as I'm not doing a update.

So in the case where the type/color shows up more than once in the source, I could see a dialog like the merge item dialog.  Then I select which one I want.  I don't know how bricksync handles this type of dupe. I can also say I do not have duplicates lots when I do this.  Perhaps once could just combine the remarks.

If the source has
Black, 1x2 Tile, Tray100
Black, 1x2 Tile, Tray101

My new document, when pulling remarks from the source document, would be
Black, 1x2 Tile, Tray100 Tray101 

- No delimiter. Today "consolidate items" I believe delimits remarks with a space.
   - Maybe add a config option to "select delimiter when consolidating remarks"

**Comment by chiminirc** [comment]
If given a preference, when I "copy remarks from another document" I'm really appending.
CURRENT (The new file I'm planning on uploading.  I'm calling this the CURRENT document)
SOURCE (the document I'm going to want to pull remarks from)

CURRENT remark = Blank,  SOURCE = Blank,  Result= Blank
CURRENT remark = Tray01, SOURCE = blank, Result = Tray01 (I didn't replace, I had nothing to append from the source)
CURRENT remark = Blank, SOURCE = Tray01, Result =Tray01 (I didn't so much replace the CURRENT, I appended it)
CURRENT remark = Tray01, SOURCE = Tray01, Result =Tray01 Tray01


I believe this logic follows what "consolidate items" does today.

**Comment by chiminirc** [comment]
I'm also adding that I have no desire to REPLACE remarks from a source document.
I realize I'm not talkin about pricing here. That clearly can't be appended. At that point I benefit from no duplicate lots so I just want pricing from my SOURCE.  I think you'd have to pick
- safe (set the price to the highest for duplicate lots)
- complicated (average, not seeing the point of doing that)
- more complicated (prompt to select which price or prompt to use highest price for all)
- based on an undisclosed sort in the code (lowest lot ID, latest lot id)

**Comment by BrickSouth** [comment]
> Bricksync's sort command: many (a majority?) of us doesn't know what that means.
> 
> BTW - the Copy from (or populate with?) idea is interesting.
> But not only for Remarks.
> You could also copy Comments, Price, etc.
> 
> How it copies needs to be described precisely in all cases.

Somebody else probably knows better than me, but I think Bricksync uses a local file of your inventory to match and update comments, remarks and price when you do a sort command. The local inventory file doesn't have a LOTID so it must just match part number, color and whether it's New/Used?

**Comment by chiminirc** [comment]
I missed the last part on condition.
Unique identifier would be part, color, AND new/used.

In the case of duplicate lots after that, what I said above.

**Comment by BrickSouth** [comment]
> Bricksync's sort command: many (a majority?) of us doesn't know what that means.
> 
> BTW - the Copy from (or populate with?) idea is interesting.
> But not only for Remarks.
> You could also copy Comments, Price, etc.
> 
> How it copies needs to be described precisely in all cases.

I think a Bricksync sort command works exactly like chiminirc's suggestion. There is a local XML file containing your inventory and it goes to that looking for a match on part, color and condition and updates based on that. It updates comments, remarks and price.

**Comment by TheBrickGuys** [comment]
What I would love to do with BrickStore in regards to remarks is this:   Import my store inventory, change ONLY the remarks for several of the items then do an Export / Bricklink mass update XML to clipboard  of the items I changed the remarks on and have the mass update reflect the change of the remarks.  

I know BrickLink will allow that because I have manually done that by using BrickLink's window for Mass Update and inputting just the info for changing only the remarks field of a particular lot id. 

Right now if you try to just change the remarks field and try to do a mass update then all you get is  one line -  <INVENTORY/>.

If this is possible then I would be greatly appreciative!

Jim

**Comment by paramecie** [comment]
@TheBrickGuys Oh yes, this old snake oil everybody complains about. I create a specific issue for this.

**Comment by paramecie** [comment]
FYI, at least in the night build (I'm not sure if it existed before?):

"Copy Remarks from Document..." works, but after a quick test it replaces any eventual Remark: it doesn't append to them.

**Comment by paramecie** [comment]
FYI, at least in the night build (I'm not sure if it existed before?):

"Copy Remarks from Document..." works, but after a quick test it **replaces** any eventual Remark: it doesn't append to them.

**Comment by frahugo** [comment]
> FYI, at least in the night build (I'm not sure if it existed before?):
> 
> "Copy Remarks from Document..." works, but after a quick test it **replaces** any eventual Remark: it doesn't append to them.

Furthermore, it is buggy. It does not match the color. Maybe just the condition and item (would have to verify). But if it was matching the Item, Condition and Color, it would be **awesome**. My process would then be:

1. `Ctrl-I` to part-out a new set
2. Set prices using the 6-months Avg Sale
3. Tweak the prices a bit
4. Import Store inventory in a second tab
5. Copy Remarks from Store inventory document
6. Part-out and fill empty remarks with new bin numbers
7. (soon set unit cost for each part - see #146)
8. Upload to Bricklink
9. Wait for orders 😄 

Note: I really prefer doing all my part-out in BrickStore and not use the Part-Out page on BL. I can take my time, can sort, revise, exclude items. And save the BSX to keep 
a trace of that part-out activity.

**Comment by paramecie** [comment]
Even more complicated?

1) If I remember well, mass UPDATE doesn't export anything when editing Remarks only (I think there's an Issue about this).

2) Consolidate Remarks, but based on what? You could have 2 lot IDs with the same item (a duplicate). Alternatively, you could have 2 lots in your list, with different Remarks - but only 1 lot ID on your Inventory.

I don't use this feature personaly, but users may help describing the whole exact process of the feature in all cases?

**Comment by chiminirc** [comment]
I'll go into detail later but I do it this way now.
Import my store, consolidate to make sure and dupe item/color combos are one row
Set all QTY to 0
Import the set I want to part out
Select all, copy, and PASTE into my zeroed out store import. 
filter by qty = 0 and delete all rows that didn't get qty added.
I'm left with rows that have remarks for lots I have, and empty remarks for new lots.

**Comment by ZZJHONS** [comment]
I use BrickSync with the command sort that does this: The fields comments, remarks and price are updated for all items found in the local inventory. 

So a similar option in BS that populates comments, remarks, price, cost, bulk, tier... etc from the user Bricklink Inv. would be the best. maybe a dialog can ask you to uncheck anything you don't want to populat.

And this window should ask if you get the info from another document or download your Inv in the backgrond, without need of doing it yourself as a open file.
