### ISSUE TITLE
Latest 2022.11.2 Ubuntu 22.04 core dump on run

### ISSUE THREAD

**Issue by henriquedesousa** [rgriebl/brickstore#640]
Hello. Updated BrickStore to latest 2022.11.2 on Linux Mint 21 (Ubuntu 22.04 based), I'm now unable to use BrickStore:

> Caches: 
>   Pictures    : 4.0 GB 
>   Price guides: 10000 entries (at /brickstore/src/bricklink/core.cpp, 514)
> Loading orders from cache: 0s 000ms 016us (at /brickstore/src/utility/stopwatch.h, 44)
> Loaded database from /home/user/.cache/BrickStore/database-v8 
>   Generated at: 30 Nov 2022 04:01:05 +0000 
>   Colors      : 201 
>   LDraw Colors: 52 
>   Item Types  : 8 
>   Categories  : 1045 
>   Items       : 163881 
>   PCCs        : 71481 
>   ChangeLog I : 36169 
>   ChangeLog C : 1 (at /brickstore/src/bricklink/database.cpp, 390)
> UI: (at /brickstore/src/common/application.cpp, 182)
>   Device pixel ratio : 1 Qt::HighDpiScaleFactorRoundingPolicy::PassThrough (at /brickstore/src/common/application.cpp, 183)
>   Screen size (in mm): 344 x 193 (at /brickstore/src/common/application.cpp, 186)
> script: Loading scripts from directory: "/home/user/.local/share/BrickStore/extensions" (at /brickstore/src/common/scriptmanager.cpp, 263)
> QQmlComponent: Component is not ready (at unknown, 0)
> script:   [fail] classic-print-script.bs.qml : Could not load QML file qrc:///extensions/classic-print-script.bs.qml
> qrc:/extensions/classic-print-script.bs.qml: module "QtQml.WorkerScript" is not installed (at /brickstore/src/common/scriptmanager.cpp, 280)
> qrc:/LDraw/PartRenderer.qml:2:1: module "QtQuick3D" plugin "qquick3dplugin" not found 
>      import QtQuick3D 
>      ^ (at qrc:/LDraw/PartRenderer.qml, 2)
> Segmentation fault (core dumped)

As alternative I'm using the AppImage, will try to revert back to 2022.11.1 in the meantime.

**Comment by henriquedesousa** [comment]
Reverted back to 2022.11.2, here's my sysinfo:

> BrickStore 2022.11.1 (build: custom)
> brickstore.ldraw: 22 Nov 2022 21:39:03 +0000
> brickstore.locale: en
> build.arch: x86_64
> build.compiler: GCC 11.3.0
> build.date: 2022-11-08T15:52:09.000
> build.host: fcb335bc8c30
> build.number: custom
> build.qt.version: 6.2.4
> hw.cpu: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
> hw.cpu.arch: x86_64
> hw.gpu: Skylake GT2 [HD Graphics 520]
> hw.gpu.arch: intel
> hw.memory.gb: 15.5
> os.arch: x86_64
> os.productname: Linux Mint 21
> qt.debug: false
> qt.version: 6.2.4

**Comment by rgriebl** [comment]
That's weird -- I didn't change anything regarding the Linux package dependencies.
Did you compile 2022.11.2 also yourself? (seeing that the 11.1 sysinfo has `build.number: custom`) or did you install the Ubuntu package from the GitHub release page?

**Comment by rgriebl** [comment]
Just tested this in a VM and I can reproduce it on Ubuntu 22.04.

The quick fix is `sudo apt install qml6-module-quick3d qml6-module-qtqml-workerscript`

I don't know why these explicit dependencies are suddenly required, but I'll fix it for the next release.

That still leaves the problem that a lot of icons in the toolbar are now also missing. Do you have the same problem on Mint?

**Comment by rgriebl** [comment]
I have updated the 11.2 release with fixed packages for Ubuntu and AppImage.

**Comment by henriquedesousa** [comment]
Many thanks once again, I was on holiday and couldn't confirm earlier. I was aware of the issue with the icons in previous versions but couldn't understand why. Much appreciated!
