### ISSUE TITLE
OSX Search much slower in recent versions

### ISSUE THREAD

**Issue by BobFlip** [rgriebl/brickstore#641]
Searching a parts list slowed down a lot sometime in the last few versions. It'll take maybe up to 30 seconds on my main parts list (20k items) and I hear my CPU fan speed up. I *think* it was introduced in the Oct 13 release. If I recall right it's working fine in Windows. OSX Version is 11.5.2.

**Comment by rgriebl** [comment]
Weird ... at least I can reproduce it. I just hadn't noticed it on my development machine, since it's not so bad with 32 cores. It's still magnitudes slower as it should be (i.e. as the exact same code that runs fast on Windows and Linux).

**Comment by rgriebl** [comment]
Please give this version https://github.com/rgriebl/brickstore/actions/runs/3606100484 a thorough test. The actual bug is in the Qt base library which I can't fix right away, so I have implemented a workaround in BrickStore for the time being.

**Comment by BobFlip** [comment]
Works much faster now, thanks!
