### ISSUE TITLE
Zusammenlegen von Teilen verfälscht den Preis

### ISSUE THREAD

**Issue by ThiloBerger** [rgriebl/brickstore#642]
Wenn Teile zusammengelegt werden, wird zum einem nicht der korrekte Durchschnittspreis berechnet (diese wäre (Preis1 + Preis2)/Gesamtanzahl), zum anderen wird auch die Währungen vermischt, statt zuvor in Euro umzurechnen. Im Nachhinein werden z.B. importierte Teile in Dänischen Kronen später in Euro ausgewiesen.

**Comment by rgriebl** [comment]
_The actual bug in English:_ copy&paste, as well "copy-values" between documents with different currencies is broken, as no currency conversion is being done at all. This will be fixed shortly.


1) in 2022.11.2 wird beim "Zusammenlegen" kein Durchschnittspreis berechnet, sondern einfach der Preis des Ziels übernommen. Beim "Werte kopieren" wird der Durchschnittspreis **gewichtet** berechnet `(preis1 * menge1 + preis2 * menge2) / (menge1 + menge2)`

   Siehe auch den Tooltip auf den `$ Durchschnitt zusammenführen` Buttons im "Werte kopieren" Dialog: _Der Zielwert wird mittels gewichtetem Durchschnitt über die Mengen berechnet_

   Die aktuellen dev Versionen (siehe `> Actions` oben) haben schon einen neuen "Zusammenlegen" Dialog, der dieselbe feine Einstellbarkeit wie "Werte kopieren" enthält.

2) Bei Copy&Paste, sowie "Werte kopieren", zwischen Dokumenten mit verschiedenen Währungen fehlt momentan die automatisch Umrechnung auf die Währung des Zieldokuments. Das wird gefixed.
