### ISSUE TITLE
'New consolidate' when there's only 1 lot

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#643]
The new consolidate seems a bit odd when there's only 1 consolidation.

The first screen (same options/individually) isn't really needed but the 2 options lead to different outcomes. If I choose 'individually' then the next 2 stages do exactly the same job.

Maybe the whole process could be reduced to a single screen for a single lot.

**Comment by SteveTheBrick** [comment]
Yes, you are right and I will close the issue. But please can you check the keyboard focus on the second screen. It looks like we can select the 'finish' button with the enter key but focus is actually on the destination dropdown (or it would be the 'next' button if doing individual lots).

**Comment by rgriebl** [comment]
Ah - that combo-box thingy is a bug in the current Qt 6.4.0 version. I've already fixed that upstream in Qt, but I need to copy over my workaround from the set-to-priceguide dialog, until 6.4.2 is released.
