### ISSUE TITLE
Endless permission dialogs for MacOS on ARM M1.

### ISSUE THREAD

**Issue by kprusov** [rgriebl/brickstore#645]
Hi, 

I've created the discussion https://www.bricklink.com/message.asp?ID=1380758 about the endless dialogs that ask for the permission for Documents folder. 

So, actually the bug is system specific, and it seems to start only on the last versions on MacOS and Brickstore. I'm attaching the video of the behaviour when I try to open an existing document. 

Please let me know if you need anything about my system (better obtained via terminal)

https://user-images.githubusercontent.com/38755408/206864855-b591374a-bf84-41e3-85bf-32692e8b6dee.mov

**Comment by rgriebl** [comment]
As I wrote in the discussion thread on BrickLink, my problems were gone with that patch to BrickStore.
Guess what ... they are suddenly back now and I get asked on each App start.
What did help for me right now, was to re-sign the App bundle locally, even though I see the signature from the build server.
So in case anybody else still has the problem: could you please open `Terminal` and run this command:
`codesign --force -s - --deep /Applications/BrickStore.app`
(just Cmd+C / Cmd+V to make sure there are no typos)
It should report "replacing existing signature" and after the next BrickStore restart the endless request should be history.
