### ISSUE TITLE
Add  optional columns to display columns using data from the priceguide.

### ISSUE THREAD

**Issue by chiminirc** [rgriebl/brickstore#65]
using the data in the priceguide, offer the ability to add columns to display
QTY sold New
Lots sold New
QTY sold Used
Lots sold Used

Perhaps a calculated field for QTY*average price.

![image](https://user-images.githubusercontent.com/76887746/104047694-aedc6600-51a7-11eb-9979-82a1bc9afd4a.png)

**Comment by rgriebl** [comment]
I've now created a super-task issue for custom columns: #617

I will close this issue here however, as it will not be implemented in BrickStore itself and just sitting around in the bug tracker as an open bug for years doesn't help anyone.
