### ISSUE TITLE
Issue with comparing from a Wanted List to inventory

### ISSUE THREAD

**Issue by Flyor** [rgriebl/brickstore#650]
I often use the function to compare a new set inventory (import -> Set) with my inventory. Normally, all the attributes of the inventory are still there (for example the reamarks, prices...) at my inventory if I clicked the source of my inventory. 

But if I Import a wishlist and compare, 90% of the items at the wishlist overwrite the attributes of the inventory (for example erasing the remarks) WITHOUT the question, which attribute source should be used. 

Tell me, if you need further information.

**Comment by rgriebl** [comment]
Please tell me exactly the commands you are clicking, as I can't follow you. Somehow importing a new document (what's a "wishlist"?) changes the remarks in an unrelated document?
Also there's no "compare" functionality in BrickStore...

**Comment by Flyor** [comment]
EDIT: Forgot what I said @rgriebl 
As I try to explain you the problem, I realized that wantedlists (in my example all oft them) are completely "used" items, but in my shop inventory the parts are all new... so it's totally correct, that this would be a new lot id instead of consilidating with the correct one. 

I will final try it tomorrow, but I think this should solve the problem. Thank you anyway!

**Comment by rgriebl** [comment]
Now I got you :)
Also - the consolidate functionality has been completely rewritten for the next version giving you much more control. You can already test it right now: https://github.com/rgriebl/brickstore/actions/runs/3660946123
(just scroll down and download for your platform)

Of course the condition still has to match, but that's an easy fix: `Ctrl+A`, right-click on any condition -> `New`
