### ISSUE TITLE
Window Sizing on Ubuntu 22

### ISSUE THREAD

**Issue by fencer** [rgriebl/brickstore#651]
On Ubuntu 22 I am unable to maximise the windows but that can be lived with. When adding a new part, the window does not fit in the screen, if I resize when searching for a new part will resize the window automatically sometimes hiding the "Add" button.

**Comment by rgriebl** [comment]
Just tested this on a fully updated 22.04 VM for both X11 and Wayland: maximizing the main window works perfectly fine. The "Add Item" window can be too big for small screen sizes, so you may have to disable one or two of the info displays via the `☰` menu in the lower left corner.
I tested the VM with a virtual resolution of 1368x830. I guess going much lower will not really work out great: in this case you'd have to decrease the overall font size in the Settings dialog.

**Comment by rgriebl** [comment]
BTW: Did you install the Ubuntu-22.04-brickstore_2022.11.2_amd64.deb from https://github.com/rgriebl/brickstore/releases? If had you installed the AppImage instead, I'd suggest switching to the native Ubuntu package.

**Comment by henriquedesousa** [comment]
I encounter this issue after I set the display percentage higher than 150% in the Display app (Linux Mint here). All Brickstore windows (main and insert parts) will then not show the maximize button, and the windows will also not be fully maximized. When I return back to 100 or 125%, the maximize button will appear and the windows positions will stay correct. 

Let me know if you need some screenshots and/or video as I'm posting this on a Windows box.

**Comment by rgriebl** [comment]
I can reproduce it, but it's quite clear why on my VM: with a 150% scaling, the minimum window height for both windows gets larger than the available screen height and this of course leads to Qt disabling the 'Maximize' action. If I reduce this font size in the settings I can get both to maximize even at 150%. (also disabling the price-guide widgets in both windows should do the trick: they have a very big and fixed size)
That being said: the minimum height of the item list in the Add-Item dialog is too large ATM and should be decreased.
