### ISSUE TITLE
Part out fig converts to the wrong parts

### ISSUE THREAD

**Issue by mevitsbricks** [rgriebl/brickstore#657]
The part numbers in BL look to be good.  However, when I part out this pig I get different pig parts ;-)
Part out Minifig: collt11  I also tried "Import bricklink Inventory" and had the same issue.

https://www.screencast.com/t/xQPCh39JV

I have tried closing out the app, reopening it, and updating the database but no luck.

Thx

**Comment by mevitsbricks** [comment]
I removed M and P cache and tried it again and it still occurred.

**Comment by rgriebl** [comment]
Duplicate of  #590. This was fixed back then. Could be that old inventories got copied over when I switched the nightly db regeneration job to a docker container.
Anyway: I've flagged both collt11 and 12 for re-download on the next db run.

**Comment by mevitsbricks** [comment]
Thanks!
