### ISSUE TITLE
22.04 Ubuntu release deb package does not install

### ISSUE THREAD

**Issue by nathaneltitane** [rgriebl/brickstore#658]
The 22.04 release at https://github.com/rgriebl/brickstore/releases/download/v2022.11.2/Ubuntu-22.04-brickstore_2022.11.2_amd64.deb
errors out on install complaining about missing QT6 dependencies.

something about conflicting versions or unavailable packages makes the deb package install impossible.

Can the dependencies be checked against the actual available versions of 22.04 and fix the .deb?

EDIT: asking the system to install qt6-base* to solve dependencies still ends up in brickstore.deb erroring with:

``
[ nathanel ] >_ $ sudo apt-get install ./brickstore.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'brickstore' instead of './brickstore.deb'
Starting pkgProblemResolver with broken count: 1
Starting 2 pkgProblemResolver with broken count: 1
Investigating (0) brickstore:amd64 < none -> 2022.10.2 @un puN Ib >
Broken brickstore:amd64 Depends on qml6-module-qtquick:amd64 < none | 6.4.1+dfsg-3+22.04+jammy+unstable+build20 @un uH >
  Considering qml6-module-qtquick:amd64 1 as a solution to brickstore:amd64 9999
  Re-Instated qt6-declarative:amd64
  Re-Instated qml6-module-qtquick:amd64
Broken brickstore:amd64 Depends on qml6-module-qtquick-controls:amd64 < none | 6.4.1+dfsg-3+22.04+jammy+unstable+build20 @un uH >
  Considering qml6-module-qtquick-controls:amd64 1 as a solution to brickstore:amd64 9999
  Re-Instated qml6-module-qtquick-controls:amd64
Broken brickstore:amd64 Depends on qml6-module-qt5compat-graphicaleffects:amd64 < none | 6.4.1-2+22.04+jammy+unstable+build11 @un uH >
  Considering qml6-module-qt5compat-graphicaleffects:amd64 1 as a solution to brickstore:amd64 9999
  Re-Instated qt6-shadertools:amd64
  Re-Instated qt6-5compat:amd64
  Re-Instated qml6-module-qt5compat-graphicaleffects:amd64
Broken brickstore:amd64 Depends on libqt6concurrent6:amd64 < none | 6.4.1+dfsg-1+22.04+jammy+unstable+build21 @un uH > (>= 6.1.2)
  Considering libqt6concurrent6:amd64 0 as a solution to brickstore:amd64 9999
  Re-Instated libqt6concurrent6:amd64
Broken brickstore:amd64 Depends on libqt6core6:amd64 < none | 6.4.1+dfsg-1+22.04+jammy+unstable+build21 @un uH > (>= 6.2.0)
  Considering libqt6core6:amd64 0 as a solution to brickstore:amd64 9999
  Re-Instated libqt6core6:amd64
Broken brickstore:amd64 Depends on libqt6gui6:amd64 < none | 6.4.1+dfsg-1+22.04+jammy+unstable+build21 @un uH > (>= 6.2.0)
  Considering libqt6gui6:amd64 0 as a solution to brickstore:amd64 9999
  Re-Instated libqt6gui6:amd64
Broken brickstore:amd64 Depends on libqt6network6:amd64 < none | 6.4.1+dfsg-1+22.04+jammy+unstable+build21 @un uH > (>= 6.1.2)
  Considering libqt6network6:amd64 0 as a solution to brickstore:amd64 9999
  Re-Instated libqt6network6:amd64
Broken brickstore:amd64 Depends on libqt6opengl6:amd64 < none | 6.4.1+dfsg-1+22.04+jammy+unstable+build21 @un uH > (>= 6.1.2)
  Considering libqt6opengl6:amd64 0 as a solution to brickstore:amd64 9999
  Re-Instated libqt6opengl6:amd64
Broken brickstore:amd64 Depends on libqt6printsupport6:amd64 < none | 6.4.1+dfsg-1+22.04+jammy+unstable+build21 @un uH > (>= 6.1.2)
  Considering libqt6printsupport6:amd64 0 as a solution to brickstore:amd64 9999
  Re-Instated libqt6printsupport6:amd64
Broken brickstore:amd64 Depends on libqt6qml6:amd64 < none | 6.4.1+dfsg-3+22.04+jammy+unstable+build20 @un uH > (>= 6.2.0)
  Considering libqt6qml6:amd64 0 as a solution to brickstore:amd64 9999
  Re-Instated libqt6qml6:amd64
Broken brickstore:amd64 Depends on libqt6quick3d6:amd64 < none | 6.4.1-1+22.04+jammy+unstable+build9 @un uH > (>= 6.2.2)
  Considering libqt6quick3d6:amd64 0 as a solution to brickstore:amd64 9999
  Re-Instated libdraco4:amd64
  Re-Instated libassimp5:amd64
  Re-Instated qt6-quicktimeline:amd64
  Re-Instated qt6-quick3d:amd64
  Re-Instated libqt6quick3d6:amd64
Broken brickstore:amd64 Depends on libqt6quick6:amd64 < none | 6.4.1+dfsg-3+22.04+jammy+unstable+build20 @un uH > (>= 6.2.0)
  Considering libqt6quick6:amd64 0 as a solution to brickstore:amd64 9999
  Re-Instated libqt6quick6:amd64
Broken brickstore:amd64 Depends on libqt6quickcontrols2impl6:amd64 < none | 6.4.1+dfsg-3+22.04+jammy+unstable+build20 @un uH > (>= 6.2.0)
  Considering libqt6quickcontrols2impl6:amd64 0 as a solution to brickstore:amd64 9999
  Re-Instated libqt6quickcontrols2impl6:amd64
Broken brickstore:amd64 Depends on libqt6widgets6:amd64 < none | 6.4.1+dfsg-1+22.04+jammy+unstable+build21 @un uH > (>= 6.1.2)
  Considering libqt6widgets6:amd64 0 as a solution to brickstore:amd64 9999
  Re-Instated libqt6widgets6:amd64
Broken brickstore:amd64 Depends on libqt6xml6:amd64 < none | 6.4.1+dfsg-1+22.04+jammy+unstable+build21 @un uH > (>= 6.1.2)
  Considering libqt6xml6:amd64 0 as a solution to brickstore:amd64 9999
  Re-Instated libqt6xml6:amd64
Broken brickstore:amd64 Depends on qt6-base-abi:amd64 < none @un H > (= 6.2.4)
  Considering libqt6core6:amd64 0 as a solution to brickstore:amd64 9999
  Considering libqt6core6:amd64 0 as a solution to brickstore:amd64 9999
Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 brickstore : Depends: qt6-base-abi (= 6.2.4)
E: Unable to correct problems, you have held broken packages.
``

**Comment by rgriebl** [comment]
Works perfectly fine here in a clean VM:
```
ubuntu@ubuntu-2204:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

Just to be sure that there are no left-overs:
```
sudo apt purge *qt6* && sudo apt update && sudo apt upgrade && sudo apt clean  
```
And installing the downloaded deb:
```
sudo apt install ./Downloads/Ubuntu-22.04-brickstore_2022.11.2_amd64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'brickstore' instead of './Downloads/Ubuntu-22.04-brickstore_2022.11.2_amd64.deb'
The following additional packages will be installed:
  libqt6concurrent6 libqt6core6 libqt6dbus6 libqt6gui6 libqt6network6 libqt6opengl6 libqt6printsupport6 libqt6qml6 libqt6qmlmodels6 libqt6qmlworkerscript6
  libqt6quick3d6 libqt6quick3druntimerender6 libqt6quick3dutils6 libqt6quick6 libqt6quickcontrols2-6 libqt6quickcontrols2impl6 libqt6quicktemplates2-6
  libqt6shadertools6 libqt6svg6 libqt6widgets6 libqt6xml6 qml6-module-qt5compat-graphicaleffects qml6-module-qtqml-workerscript qml6-module-qtquick
  qml6-module-qtquick-controls qml6-module-quick3d qt6-gtk-platformtheme qt6-qpa-plugins
Suggested packages:
  qt6-qmltooling-plugins
The following NEW packages will be installed:
  brickstore libqt6concurrent6 libqt6core6 libqt6dbus6 libqt6gui6 libqt6network6 libqt6opengl6 libqt6printsupport6 libqt6qml6 libqt6qmlmodels6 libqt6qmlworkerscript6
  libqt6quick3d6 libqt6quick3druntimerender6 libqt6quick3dutils6 libqt6quick6 libqt6quickcontrols2-6 libqt6quickcontrols2impl6 libqt6quicktemplates2-6
  libqt6shadertools6 libqt6svg6 libqt6widgets6 libqt6xml6 qml6-module-qt5compat-graphicaleffects qml6-module-qtqml-workerscript qml6-module-qtquick
  qml6-module-qtquick-controls qml6-module-quick3d qt6-gtk-platformtheme qt6-qpa-plugins
0 upgraded, 29 newly installed, 0 to remove and 0 not upgraded.
Need to get 17.8 MB/24.0 MB of archives.
After this operation, 78.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```
And it installs perfectly fine after pressing `Y`. (and yes, it does work with the low-level `apt-get` as well)

What's weird in your output are these: "Broken brickstore:amd64 Depends on qml6-module-qtquick:amd64 < none | 6.4.1+dfsg-3+22.04+jammy+unstable+build20 @un uH >"
Note the `6.4.1` and `unstable`. You must have more apt repos registered than the default ones, as there is no 6.4.1 build at all for any Ubuntu: https://launchpad.net/ubuntu/+source/qt6-base/+publishinghistory

Check the output of `apt policy libqt6core6` which should be:

```
ubuntu@ubuntu-2204:~$ apt policy libqt6core6
libqt6core6:
  Installed: (none)
  Candidate: 6.2.4+dfsg-2ubuntu1.1
  Version table:
     6.2.4+dfsg-2ubuntu1.1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages
     6.2.4+dfsg-2ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages

```

**Comment by henriquedesousa** [comment]
You could also consider using the AppImage, which I use on my older Ubuntu boxes.

**Comment by nathaneltitane** [comment]
> You could also consider using the AppImage, which I use on my older Ubuntu boxes.

thanks but not a fan of storage overhead.
do you happen to have said list of deps?

[here's a good example](https://www.leocad.org/docs/compiling.html) of how leocad specifies it'S deps for whomever want'S to compile:

**Comment by rgriebl** [comment]
Just read the wiki: https://github.com/rgriebl/brickstore/wiki/Building-from-Source

**Comment by nathaneltitane** [comment]
Thanks!

**Comment by henriquedesousa** [comment]
Hello there, I'm installing a new system and found out that the per-requisites are still not quite completed:

I was installing BrickStore on Linux Mint 21 which is Ubuntu 22.04 derived and while trying to install I got the following message:

![Screenshot from 2023-02-14 12-37-53](https://user-images.githubusercontent.com/12630569/219731165-7f4d34d0-744f-454a-b9ed-5a6923779534.png)

I only had to `sudo apt install qt6-base-dev` and after that, all the rest of the dependencies appeared and installed automatically:

![Screenshot from 2023-02-14 12-38-45](https://user-images.githubusercontent.com/12630569/219732069-e11be239-ff5c-4810-8f2b-b80d5c3090d1.png)
![Screenshot from 2023-02-14 12-39-02](https://user-images.githubusercontent.com/12630569/219732150-2d96dbce-75b6-4603-b074-244a2c247144.png)

Thanks again for this great software!

**Comment by rgriebl** [comment]
Still works perfectly fine on a stock Ubuntu 22.04 where it is also compiled.
Try `apt show libqt6core6 | grep Provides`
On Ubuntu 22.04 this returns: `qt6-base-abi (= 6.2.4)` and that's exactly how it should be: BrickStore is compiled against Ubuntu's Qt 6.2.4, so it also has to depend on this ABI level.
If that virtual ABI package is not available on Mint, then Mint is a bit more than a "derivative". Running `apt install brickstore.deb` on the command line might tell you more WHY the abi package is not installable.

PS: I've tested with the 2022.11.1 release - the current dev build (929) is still missing the WEBP image format plugin: it does install fine, but complains when being run.

**Comment by rgriebl** [comment]
Just tested a Mint 21 VM: the graphical installer is broken there.
I can `sudo apt install brickstore.deb` from the command line and it resolves the virtual *qt6-base-abi* package correctly to *libqt6core6*. For whatever reason, the graphical installer cannot deal with this virtual package.
You might want to report this bug to the Mint developers.
In the meantime, I've updated BrickStore's installation instructions to include Mint 21 and the workaround needed:
https://github.com/rgriebl/brickstore/wiki/Installation-Instructions

**Comment by henriquedesousa** [comment]
Hi there, cjust checked in a VM and just a small correction for the installation instructions:

First, install qt6 base with `sudo apt install qt6-base-api`, followed by `sudo dpkg -i ./Downloads/Ubuntu-22.04-brickstore_<VERSION>_amd64.deb`

Then it'll work.

Many thanks for your work on BrickStore.
