### ISSUE TITLE
Recent REinstall on Fresh windows build copy remarks Fail

### ISSUE THREAD

**Issue by Argmentum** [rgriebl/brickstore#659]
Just reinstalled windows 10 on my machine as my H-drive failed. Slowly rebuilding everything , installed Brickstore to start things uploading again but the Copy from another document function doesn't seem to want to work.. at least not properly.

I've restarted my machine multiple times,

 I created a proxy document and can copy from one to another but I cant copy from my imported bricklink store.

Trevor

**Comment by rgriebl** [comment]
Make sure that all of item-id, color, condition (new, used) and status (+, -, x) match for the lots you want to copy from.

**Comment by Argmentum** [comment]
Yup .. the new default is NEW not used .. thx so much .. Im gonna blame it on being late and having spent the last few hours staring at this monitor.. thx again
