### ISSUE TITLE
Difference mode columns not saving with Layout

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#66]
Inside a File the width of the Diff columns its saved, so activating and deactivating it is okay. But I moved them to the left of QTY and PRICE but they are always put after when act/deact it.

Opening a new file and applying a created layout (while Diff was active and rearranged) doesn't affects Diff columns and they are as default.

PD: I have to test more, but I have a couple of columns that seem to jump to the right in a custom layout saved.

**Comment by paramecie** [comment]
Many other little problems with Diff mode: #28 

I guess Robert will fix them maybe in one batch when he'll start this specific subject.
