### ISSUE TITLE
A picture is worth a thousand words

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#660]
Consider adding a small image column in the Item Inventory widget on both tabs.

<img width="245" alt="image" src="https://user-images.githubusercontent.com/1063368/212271284-34201c15-b170-4368-a854-e023c08d4dee.png">

PD: Also let the Qty. row be downsized a bit more as of now it is quite wide, most times it only needs to show 1-99 counts.

**Comment by rgriebl** [comment]
Already implemented in the current dev build. You can make the image as big or as small as you want with `Ctrl+MouseWheel`.
The columns are auto-sized to the maximum of all cell widths and also the header width.
