### ISSUE TITLE
Sets import with quantities multiplied by 851, Mac M1

### ISSUE THREAD

**Issue by lordrocco** [rgriebl/brickstore#662]
Using Brickstore (build 890 and earlier) on a M1 Mac, when I import any set, quantities are multiplied by 851. In other words, to get the proper part-out quantity, I have to divide all items by 851.

I also have this app on a Windows PC and it imports sets correctly. The problem is only on my Mac.

Why does this happen? Can it be fixed?

**Comment by rgriebl** [comment]
Did you check the `quantity` field in the Import Inventory dialog? BrickStore saves the state of all fields across restarts, so it will always show the last used value (which might have been 851 at one point).

**Comment by lordrocco** [comment]
Thanks! So simple, but I never spotted it. I have never knowingly imported that many sets, but whatever.
