### ISSUE TITLE
Paste to item ID with start or end spaces

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#666]
Sometimes when copying something from the BL website a space is added before or after, when pasting to the ID column it does nothing as it only accepts exact match, can it remove spaces automatically?

Example pasted from selecting the Id here:
https://www.bricklink.com/v2/catalog/catalogitem.page?B=9783833236549&name=Kettenreaktionen%20(Panini)%20(German%20Edition)&category=%5BIdea%20Book%5D#T=I

`<html>
<body>

x77ac100
--

</body>
</html>[x77ac100](https://www.bricklink.com/v2/catalog/catalogitem.page?P=x77ac100&idColor=11)`

Strange, when pasting in the BS filter it pastes a space and the Id,  when pasting here it shows all these data, but when pasting to edge top bar it just pastes the correct ID without spaces.

**Comment by rgriebl** [comment]
It's even worse: you also get `TAB` characters in the string if you select a pixel too far to the left. I think I'll deactivate the input validation and just clean out all the white-space when pressing return.
