### ISSUE TITLE
Wrong User/password bug

### ISSUE THREAD

**Issue by NavalBrickCo** [rgriebl/brickstore#670]
I inputted the wrong password and user name into the application and it will not give me any option to change it or try again. it only gives there was an error and the operation was cancelled i have deleted the application and the bug persists. as of right now i cannot use the application at all.

**Comment by rgriebl** [comment]
Just open the settings dialog (Extras -> Settings) and change your credentials on the BrickLink page.

**Comment by NavalBrickCo** [comment]
Thank you!!
