### ISSUE TITLE
Brickstore stops responding when I attempt to load an existing bsx file

### ISSUE THREAD

**Issue by Joesecc** [rgriebl/brickstore#672]
I am using version 2022.11.2  (build:890)

I am not able to open any existing bsx file the program stops responding and has to be closed.

**Comment by rgriebl** [comment]
Please try with any anti-virus/firewall disabled. Most likely someone thinks BrickStore is not allowed to access a specific filesystem location and totally blocks access.

**Comment by rgriebl** [comment]
No feedback in a week. Closing for now. Please reopen if you add more information.
