### ISSUE TITLE
Copy Value from document not working 

### ISSUE THREAD

**Issue by NinjaMantis** [rgriebl/brickstore#673]
Trying to load remarks from brick link inventory to new part out file, which i have done successfully numerous times before, but now its stopped working and not sure why.

**Comment by rgriebl** [comment]
Check the condition (New/Used) on both sides. If they don't match, copy-values won't work.

**Comment by NinjaMantis** [comment]
> Check the condition (New/Used) on both sides. If they don't match, copy-values won't work.

Thank you for the quick response- This was the exact issue and is now working perfectly again.
