### ISSUE TITLE
IT REARANGES THE PARTS  :-(

### ISSUE THREAD

**Issue by KreativSnail** [rgriebl/brickstore#676]
Is there any way to change the settings so that the parts stay in the file in the same order that I add them to the file?

I add parts to the file and put them in cups. Then if the program closes and re-opens, they are in a different order. This is a real problem, because the file is no longer in the same order as the parts in the cups.

The other program I used to use, kept them in the same order. Other than that, your program is 8,000,000 times better than what I used to use.

**Comment by rgriebl** [comment]
Closing due to no feedback. Please re-open if this didn't fix your problem.
