### ISSUE TITLE
Import csv with Lego Element Id

### ISSUE THREAD

**Issue by mmally** [rgriebl/brickstore#677]
Hi,

I have several orders made from the Lego Pick a Brick shop about 200 parts each.
From the pdf I extracted (copy+paste) the Lego element id, quantity and price into Excel.

Now I am looking for a way to import this into Brickstore.
First, I thought of writing a small script that generates a Bricklink compatible xml, but since I have no idea how to decode the part id and color from the Lego element id, this won't work.

Adding everything by hand in the "add part" dialogues is also not my preferred way.

So, any idea how to automate the import would be very welcome.

Best Regards,
Michael

**Comment by ZZJHONS** [comment]
You can donwload the Bricklink catalog with the Part Color Codes (element ID) here:

https://www.bricklink.com/catalogDownload.asp

Then in excel you can write a formula to match them and export.

**Comment by mmally** [comment]
Thank you @ZZJHONS that helped me a lot!

**Comment by chiminirc** [comment]
Small tip.   A part can have more than one PCC.  So looking up a code to get color and part # easy.  Looking up "the code" the other way, not so easy as you will only find one on the LEGO site.
Example.

41663	Pearl Light Gray	4176020
41663	Pearl Light Gray	4199348
41663	Pearl Light Gray	4531087
