### ISSUE TITLE
Edited remarks/comments in Store Inventory should be "mass-updatable"

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#68]
#64 

An old problem (since day 1?), please make it possible to edit some Remarks/Comments (or both) in a Store Inventory, then be able to Export as BrickLink Mass UPDATE (to update just those remarks).

With no other change like Price or Qty.

Just tested in the current version, produces a single line [Inventory] and that's it.

**Comment by TheBrickGuys** [comment]
To have this happen in a future update (or easy work around) would be such a huge time and life saver. Well maybe it won't literally save anybody's life but it would still be greatly appreciated!!

Jim.

**Comment by ZZJHONS** [comment]
I would like this implemented too. +1

**Comment by rgriebl** [comment]
Tell me how this should work in practice. For price/qty updates we have the difference mode, so you see what's changed.
What should be done about the other fields?

a) remember their current state when downloading your store inventory and use that value to see if things changed. What about saving and re-loading the document: should these values be saved? (needs bigger changes in the bsx format)

b) don't remember the state on import, but do an implicit store download before exporting the mass-upload to calculate the differences. Should BrickStore show what it would upload or would it be enough to view the generated XML on BL?

c) other ideas anyone?

**Comment by paramecie** [comment]
For me setting price or qty may be tricky.
Nothing's more difficult to remember 262 x 0.037 or 267 x 0.032...
Seeing the difference, and especially (for me) to sort by difference is a must.

A remark or a comment, I do set it, like "Brand New, I played with it only 6 months!"
You see the remarks or comments, and you see them again when uploading.

So, for me, simply upload what has been marked "edited" would be fine.
Edited should be as a flag set up "edited", and a final control that 2 successive editions didn't provide the same as it was before...

And alzo, when saved, it's saved. No previous state saved.

**Comment by ZZJHONS** [comment]
I too don't think that any difference mode is needed.

The best thing I can think is to compare the current file to a download of the inventory, that BS checks in the background what fields changed, and then generate the clipboard "file" to paste in the mass update.

This could work for any field, not just remarks/comments so to cost, bulk, tier, sale etc. too.

Maybe the code to check against a download of the inventory could be used too to the populate fields request. #71 #64

**Comment by rgriebl** [comment]
Please test the newest dev build (261 or newer). Difference mode changed significantly and can handle all fields that are Mass-Updatable in BL now.
DON'T SAVE AND OVERWRITE YOUR IMPORTANT FILES while the new Difference mode is active - "Save as" to a new file instead. The actual file format for saving the diff-mode data is not finalized yet.

**Comment by paramecie** [comment]
Wow thanks!

Tested Build 262.

Remarks:

**The warning message is too long, maybe:**
All differences will be consolidated. This can't be undone. Continue?

**Why can't we mass update without lotID?**
I wouldn't open this msg box (no Lot ID), there are already too many (3 or 4?)
Simply do NOT open the BrickLink mass upload page, as you can't use it _there_ ;-)

**Comment by rgriebl** [comment]
> Why can't we mass update without lotID?

Because it is THE required field for BL's mass update. You cannot update anything without the lotid: https://www.bricklink.com/help.asp?helpID=251&viewType=shop

**Comment by rgriebl** [comment]
> **The warning message is too long, maybe:**
> All differences will be consolidated. This can't be undone. Continue?

I know. I'll leave it at that for now, since "difference mode" changed significantly to how it operated the last 15 (?) years. I'll shorten it once I know this change didn't cause too much problems.

**Comment by paramecie** [comment]
Yes, but why not leaving people use this information as they wish?

Not for me - I don't care (for now).

**Comment by paramecie** [comment]
> You cannot update anything without the lotid

Yes, but why not letting people use this information (outside BL) as they wish?

Not for me - I don't care (for now).

**Comment by paramecie** [comment]
> I'll leave it at that for now

No - please add an "e" at "therefor" :)
Apart this, you're the boss, Boss!

**Comment by rgriebl** [comment]
Have a look at build 263 (it's currently building)

**Comment by ZZJHONS** [comment]
Seems to be working fine!

Also, if I want to mass change my remarks to add a 0 between a letter and a number I already have, I can do it in notepad/VS Code and save the file, and when opening the file in BS it recognizes these changes and lets you mass update them, so perfect!

But I noticed important info missing, the Totals that were bottom left disappeared, can this info be added back? Not in the bottom again, just next to the currency.
