### ISSUE TITLE
On opening, application hangs on "Update Database" but also remarks "Already up-to-date"

### ISSUE THREAD

**Issue by TygerBurning** [rgriebl/brickstore#691]
As title - shown by screenshots below:
![image](https://user-images.githubusercontent.com/6792948/226351368-a265d539-c8b2-41e6-b1b1-5a2d9624a68d.png)
![image](https://user-images.githubusercontent.com/6792948/226351429-20dfca26-6468-408e-a56b-2bb5bd0eac85.png)

If I ignore the error, I can still navigate the application - until I try to open an old `.bsx` file - that has the chance of crashing the application. I don't know what it is about the `.bsx` file that causes it to crash.

If you can tell me where any debug logs are found, I'm happy to attach them.

Equally, https://github.com/rgriebl/brickstore/commit/e365eee73944ae3f04d9940bb1e981953be0c63b looks like it might help if it's a corrupt database - do you have plans on a next release?

Thanks!

**Comment by rgriebl** [comment]
The new functionality in e365eee is just an easy way to get around an corrupt database that could happen due to something outside of BrickStore's control, like a stuck system clock. You are the second person now with this exact error message, so it seems there's more to it...

If you still have that error, could you please start BrickStore, create a new document, then enable the error log via `View` > `View Info Docks` > `Error Log`.
In the error log, right-click `Select All` and then right-click-again `Copy`.
Please paste the log here as an reply.

**Comment by TygerBurning** [comment]
Thanks for your prompt response. Here's the output:

```
INFO sentry: Successfully initialized [sentry.io](http://sentry.io/)
INFO default: Using BrickLink price-guide retriever plugin: "Batched Affiliate API"
INFO default: Picture cache: 1.0 GB
INFO default: Loading database: 0s 386ms 186us
INFO default: Loaded database from C:/Users/Dave/AppData/Local/BrickStore/cache/database-v8
INFO default:   Generated at  : 16 Mar 2023 04:01:35 +0000
INFO default:   ChangeLog I   :     36 504
INFO default:   ChangeLog C   :          1
INFO default:   PCCs          :     76 744
INFO default:   Colors        :        201
INFO default:   LDraw Colors  :         52
INFO default:   Item Types    :          8
INFO default:   Categories    :      1 059
INFO default:   Items         :    167 944
INFO default:     Book        :      6 235
INFO default:     Catalog     :      4 578
INFO default:     Gear        :     17 042
INFO default:     Instruction :     11 198
INFO default:     Minifigure  :     15 172
INFO default:     Original Box:     18 568
INFO default:     Part        :     76 585
INFO default:     Set         :     18 566
INFO default: UI:
INFO default:   Device pixel ratio: 1 / Qt::HighDpiScaleFactorRoundingPolicy::RoundPreferFloor
INFO default:   Screen size in pix: 1920 x 1080
INFO default:   Screen size in mm : 531 x 299
INFO script: Loading scripts from directory: "C:/Users/Dave/AppData/Roaming/BrickStore/extensions"
INFO script:   [ ok ] classic-print-script.bs.qml
INFO default: Loading orders from cache: 2s 299ms 599us
WARN qt.tlsbackend.ossl: Failed to load libssl/libcrypto.
WARN resolver:  [FAIL] P-973c03h22pr6449 (11) at core.cpp, line 882
WARN resolver:  [FAIL] P-973c03h27pr6448 (11) at core.cpp, line 882
WARN resolver:  [FAIL] P-3626cpr3931 (1) at core.cpp, line 882
INFO default: Reading ZIP directory: 0s 055ms 884us
INFO default: Found LDraw at C:/Users/Dave/AppData/Local/BrickStore/cache/ldraw/complete.zip 
INFO default:   Last updated: 18 Mar 2023 13:26:57 +0000
```

**Comment by rgriebl** [comment]
Thanks for the log. I can reproduce the problem now:
1) the weird message boxes: this is a combination of the daily database update job on my server being stuck for 4 days now and BrickStore not handling that situation correctly. It's weird, but harmless.
2) as for the crash on some files: this is actually bug #686. You can either wait for the next release (which is hopefully in the next days) or just install the current development version from here: https://github.com/rgriebl/brickstore/actions/runs/4463478934 (scroll down, download Windows-x64)

**Comment by TygerBurning** [comment]
1. Aha! No problem - just a coincidence that started happening when the crashes started so I assumed it was relevant.
2. D'oh - I should have spotted that. Agreed that it looks like the same issue. I'm okay to wait until the next release :)

Many thanks for your speedy investigation and resolution. All the best.
