### ISSUE TITLE
Antivirus reporting "Unauthorized file encryption"

### ISSUE THREAD

**Issue by CamelCityBH** [rgriebl/brickstore#695]
I am getting an anti-virus quarentine message for BrickStore when I try installing the latest version: "unauthorized file encryption".  This is being reported by TrendMicro enterprise security.  Any idea what might have changed since the previous version?

**Comment by rgriebl** [comment]
Don't use Trend-Micro: see #684

**Comment by CamelCityBH** [comment]
Unfortunately, not an option.  It is what is in place at our corporate
level.  I use BrickStore on several systems at home with no problems.  In
fact, I've used the donation feature several times out of appreciation for
your hard work.  Just wanted to make you aware of the issue being
reported.  I'll just have to avoid using BrickStore during my lunch hour
and save it for my time at home.

Gene C
Camel City Brickhouse

**Comment by rgriebl** [comment]
There's nothing I can do. If you can white-list BrickStore.exe yourself, just do it (check with virustotal.com first to be 100% sure). Otherwise you need to talk to your IT department and ask them to white-list it for you.

**Comment by CamelCityBH** [comment]
Thanks for the quick replies.  Unfortunately, white-listing it isn't
working.  I've talked with TrendMicro and their position is that something
close enough to the signature for a common ransomware profile that it is
triggering it despite white-listing brickstore.exe.  I AM the IT director
for our architectural firm.  I've been trying to find the issue for a few
weeks now, not wanting to bug you with a problem, hoping instead to offer a
solution.  But nothing has popped up.
