### ISSUE TITLE
Option to hide only Modulex Colors

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#7]
In the color selector, there is a dropdown on top to select All Colors or only some.

I think it would be great to have an option to show all except Mx Colors.

And an option to default it, or at least remember it, now it remembers it only if you don't close the program.

Thanks

**Comment by chiminirc** [comment]
I would benefit from this as well.

**Comment by paramecie** [comment]
Or maybe simply, have an Options setting where you choose your facorite set of colors:

All colors
Popular colors
[x] Most popular colors => (for me)

Then every time you change an iten color or add an item, this specific set of colors is displayed by default?

**Comment by rgriebl** [comment]
Modulex colors are now gone from all the normal filters, except the "Show only Modules colors" filter.
If and when somebody really wants to use BrickStore to deal with his Modulex bricks, I guess he can deal with that minor inconvenience ;)
