### ISSUE TITLE
Application error. Suddenly closed during priceguide download "Verifying Price Guide Data"

### ISSUE THREAD

**Issue by chiminirc** [rgriebl/brickstore#70]
It is intermittent. The first time it happened I loaded the wool farm from Minecraft and updated prices.
I relaunched the app and tried again and the same kit loaded fine.  I tried some other kits and it worked.
I then loaded my store inventory and did an update and it crashed again during "Verifying Price Guide Data"

![image](https://user-images.githubusercontent.com/76887746/104093302-5f517500-524f-11eb-8d3a-d6f042b3651e.png)

**Comment by chiminirc** [comment]
Version 2021.1.3 64 bit. Windows 10 version 1909

**Comment by paramecie** [comment]
Where are you located (Country)?
That *may* "simply" be BrickLink not accessible from time to time where you live.
But of course it shouldn't crash but provide some information.
Here no problem all day long (monitoring 7/24).

If it crashes open or refresh a web page on your BrickLink shop and confirm it it works?

Just an idea, though...

**Comment by chiminirc** [comment]
I'm in the USA. 
Running bricklink tabs in Chrome all the time and no errors, timeouts, or missing data due to excessive calls from my IP Address.

**Comment by paramecie** [comment]
21153-1?
I just did both Import and Part-out, zero problem.

Might be it temporarily not available while BrickLink is updating it? Really no idea.

Robert will tell us I guess!

**Comment by rgriebl** [comment]
I found a bug in the set-to-priceguide code that only triggers, if you have two or more lots of the same item/color AND the price-guide has to be downloaded.
Fix is baked into the latest build found under "Actions".
I hope it was this you were hitting.
