### ISSUE TITLE
Lock color option

### ISSUE THREAD

**Issue by TGS-Bricks** [rgriebl/brickstore#702]
When adding items and use unlocki color, the item list is updated, but the colorlist stay at the choosen color.

**Comment by rgriebl** [comment]
Please give an example of what you are doing, what is happening and what you expect to be happening.
Also, please add the BrickStore version you are using.

**Comment by TGS-Bricks** [comment]
Hi

Maybe I’m using the feature in a way it wasn’t intented to be.

 

When adding torsos I choose “Black” and choose the “Lock color”, then I have all the black torsos in the item add window. When done I again choose “Lock color” to deactivate, but then the item add window gets updated with all items, but the color list continue to show black.

 

Regards

TGS

 

Fra: rgriebl ***@***.***> 
Sendt: 9. april 2023 10:53
Til: rgriebl/brickstore ***@***.***>
Cc: TGS-Bricks ***@***.***>; Author ***@***.***>
Emne: Re: [rgriebl/brickstore] Lock color option (Issue #702)

 

Please give an example of what you are doing, what is happening and what you expect to be happening.
Also, please add the BrickStore version you are using.

**Comment by rgriebl** [comment]
What would you expect to happen? You have selected "Black" before, so it's still selected... The color "lock" just influences the filtering of the item list (only show items that are known to ne available in the selected color)

**Comment by TGS-Bricks** [comment]
Hi

Well, when deselecting the ”lock color” I expect to see all the colors in the colorlist again, but I don’t, I only see the selected color. I have to select another categori in the Categori list to see all colors again.

I’m now using your latest release.

Regards

TGS

 

Fra: rgriebl ***@***.***> 
Sendt: 9. april 2023 22:08
Til: rgriebl/brickstore ***@***.***>
Cc: TGS-Bricks ***@***.***>; Author ***@***.***>
Emne: Re: [rgriebl/brickstore] Lock color option (Issue #702)

 

What would you expect to happen? You have selected "Black" before, so it's still selected... The color "lock" just influences the filtering of the item list (only show items that are known to ne available in the selected color)

**Comment by rgriebl** [comment]
For me, it works exactly like you expect it to work. Please describe in steps, which buttons/items you click in the add-item dialog, and how the color listview changes.
Or make a quick video, recording your screen. (Windows+G and then "Capture" (3rd) button)

**Comment by TGS-Bricks** [comment]
Thanks to ZZJHONS, problem solved.
