### ISSUE TITLE
Addition error when adding items to file - *** still broken ***

### ISSUE THREAD

**Issue by Brickadoon** [rgriebl/brickstore#705]
Hi, this was originally logged as issue #678 and marked as closed, however the issue still exists in the latest version I've downloaded (2023.4.1). Can you revisit this please?

_I've come across an error in the latest version I downloaded (2023.2.1).

When I'm adding items to my store, I import my BL store and set the quantities of all items to 0. I then copy & paste the values from the bsx file that holds the items I'm importing, so it consolidates with the lots I already have and adds new lots where necessary.

I've discovered that when doing this in the new version, if a lot already exists the quantity of items imported is doubled. For example in the bsx I'm copying from if a quantity says 100, when it gets copied over & consolidated it will say 200. This only happens on lots that already exist - new lots created are fine.

I've downloaded the previous version I was using (2022.11.2) and that works fine._

**Comment by Brickadoon** [comment]
Hi,

Yes I can still produce the error. I’ve attached the two files I’ve tested with, and these are the tests I’ve performed:

Two files (filea & fileb) with the same items:

The white items have a quantity of 10, the black items have a quantity of 4 - total quantity in each file is 28

Test 1
Highlight all items in fileb, right click & copy
Go to filea, right click & paste
Choose first option (Use the same options to consolidate all lots) and click finish
Filea is correct, all items have double what they had previously, total quantity is 56

Test 2
Highlight all items in filea, choose Set Quantity to 0 - total quantity in filea now 0
Highlight all items in fileb, right click & copy
Go to filea, right click & paste
Choose first option (Use the same options to consolidate all lots) and click finish
Filea is incorrect, all items have twice what they should have, total quantity shown is 56, but should be 28

Thanks for taking a look at this again.

Rich

**Comment by rgriebl** [comment]
Your attachments are not showing. To attach files to Github issues, you have to ZIP them.
Also, I'm not sure if email attachments are transferred over, so better use the web interface here: https://github.com/rgriebl/brickstore/issues/705

**Comment by Brickadoon** [comment]
[brickstock.zip](https://github.com/rgriebl/brickstore/files/11191665/brickstock.zip)

**Comment by Brickadoon** [comment]
I’ve attached them via the web interface – hopefully you can see them now 😊

**Comment by Brickadoon** [comment]
Thankyou! It’s working now.

Rich
