### ISSUE TITLE
Install Database update errors

### ISSUE THREAD

**Issue by JamesSauter** [rgriebl/brickstore#709]
Easier to just link my post
https://www.facebook.com/groups/2318028917/posts/10159831737613918/

**Comment by rgriebl** [comment]
Something is broken with the certificate store of your OS. 
- Can you view https://www.brickstore.dev ?
- Can you download https://data.brickstore.dev/complete.zip ?
Please test at least with Edge, ideally also with another browser like Firefox or Chrome.

While the data moved to a new domain (data.brickstore.dev), the SSL certificate there is valid according to all online test tools.

**Comment by JamesSauter** [comment]
Yes I can open the page and DL the file both in Chrome and Edge

**Comment by JamesSauter** [comment]
App seems to be working ok.. but I get the same errors if I try to update
the db again

**Comment by JamesSauter** [comment]
Correction.. I just opened it, and it ran through the db update without any
errors this time.  I guess its fixed now :)

James

**Comment by JamesSauter** [comment]
Probably just a dns update lag at my end. I've seen that before too.
