### ISSUE TITLE
Brickstore camera IOS

### ISSUE THREAD

**Issue by Gizmo19699** [rgriebl/brickstore#715]
Hi there,

With the new update, my camera shows no on-screen picture, on either the laptop camera or my web cam.

Mark (Gizmo)

**Comment by Gizmo19699** [comment]
oh, sorry.... I'm on MacOS

**Comment by StoneyBricks** [comment]
Same issue on my MacBook Pro

**Comment by rgriebl** [comment]
Please be more specific:
 - which macOS version?
 - did you get the question to allow BrickStore to access the camera?
 - even if you did click "allow": have you checked in the System Preferences that BrickStore has access (just search for `camera` to get to the right preferences pane)
 - when you say "no on-screen picture": does this mean a black rectangle?
 - if there's nothing at all, have you tried resizing the dialog?

**Comment by Gizmo19699** [comment]
Hi,

I have a MacBook Pro (2015) running MacOS Monterey.
I have checked, and Brickstore has access to my cameras.
I have the camera dialog box, but it is just black (no picture). Both cameras show up as options.... It does this for both my USB camera and the built in FaceTime camera.
Yes, I have tried re-sizing the box.

The camera worked fine, till i updated to the new Brickstore version (2023.4.4)

Cheers!
Mark

> Please be more specific:
> 
> * which macOS version?
> * did you get the question to allow BrickStore to access the camera?
> * even if you did click "allow": have you checked in the System Preferences that BrickStore has access (just search for `camera` to get to the right preferences pane)
> * when you say "no on-screen picture": does this mean a black rectangle?
> * if there's nothing at all, have you tried resizing the dialog?

**Comment by rgriebl** [comment]
I don't have  a macOS 12 machine to test and my macOS 13 based ones seem to work fine.

I did find this Qt bug report however: https://bugreports.qt.io/browse/QTBUG-111704
Qt 6.5.1 will be released on May 24th, so I can create a test build later this week to see if that fixes your issue as well.

**Comment by mrEelco** [comment]
macOS: Ventura 13.3.1
yes, i allow the camera. Until the last version of Brickstore it worked fine. The last update i can select the USB-camera (the Instabrick camera) and it stays black rectangle if i select the camera on an other application the camera works fine.
resizing the window doesn't solve the issue

**Comment by rgriebl** [comment]
Here's a build against Qt 6.5.1: https://github.com/rgriebl/brickstore/actions/runs/5068767245 (you need to be logged in. just download, unzip and install as usual)

**Comment by cajunik** [comment]
Problem solved! Thanks

**Comment by rgriebl** [comment]
@Gizmo19699 @mrEelco Could you please also test this build and see if it solves your problem?

**Comment by Gizmo19699** [comment]
That fixed it!!!  Awesome!  Thank you!!!!

**Comment by mrEelco** [comment]
It works fine now! Thanks!

**Comment by rgriebl** [comment]
Fixed in QtMultimedia 6.5.1
