### ISSUE TITLE
Newer updates not taking

### ISSUE THREAD

**Issue by Dhomal** [rgriebl/brickstore#718]
So, the last couple of updates perhaps are causing issues on my main laptop of not updating.

Open BS. See pop-up of newer version. Follow update steps. Seems OK. Close BS. Open again. Same pop-up.

I have uninstalled and re-installed BS and the same issue is happening. It is the (Current, I presume) 2023.4.4 update that I see as the newest. Looking at help/about, it says my version is 2022.4.1 (yes, 2022).  

I have three other 'store' laptops that seem to be updating fine, but not the main one.

For now, it is not an issue, as it still seems to be Working for me, but clearly, I would like to get some updates eventually!

Any assistance would be appreciated, thank you.

**Comment by rgriebl** [comment]
Open https://www.brickstore.dev/download and read the part about the legacy version ("If you are stuck...")

If you are NOT running one of those old systems, then please report back which OS and version you are using. (see also Help > System information in BrickStore)

**Comment by Dhomal** [comment]
Hello-

Running Windows 10 Home, 64 bit. Version seems to show as '22H2'

I looked at Help>System Information in BS, and was not sure what I should be looking for, so I opted to copy it all and it follows:

### BrickStore 2022.4.1 (build: 663)

* **brickstore.ldraw**: 31 Mar 2022
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930141)
* **build.date**: 2022-04-01T23:02:53.000
* **build.host**: fv-az28-463
* **build.number**: 663
* **build.qt.version**: 5.15.2
* **hw.cpu**: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: Intel(R) UHD Graphics 630
* **hw.memory.gb**: 63.9
* **os.arch**: x86_64
* **os.name**: Windows 10 Version 2009
* **qt.debug**: false
* **qt.version**: 5.15.2

**Comment by rgriebl** [comment]
That looks good and you should be able to install newer BrickStore versions perfectly fine. I can only think that something went south during one of the attempted updates and now the Windows' installation database is broken.
Your best bet would be to manually de-install the "sticky" 2022.4.1 version and then install a current version afterwards:
1) Press `Windows`, type `Add` and pick `Add or remove programs`. Find *BrickStore*, click on it and then pick `Uninstall` (repeat if there are multiple entries).
1) Afterwards, go to https://github.com/rgriebl/brickstore/releases/latest, download the Windows/x64 version and install it.
1) Keep fingers crossed that future updates will now work ;-)

**Comment by Dhomal** [comment]
Hello-

I am not sure what the remove programs uninstall did this time that was different, but now it seems to be better. My thanks!

-Doug
