### ISSUE TITLE
CTRL+F to set focus to Filter field

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#72]
As title says.

And of course show this Shortcut, like here:
![image](https://user-images.githubusercontent.com/32078594/104104515-f72f7d00-52a8-11eb-85d7-2522238e01fd.png)

**Comment by chiminirc** [comment]
This would be handy. Filter is a go to for me with jersey all actions. A shortcut key to clear it too would be handy. CTRL SHIFT F maybe.
