### ISSUE TITLE
Feature Requests for "ADD ITEM" window

### ISSUE THREAD

**Issue by ZchPetit** [rgriebl/brickstore#721]
First of all, thanks for this amazing software; BrickStore has saved me and many others I know so much time and energy, and we appreciate the work you are doing.

I was wondering if when we click (on a Part, MF, etc) in ADD ITEM, it automatically selects the top colour and displays it's price info, instead of having to select it. Only because many parts are only in one or two colours, and it would save an action.

Also I need to compile very big lists of Parts and Figures from only one theme (for example, I'd like a document of all colours of Lego Parts every released in the 'Brick, Decorated' category), and I'd especially like a document of every colour of every Lego Part EVER released so I can easily filter every piece through the amazing amount of options to sort by that BrickStore allows to be possible.
So more generally it would be great to mass ADD ITEMS to documents of all the colours of parts; perhaps we could add an option to MASS ADD or be able to shift/ctrl-click items to add in the ADD ITEMS window, and to quickly add all parts from a category into a Document.

If anything like this could be implemented it would be amazing. Feel free to discuss what might be better ways of doing this.

Zac

**Comment by ZZJHONS** [comment]
Suggestion to auto select color when only one color: https://github.com/rgriebl/brickstore/issues/150
Also option to mass add items too: https://github.com/rgriebl/brickstore/issues/668
