### ISSUE TITLE
Importing orders received does not import cost data when available

### ISSUE THREAD

**Issue by jmcadams** [rgriebl/brickstore#723]
**Describe the bug**
When importing orders received, the MYCOST tag value does not seem to be imported.

**To Reproduce**
ctrl-i then ctrl-o
pick any order
click import button
view results, most data is correct, however cost data from MYCOST is missing.

**Expected behavior**
Cost data to be available

**Screenshots**
![NoCost](https://user-images.githubusercontent.com/3865986/235820287-7a1c832b-debf-4eb5-87f5-b788deaefba0.jpg)

**System information**
### BrickStore 2022.4.2 (build: 669)

* **brickstore.ldraw**: 31 Mar 2022
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930146)
* **build.date**: 2022-09-14T22:41:04.000
* **build.host**: fv-az455-660
* **build.number**: 669
* **build.qt.version**: 5.15.2
* **hw.cpu**: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: Intel(R) HD Graphics 4000
* **hw.memory.gb**: 15.9
* **os.arch**: x86_64
* **os.name**: Windows 7 Version 6.1 (Build 7601: SP 1)
* **qt.debug**: false
* **qt.version**: 5.15.2

**Comment by jmcadams** [comment]
@rgriebl Thank you, I am setting up a Linux VM so I can test (Since I have windows 7).

**Comment by jmcadams** [comment]
Still broken in 2023.5.1 (build 1049), the main store inventory page now imports (ctrl-I ctrl-S) inventory correctly, but the order (ctrl-I, ctrl-O) does not.

**Comment by rgriebl** [comment]
It does import for me. You have to update your order list, as the MYCOST field wasn't even downloaded from BrickLink before.

**Comment by jmcadams** [comment]
Wow! You are good.  Troubleshoot, diagnose, provide a solution to my ignorance all within 2 hours!  Thank you.

It works!
