### ISSUE TITLE
parse error bricklink download store inventory

### ISSUE THREAD

**Issue by tallytoyBL** [rgriebl/brickstore#725]
"Failed to import the store inventory: XML parse error at line 282660, column 45..."
When I look at the XML file from BrickLink, there are only 282653 rows and only 1 column.
What am I missing?

**Comment by rgriebl** [comment]
Why didn't you add the full error message here, like you did on the BL forum?

`Expected '#' or 'a-z', but got ''." ` means that BrickLink - once again - is not escaping the `&` character correctly and thus produces invalid XML ... this is an on-going theme for the last 15 years. Check your descriptions/comments/remarks for `&` and remove it.
You might also want to report this bug to BrickLink.

**Comment by tallytoyBL** [comment]
Hi,
I figured it out. There was an issue with a super lot I created. I'm not sure what caused the problem, I was just checking the items I worked on yesterday. I unbound the super lot and the file downloaded correctly.
Joe
