### ISSUE TITLE
Can't link to bricklink store after username change

### ISSUE THREAD

**Issue by PurpleFish151** [rgriebl/brickstore#726]
Unable to download store inventory from bricklink into brickstore after changing my username on my bricklink account.  Gonna try uninstall/reinstall brickstore.

**Comment by PurpleFish151** [comment]
Well, well, well, that didn't work.

**Comment by rgriebl** [comment]
Did you change your BL username and password in the Settings dialog? What is the exact error message you get?

**Comment by rgriebl** [comment]
No feedback - closing
