### ISSUE TITLE
Minor, tooltip on clear filter "x" button

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#73]
Showing something like "Clear Filter" ?

(as we've a tooltip over the close file symbol)

![image](https://user-images.githubusercontent.com/32078594/104104632-a5d3bd80-52a9-11eb-9597-0aacc870a230.png)

**Comment by rgriebl** [comment]
Would make sense, but I can't easily set a tooltip there, because this button is an Qt internal action.
