### ISSUE TITLE
Crash upon using webcam to find part

### ISSUE THREAD

**Issue by Schoen98** [rgriebl/brickstore#730]
Brickstore crashes when trying to find a part with webcam in the add parts window. It happens when i click the icon and also when using the keyboard shortcut. 

**System information**
I'm running on ChromeOS
Version 112.0.5615.134 (Official Build) (64-bit)

with version:
### BrickStore 2023.4.4 (build: 1014)

* **brickstore.ldraw**: 04 Apr 2023 16:40:06 +0200
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: GCC 10.3.0
* **build.date**: 2023-04-18T15:11:04.000
* **build.host**: fv-az207-892
* **build.number**: 1014
* **build.qt.version**: 6.4.2
* **hw.cpu**: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: ?
* **hw.gpu.arch**: ?
* **hw.memory.gb**: 14.2
* **os.arch**: x86_64
* **os.productname**: Debian GNU/Linux 11 (bullseye)
* **qt.debug**: false
* **qt.platformname**: xcb
* **qt.version**: 6.4.2

**Comment by rgriebl** [comment]
ChromeOS is not a supported platform and I have no way of debugging this at all.
You might get lucky with a newer Qt 6.5 based build from here: https://github.com/rgriebl/brickstore/actions/runs/4914632065 (you have to be logged into GitHub to access these dev builds)

**Comment by rgriebl** [comment]
Closing, as this is a non supported setup
