### ISSUE TITLE
papalook webcam problem

### ISSUE THREAD

**Issue by cajunik** [rgriebl/brickstore#732]
I have a Papalook AF925 webcam that works fine on my MacBook Pro (intel) with Teams or Meet, but it give a black image on brickstore. The webcam lights turns on as it is connected, but I have no image. If I try with integrated MacBook Pro webcam the images works fine. Is there any incompatibility with this webcam? do you have a webcam compatibility list?
Thanks

**Comment by rgriebl** [comment]
Please see here #715 and test the linked BrickStore version from my latest comment

**Comment by rgriebl** [comment]
Fixed in QtMultimedia 6.5.1
