### ISSUE TITLE
No consolidation using XML upload

### ISSUE THREAD

**Issue by ThoronSteynar** [rgriebl/brickstore#733]
When using the "Bricklink mass upload", parts in that file are not consolidated with existing parts in my inventory. The uploaded parts get a new lot-ID and can be found twice in my inventory.
Brickstore Version 2023.4.4 (Build1014)
System-Information:
### BrickStore 2023.4.4 (build: 1014)

* **brickstore.ldraw**: 21 May 2023 22:52:47 +0200
* **brickstore.locale**: de
* **build.arch**: x86_64
* **build.compiler**: clang 14.0.0 (clang-1400.0.29.202)
* **build.date**: 2023-04-18T15:18:58.000
* **build.host**: Mac-1681830415917.local
* **build.number**: 1014
* **build.qt.version**: 6.5.0
* **hw.cpu**: Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: Intel Iris Pro
* **hw.gpu.arch**: Intel
* **hw.memory.gb**: 16.0
* **os.arch**: x86_64
* **os.productname**: macOS 11.7
* **qt.debug**: false
* **qt.platformname**: cocoa
* **qt.version**: 6.5.0

How to fix this problem?

**Comment by rgriebl** [comment]
This consolidation step is done directly in the mass-upload form on BrickLink: https://www.bricklink.com/invXML.asp?utm_content=subnav
See the `[x] Consolidate lots by using:` checkbox and its options on the left side.
