### ISSUE TITLE
Brickstore crashes on MacOS after latest update

### ISSUE THREAD

**Issue by BrickArena** [rgriebl/brickstore#736]
**Describe the bug**
I have just installed the latest version of Brickstore and although it launches OK any attempt to open or create a new file simply closes the app. There is no error, no dialogue box nothing. It just disappears.

**To Reproduce**
Launch Brickstore on Mac
Click new document icon (or open any existing document) 

**Expected behavior**
Clearly system should not crash

**Screenshots**

**System information**
Please tell us which system you are running on and which BrickStore version you are using.
In BrickStore, just open `Help` > `System information...`, Click `Copy to clipboard` and then paste  here.

### BrickStore 2023.5.1 (build: 1049)

* **brickstore.ldraw**: 12 Apr 2023 12:25:37 +0100
* **brickstore.locale**: en
* **build.arch**: arm64
* **build.compiler**: clang 14.0.0 (clang-1400.0.29.202)
* **build.date**: 2023-05-29T16:14:39.000
* **build.host**: Mac-1685375730254.local
* **build.number**: 1049
* **build.qt.version**: 6.5.1
* **hw.cpu**: Apple M1 Max
* **hw.cpu.arch**: arm64
* **hw.gpu**: Apple M1 Max
* **hw.gpu.arch**: sppci_vendor_Apple
* **hw.memory.gb**: 32.0
* **os.arch**: arm64
* **os.productname**: macOS Ventura (13.4)
* **qt.debug**: false
* **qt.platformname**: cocoa
* **qt.version**: 6.5.1

**Additional context**
You can also attach BSX files, but GitHub only accepts these if added to a ZIP file first.

**Comment by rgriebl** [comment]
I can't reproduce this (yet), but looking at the Sentry crash reports, this only happens on macOS 13.4.0 and it's the OS that is triggering an exception.
I'm updating my Mac to 13.4.0 right now

**Comment by BrickArena** [comment]
OK thanks for the update. I have reverted to previous version for now.

**Comment by rgriebl** [comment]
I cannot reproduce this crash -- neither on Intel nor on an M2. Could you please install this version of BrickStore:
https://github.com/rgriebl/brickstore/actions/runs/5123274290
Make sure crash reports are enabled and then try to make it crash a few times.
I've made the macOS crash handler a bit more verbose, so hopefully the Sentry crash reports can give me a better clue this time.

**Comment by rgriebl** [comment]
This is a Qt bug: https://codereview.qt-project.org/c/qt/qtbase/+/478511
It gets triggered if you have accessibility options enabled in the system preferences. I'll try to disable accessibility support until a new Qt version is released. This isn't ideal, but 6.5.0 has problems with a bunch of webcams, so Qt version wise, we're stuck between a rock and a hard place.

**Comment by BrickArena** [comment]
Thanks for looking into this. Sorry I missed your message yesterday and was unable to test.

**Comment by rgriebl** [comment]
Can anyone please test this? I see a lot of crashes in Sentry, but I really would like to have a confirmation that my workaround works before releasing an update.

**Comment by BrickArena** [comment]
> No problem. But could you then please test this version? https://github.com/rgriebl/brickstore/actions/runs/5133431907
> If it works for you as well, I'll create a new official release.

I have installed and tested this version and it is no longer crashing. I can now open files OK and create new ones, which is what would cause the app to crash previously.
