### ISSUE TITLE
Checkbox to "include and consolidate extra parts"

### ISSUE THREAD

**Issue by chiminirc** [rgriebl/brickstore#74]
When importing bricklink inventory, offer a checkbox next to quantity to "include and consolidate extra parts"
It is very frequent that I'll do this as I include parts in my uploads.  
Today I
CTRL + I, CTRL + I, Select all, right click status INCLUDE, click "consolidate items"

With this new checkbox, it would be similar to above but would not prompt for parts consolidation and just accept defaults (equivalent of check "do the same for remaining lots" and clicking YES)

**Comment by rgriebl** [comment]
Already implemented, just not cross-referenced from the commit message.
