### ISSUE TITLE
Minor issue: pop up "Update Database" remains open (and animated)

### ISSUE THREAD

**Issue by froqzy** [rgriebl/brickstore#746]
**Describe the bug**
Since a few weeks, on opening Brickstore or manually updating de database, the "Update Database" Pop up replies "Already up-to-date", but the pop-up remains open and animated. Pop up can be closed manually so not a big issue.

**To Reproduce**
1. Go to 'Extras'
2. Click on 'Update Database'
3. See error

**Expected behavior**
No pop-up on start-up if Database is already up-to-date. No animation in pop-up if message is "Already up-to-date"

**Screenshots**
![image](https://github.com/rgriebl/brickstore/assets/115467136/7dfe2708-0c13-4aa5-99bd-8a073d6efe70)

**System information**
### BrickStore 2023.5.1 (build: 1049)

* **brickstore.ldraw**: 26 Mar 2023 17:11:09 +0200
* **brickstore.locale**: nl
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930148)
* **build.date**: 2023-05-29T16:12:29.000
* **build.host**: fv-az171-567
* **build.number**: 1049
* **build.qt.version**: 6.5.1
* **hw.cpu**: 13th Gen Intel(R) Core(TM) i5-13600K
* **hw.cpu.arch**: x86_64
* **hw.gpu**: NVIDIA GeForce RTX 3060
* **hw.gpu.arch**: nvidia
* **hw.memory.gb**: 31.8
* **os.arch**: x86_64
* **os.productname**: Windows 10 Version 22H2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.5.1
* **windows.tabletmode**: false

**Comment by Leovaliant** [comment]
It has been happening to me too for a few days. Just came here to see if anyone else was having the problem.  I was going to update BrickStore, but I see you are running a later version than me and having the issue.  The database will not update.

### BrickStore 2023.4.4 (build: 1014)

* **brickstore.ldraw**: 15 Mar 2023 11:20:42 -0700
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930148)
* **build.date**: 2023-04-18T15:14:01.000
* **build.host**: fv-az1251-533
* **build.number**: 1014
* **build.qt.version**: 6.4.2
* **hw.cpu**: 12th Gen Intel(R) Core(TM) i9-12900K
* **hw.cpu.arch**: x86_64
* **hw.gpu**: NVIDIA GeForce RTX 3060 Ti
* **hw.gpu.arch**: nvidia
* **hw.memory.gb**: 63.7
* **os.arch**: x86_64
* **os.productname**: Windows 11 Version 22H2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.4.2
* **windows.tabletmode**: false

**Comment by froqzy** [comment]
I'm not sure whether the Database actually stopped updating or whether de pop-up simply stays active

**Comment by froqzy** [comment]
Thanks for the info/update. Regarding manual DB update: only unexpected behavior is that the animation doesn't stop in the pop-up after displaying "Already up-to-date". Very minor as long as the message "Already up-to-date" is actually correct.

**Comment by rgriebl** [comment]
Fixed in f4489245b932fa7ddbdb10d30ccace3416fa3da5
