### ISSUE TITLE
Fullstop not working on macbook pro ventura 13.2

### ISSUE THREAD

**Issue by grahamjcaisley** [rgriebl/brickstore#749]
**Describe the bug**
When trying to enter prices the fullstop key doesn't work at all

**To Reproduce**
1. Go to 'brickstore'
2. Click on 'price field'
3. Try to enter a price using full stop

**Expected behavior**
Full stop should be visible for prices 0.10, 0.50 etc, but just doesn't accept the fullstop

**Comment by loix623** [comment]
Yes, similar problem here. :/

I asked about it in Discussions...
