### ISSUE TITLE
Set to Price Guide

### ISSUE THREAD

**Issue by bjunited** [rgriebl/brickstore#75]
When trying to set the price guide to last 6 months average in a different currency to USD such as GBP or EUR it will only pull the USD price and not the GBP/EUR price even though this currency is selected in the configuration settings.

**Comment by paramecie** [comment]
The currency in settings becomes the currency of the document only when creating a new document (or importing if I remember well).

The one in your document is shown at the bottom right.
You've to change it if it's not the one you wish.

![image](https://user-images.githubusercontent.com/32078594/104148596-2e9a4880-53d3-11eb-825f-324977d18848.png)

When EUR set up (in this example), double clicking on the Avg price sets the correct Avg price in EUR.

Note: files before the 2020/21 BrickStore BSX files or BrickSTOCK files don't have a currency attribute. It means those will opened in the default currency (USD) - until you change this currency manually, and save them.

HTH?

**Comment by bjunited** [comment]
Hello,

I have just tried this, however for example when I part out a set a part shows as being £0.091 on BrickStore, whereas on bricklink it is actually £0.097, the whole part out was about 10-15% lower than what Bricklink said it was too. 

![image](https://user-images.githubusercontent.com/34009740/105084150-d8419f80-5a8d-11eb-8a07-f94265b609a2.png)
![image](https://user-images.githubusercontent.com/34009740/105084177-e2639e00-5a8d-11eb-8c36-31dd52aa7d2a.png)

**Comment by paramecie** [comment]
GBP? What's this?
:-)

Read #80 - it's probably unsolvable AFAIK, very sorry.

If you wish to sell fast, be under, very under the Avg, a few % won't make any difference.

If you've a precious lot, like because you're the one with a high qty compared to the other sellers, sell it over the Avg, slowly (if not, some seller will come and take the whole).

My 0.02 GBPs ;-)

**Comment by bjunited** [comment]
Hello,

This is GBP, if I just set it to USD and then I manually reduce it like I currently do on BrickStock should this fix the issue? Guessing the conversion rate is slightly wrong on BrickStore for some reason. I mainly price everything at average, and cutting my "selling" price by 10-15% is a significant portion of the profits lost if using this. Will give the way I do it with BrickStock a try and see if that helps, as I can't really use it if it will price everything way too cheap.
