### ISSUE TITLE
Can't add items

### ISSUE THREAD

**Issue by Ro8st3r** [rgriebl/brickstore#750]
Since last update:
When clicking on 1x1brick icom with green +, the Add Item pop up does not open. 
Also not when selecting via menu on top
Also not with keyboard shortcut.
New installation does not solve the issue

I use macOS Monterey 12.6.5
Apple MacBook Pro 2018 
Brickstore 2023.5.1(build 1049)

**Comment by KevinRaiss** [comment]
Same problem here:

when clicking on Button to add Item pop up does not open.

Used following specs:

Apple MacBook Pro 2019
macOS Ventura 13.4
Brickstore 2023.5.1(build 1049)

**Comment by Ro8st3r** [comment]
Solved with new update
