### ISSUE TITLE
issue with part numbers

### ISSUE THREAD

**Issue by magicbricksuk** [rgriebl/brickstore#753]
part numbers 30241b and 30241 have changed on Bricklink to new numbers and is creating issues with updating, copying values, and consolidation so need to be altered to the new part numbers on the brick store database

**Comment by rgriebl** [comment]
I guess this one slipped through the crack during my vacation.
The BrickStore DB is automatically regenerated from BrickLink data every night at 05:00 CET.
Just update the DB via the Tools menu and you should be good to go. BSX files will get auto adjusted on load to use the new item numbers.
If this is still a problem, please re-open the bug.
