### ISSUE TITLE
Missing search function on add item page

### ISSUE THREAD

**Issue by uvt203** [rgriebl/brickstore#77]
Old version had this feature next to the filter window.

**Comment by paramecie** [comment]
I has a search function, and contrary to the "old version" it's ULTRA fast - even showing pictures or thumbnails!

![image](https://user-images.githubusercontent.com/32078594/104216625-9637ae80-543a-11eb-8156-d6e6b124990e.png)

**Comment by uvt203** [comment]
OK thought it was the old filter window. But then I just tried to use it and it does not work here. I run on MAC OS 10.13.6 Safari and version 2021.1.3

**Comment by paramecie** [comment]
MAC OS you say? Reminds me another Issue ;-) Those both will be checked.

**Comment by uvt203** [comment]
Oh I just found out that the search function only works within the chosen category. To search the hole database you need to select 'All Items' as on your picture. This is new from the old version where the search function didn't rely on the catagory selected.

**Comment by paramecie** [comment]
Here "All" is selected by default when you open the Add window.

It's a focus problem - maybe related to your non-scroll problem, I don't know.

**Comment by uvt203** [comment]
I have now been using the search function a lot - and I must say after getting aquatinted with it - it works very well and is a major improvement to the programme. Thank you for that. 
I would recommend to close this issue then.

**Comment by ZZJHONS** [comment]
Before closing it I would like to have a button to search in all items if you are inside a category. That way you don't have to scroll up to all items and select it and then search...

**Comment by rgriebl** [comment]
You can also enable Regular Expressions in the magnifier glass menu: then you can really narrow down searches like `^3001$` (but you have to learn RegExps ;) )
@ZZJHONS makes sense, but please open a separate request

**Comment by ZZJHONS** [comment]
I did before that comment ;) #9
