### ISSUE TITLE
Enable use of LEGO SAP numbers next to Bricklink item numbers

### ISSUE THREAD

**Issue by froqzy** [rgriebl/brickstore#779]
LEGO increasingly uses their internal (often 7-digit) element (SAP) number to refer to a specific item with a specific colour, eg in their Pick-a-Brick interface on lego.com. If you type the element number into the Bricklink search field then you are directed to the right Bricklink item number and colour, but this is a manual two-step process on Bricklink that is a lot of work for handling large PAB-orders or part lists.

It would be awesome if it were possible to import LEGO element numbers directly into Brickstore instead of "translating" them piece by piece, or if it where possible to use the LEGO element number in the Brickstore search fielding when adding items.

I'm not sure whether this is accessible through the Bricklink API.

**Comment by rgriebl** [comment]
These numbers are called PCC (part color code) on BrickLink. The full database is here: https://www.bricklink.com/catalogDownload.asp
BrickLink supports them via the the "Add Items" dialog: click the 🔍 icon or press `Ctrl+E`

**Comment by froqzy** [comment]
Thanks a lot! I've always dowloaded the sets, minifigs and parts databases but never knew there was a proper translation table. Awesome!
