### ISSUE TITLE
Page not scrolling up when new items are added

### ISSUE THREAD

**Issue by uvt203** [rgriebl/brickstore#78]
When adding new items to a file using the pop up window 'add items to xxx' the file window is not scrolling when the page is full and new items are loaded. The old version did this.

**Comment by paramecie** [comment]
I does scroll here :-(

Did you use the latest version 2021.1.3?

**Comment by uvt203** [comment]
I run on MAC OS 10.13.6 Safari and version 2021.1.3 and it does not scroll.

**Comment by paramecie** [comment]
Then it's specific your system (or, at least not Microsoft's ones) - Robert will check this.

**Comment by rgriebl** [comment]
I think I finally know what happens on your machine: your screen is too small :) You probably don't even see the status bar in the main window? This just happened on our laptop when my wife turned up the font size and the side widgets (Info + PriceGuide + AppearsIn) couldn't fit into the window anymore.
Try to disable one of them and then resize/re-maximize the window.

**Comment by uvt203** [comment]
I use a 27" high resolution screen and can see both the status bar and the menu line so I guess that is not the problem.

**Comment by rgriebl** [comment]
That's weird - I have no idea what might be happening on your side then. I cannot reproduce this otherwise. (I don't have anything older than 10.15 to test against, but the code in question is totally platform independent)

**Comment by uvt203** [comment]
I have today received my new Mac Mini M1 with Big Sur. When up and running I'll try again to see if the error appears on that. St.by. it might take a day or two.

**Comment by ZZJHONS** [comment]
Any update on this?

This is happening to me too. When adding one item the file doesn't scrolls down.

**Comment by ZZJHONS** [comment]
Okay, I don't know how to reproduce but,

Adding 1 item scrolls the page, but adding another one doesn't scroll it again...

**Comment by ZZJHONS** [comment]
@rgriebl still not working in latest build (244)

It only works if you are scrolled at the bottommost, once you add 1 item the file scrolls a bit, but not enough to be at the bottommost, then any other additions don't scroll the file if you don't scroll manually to the end of the file.

<img width="1139" alt="Captura de pantalla 2021-01-27 175737" src="https://user-images.githubusercontent.com/1063368/106025701-4bb86200-60c9-11eb-9ee5-bca102e59f56.png">

**Comment by ZZJHONS** [comment]
@rgriebl this is still happening with latest Build 245, could you reopen this issue?

**Comment by rgriebl** [comment]
Only if you promise to attach a bsx with which I can reproduce this issue. Plus detailed instructions what else you did after a clean restart and loading the file to trigger the bug. 
I cannot reproduce this otherwise.

**Comment by rgriebl** [comment]
Just got an idea: you have disabled the "Index" column, right?

**Comment by ZZJHONS** [comment]
I do have it disabled yeah...

If I enable it, it scrolls the same distance as shown in the previous screenshot, but quickly auto scrolls correctly to the bottommost.

So only with Index enabled it works correctly...

**Comment by ZZJHONS** [comment]
I confirm this is working now perfectly!
