### ISSUE TITLE
Brickstore for android

### ISSUE THREAD

**Issue by newfie675** [rgriebl/brickstore#780]
I am using galaxy 23+ with the android version of the app. Every time i exit the app the default currency disappears and i have to remove Brickstore and reinstall it. It works for a single use then repeat the whole process again.
![Screenshot_20231011_145931](https://github.com/rgriebl/brickstore/assets/96376889/4e09f8b7-9000-4637-b47e-af301dbfbfb1)
Thanks

**Comment by mmally** [comment]
Same for me on my S21 FE and a Lenovo P11 tablet.

**Comment by rgriebl** [comment]
Fixed. Some Androids are very slow in reporting the online state and BrickStore was a bit too impatient
