### ISSUE TITLE
"Lock color selection" doesn't work with Category "Minifigure, Torso"

### ISSUE THREAD

**Issue by BrickStoreUser** [rgriebl/brickstore#782]
**Describe the bug**
A clear description of what the bug is.

"Lock color selection" not activate, BrickStore shows all the parts. By activating "Lock color selection" with any given color, the parts vanish.

**Expected behavior**

To create a part list, I like to sort the parts by color.

**System information**
Please tell us which system you are running on and which BrickStore version you are using.

BrickStore 2023.8.1 (build: 1059)
brickstore.ldraw: 05 Oct 2023 14:07:28 +0200
brickstore.locale: de
build.arch: x86_64
build.compiler: Microsoft Visual-C++2019 (192930151)
build.date: 2023-08-12T14:25:40.000
build.host: fv-az1237-625
build.number: 1059
build.qt.version: 6.5.2
hw.cpu: Intel(R) Core(TM) i5-2320 CPU @ 3.00GHz
hw.cpu.arch: x86_64
hw.gpu: Intel(R) HD Graphics
hw.gpu.arch: intel
hw.memory.gb: 7.9
os.arch: x86_64
os.productname: Windows 10 Version 22H2
qt.debug: false
qt.platformname: windows
qt.version: 6.5.2
windows.tabletmode: false

User error?!? I did check for BrickStore updates several times. Restarted the system, etc. On all other categories, BrickStore Color Selection works fine :)

**Comment by ZZJHONS** [comment]
Torsos have variable color on their inventories and also don't have PCC, maybe BrickStore DB can make a quirk and copy the known colors of the torso assemblies each torso appears in.

**Comment by BrickStoreUser** [comment]
Thank you for the informations! That's easy to understand. One more thing: The category "Minifigure, Torso Assembly, Decor." works fine with teh functin "Lock color selection" - maybe the quirk is already real?!?

Have a great day!
