### ISSUE TITLE
Cost property of Lot is not available in an extension script

### ISSUE THREAD

**Issue by mmally** [rgriebl/brickstore#784]
My goal is to transfer the buying price to the costs of an item for reselling and wanted to write a script.

For example this simple script returns "undefined" for the cost.

let current=thisDoc.lots.at(0)
console.log(current.cost)

**Comment by rgriebl** [comment]
This has been fixed for quite some time via db6d0e34676a7f17cbe751a9e9e4d28d678ad53a and it's in the latest release.
Forgot to close this bug report, as I confused it with another one.

**Comment by mmally** [comment]
I can now read the value, but not set it.

I had a quick lock at the changed code line 387:  `Q_PROPERTY(double cost READ cost)`
Should this not be `Q_PROPERTY(double cost READ cost WRITE setCost)` ??

By the way: Is there a way to get the current exchange rate e.g. USD to default currency EUR?

BR,
Michael
