### ISSUE TITLE
Issue importing new Studio files.

### ISSUE THREAD

**Issue by buildamoc** [rgriebl/brickstore#785]
Studio might have changed something on their latest update (today I believe), tha
![Captura de pantalla 2023-11-02 165738](https://github.com/rgriebl/brickstore/assets/149534875/b06ccaf5-3643-46b6-a0e5-b8d1e81c7b7d)
t broke the BS import. 

Attached is a screenshot of the error. Let me know if you need anything else to reproduce it. It only happens in newly saved items with the updated Studio.

**Comment by ZZJHONS** [comment]
They removed the password from the .io file saved after todays' update, Brickstore might need a mix method for opening old and new .io files

**Comment by buildamoc** [comment]
I would just update to the new method if it is easier. After all if you
want to import An older file just just open and re-save it.

**Comment by Brick-Top** [comment]
Appreciate the quick fix!
