### ISSUE TITLE
Passwords longer than 15 characters now allowed 

### ISSUE THREAD

**Issue by reni3008** [rgriebl/brickstore#787]
Bricklink now allows passwords with more than 15 characters, but Brickstore only accept max 15 characters

**Comment by rgriebl** [comment]
The FAQ says: 
_Will BrickLink be adding other account security like two-factor authentication and longer passwords?_

> At the moment, BrickLink hasn't updated our password requirements and does not support two-factor authentication. We'll continue to increase security on our platform and will communicate about any new security features as they become available.

So where do get that information from?
BTW: You could always type more than 15 characters into that password fields on BL, but only the first 15 are used.

**Comment by froqzy** [comment]
I had the same experience. I used a password > 15 chars on Bricklink yesterday and updated it in Brickstore. As a result Brickstore couldn't retrieve info from our Bricklink store anymore. If both (Bricklink and Brickstore) would have been truncated at 15 chars there wouldn't have been a problem. So I guess Bricklink does allow for more than 15 chars that are used. Changed the password back to 15 chars on Bricklink and both worked fine again. Not proof but it might be an undocumented change. Wouldn't be a first for Bricklink ;-)

**Comment by rgriebl** [comment]
It seems that > 15 are only possible via the new pw-reset mechanism the?. The classic way of changing your PW in the account info (*) is still limited to 15 chars (you cannot type in more)
So I'm not even sure how you managed to switch back from a > 15 char PW, as you couldn't even type that into the "Current Password" field

(*) https://www.bricklink.com/pref_general.asp?rD=Y

**Comment by froqzy** [comment]
That's very well possible, since I originally added a >15 char pwd during the pwd-reset mechanism. I switched back using the same pwd-reset mechanism. Oddly enough you can use those links more than once...
So probably this isn't an issue for Brickstore at all but more like a one-off thing.

**Comment by rgriebl** [comment]
https://www.bricklink.com/message.asp?ID=1438248

**Comment by rgriebl** [comment]
Closing, as the 15 char limit is still in place on BL.

That being said, you can enter a longer password in BrickStore and it will use it (that warning you get in the settings dalog is just FYI).

So what you have been running into is this: you reset your PW to something > 15 chars and the reset procedure let you input that. It did however only save the first 15 chars, so the "full" password in BrickStore didn't match.
If you had set the password to only the first 15 chars in BrickStore, it would have worked.

Ergo: that BrickStore warning about >15 char passwords was and still is doing its job perfectly fine
