### ISSUE TITLE
Import Bricklink Inventory window shrinks when moving main windo

### ISSUE THREAD

**Issue by mevitsbricks** [rgriebl/brickstore#789]
When moving the main brickstore window the "Import Bricklink Inventory" Window shrinks

See video:
https://app.screencast.com/tsNU9BzfOz4ZL

### BrickStore 2023.11.1 (build: 1086)

* **brickstore.ldraw**: 04 Oct 2023 15:13:38 -0500
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930152)
* **build.date**: 2023-11-06T12:13:08.000
* **build.host**: fv-az845-519
* **build.number**: 1086
* **build.qt.version**: 6.5.3
* **hw.cpu**: Intel(R) Xeon(R) CPU E3-1270 v3 @ 3.50GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: NVIDIA NVS 310
* **hw.gpu.arch**: nvidia
* **hw.memory.gb**: 31.9
* **os.arch**: x86_64
* **os.productname**: Windows 10 Version 22H2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.5.3
* **windows.tabletmode**: false

**Comment by rgriebl** [comment]
That's a really crazy bug :)
It's in the base Qt libraries though: https://bugreports.qt.io/browse/QTBUG-117779
The next Qt release (containing a fix for this) is planned for Nov 23rd.

**Comment by rgriebl** [comment]
This should finally be fixed for good with 2024.1.2. Please reopen if it occurs again.
