### ISSUE TITLE
Sale %off not working

### ISSUE THREAD

**Issue by BrickSouth** [rgriebl/brickstore#79]
I added a part with a percentage off sale applied, but the sale was still at 0 after importing into Bricklink.

**Comment by paramecie** [comment]
You set a sale on a new document, or an imported store?
You uploaded using mass upload or mass update?

**Comment by BrickSouth** [comment]
Nevermind...I was trying to do it with a mass update and just remembered that mass update will only update the price. Adding a sale works fine if you are uploading. It would be nice if mass update changed stuff other than price, though...

**Comment by paramecie** [comment]
You're right - see an push #68, same problem ;-)
