### ISSUE TITLE
.11 update the camera interface open delayed

### ISSUE THREAD

**Issue by GreatBrickLab** [rgriebl/brickstore#792]
**Describe the bug**
The time to open the camera window to identify parts has a minor delay to open with both the new .11 versions

**To Reproduce**
1. Go to add items window
2. Click on camera icon or Ctrl+D
3. The windows has a 1-2 sec delay to open.  

**Expected behavior**
In previous versions,  the window opened much faster.   This is only a minor inconvenience.   However it has slowed my rate to process parts.

**Comment by rgriebl** [comment]
This seems to be heavily system/driver dependent: macOS and Linux have little to no delay for me, but my Windows machine has a 600msec delay just to detect the single webcam that's attached it.

**Comment by rgriebl** [comment]
GitHub had a few problems yesterday, so it took a while to get a test build:
https://github.com/rgriebl/brickstore/actions/runs/6877396901
Could you please install this one and test if it works correctly on your machine? (there should only be a delay the first time you click on the camera icon)

**Comment by GreatBrickLab** [comment]
Confirmed that the first click delayed some,  then after that the window
opened right away.   Tested for 1 min and was fast.

Closed Brickstore and again the first was slow and after that was a quick
open window.

If there was a way to pin the camera window open permanently that would be
great (or something to try)    Then I would have one less click,  to id the
parts.

Thank you!

CJ

**Comment by GreatBrickLab** [comment]
To add a little bit more what I mean about keeping the camera window open,
with a pin or maybe it could be a part of the add items window that is
pinned open,   since I open that for every part,  that would speed up the
cataloging even more.

Thank you again
Chris

**Comment by GreatBrickLab** [comment]
Last week this was working great.  Today I am getting inconsistent
crashes.   The camera app operates the same,  600ms delay first open then
after that no delay.   However it has been crashing.   I was using it for
an hour fine,  then could not keep it open for even two minutes.

**Comment by rgriebl** [comment]
Which build are you on? You need at least 1100. If you are not, just click "Actions" at the top, then pick the latest build (should be 1101 right now)

**Comment by GreatBrickLab** [comment]
1099

**Comment by GreatBrickLab** [comment]
Installed  build 1101,  I will test later.  Thanks!   I will test later. I
need to get a battery for the minivan!

Chirs

**Comment by GreatBrickLab** [comment]
The 1101 build is stable for about 2.5 hours at this point.   I am also
using the PIN on the Item Scanner,  it works fine.   I can understand that
keeping a constant video feed may not be a good idea and also from my
testing not a must.  I am working fine in this build.   I do suggest that a
key board shortcut be allowed for the click of the part from the mouse.
 Since the workflow to add parts is changing with this I noticed I am using
the key board to add parts +1+1+1+1+1 to the count.

Thank you for adding that so quickly.

CJ

**Comment by rgriebl** [comment]
I had to rewrite the camera interface again, as there were multiple problems on macOS as well...

Could you please test the current dev build here and let me know if it works now?
https://github.com/rgriebl/brickstore/actions/runs/7455383752
(you have to be logged into Github to download)
