### ISSUE TITLE
Two monitors and a menu problem

### ISSUE THREAD

**Issue by judamPL** [rgriebl/brickstore#794]
If there are two monitors then the menu opens in monitor 1. The program opens in monitor 2 and the menu always in monitor 1.

The problem used to occur in older versions. In 2023.11.1 it was fine and again in 2023.11.2 there is a problem

**Comment by rgriebl** [comment]
That's an unfortunate collateral damage, trying to get around #789 
I had to revert to an older Qt version that apparently still has the multi-screen menu bug. Qt 6.6.1 is scheduled to release on Nov 29th, so hopefully this has fixes for both problems.

**Comment by rgriebl** [comment]
This should finally be fixed for good with 2024.1.2. Please reopen if it occurs again.
