### ISSUE TITLE
Show PCC somewhere

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#796]
When you have a list of parts it would be great to know and be able to copy the PCCs so you can search in some other databases like Lego or Brickset.

Having them in the info tab would be great, as a column they would be weird as there can be multiple for each color.

<img width="363" alt="image" src="https://github.com/rgriebl/brickstore/assets/1063368/f0d601f1-55af-4346-b4aa-3b99d1227965">

**Comment by ranksterbricks** [comment]
That would be really great, it would speed up the uploading process a lot!

**Comment by ranksterbricks** [comment]
The ability of searcing by PCC would be also really great, it would speed up the uploading process a lot.

**Comment by ZZJHONS** [comment]
> The ability of searching by PCC would be also really great, it would speed up the uploading process a lot.

It is already possible: https://github.com/rgriebl/brickstore/issues/779#issuecomment-1758097755

But indeed it would be easier for users if it just worked in the default search input.

**Comment by ranksterbricks** [comment]
Great, thanks for letting me know!

**Comment by rgriebl** [comment]
Showing all possible PCCs if no color is selected might get a bit crowded :wink:

![image](https://github.com/rgriebl/brickstore/assets/3710520/08ff2462-f59e-4638-b7f4-9a5b719ed1f2)

**Comment by ZZJHONS** [comment]
Wow nice to see them! That one part should be one with the most PCCs, maybe a button to toggle showing them or not down there with the image ones.

PD: 2D shows an error image for N/A maybe the 3d one should show something also over the part rendered?

**Comment by rgriebl** [comment]
How about this for "no color" / "not applicable"?
![image](https://github.com/rgriebl/brickstore/assets/3710520/87737422-dacf-4b41-a55b-e806d7f1f5b8)

**Comment by ZZJHONS** [comment]
Seems a good solution!

**Comment by rgriebl** [comment]
Implemented in 2024.1.2
