### ISSUE TITLE
Camera shows white

### ISSUE THREAD

**Issue by ChristianGrieger** [rgriebl/brickstore#798]
I have now tried the internal MAC camera, a document camera and also the iPhone camera and I get strange white areas on everything I want to scan. If I go directly to https://brickognize.com/ all 3 cameras work without any problems. Is there a solution for this?

<img width="654" alt="Bildschirmfoto 2023-11-29 um 17 33 27" src="https://github.com/rgriebl/brickstore/assets/8712219/b6185d43-7b2f-4c02-bf0e-de16a1a04741">
<img width="406" alt="Bildschirmfoto 2023-11-29 um 17 34 07" src="https://github.com/rgriebl/brickstore/assets/8712219/91535f2d-078b-4adc-bc7b-aff12688cac7">

**Comment by rgriebl** [comment]
This works perfectly fine for me.
Please add more information: run BrickStore, go to Help -> Systeminformation, copy to clipboard and paste the info here.

**Comment by ChristianGrieger** [comment]
```
### BrickStore 2023.11.2 (build: 1093)

* **brickstore.ldraw**: 16 Nov 2023 09:27:59 +0100
* **brickstore.locale**: de
* **build.arch**: x86_64
* **build.compiler**: clang 14.0.0 (clang-1400.0.29.202)
* **build.date**: 2023-11-14T02:05:41.000
* **build.host**: Mac-1699926684847.local
* **build.number**: 1093
* **build.qt.version**: 6.5.2
* **hw.cpu**: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: Intel UHD Graphics 630
* **hw.gpu.arch**: Intel
* **hw.memory.gb**: 16.0
* **os.arch**: x86_64
* **os.productname**: macOS 14.1
* **qt.debug**: false
* **qt.platformname**: cocoa
* **qt.version**: 6.5.2

```

**Comment by RedWolves** [comment]
I am having the exact same issue.  

### BrickStore 2023.11.2 (build: 1093)

* **brickstore.ldraw**: 14 Nov 2023 09:55:40 -0500
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: clang 14.0.0 (clang-1400.0.29.202)
* **build.date**: 2023-11-14T02:07:40.000
* **build.host**: Mac-1699925540123.local
* **build.number**: 1093
* **build.qt.version**: 6.4.3
* **hw.cpu**: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: Intel HD Graphics 630
* **hw.gpu.arch**: Intel
* **hw.memory.gb**: 16.0
* **os.arch**: x86_64
* **os.productname**: macOS 13.6
* **qt.debug**: false
* **qt.platformname**: cocoa
* **qt.version**: 6.4.3

**Comment by RedWolves** [comment]
Similar bug report over at qt.io https://bugreports.qt.io/browse/QTBUG-119834

**Comment by rgriebl** [comment]
Could you please test the current dev build here and let me know if it works now?
https://github.com/rgriebl/brickstore/actions/runs/7455383752
(you have to be logged into Github to download)
