### ISSUE TITLE
Part 3729 Plate, Modified 2 x 2 with Tow Ball is not recognized

### ISSUE THREAD

**Issue by AccidentalSith** [rgriebl/brickstore#799]
**Describe the bug**

Part 3729 Plate, Modified 2 x 2 with Tow Ball is not recognized within BrickStore.  When importing my store inventory BrickStore tells me the part is unrecognized.  When attempting to add it as a new part it cannot be found by typing/searching for 3729.  Browsing the catalogue by category to Plate, Modified and searching for "Tow ball" will reveal this part but it is numbered as 3731 which is wrong according to BrickLink.

Screenshot below.

I believe my copy of BrickStore and database are up to date.  Is anyone else experiencing this problem or just me?

Thanks.

**System information**
### BrickStore 2023.11.2 (build: 1093)

* **brickstore.ldraw**: 30 Nov 2023 18:58:53 +0000
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930152)
* **build.date**: 2023-11-14T02:11:09.000
* **build.host**: fv-az1457-229
* **build.number**: 1093
* **build.qt.version**: 6.5.2
* **hw.cpu**: AMD Ryzen 7 4700U with Radeon Graphics
* **hw.cpu.arch**: x86_64
* **hw.gpu**: AMD Radeon(TM) Graphics
* **hw.gpu.arch**: amd
* **hw.memory.gb**: 15.4
* **os.arch**: x86_64
* **os.productname**: Windows 11 Version 22H2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.5.2
* **windows.tabletmode**: false

![Screenshot 2023-11-30 224718](https://github.com/rgriebl/brickstore/assets/100717543/f3811198-996f-47cf-a9f9-f1857da9fbee)

**Comment by rgriebl** [comment]
This item was renamed on BL, but BrickStore's database update was stuck for the last 4 days and didn't pick up that rename. Fixed now, just update the database.
