### ISSUE TITLE
Windows Defender flags BrickStore.exe as Trojan

### ISSUE THREAD

**Issue by Nouvilas** [rgriebl/brickstore#801]
**Describe the bug**
After installing the latest update and trying to launch BrickStore, Windows Defender (Windows 10 Home) gave a pop-up saying it detected a Trojan:Win32/Convagent!pz virus in:
file: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\BrickStore.lnk
file: <Install directory>\BrickStore\BrickStore.exe
regkey: HKLM\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\UNINSTALL\BrickStore_is1
startup: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\BrickStore.lnk
uninstall: HKLM\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\UNINSTALL\BrickStore_is1

**To Reproduce**
1. Update BrickStore to latest version
2. Launch Brickstore through start menu link

**Expected behavior**
BrickStore should not contain a trojan virus and Windows Defender should not flag it as such if it doesn't

**System information**
Windows 10 Home

**Comment by rgriebl** [comment]
The download from Github here https://github.com/rgriebl/brickstore/releases/tag/v2023.11.2 is clean: it's built on Microsoft servers, using Microsoft tools. It works for me in Window 10 Pro without Defender complaining.
If you got it from here, then maybe your machine/network has problems? Check your BrickStore installer download on https://virustotal.com

That being said: I can't do anything about it, if Microsoft (or any other AV vendor) incorrectly flags BrickStore as malicious. There's no way to appeal such a decision, unless you are a big corporation.
The only way to use BrickStore in this case, is to make sure virustotal says it's clean and then add an exception to your AV program.
