### ISSUE TITLE
Code 0x80070005

### ISSUE THREAD

**Issue by TheLittleBrickShop** [rgriebl/brickstore#803]
**Describe the bug**
I seem to have this issue every time there is an update. It results in me having to re download the program from scratch.
When you initially install BrickStore, you have to run it as an administrator and it installs just fine. BrickStore occasionally has updates. These pop up as a notification with the option to install. It doesn't give me the option to run the install as an administrator so always comes up with an error message meaning the installation/update is never successful. It removes the BrickStore shortcut from my desktop and is impossible to then find the program when searching for it. What can I do to prevent this from happening and authorising the updates as an administrator?

**Screenshots**
![20240110_093629](https://github.com/rgriebl/brickstore/assets/156410894/3eec5067-2d07-462d-ad27-95b190d8c7a4)

**System information**
### BrickStore 2024.1.2 (build: 1143)

* **brickstore.ldraw**: 11 Oct 2023 16:27:45 +0100
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930153)
* **build.date**: 2024-01-11T21:19:23.000
* **build.host**: fv-az662-930
* **build.number**: 1143
* **build.qt.version**: 6.6.1
* **hw.cpu**: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: Intel(R) UHD Graphics 620
* **hw.gpu.arch**: intel
* **hw.memory.gb**: 7.9
* **os.arch**: x86_64
* **os.productname**: Windows 11 Version 22H2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.6.1
* **windows.tabletmode**: false

**Additional context**
You can also attach BSX files, but GitHub only accepts these if added to a ZIP file first.

**Comment by rgriebl** [comment]
Your windows installation is broken and the installer cannot create an entry in the start menu.
There is nothing I can do on BrickStore's side to fix or circumvent that.
Short of reinstalling Windows, your best bet is to google for `IPersistFile::Save failed  0x80070005` and see what comes up.

**Comment by rgriebl** [comment]
Also: "When you initially install BrickStore, you have to run it as an administrator and it installs just fine. "
Why do you have to run it as admin?

**Comment by TheLittleBrickShop** [comment]
Thanks for you quick reply. 
Having Googled it as you suggested, I think it may be the anti virus software creating the 'save failed' error.
The running right click and 'running as an administrator'. that's actually in your installation instructions :)
<img width="946" alt="image" src="https://github.com/rgriebl/brickstore/assets/156410894/50b1a6c4-8e50-41e2-b746-fe7c3a9eeabb">

**Comment by rgriebl** [comment]
It's in the instructions, but with the caveat "this shouldn't happen" :)
I think the IPersist failure when installing updates is just a result of installing BrickStore as admin in the first place (the start menu entry is created with admin privileges, so the normal updater is not allowed to overwrite it).
The actual real problem on your machine is the need to install BS as admin in the first place. I can't help you with that, as I cannot reproduce it. I just had a few bug reports over the years and that's why I added that paragraph to the installation instructions.
Please let me know if you can figure something out!

**Comment by TheLittleBrickShop** [comment]
If I don't use the option to run as an administrator, these are the various warnings I get until the fatal Save Fail :)
<img width="344" alt="Error 1" src="https://github.com/rgriebl/brickstore/assets/156410894/87b0c3ca-04c6-4d1c-856c-aeaf4dab5424">
<img width="401" alt="Error 2" src="https://github.com/rgriebl/brickstore/assets/156410894/a57af0f2-7509-4723-812c-9ed985185052">
<img width="401" alt="Error 3" src="https://github.com/rgriebl/brickstore/assets/156410894/78d13b84-9997-412a-a5b0-f2a4ee3933f8">
<img width="478" alt="Error 4" src="https://github.com/rgriebl/brickstore/assets/156410894/f0b6db75-3ff9-43f6-90e5-63e6253a14c7">
<img width="375" alt="Error 5" src="https://github.com/rgriebl/brickstore/assets/156410894/75821b24-db1e-419c-9fb6-a628a61a6fc8">
