### ISSUE TITLE
Legacy database

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#804]
Bricklink just announced that on Feb 1st a major merge/change is going to happen:

https://www.bricklink.com/messageThread.asp?ID=352477&nID=1447090

A lot of data will be lost regarding variants and stud types, like merging all Hollow, Blocked and Vented stud heads.

So will it be possible a setting in BrickStore to use a Legacy version of the database from the end of January 2024 so collectors in the future have a place to check all this data?

I know it is a long shot, but here we are...

Thanks.

**Comment by rgriebl** [comment]
I personally am happy that these pointless variants are gone.

Bit, if you want to preserve the DB, then you have to make a copy first:
`%LOCALAPPDATA%\BrickStore\cache\database-v11`
I don't keep any backups as those files are regenerated every day.

The second part would be to patch BrickStore to NOT use the upstream DB, but a local file. How would that work UI-wise? You probably want to switch back and forth between the 2?

**Comment by rgriebl** [comment]
And another thing: any BrickStore version can write old formats, but it can only ever read the current DB version (11 right now). So even if you copy the current DB, you may not be able to load that in a future BrickStore version, if I have to bump the DB version (new feature, bug fix, ...)

**Comment by ZZJHONS** [comment]
After thinking it a bit more I think this couldn't work per se, it would need a wiki page explaining it with the DB file attached and the latest working Brickstore installer for it.

On the current distribution maybe a view only dialog like the add item one to browse the catalog (old DB) that you can navigate similarly. But the affected items would be without images.

Maybe someone else has any better idea to not lose this data, it doesn't need to be usable, as Bricklink will keep evolving and with it Brickstore, just viewable.

**Comment by rgriebl** [comment]
I'm closing this now as the changes are already being rolled in tiny bits daily on BrickLink.
