### ISSUE TITLE
BrickStore Version 2024.1.2 (build: 1143) Crashes on mac OS Ventura (13.6.3)

### ISSUE THREAD

**Issue by jmkiska** [rgriebl/brickstore#809]
**Describe the bug**

I downloaded and installed “macOS-BrickStore-2024.1.2.dmg” on my MacBook Pro running macOS Ventura (13.6.3).  The app launches fine, but when I try to open the “Preferences” or add a file the program immediately crashes.

**System information**

### BrickStore 2024.1.2 (build: 1143)

* **brickstore.ldraw**:
* **brickstore.locale**: en
* **build.arch**: arm64
* **build.compiler**: clang 14.0.3 (clang-1403.0.22.14.1)
* **build.date**: 2024-01-11T21:23:36.000
* **build.host**: Mac-1705006183365.local
* **build.number**: 1143
* **build.qt.version**: 6.6.1
* **hw.cpu**: Apple M2 Pro
* **hw.cpu.arch**: arm64
* **hw.gpu**: Apple M2 Pro
* **hw.gpu.arch**: sppci_vendor_Apple
* **hw.memory.gb**: 16.0
* **os.arch**: arm64
* **os.productname**: macOS Ventura (13.6)
* **qt.debug**: false
* **qt.platformname**: cocoa
* **qt.version**: 6.6.1

**Comment by jmkiska** [comment]
﻿Hello,I see you closed my issue but I don’t see a response to solve my issue.  Is there any fix for BrickStore crashing on my MacBook Pro?Any help would be greatly appreciated. Thank you in advance for your time and consideration. Regards,JohnSent from my iPadOn Jan 14, 2024, at 3:03 PM, rgriebl ***@***.***> wrote:﻿
Closed #809 as completed via 824cdeb.

**Comment by rgriebl** [comment]
As always, the latest development snapshot build is available here:
https://github.com/rgriebl/brickstore/actions/workflows/build_cmake.yml

(also documented here: https://www.brickstore.dev/download)

I'll do an official bug fix release in a few days - there is another weird crash on macOS on shutdown that I cannot reproduce yet.

**Comment by jmkiska** [comment]
Thanks for getting back to me.  I’ll watch for the bug fix release. Regards,JohnSent from my iPadOn Jan 14, 2024, at 6:20 PM, rgriebl ***@***.***> wrote:﻿
As always, the latest development snapshot build is available here:
https://github.com/rgriebl/brickstore/actions/workflows/build_cmake.yml
(also documented here: https://www.brickstore.dev/download)
I'll do an official bug fix release in a few days - there is another weird crash on macOS on shutdown that I cannot reproduce yet.

**Comment by jmkiska** [comment]
Hello,

I posted Issue #839 earlier today as follows:

Describe the bug
Downloaded and installed version 2024.2.1. It crashes when I try to open it.

System information
macOs Big Sur
Version 11.7.10
Mac min (2018)
Processor GHz 6-Core Intel Core i7
Memory 16 GB 2667 MHz DDR4
Graphics Intel UHD Graphics 630 1536 MB

This morning I attached the Apple crash report in a file named "Brickstore 2024.2.1 Crash Report” (attached below).  I then found the file "BrickStore_2024-02-17-113010_Johns-Mac-mini.crash” which is attached below as well.

I reinstalled v2024.1.4.  It opens, but is acting strange.  I cannot open the Preferences. And when I try to close a file it crashes.

Please advise.

Thanks.

John

John Kiska
***@***.***
