### ISSUE TITLE
v2024.1.3 build 1157 - black camera preview on macOS

### ISSUE THREAD

**Issue by adbertram** [rgriebl/brickstore#817]
I just updated and now when I click on the Camera icon to bring up the Brickognize box, the camera box is black regardless of the camera I choose. I see the light come on like BrickStore is accessing it but I get nothing in the preview box and clicking it, does nothing.

**Comment by mmally** [comment]
it is the same on Windows. Regardless of the selected camera the preview remains black.
Reverting back to 2024.1.2 and the preview works again.
