### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [rgriebl/brickstore#820]
https://hosted.weblate.org/projects/brickstore/#information says GPLv3-only,
when
https://github.com/search?q=repo%3Argriebl%2Fbrickstore%20any%20later&type=code
is GPLv3-or-later.

I think it should all be GPLv3-or-later, which is clearly compatible now and for the future.

It can be changed in

https://hosted.weblate.org/projects/settings/translations/
and
https://hosted.weblate.org/projects/settings/glossary/

:)

**Comment by rgriebl** [comment]
Just grepping through the repo will loose any context..
1. The LICENSE file is a 1:1 copy of the GPL3
2. README.md clarifies this to be GPL3-only for this project, with the exception of a few 3rd-party files that are explicitly listed (that's exactly how the setup should be done according to GitHub guidelines)
3. The modified copies of Qt5 files are multi-licensed and in this case they are incorporated into a GPL3-only project. That doesn't give me the freedom to remove the full (c) header though.

And no - picking GPL3-only is not an oversight, but a conscious decision.

Closing as invalid.
