### ISSUE TITLE
Appimage segfaults on webcam opening

### ISSUE THREAD

**Issue by netforce** [rgriebl/brickstore#821]
**Describe the bug**
Brickstore Appimage 2024.1.4 and 2024.1.3  segfaults when opening 'find a part via webcam'

**To Reproduce**
1. start normaly
2.add new items
4. click 'find item via webcam'

**System information**
### BrickStore 2024.1.4 (build: 1160)

* **brickstore.ldraw**: 23 Jan 2024 22:02:58 +0100
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: GCC 10.5.0
* **build.date**: 2024-01-21T13:15:13.000
* **build.host**: fv-az1270-388
* **build.number**: 1160
* **build.qt.version**: 6.6.1
* **hw.cpu**: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: GP107M [GeForce GTX 1050 Mobile]
* **hw.gpu.arch**: nvidia
* **hw.memory.gb**: 15.5
* **os.arch**: x86_64
* **os.productname**: Ubuntu 22.04.3 LTS
* **qt.debug**: false
* **qt.platformname**: xcb
* **qt.version**: 6.6.1

**Additional context**
➜  Downloads /usr/bin/Linux-AppImage-BrickStore-2024.1.4-x86_64.AppImage 
Failed to load BrickLink password: "libsecret: unexpected content type: text/plain" (at /home/runner/work/brickstore/brickstore/src/common/config.cpp, 63)
Failed to load QNetworkInformation's default backend (at /home/runner/work/brickstore/brickstore/src/common/onlinestate.cpp, 30)
Could not load cookies for "BrickLink" : "libsecret: unexpected content type: text/plain" (at /home/runner/work/brickstore/brickstore/src/utility/persistentcookiejar.cpp, 33)
Using BrickLink price-guide retriever plugin: "Batched Affiliate API"
Picture cache: 4.0 GB
Currently active BrickLink API quirks:
  OrderQtyHasComma
  OrderXmlHasUnescapedFields
  InventoryCommentsAreDoubleEscaped
  InventoryRemarksAreDoubleEscaped
Importing orders from old cache: 0s 000ms 073us
Loading orders: 0s 000ms 000us
Loading database: 0s 140ms 453us
Loaded database from /home/eelco/.cache/BrickStore/database-v11
  Generated at : 23 Jan 2024 04:01:33 +0000
  Changelog Id : 380964
    Items      :     37 998
    Colors     :          1
  Relationships:         21
    Matches    :     12 279
  Item Types   :          8
  Categories   :      1 091
  Colors       :        209
  LDraw Colors :         54
  PCCs         :          0
  Items        :    177 834
UI:
  Device pixel ratio: 1 / Qt::HighDpiScaleFactorRoundingPolicy::PassThrough
  Screen size in pix: 1920 x 1080
  Screen size in mm : 344 x 194
script: Loading scripts from directory: "/home/eelco/.local/share/BrickStore/extensions"
script:   [ ok ] classic-print-script.bs.qml
Reading ZIP directory: 0s 057ms 716us
Found LDraw at /home/eelco/.cache/BrickStore/ldraw/complete.zip 
  Last updated: 23 Jan 2024 22:02:58 +0100
qt.multimedia.ffmpeg.libsymbolsresolver: Couldn't load VAAPI library (at unknown, 0)
qrc:/Scanner/CameraPreview.qml:2:1: module "QtMultimedia" is not installed 
     import QtMultimedia 
     ^ (at qrc:/Scanner/CameraPreview.qml, 2)
qt.core.qobject.connect: QObject::connect: Cannot connect (nullptr)::clicked() to CameraPreviewWidget::clicked() (at unknown, 0)
[1]    1380967 segmentation fault (core dumped)  /usr/bin/Linux-AppImage-BrickStore-2024.1.4-x86_64.AppImage

libqt6multimedia6 is already the newest version (6.2.4-1).

**Comment by rgriebl** [comment]
Could you please test build 1164 from here? https://github.com/rgriebl/brickstore/actions/runs/7641520996

**Comment by netforce** [comment]
that seems to work, no crashes, a lot of "Brickonize returned an invalid status code: 429" errors the first run, but that seems to have vanished after a restart.

Reason for error 429:
```
Invalid texture upload for 0x7ff318026b90 layer=0 mip=0 (at unknown, 0)

```

 Still the error below. But for now it seems stable.
```
Found LDraw at /home/eelco/.cache/BrickStore/ldraw/complete.zip 
  Last updated: 23 Jan 2024 22:02:58 +0100
Cannot resolve symbol vaSyncBuffer (at unknown, 0)
qt.multimedia.ffmpeg.libsymbolsresolver: Couldn't resolve VAAPI symbols (at unknown, 0)
```

full run log for complete story
```
➜  appimage ./BrickStore-2024.1.4-x86_64.AppImage
Failed to load BrickLink password: "libsecret: unexpected content type: text/plain" (at /home/runner/work/brickstore/brickstore/src/common/config.cpp, 63)
Failed to load QNetworkInformation's default backend (at /home/runner/work/brickstore/brickstore/src/common/onlinestate.cpp, 30)
Could not load cookies for "BrickLink" : "libsecret: unexpected content type: text/plain" (at /home/runner/work/brickstore/brickstore/src/utility/persistentcookiejar.cpp, 33)
Using BrickLink price-guide retriever plugin: "Batched Affiliate API"
Picture cache: 4.0 GB
Currently active BrickLink API quirks:
  OrderQtyHasComma
  OrderXmlHasUnescapedFields
  InventoryCommentsAreDoubleEscaped
  InventoryRemarksAreDoubleEscaped
Importing orders from old cache: 0s 000ms 041us
Loading orders: 0s 000ms 000us
Loading database: 0s 124ms 399us
Loaded database from /home/eelco/.cache/BrickStore/database-v11
  Generated at : 23 Jan 2024 04:01:33 +0000
  Changelog Id : 380964
    Items      :     37 998
    Colors     :          1
  Relationships:         21
    Matches    :     12 279
  Item Types   :          8
  Categories   :      1 091
  Colors       :        209
  LDraw Colors :         54
  PCCs         :          0
  Items        :    177 834
UI:
  Device pixel ratio: 1 / Qt::HighDpiScaleFactorRoundingPolicy::PassThrough
  Screen size in pix: 1920 x 1080
  Screen size in mm : 344 x 194
script: Loading scripts from directory: "/home/eelco/.local/share/BrickStore/extensions"
script:   [ ok ] classic-print-script.bs.qml
Reading ZIP directory: 0s 039ms 214us
Found LDraw at /home/eelco/.cache/BrickStore/ldraw/complete.zip 
  Last updated: 23 Jan 2024 22:02:58 +0100
Cannot resolve symbol vaSyncBuffer (at unknown, 0)
qt.multimedia.ffmpeg.libsymbolsresolver: Couldn't resolve VAAPI symbols (at unknown, 0)
scanner: Match: P "4349"  Score: 0.849871
scanner: Match: P "39144"  Score: 0.683506
scanner: Match: P "93080c"  Score: 0.610414
scanner: Match: P "x383"  Score: 0.529133
scanner: Match: P "6246f"  Score: 0.510449
scanner: Match: P "3963"  Score: 0.505688
scanner: Match: P "sc002"  Score: 0.461106

```

**Comment by netforce** [comment]
Donation done for the speedy fix!

**Comment by rgriebl** [comment]
I have the same missing symbol on my side, but it doesn't seem to affect the preview.
Closing for now. Please re-open in case there are more problems.
