### ISSUE TITLE
M2 Macbook Air camera issue

### ISSUE THREAD

**Issue by zebrasbricks** [rgriebl/brickstore#822]
**Describe the bug**
After looking up items on brickognize with the iphone's camera the laptop's camera will turn on and stay on, even if Brickstore is minimized in the background

**To Reproduce**
1. Go to 'Find a part using a webcam'
2. Click on 'iphone camera'
3. Close the camera feature
4. wait a few minutes, minimize Brickstore, you can even close the laptop's lid. When you open the lid again, you will see error: your laptop's camera is on

**Expected behavior**

**Screenshots**

**System information**
Please tell us which system you are running on and which BrickStore version you are using.
In BrickStore, just open `Help` > `System information...`, Click `Copy to clipboard` and then paste  here.
Model Name:	MacBook Air
  Model Identifier:	Mac14,2
  Model Number:	MLY33LL/A
  Chip:	Apple M2
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	8 GB
  System Firmware Version:	10151.81.1
  OS Loader Version:	10151.81.1

### BrickStore 2024.1.4 (build: 1160)

* **brickstore.ldraw**: 17 Oct 2023 12:57:22 -0700
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: clang 14.0.0 (clang-1400.0.29.202)
* **build.date**: 2024-01-21T13:15:56.000
* **build.host**: Mac-1705840749470.local
* **build.number**: 1160
* **build.qt.version**: 6.4.3
* **hw.cpu**: Apple M2
* **hw.cpu.arch**: x86_64
* **hw.gpu**: Apple M2
* **hw.gpu.arch**: sppci_vendor_Apple
* **hw.memory.gb**: 8.0
* **os.arch**: x86_64
* **os.productname**: macOS 14.3
* **qt.debug**: false
* **qt.platformname**: cocoa
* **qt.version**: 6.4.3

**Additional context**
You can also attach BSX files, but GitHub only accepts these if added to a ZIP file first.

**Comment by rgriebl** [comment]
Works as expected on the exact same laptop over here:
- The camera is stopped instantly when closing the camera preview dialog.
- The camera is stopped after 10sec if the camera preview dialog is pinned and the dialog looses focus (this includes switching to a different app)

BUT: you are using the "legacy" version of BrickStore that should only be used on macOS 10.14 / 10.15 and this one has a few issues with webcams. (this might have been the result of a buggy auto-update in the past) 

Can you please re-install the "normal" version and check again?

**Comment by zebrasbricks** [comment]
> Works as expected on the exact same laptop over here:
> 
>     * The camera is stopped instantly when closing the camera preview dialog.
> 
>     * The camera is stopped after 10sec if the camera preview dialog is pinned and the dialog looses focus (this includes switching to a different app)
> 
> 
> BUT: you are using the "legacy" version of BrickStore that should only be used on macOS 10.14 / 10.15 and this one has a few issues with webcams. (this might have been the result of a buggy auto-update in the past)
> 
> Can you please re-install the "normal" version and check again?

My apologies, I wasn't aware I'm on the legacy version.
I've updated to the regular version and will report back if there's any more issues

**Comment by rgriebl** [comment]
No need to apologize ... like I said: there was a bug in the auto-update that sometimes downloaded the wrong version.

**Comment by rgriebl** [comment]
Closing now, as there were no more reports of the camera not working
