### ISSUE TITLE
Mic button 

### ISSUE THREAD

**Issue by Jeremy-Back2BackBrix** [rgriebl/brickstore#824]
**Is your feature request related to a problem? Please describe.**
A clear description of what the problem is. Ex. I'm always frustrated when [...] I have to type. 

**Describe the solution you'd like**
A clear description of what you want to happen.

I want to hit a button and speak on lines of importance such as comments.

**Describe alternatives you've considered**
A clear description of any alternative solutions or features you've considered.
I haven't found any. 

**Additional context**

**Comment by rgriebl** [comment]
Use the text-to-speech accessibility feature of your operating system then. This is not something that will be solved on a per-application level.
