### ISSUE TITLE
Databases aren't downloading

### ISSUE THREAD

**Issue by mevitsbricks** [rgriebl/brickstore#827]
I have installed the latest version 2024.1.2.  After installation I get the following windows popping up:
![brickstore](https://github.com/rgriebl/brickstore/assets/91765501/a2f84645-e54d-4d2d-ad08-9119592f3a27)
![brickstore2](https://github.com/rgriebl/brickstore/assets/91765501/03ab42fe-81ff-4750-87ff-2d7e0c8778a4)

After the installation and startup of the app these messages pop up. I can't go any further. 

Sys Info:
### BrickStore 2024.1.2 (build: 1143)

* **brickstore.ldraw**:
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930153)
* **build.date**: 2024-01-11T21:19:23.000
* **build.host**: fv-az662-930
* **build.number**: 1143
* **build.qt.version**: 6.6.1
* **hw.cpu**: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: Intel(R) HD Graphics 520
* **hw.gpu.arch**: intel
* **hw.memory.gb**: 15.9
* **os.arch**: x86_64
* **os.productname**: Windows 10 Version 1607
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.6.1
* **windows.tabletmode**: false

**Comment by ZZJHONS** [comment]
Just updated mine now that was generated 5h ago.

**Comment by rgriebl** [comment]
Something (anti-virus/firewall) on your machine is messing with BrickStore's HTTPS connections.
Nothing I can help you with unfortunately.
