### ISSUE TITLE
Not pulling price guide data

### ISSUE THREAD

**Issue by StrayBricks** [rgriebl/brickstore#828]
**Describe the bug**
The "Set to Price Guide" feature is not consistently pulling data, throwing errors for some parts but not others.

**To Reproduce**
1. Import a set inventory.
2. Select all (Ctrl-A)
3. Set to price guide (Ctrl-G)
4. Get error "N items have been skipped because of missing price records or network errors."

In the case of set # 10018, it isn't downloading any data at all, all fields are errors, but if you click on a part, it gives you the little table to the left with last 6 months sale clearly visible.

I'm running the newest BrickStore, and manually updated the BrickLink database twice while troubleshooting.

### BrickStore 2024.1.4 (build: 1160)

* **brickstore.ldraw**: 03 Oct 2023 21:13:55 -0400
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930153)
* **build.date**: 2024-01-21T13:15:56.000
* **build.host**: fv-az845-503
* **build.number**: 1160
* **build.qt.version**: 6.6.1
* **hw.cpu**: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: NVIDIA GeForce GT 730
* **hw.gpu.arch**: nvidia
* **hw.memory.gb**: 31.9
* **os.arch**: x86_64
* **os.productname**: Windows 10 Version 22H2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.6.1
* **windows.tabletmode**: false

**Comment by StrayBricks** [comment]
A brief example as it appears in my desktop app.  If I import set 21001, select all, and Ctrtl-G for the guide, I get these inconsistent results.
![21001](https://github.com/rgriebl/brickstore/assets/158521850/cfd9a374-c34f-46b3-b161-364436c749a6)

**Comment by StrayBricks** [comment]
Update - it doesn't appear to be pulling data at all.  I imported 21001 again and did Ctrl-G for the guide, ticked the advanced option to download even if in cache, and everything is an error.

![21001](https://github.com/rgriebl/brickstore/assets/158521850/9509f502-0ce4-4d46-af3b-c641393eb38a)

**Comment by ZZJHONS** [comment]
Update the database under the Extras menu, once the new IDs of parts are changed (automatically) pricing all the document will work. 

It was happening the same to me but was able to make it work that way!

**Comment by rgriebl** [comment]
Closing as this is normal, if item ids change. This is just happening a lot more frequently now with the current variant marge.
