### ISSUE TITLE
Order Download hangs during import address records

### ISSUE THREAD

**Issue by reyberrones** [rgriebl/brickstore#83]
When trying to download an order by entering the order ID, the program task bar gives (Not Responding). When the not responding error goes away, the program lets the user hit cancel. After hitting cancel, an error message appears with the text "There was a problem downloading the data for the specified order(s). This could have been caused by three things:
•a network error occured
•the order number and/or type you entered is invalid
• there are no orders of the specified type in the given time period"

This error does not occur when doing the same thing with brickstock.

**Comment by paramecie** [comment]
Order received or placed? Let me test this...

**Comment by reyberrones** [comment]
Order placed.

**Comment by paramecie** [comment]
Agree - order received, using the order ID, it freezes here:

![image](https://user-images.githubusercontent.com/32078594/104497946-5d830b00-55db-11eb-85d3-5daddd49c0de.png)

Changes in the address format that BrickStore doesn't know? Phone number field?
Where is this Robert :O)

**Comment by paramecie** [comment]
Oh - parsing?

Anyway... WE WANT A RELEASE, WE WANT A RELEASE, WE WANT A RELEASE !!!

;-)
