### ISSUE TITLE
Habe diese Fehlermeldung- im ablauf des ssl-protokolls ist ein fehler aufgetreten.: das oberste zertifikat der zertifikatstelle ist für diesen fall nicht vertrauenswürdig

### ISSUE THREAD

**Issue by StefanHeuer1985** [rgriebl/brickstore#830]
Kann mir jemand helfen?

**Comment by rgriebl** [comment]
Bitte unter `Hilfe` -> `Systeminformationen` in die Zwischenablage kopieren und hier einfügen.

**Comment by StefanHeuer1985** [comment]
### BrickStore 2024.1.4 (build: 1160)

* **brickstore.ldraw**: 04 Feb 2024 16:30:18 +0100
* **brickstore.locale**: de
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930153)
* **build.date**: 2024-01-21T13:15:56.000
* **build.host**: fv-az845-503
* **build.number**: 1160
* **build.qt.version**: 6.6.1
* **hw.cpu**: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: Intel(R) HD Graphics 620
* **hw.gpu.arch**: intel
* **hw.memory.gb**: 31.9
* **os.arch**: x86_64
* **os.productname**: Windows 11 Version 21H2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.6.1
* **windows.tabletmode**: false

**Comment by rgriebl** [comment]
Das ist seltsam - ich kenn diese Art Fehler nur von sehr alten Windows 7 Installationen.

Hattest du das Problem schon mit einer älteren BrickStore Version oder erst seit dem Update auf 2024.1.4?

Es kann sein, dass eine Anti-virus/Firewall Software in die Netzwerkverbindungen von BrickStore eingreift und stört. Versuch doch mal diese temporär auszuschalten, bzw. für BrickStore eine Ausnahme zu erstellen.

**Comment by StefanHeuer1985** [comment]
Das ist mein erste brickstore version.
Das mit der Firwall/ Anti-virus bringt nichts.

**Comment by rgriebl** [comment]
Versuch mal https://valid-isrgrootx1.letsencrypt.org/ **und** https://www.brickstore.dev/ in **Microsoft Edge** (nicht FireFox, nicht Chrome) aufzurufen. Evtl. installiert Windows dann ein fehlendes Zertifikat nach. Es gab vor ca. 2 Jahren mal ein ähnliches Problem (andere Fehlermeldung), aber evtl. hilft es auch hier.

Wenn nicht, dann weiss ich auch nicht, was auf deinem Windows schief läuft.

**Comment by StefanHeuer1985** [comment]
Hi, danke schonmal.
muss ich einfach nur die Adressen aufrufen? Wenn ja, klappt es nicht.

**Comment by rgriebl** [comment]
Dann weiss ich auch nicht weiter. Das einzige was mir noch auffällt: Dein Windows 11 21H2 ist seit 4 Monaten schon ohne Support:

https://learn.microsoft.com/de-de/lifecycle/products/windows-11-home-and-pro

Evtl. hilft es ja mal ein Update auf eine aktuelle W11 Version zu machen.

**Comment by StefanHeuer1985** [comment]
Ich habe mir jetzt einen neuen laptop geholt.
