### ISSUE TITLE
Bricklink - Database Breaking changes 

### ISSUE THREAD

**Issue by Sofrosyn** [rgriebl/brickstore#832]
Hello @rgriebl, now that Bricklink is doing away with some parts. For us that would like to retain a version of the old parts. Can you make provisions for us. I tried generating the database but it gets corrupted. I believe this way we can easily view with any database client.

https://drive.google.com/drive/folders/1psicpJMju50b-5w95xk-6y32LH2bsIIL?usp=sharing

You can find the generated db here. 

Thank you

**Comment by rgriebl** [comment]
You are way too late for that ... the changes have been gradually rolling in since Feb 1st.
Please also see #804

**Comment by joseph-fidelis** [comment]
I have a few old databases I generate, is there a way I can view them with any database client ?

**Comment by rgriebl** [comment]
What is a "database client"? If you think the BrickStore DB is a SQL DB, then you are completely wrong: it is a custom binary serialization format specifically for BrickStore.
All the data in there is freely available in plain XML format directly from bricklink.com (catalog download)

**Comment by rgriebl** [comment]
I'm closing this now, as I personally have zero interest in this whole variant business.
