### ISSUE TITLE
Brickstore does not seem to load images and prices, reason unkown

### ISSUE THREAD

**Issue by Kopareo** [rgriebl/brickstore#833]
**Describe the bug**
Since the last update, it seems my BrickStore does not load any of the database. I did not found any solution to indicate a fresh load from scratch. I neither have any pictures, nor does it load any prices or anything. This seems not to be a bug, it's mainly just my issue, but i did not found any other solution were i may can get some tipps how to avoid this or have a solution. 

**To Reproduce**
Steps to reproduce the behavior (in my personal case)
1: Scan an item
2: Pick the item
3: Wait for it to load the image or prices - does not happen. With any item. 

**Expected behavior**
Should load the picture and show me the prices

**Screenshots**
![image](https://github.com/rgriebl/brickstore/assets/75340632/5bc08eb2-1b79-4af1-8296-0d873061d517)

**System information**
Windows 10. Build 1160.

**Comment by Kopareo** [comment]
Now i found the button "Update Datebase" under Extras but its greyed out. Can't click it.

**Comment by rgriebl** [comment]
no feedback - closing
