### ISSUE TITLE
Webcam zeigt nichts an

### ISSUE THREAD

**Issue by StefanHeuer1985** [rgriebl/brickstore#835]
Wenn ich Teile mit Hilfe der Webcam bestimmen möchte, ist das Bild der Webcam schwarz.

### BrickStore 2024.1.4 (build: 1160)

* **brickstore.ldraw**: 05 Feb 2024 12:29:34 +0100
* **brickstore.locale**: de
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930153)
* **build.date**: 2024-01-21T13:15:56.000
* **build.host**: fv-az845-503
* **build.number**: 1160
* **build.qt.version**: 6.6.1
* **hw.cpu**: Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: Intel(R) HD Graphics 4600
* **hw.gpu.arch**: intel
* **hw.memory.gb**: 7.9
* **os.arch**: x86_64
* **os.productname**: Windows 10 Version 20H2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.6.1
* **windows.tabletmode**: false

**Comment by rgriebl** [comment]
Das Problem ist bekannt und sollte im nächsten Release behoben sein.
Bitte zur Sicherheit einfach den aktuellen Build installieren: https://github.com/rgriebl/brickstore/actions/runs/7774829422  (runter scrollen und Windows-x64 downloaden) und kurz Rückmeldung geben, ob das Problem damit behoben ist.

**Comment by rgriebl** [comment]
No feedback - closing
