### ISSUE TITLE
Automatically recognize type file

### ISSUE THREAD

**Issue by buildamoc** [rgriebl/brickstore#837]
Hi! I have no idea how coding works - so not sure how hard or possible this is, but I wanted to suggest that it would be great to be able to open multiple types of files without having to specifically import that type of file.

For example, sometimes I go into an old folder, and I don't know if I have a bsx saved of that studio file, a XML, or the studio file. It would be great to just select the file and the program to recognize what type of file it is and open it correctly.

Just a suggestion,

Gerardo

**Comment by rgriebl** [comment]
Forgot to close this one ... already implemented in 2024.4.1
