### ISSUE TITLE
server replied bad request

### ISSUE THREAD

**Issue by Doober1989** [rgriebl/brickstore#838]
database wont update
its been10 days now and the new data base  wont update 

**To Reproduce**
just try and update and i get the same message 

could not load the new database:
download and decompress failed:
error transferring https://data.brickstore.dev/database-v11.lzma - server replied: Bad request 

**Expected behaviour**
just wondering if this is something i have done or can fix my end or is it a tempory issue with the servers?

**System information**
### BrickStore 2024.1.4 (build: 1160)

* **brickstore.ldraw**: 11 Feb 2024 12:17:36 +0000
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930153)
* **build.date**: 2024-01-21T13:15:56.000
* **build.host**: fv-az845-503
* **build.number**: 1160
* **build.qt.version**: 6.6.1
* **hw.cpu**: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: NVIDIA GeForce GTX 1080 Ti
* **hw.gpu.arch**: nvidia
* **hw.memory.gb**: 31.9
* **os.arch**: x86_64
* **os.productname**: Windows 10 Version 22H2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.6.1
* **windows.tabletmode**: false

**Comment by rgriebl** [comment]
The download works perfectly fine, plus my server logs do not show a single `400 Bad Request` in the last 2 months.
This must be something on your machine or in your network. Most likely some anti-virus/firewall tool that is intercepting or re-directing BrickStore's HTTPS requests.

**Comment by Doober1989** [comment]
ok thanks for a quick reply. at least i know where to start looking, i will put an update here when i find the problem
