### ISSUE TITLE
Version 2024.2.1 Crashing on macOS Big Sur

### ISSUE THREAD

**Issue by jmkiska** [rgriebl/brickstore#839]
**Describe the bug**
Downloaded and installed version 2024.2.1.  It crashes when I try to open it.

**System information**
macOs Big Sur
Version 11.7.10
Mac min (2018)
Processor GHz 6-Core Intel Core i7
Memory 16 GB 2667 MHz DDR4

[Brickstore 2024.2.1 Crash Report.pdf](https://github.com/rgriebl/brickstore/files/14319289/Brickstore.2024.2.1.Crash.Report.pdf)

Graphics Intel UHD Graphics 630 1536 MB

**Comment by rgriebl** [comment]
Thanks for the detailed bug report. It does however not make any sense why the app crashes, where the report tells me it does.
The other problem is that I don't have a macOS 11 System to test on. My oldest one is a 12.6 and BrickStore works perfectly fine there.
Please try to install the "macOS 10 Legacy" download instead of the normal one and let me know if this one works.

**Comment by jmkiska** [comment]
Hello,

I just sent you another email.  Please review that information and let me know your thoughts before I try installing the "macOS 10 Legacy” version.

Thanks,

John

John Kiska
***@***.***

**Comment by jmkiska** [comment]
I should have mentioned that Brickstore was working just fine on my system until I installed the 2024.2.1 update.

Regards,

John

John Kiska
***@***.***

**Comment by rgriebl** [comment]
That information doesn't change anything: all 2024.1.x versions had random crashes on macOS if you had any Accessibility option enabled in macOS. This is fixed in 2024.2.1.

Your problem now seems specific to macOS 11 and installing the legacy version should fix it. The only difference to the normal version is that not all web-cam may work.

**Comment by jmkiska** [comment]
Hello,

I installed the legacy version and it appears to be working just fine.  My web-cam is also working.

If you find the issue with the normal version, please let me know.

Thanks for the great support.

Regards.

John

John Kiska
***@***.***

**Comment by rgriebl** [comment]
Talked to a colleague today: this is likely a bug in Apple's XCode build tool in the version provided by Github. I'll play around with forcing a more recent version of XCode when building BrickStore.
(for reference: https://developer.apple.com/forums/thread/740889)

**Comment by jmkiska** [comment]
Good morning,Thanks for the update. Please keep me posted on your progress. For now I’ll use the legacy version. Just as a test I installed v2024.2.1 on my work MacBook Pro M1 running macOS Ventura v13.6.3 and it ran with no issues. Thanks for the great support. Regards,JohnSent from my iPadOn Feb 19, 2024, at 5:47 AM, rgriebl ***@***.***> wrote:﻿
Talked to a colleague today: this is likely a bug in Apple's XCode build tool in the version provided by Github. I'll play around with forcing a more recent version of XCode when building BrickStore.
(for reference: https://developer.apple.com/forums/thread/740889)

**Comment by rgriebl** [comment]
Sorry for the late reply - I somehow missed your message.
Could you please try to install the current developer build from here, as I do not have a macOS 11 to test this on:
https://github.com/rgriebl/brickstore/actions/runs/8366764449 
(scroll down and pick the `macOS` build)

Please note: You have to be logged in to GitHub to able to download. After download, open the ZIP, then open DMG within and continue to install as usual.

**Comment by jmkiska** [comment]
Thanks for getting back to me.  I’m traveling on business this week so I won’t be able to install the developer build until I get home this weekend.Before I do the install, do I have to uninstall the legacy version?  Or will the developer build replace the legacy version?Regards,JohnSent from my iPadOn Mar 20, 2024, at 7:03 PM, rgriebl ***@***.***> wrote:﻿
Sorry for the late reply - I somehow missed your message.
Could you please try to install the current developer build from here, as I do not have a macOS 11 to test this on:
https://github.com/rgriebl/brickstore/actions/runs/8366764449
(scroll down and pick the macOS build)
Please note: You have to be logged in to GitHub to able to download. After download, open the ZIP, then open DMG within and continue to install as usual.

**Comment by jmkiska** [comment]
Hello,

When I opened BrickStore on the MacBook Pro running macOS Ventura 13.6.3 (22G436) I get the following pop-up:

￼

When I click “Ok” it opens and appears to be work fine.

I then tried to access https://www.brickstore.dev/ and get the following:

￼

I was able to access the website on my iPad Pro.

Your thoughts on this issue?

Regards.

John

John Kiska
***@***.*** ***@***.***>

**Comment by rgriebl** [comment]
Hi John,
GitHub doesn't import images attached to mails. You have to add them via the web interface.
Thanks,
Robert
