### ISSUE TITLE
Extension Scripting: document.lotCount with active filter

### ISSUE THREAD

**Issue by mmally** [rgriebl/brickstore#840]
a document has e.g. 10 items
I set a filter so that only 3 items remain e.g. Index 1, 4 and 6

if I now call document.lotCount it returns 3.
now I want to iterate those 3 filtered items:
```
for (var i=0; i<items; i++)
{
	let current=thisDoc.lots.at(i)
	console.log("ItemId:" + current.itemId)
}
```
this returns - of course - the items at index 0, 1 and 2.

Currently I see no way to access only the filtered lots

**Comment by rgriebl** [comment]
New docs are available now: https://www.brickstore.dev/extensions/qml-brickstore-document.html

**Comment by mmally** [comment]
Thank you for the quick solution !
