### ISSUE TITLE
Brick Store Wanted List closes

### ISSUE THREAD

**Issue by inroberts** [rgriebl/brickstore#842]
**Describe the bug**
A clear description of what the bug is.
When I try to import a Bricklink Wanted List into Brick Store, Brickstore closes after I log in. This recently started occurring. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information**
Please tell us which system you are running on and which BrickStore version you are using.
In BrickStore, just open `Help` > `System information...`, Click `Copy to clipboard` and then paste  here.

**Additional context**
You can also attach BSX files, but GitHub only accepts these if added to a ZIP file first.

**Comment by rgriebl** [comment]
I have seen these already in the Sentry crash reports (only macOS on M1/M2), but I just cannot reproduce them and the code does look ok.

There seems to be something about your specific wanted list(s) that triggers a crash. It would be very helpful, if you could give me temporary access to your BrickLink account to have a look at your wanted list setup.
Other people have done this before to let me reproduce obscure errors, but I won't blame you if you do not want to give your account credentials to a stranger, but then I just can't fix that bug.

If you are up for it: change your password on BrickLink to something else and send it to me via MAIL (not here). Click on my name/icon to see my email address. I'll let you know once I have finished my investigation and you can then reset your password back to your "real" one.

**Comment by inroberts** [comment]
I installed the previous version of Brickstore and it worked. Must be something with the latest update. 
Thanks


Sent from AT&T Yahoo Mail for iPhone


On Wednesday, February 28, 2024, 7:08 PM, rgriebl ***@***.***> wrote:




I have seen these already in the Sentry crash reports (only macOS on M1/M2), but I just cannot reproduce them and the code does look ok.

There seems to be something about your specific wanted list(s) that triggers a crash. It would be very helpful, if you could give me temporary access to your BrickLink account to have a look at your wanted list setup.
Other people have done this before to let me reproduce obscure errors, but I won't blame you if you do not want to give your account credentials to a stranger, but then I just can't fix that bug.

If you are up for it: change your password on BrickLink to something else and send it to me via MAIL (not here). Click on my name/icon to see my email address. I'll let you know once I have finished my investigation and you can then reset your password back to your "real" one.

**Comment by ZZJHONS** [comment]
Maybe related to Bricklink not letting you use WL if you have any with a duplicate item:

![image](https://github.com/rgriebl/brickstore/assets/1063368/f6882695-2f04-47f9-b950-507ff2509588)

**Comment by placenamehere** [comment]
I'm seeing this as well. 

* Immediate crash when I attempt to open a want list
* If I first open an order (noticed while i was testing other BL account things) then try and open a want list the dialog shows it's loading want lists for 2 or 3 seconds and then crashes.

NOTE FOR LAST COMMENT: I can edit my want lists on the bricklink site just fine, so this isn't a the case of having multiple of the same item after a merge causing an issue

Mac M1 Pro / OS X 14.3.1 (23D60) / Brickstore 2024.2.1 (bild: 1184)

**Comment by rgriebl** [comment]
I still see a lot of crashes on Sentry, but I can't fix this without a way to reproduce it.
So, if somebody affected by this is willing to help -- see my comment above.
