### ISSUE TITLE
App crashes on Android 14.0 after opening anything (order / inventory bsx-file)

### ISSUE THREAD

**Issue by habex-ch** [rgriebl/brickstore#848]
**Describe the bug**
App crashes as soon as I open anything in the app. I already reinstalled the app, cleared the cache and data but it still occurs. I starts happining the last have year.

**To Reproduce**

1. Go to 'BrickLink Order' (or any other menu point except new)
2. Select an order
3. Crash happening

**Expected behavior**
No crashes

**System information**
Samsung Galaxy A53 5G
![image](https://github.com/rgriebl/brickstore/assets/34911987/1a92b576-82aa-46b2-9b95-52f5fc0c2264)

**Comment by tom-greene** [comment]
Can confirm. Crashes in the same vein on my Pixel 6A.

**Comment by rgriebl** [comment]
I don't have a Android 14 device to test, but I also don't see any crashes in the Android 14 desktop emulator.
I just had a friend of mine quickly test the current version (2024.4.1, build 1211) on his Samsung S and it didn't crash when importing `Bricklink Set Inventory` -> `Agents` -> `8637-1`
Could you please re-test with the latest version and let me know if (a) it still crashes and (b) there is a simple way to reproduce that crash via "import inventory" (i.e. no BL account required)

**Comment by tom-greene** [comment]
I was not able to Import Inventory > Agents > 8627-1. It crashed doing that as well.

**Comment by rgriebl** [comment]
Could you try again with the latest (1213) build?

**Comment by habex-ch** [comment]
> I don't have a Android 14 device to test, but I also don't see any crashes in the Android 14 desktop emulator. I just had a friend of mine quickly test the current version (2024.4.1, build 1211) on his Samsung S and it didn't crash when importing `Bricklink Set Inventory` -> `Agents` -> `8637-1` Could you please re-test with the latest version and let me know if (a) it still crashes and (b) there is a simple way to reproduce that crash via "import inventory" (i.e. no BL account required)

It still crashes with 2024.4.1.1213 while I tried importing `Bricklink Set Inventory` -> `Agents` -> `8637-1`

Can I give you somehow more information like a log file?

**Comment by mmally** [comment]
On my Samsung S21 FE,it also crashes when I try to import Bricklink Set Inventory -> Agents -> 8637-1.
I also crashes when I try to open any bsx file form PC. This happens since installing Brickstore 2023.11.1.
Currently I am running Android 14.
I tested it also with a Pixel 7 and Lenovo Tab P11 with the same result.

How can we assist you in finding the problem?

**Comment by rgriebl** [comment]
Could you all please update Brickstore to the latest build available in the Play store?
Then make it crash once and - important- restart Brickstore after it crashed. 

(The newest build now has crash reporting via sentry.io just like the Windows and macOS versions)

**Comment by rgriebl** [comment]
I have 7 crash reports now on sentry and they all point towards 'Accessibility' ... could you check your system settings what specific accessibility options you have enabled and also if deactivating them makes BrickStore work again?

**Comment by rgriebl** [comment]
This should be fixed now. Please re-open this bug if it still crashes for you.
