### ISSUE TITLE
Username and Password missmatch

### ISSUE THREAD

**Issue by Wasserlasser** [rgriebl/brickstore#849]
**Describe the bug**
When I want to log on, it says Username and Password missmatch even though I can log on to the Bricklink Website with exactly that data.

**To Reproduce**

**Expected behavior**
I want to log on.

**Screenshots**
![image](https://github.com/rgriebl/brickstore/assets/13897364/0b634d50-5180-47f2-8e4f-520e27c4eb8d)

**System information**
Please tell us which system you are running on and which BrickStore version you are using.
In BrickStore, just open `Help` > `System information...`, Click `Copy to clipboard` and then paste  here.

**Additional context**
You can also attach BSX files, but GitHub only accepts these if added to a ZIP file first.

**Comment by rgriebl** [comment]
Since you didn't include any system information, I have to assume you are using the latest 2024.2.1 on Windows?
Have you checked the username and password fields in the settings dialog? If they turn red, you are using invalid credentials: check the tool-tips on the these fields then (typically email instead of username or a password with more than 15 characters)

**Comment by Wasserlasser** [comment]
Sorry, yes, I am using the latest version of Windows and Brickstore.
All fields are correct and nothing turns red. 
It looks like the password length seems to be the issue as my Password is over 20 characters, I will need to try this.

**Comment by rgriebl** [comment]
If you input for than 15 characters in the settings dialogs, BrickStore will tell you:
![image](https://github.com/rgriebl/brickstore/assets/3710520/d45b0449-7deb-406f-9668-a0f3542768e5)

Also these 2 comments from 2021 still apply: https://github.com/rgriebl/brickstore/issues/378#issuecomment-904543237

**Comment by rgriebl** [comment]
Your password does not have more than 15 characters - it silently gets truncated to 15 when entering it on BrickLink. I'll add another warning dialog though.
