### ISSUE TITLE
Filter by a blank field value

### ISSUE THREAD

**Issue by frahugo** [rgriebl/brickstore#85]
Feature request.

Example: if I want to see the items with no remarks, I currently have to do something like this: `remarks !~ [a-z]`.

It would nice to have something like this: `remarks is blank` or `remarks is empty`.

**Comment by paramecie** [comment]
I usually simply sort the column, and that's it.

But a feature would be nice.

**Comment by frahugo** [comment]
Yup, but it's nice to be able to sort the items without remarks (I use remarks for the location of the item in my inventory). Pretty useful when parting out a set to only see the items that have not yet been placed in a bin.

**Comment by frahugo** [comment]
My little RegEx trick does not work anymore in 2021.1.6. I looked at the code. Maybe using `QString::indexOf` instead of `QString::contains` would fix the issue? I'll see if I can set-up the dev environment on my Mac and see if`indexOf` helps, and in that case submit a PR.

**Comment by frahugo** [comment]
See PR #120

**Comment by rgriebl** [comment]
My original plan was always to have `""` and `''` to describe an empty field. Your PR finally gave me the hint where to look for the problem :)
I'll have another look at your PR later to see how to best integrate it and also make it translatable.
