### ISSUE TITLE
Invalid device information

### ISSUE THREAD

**Issue by 77JR** [rgriebl/brickstore#852]
**Describe the bug**
A clear description of what the bug is.

When trying to import store inventory.

**To Reproduce**
1. Go to '...' File, Import, Bricklink store inventory

**Expected behavior**
To import my store inventory. Instead I keep getting the error of invalid device information.

**Screenshots**
![image](https://github.com/rgriebl/brickstore/assets/165317496/145bd383-db65-4824-aa1c-6991b3e770ad)
![image](https://github.com/rgriebl/brickstore/assets/165317496/befa6bcc-04b6-44ad-9f83-947689f4c934)
![image](https://github.com/rgriebl/brickstore/assets/165317496/eddfc892-33e5-4cb1-b46c-0bf3820eedff)

**System information**
Please tell us which system you are running on and which BrickStore version you are using. 3.1. 
In BrickStore, just open `Help` > `System information...`, Click `Copy to clipboard` and then paste  here. 

**Additional context**
You can also attach BSX files, but GitHub only accepts these if added to a ZIP file first.

I have been using today and worked fine. Even after I did the update. Tried again a few hours later and I now keep getting this error. I have checked my settings and re entered password and is correct.

**Comment by mattymemezoid** [comment]
### BrickStore 2024.3.1 (build: 1203)

* **brickstore.ldraw**: 28 Mar 2024 14:19:44 -0400
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930154)
* **build.date**: 2024-03-25T23:08:20.000
* **build.host**: fv-az533-485
* **build.number**: 1203
* **build.qt.version**: 6.6.2
* **hw.cpu**: AMD Ryzen 5 5600G with Radeon Graphics
* **hw.cpu.arch**: x86_64
* **hw.gpu**: NVIDIA GeForce GTX 1660 Ti
* **hw.gpu.arch**: nvidia
* **hw.memory.gb**: 13.9
* **os.arch**: x86_64
* **os.productname**: Windows 11 Version 23H2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.6.2
* **windows.tabletmode**: false

**Comment by Gertjannemannetje** [comment]
Same goes for importing CARTS, ORDERS, WANTED LISTS.

Looks like the door is closed at BL-end for these information requests.

Price guide and  updating database works ok.

**Comment by mattymemezoid** [comment]
How many people are having this problem? I just downloaded Brick Store for the first time and right now this does not seem like a good look for me

**Comment by FireStarBricks** [comment]
I have also have the same issues. Hoping that it will be fixed soon.

**Comment by skidoo6** [comment]
> **Describe the bug** A clear description of what the bug is.
> 
> When trying to import store inventory.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Go to '...' File, Import, Bricklink store inventory
> 
>     2. Click on '....'
> 
>     3. Scroll down to '....'
> 
>     4. See error
> 
> 
> **Expected behavior** A clear and concise description of what you expected to happen. To import my store inventory. Instead I keep getting the error of invalid device information.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. ![image](https://private-user-images.githubusercontent.com/165317496/317836261-145bd383-db65-4824-aa1c-6991b3e770ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NTMyNjMsIm5iZiI6MTcxMTY1Mjk2MywicGF0aCI6Ii8xNjUzMTc0OTYvMzE3ODM2MjYxLTE0NWJkMzgzLWRiNjUtNDgyNC1hYTFjLTY5OTFiM2U3NzBhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQxOTA5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2JiZmRlZTgzZjhiNDMxMGUxOTZhMDU0N2Y4NjFmODBlMTk4MjBhNmU4NDE2YTY0OWQ1ZjNkODFjNzE3M2IwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1qST_jGDD5zylCfzazsPhhOt9WpujReQIV5MH0F5YPA) ![image](https://private-user-images.githubusercontent.com/165317496/317836283-befa6bcc-04b6-44ad-9f83-947689f4c934.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NTMyNjMsIm5iZiI6MTcxMTY1Mjk2MywicGF0aCI6Ii8xNjUzMTc0OTYvMzE3ODM2MjgzLWJlZmE2YmNjLTA0YjYtNDRhZC05ZjgzLTk0NzY4OWY0YzkzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQxOTA5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDJmNTU4NjUyMWNlMDlhMjFhZDkwOWYwYmNjMmM5YzRlZWRjMjllYmM1YWJmYWU4OWEzNjc1ZjI1MzYzYTVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IlxDixTOqqx1TtD5A0LinJAFJ94BMqEAiy_N_PkxJV4) ![image](https://private-user-images.githubusercontent.com/165317496/317836296-eddfc892-33e5-4cb1-b46c-0bf3820eedff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NTMyNjMsIm5iZiI6MTcxMTY1Mjk2MywicGF0aCI6Ii8xNjUzMTc0OTYvMzE3ODM2Mjk2LWVkZGZjODkyLTMzZTUtNGNiMS1iNDZjLTBiZjM4MjBlZWRmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQxOTA5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzMzNTczODgyMjI0YzhhZGJlZWI3NTNiNzM0MmQ1MzNmM2VkMzMxMDgxNjc4N2E4MTE4MTdlOGU0MWNhOWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Wive_gubGmRS7tORz5jbCJ9IXmh6rMsCHt32BmF4vbc)
> 
> **System information** Please tell us which system you are running on and which BrickStore version you are using. 3.1. In BrickStore, just open `Help` > `System information...`, Click `Copy to clipboard` and then paste here.
> 
> **Additional context** Add any other context about the problem here. You can also attach BSX files, but GitHub only accepts these if added to a ZIP file first.
> 
> I have been using today and worked fine. Even after I did the update. Tried again a few hours later and I now keep getting this error. I have checked my settings and re entered password and is correct.

I have the same issue

**Comment by IndeSteine** [comment]
Me too.

**Comment by istaylor92** [comment]
same

**Comment by 77JR** [comment]
> I have the same issue tried with and without PIN tried a new password tried using bricklink user id instead of user name tried the lastest windows update still have same error might try a re-install??


I tried reinstalling. Also tried the previous version too. All with the same outcome :(

**Comment by rgriebl** [comment]
https://www.bricklink.com/message.asp?ID=1461866

**Comment by brixmix** [comment]
same problem for me as well

**Comment by skidoo6** [comment]
tried un-istalling and reinstalling brickstore and related appdata w/o success

also, am able to manually import inventory, but get the following error trying to import orders received/placed manually:

![Screenshot 2024-03-28 181436](https://github.com/rgriebl/brickstore/assets/165322144/f4b40d95-d00d-43d8-9f1a-c243c9be9569)

**Comment by rgriebl** [comment]
Please read the BrickLink forum message I linked to. I can't do anything right now.

Also: you can't import order XML data without manually transforming it into a normal BL XML document in a text editor first.

**Comment by IndeSteine** [comment]
I tried again this morning and it works again (at least in this moment).

**Comment by rgriebl** [comment]
See https://www.bricklink.com/message.asp?ID=1461877

> UPDATE:
> 
> The new login procedure was launched as a security feature, but we have rolled
> it back. There should be no issues with Brickstore login at this point.
> 
> Please let us know if you continue to experience problems. Thank you for your
> patience.

**Comment by ZZJHONS** [comment]
Last year or so Bricklink stated that in the near future they would merge or link the BL account to the LEGO account, so it might be good to test if there are ways to connect to the LEGO.com login too.
