### ISSUE TITLE
Brickstore Price guide error

### ISSUE THREAD

**Issue by A2Z082499** [rgriebl/brickstore#857]
yesterday it was working fine then I suddenly encounter this error with the price guide please help guys
![image](https://github.com/rgriebl/brickstore/assets/166113776/38900ee9-ba77-40b8-b3c5-e1edcefc09ed)

**Comment by A2Z082499** [comment]
![image](https://github.com/rgriebl/brickstore/assets/166113776/b1330bbf-8d25-4144-bcf7-63d0a6601d34)

**Comment by rgriebl** [comment]
Duplicate of #858
