### ISSUE TITLE
Item ID's not sorted in correct order

### ISSUE THREAD

**Issue by anton249** [rgriebl/brickstore#860]
Sorting by 'Item Id' does not provide correct results within a group of item id's with the same number of digits. It seems that the first digit of the item id is ignored. 
Example: Part 3622, Blue Brick: when sorted up 'S 71791-1' is listed before 'S 42619-1'. 
But 'S 4997-1' is followed correctly by 'S 10009-1' (5-digits after 4-digits)

This happens both in the 'Show item inventory and appearance' window when adding an item and when an inventory is listed and a part is marked/selected in the 'Item Inventory' window.

Item id's were correctly sorted until the previous version.

Version: 2024.4.1 (build 1211)
Windows 10

**Comment by gradams1** [comment]
Issue still exists for minifigures with four digits in Item ID such as City and Star Wars. First digit after the theme's alphabetic category ("cty" and "sw") is ignored when sorting by Item ID, so all figures with numbers over 1000 are now incorrectly placed around Item IDs starting with a 0. 
Ex: sw0021, sw1021, sw0022, sw1022
