### ISSUE TITLE
Add would like to be a beta tester for IOS

### ISSUE THREAD

**Issue by Yayaa10** [rgriebl/brickstore#861]
Hello, I would like to use brickstore with my Ipad.

To help de deployment in IOS, is it possible to be in the beta testers ?

Thanks in advance

**Comment by rgriebl** [comment]
I finally understood now how TestFlight works and found out I got it wrong all the time and nobody past the first 100 testers was able to sign up.
The current build is currently being reviewed by Apple (probably a few days) and as soon as they give me an ok, I can push that to the general public.

**Comment by rgriebl** [comment]
Could you please try clicking that TestFlight invite link again and report back if it works now? https://www.brickstore.dev/installation
