### ISSUE TITLE
Doesn't recognize or upload some items

### ISSUE THREAD

**Issue by mousiesoshie** [rgriebl/brickstore#868]
**Describe the bug**
On two of my computers I have had issues with BrickStore recognizing some items (ex. 3068pb1291) and it turns up as an error when uploading to Bricklink. It not only won't recognize the items in my store when I go to import the information to load to that item, but it also won't find it on Bricklink. When trying to upload to Bricklink, those items show an error on the upload page so it won't even upload them as a new upload to my online store.
I did try updating the BrickStore on both computers, but the error is still occurring.

**To Reproduce**
1. Upload set # and part out
2. Click on 'Price Guide - Last 6 months'
3. See error - Only 1 item imported a price in this example - all of these items are in my store, but not all will load from there either when importing.

**Expected behavior**
For everything to load properly from imported store copy over and from importing last 6 months sales information
**Screenshots**
What appeared after trying to import 'Last 6 Month Sales' price guide. Items will appear when parting out but not if the item number is imported on it's own (ex. 3068pb1291).
![1 - Problem in BrickStore](https://github.com/rgriebl/brickstore/assets/166745197/32cbae52-a713-4f1a-abe4-d290506a8b06)
.

**System information**
Please tell us which system you are running on and which BrickStore version you are using.
BrickStore 2024.4.1 (build: 1211)
brickstore.ldraw: 09 Apr 2024 14:40:10 -0500
brickstore.locale: en
build.arch: x86_64
build.compiler: Microsoft Visual-C++2019 (192930154)
build.date: 2024-04-05T12:55:13.000
build.host: fv-az981-840
build.number: 1211
build.qt.version: 6.6.2
hw.cpu: Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
hw.cpu.arch: x86_64
hw.gpu: Radeon RX550/550 Series
hw.gpu.arch: amd
hw.memory.gb: 15.9
os.arch: x86_64
os.productname: Windows 10 Version 22H2
qt.debug: false
qt.platformname: windows
qt.version: 6.6.2
windows.tabletmode: false

**Additional context**
Errors when trying to upload are consistent with the errors shown in BrickStore - Bricklink will not recognize the item. 
When looking up the item on Bricklink (ex. 3068pb1291), everything works fine, so it's an issue is with BrickStore I believe and not Bricklink.

**Comment by ZZJHONS** [comment]
You need to go to Extras -> Update Database, as Bricklink is changing the IDs of some items in a day to day basis for some items for now.
