### ISSUE TITLE
with the last update the import does not work

### ISSUE THREAD

**Issue by ThiloBerger** [rgriebl/brickstore#877]
Concerns Build 1256

Import of orders (both single and multiple), import is carried out, but the lists are empty afterwards

**Comment by Samst79** [comment]
I confirm. Order import no longer works. No items are displayed. The list of items is empty.

**Comment by CornerstoneBrickCo** [comment]
Doesn't import orders and synchronized every order back to 2011... not just the 15 days as stipulated

**Comment by skidoo6** [comment]
same

**Comment by ThiloBerger** [comment]
Thanks for the fix, works again.
