### ISSUE TITLE
unable to import order from bricklink

### ISSUE THREAD

**Issue by willebrick** [rgriebl/brickstore#882]
**Describe the bug**
A clear description of what the bug is.
when going to "import order" selecting an order, clicking on import, it gives a blank result

**To Reproduce**
1. Go to '...' file > import > bricklink order
2. Select '....' order line  and click on "import"
3. See empty scrreen

**Expected behavior**
expected to see all ordered parts

**Screenshots**

**System information**
Please tell us which system you are running on and which BrickStore version you are using.
In BrickStore, just open `Help` > `System information...`, Click `Copy to clipboard` and then paste  here.
### BrickStore 2024.5.2 (build: 1261)

* **brickstore.edition**: desktop
* **brickstore.ldraw**: 01 May 2024 09:37:50 +0200
* **brickstore.locale**: nl
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930154)
* **build.date**: 2024-05-02T09:26:17.000
* **build.host**: fv-az522-729
* **build.number**: 1261
* **build.qt.version**: 6.6.3
* **hw.cpu**: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: NVIDIA GeForce RTX 2060 SUPER
* **hw.gpu.arch**: nvidia
* **hw.memory.gb**: 15.9
* **os.arch**: x86_64
* **os.productname**: Windows 11 Version 23H2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.6.3
* **windows.tabletmode**: false
![brictstore import problem 2](https://github.com/rgriebl/brickstore/assets/136175929/2af4730b-e45a-4db4-8672-275b51dc5b7e)
![brictstore import problem 1](https://github.com/rgriebl/brickstore/assets/136175929/db71cdbb-4f3f-411e-8d55-d61985b7c3d9)
![brictstore import problem 1](https://github.com/rgriebl/brickstore/assets/136175929/803a9503-fd46-46ac-bc2a-3774a0e75ea3)

**Additional context**
You can also attach BSX files, but GitHub only accepts these if added to a ZIP file first.

**Comment by rgriebl** [comment]
Sorry - I missed this one.
This should be fixed by clicking the "Update" button. The previous version (2024.5.1) had a bug when updating orders and it seems like it cleared the order details for you when updating.

**Comment by willebrick** [comment]
thank you for your reply, no need to apologize. I re-installed the latest brickstore, did a refresh of the orders, and then it worked. All good now, thanks for your support!

**Comment by cwmcd** [comment]
i'm not sure if this should be under the same or another one, but i'm having similar except not a blank screen.

went to import orders and it only shows 3 of the 4 orders. one in the middle is missing.

![bricklink-list](https://github.com/rgriebl/brickstore/assets/7256436/b57ac33a-7e9d-4e5d-942e-4534e439ba18)
![brickstore-list](https://github.com/rgriebl/brickstore/assets/7256436/2ab2b3dc-8dc9-4589-b097-e363bdda188a)

**Comment by rgriebl** [comment]
Set your days to sync to 180 and click update. This should get everything back on track.

**Comment by cwmcd** [comment]
> Set your days to sync to 180 and click update. This should get everything back on track.

fixed. set to 180 and hit the refresh icon
![image](https://github.com/rgriebl/brickstore/assets/7256436/bb0fca93-d148-475f-acc9-22f3b6f25d3b)
thank you for your help!
