### ISSUE TITLE
copy values from document not working

### ISSUE THREAD

**Issue by polarbits1** [rgriebl/brickstore#889]
**Describe the bug**
When I try to use the copy values from document function nothing happens. Everything in the document I want to copy too is selected and I know I have bricks in my store document with values that should be copied. Currently I am trying to copy over price, remark, retain flag and stockroom. I use this function all the time and as far as I'm aware have not changed any brickstore settings since the last time I used it.

**To Reproduce**
Create a document of parts too add to your store and try to use the copy values from document function.

**Expected behavior**
I expected the values to copy.

**System information**
### BrickStore 2024.5.2 (build: 1261)

* **brickstore.edition**: desktop
* **brickstore.ldraw**: 20 May 2024 09:44:59 -0400
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930154)
* **build.date**: 2024-05-02T09:26:17.000
* **build.host**: fv-az522-729
* **build.number**: 1261
* **build.qt.version**: 6.6.3
* **hw.cpu**: 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: Intel(R) UHD Graphics
* **hw.gpu.arch**: intel
* **hw.memory.gb**: 7.7
* **os.arch**: x86_64
* **os.productname**: Windows 11 Version 23H2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.6.3
* **windows.tabletmode**: false

**Comment by rgriebl** [comment]
Most likely the condition (new/used) of the items in both documents is different.

**Comment by polarbits1** [comment]
Thank you so much for the tip, it was exactly that. you have no idea how much time i spent trying to figure out why it wasn't copying over yesterday.
