### ISSUE TITLE
 QMake Build Matrix #175, rotating part, wow, head turns, much sick ;-)

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#89]
Wow nice feature as the 3D rotating part in Info - but could that be in option and NOT to be a default?

We could have a click or a button or a mouse down/move to start it manually, but please NOT always.

I fear it'll make me vomit on the keyboard :-(

![image](https://user-images.githubusercontent.com/32078594/104796968-f459ee00-57ba-11eb-8337-e135e86484a4.png)

Thank youuu!

**Comment by rgriebl** [comment]
No worries -- that's just a test build with the improved OpenGL renderer. There'll be a few buttons: `2D`, `3D`, `Play`, `Pause`, `Reset Camera`. Plus you can always grab the part yourself and drag to rotate.
