### ISSUE TITLE
Problem trying to hide the filter

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#896]
When working with multiple documents it's sometimes not possible to hide the filter.

To reproduce:

Open Brickstore and select File-New to create a document. Select View-Filter to show the filter.

Select File-New to create another document - the filter is already visible (as expected).

Click the little 'x' on the filter bar to close the filter - the filter drop-downs dissappear but the bar containing them is still visible.

If I switch to the first document and then back to the second the filter re-appears.

Win10, build #1273

**Comment by rgriebl** [comment]
The bug is that the filter bar is visible in new documents, as the filter state really is per-document. Also the new document's filter toggle button is off (correct), but the filter bar is visible (wrong). The fix is make sure the filter bar follows the button state.
