### ISSUE TITLE
The set 76434 "Aragog in the Forbidden Forest" not found.

### ISSUE THREAD

**Issue by spaa1266** [rgriebl/brickstore#899]
**Describe the bug**
When I go to "Import Bricklink Inventory" and then type the set number (76434) in the filter field, I get no result.

**To Reproduce**
1. Press [CTRL] - [I}
2. Type at the filter input field: 76434

**Expected behavior**
Normally a picture of the set, an Item ID and a description will appear.

**System information**
### BrickStore 2024.5.2 (build: 1261)

* **brickstore.edition**: desktop
* **brickstore.ldraw**: 24 Jun 2024 17:15:11 +0200
* **brickstore.locale**: nl
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930154)
* **build.date**: 2024-05-02T09:26:17.000
* **build.host**: fv-az522-729
* **build.number**: 1261
* **build.qt.version**: 6.6.3
* **hw.cpu**: 12th Gen Intel(R) Core(TM) i7-1255U
* **hw.cpu.arch**: x86_64
* **hw.gpu**: Intel(R) Iris(R) Xe Graphics
* **hw.gpu.arch**: intel
* **hw.memory.gb**: 15.7
* **os.arch**: x86_64
* **os.productname**: Windows 11 Version 23H2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.6.3
* **windows.tabletmode**: false

**Comment by ZZJHONS** [comment]
The inventory is still not done on Bricklink

![image](https://github.com/rgriebl/brickstore/assets/1063368/c18c9c05-5a38-44d0-9243-ba9ea563f734)
