### ISSUE TITLE
Add direct item search option in the Add item... tab

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#9]
On Brickstock when you know the item id of the item you want to add, you could click that icon an go to ir directly.

Now you would need to scroll to top of categories, click [all Items] and then input it in the top search.

It was also mentioned in the comments of the Bricklink announcement.

PD: Gladly the [all items] list loads super fast!

**Comment by paramecie** [comment]
I don't agree on this one ;-)

If you know the reference of a 3001 you can directly type it in the Part # column.

If you opened the the window in clicking the Description, automatic selection of the All items would make many problems, like:

- how to revert to the original category?
- how to find alternate versions, like 4085a, 4085b...

In short, I wouldn't like behaviour (IMHO).

**Comment by ZZJHONS** [comment]
What I mean is, when you are adding used parts manually, you sometime know exactly to which category go for it, but once you are there and want to search for another item with the search bar, you would need to go scroll to top in the categories, click All items, and then click again in the search and type.

So the suggestions was to add a button (like where I put the yellow dot) that you can click so the search is for all items instead of just the category.

Another option is to add this to the already menu in the search icon, but that would be 2 clicks...

<img width="913" alt="Captura de pantalla 2021-01-18 204155" src="https://user-images.githubusercontent.com/1063368/104957023-a0732300-59cd-11eb-9948-2bf2ecc4d3b0.png">

Also, I can't seem to be able to resize the blue bar, I don't need it to be that big

**Comment by rgriebl** [comment]
The fields within the dialog are now resizable. Right clicking on an item gives you the option to either switch to the item's category, or - if you are already there - to go back to the [All Items].

**Comment by ZZJHONS** [comment]
There is no way to right click to search in the [all items] if there are no results...

<img width="752" alt="Captura de pantalla 2021-01-27 165355" src="https://user-images.githubusercontent.com/1063368/106016973-46a2e500-60c0-11eb-8127-49c3c5366df8.png">

**Comment by paramecie** [comment]
Yes but hey, now BrickStore is FAST as Hell, you don't have to select a Category then to type the set number.
Leave it "All items" and type your set number?

**Comment by ZZJHONS** [comment]
When sorting used parts I do it physically by category, then in BS its easier to select a part category and add all the items, but most times there is a couple from other category that you need to search in [all items] as yeah, it is FAST AS HELL.

The set attached image was just to show.

That's why I suggest that if no results found, add an option somewhere to click it and search in all items.

**Comment by paramecie** [comment]
Yes, good idea:
* if a Category is selected,
* and if no result is found,
* then show "Do you wish to search in all categories" and it does the thing...

**Comment by rgriebl** [comment]
The latest dev build has the first row "All Items" frozen and always visible. I think this is the cleanest solution UI wise.

**Comment by ZZJHONS** [comment]
Perfect!

**Comment by paramecie** [comment]
Smart! Perfect.
