### ISSUE TITLE
Difference mode, should be an Edition to be saved

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#90]
A detail, but anyway:

>Difference mode is now a per-document setting and survives saving and re-loading the document.

Yes/no - It's persistent only if you DO save the document, meaning you've to make a (any) change in order the file to be saved.

Just like the Currency in the document (bottom right), please make the Difference Mode trigger an Edition, so the file MUST be saved in order to be persistent.

And I guess CTRL+Z may do the proper cancellation, just like Currency.

Thank you!

**Comment by paramecie** [comment]
It's fixed in 2021.1.17 - however, note that it can't be canceled, even if you toggle difference mode again ;-)

**Comment by rgriebl** [comment]
Yes - any changes to the columns just set a `modified` flag.
Implementing full undo/redo support for those changes would be a crazy amount of work and this is just not worth it.

**Comment by paramecie** [comment]
Don't worry - that's VERY fine as is!
