### ISSUE TITLE
Can't add parts to Brickstore - can pick the part and the quantity but the add button will not turn on

### ISSUE THREAD

**Issue by RockiesGuyBrickStore** [rgriebl/brickstore#900]
**Describe the bug**
A clear description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information**
Please tell us which system you are running on and which BrickStore version you are using.
In BrickStore, just open `Help` > `System information...`, Click `Copy to clipboard` and then paste  here.

**Additional context**
You can also attach BSX files, but GitHub only accepts these if added to a ZIP file first.

**Comment by ZZJHONS** [comment]
Same a #901: 

Parts need a color to be selected to be able to add them to the file.
