### ISSUE TITLE
I can't add parts because the add button won't light up to allow me to push it to add parts

### ISSUE THREAD

**Issue by RockiesGuyBrickStore** [rgriebl/brickstore#901]
**Describe the bug**
A clear description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information**
Please tell us which system you are running on and which BrickStore version you are using.
In BrickStore, just open `Help` > `System information...`, Click `Copy to clipboard` and then paste  here.

**Additional context**
You can also attach BSX files, but GitHub only accepts these if added to a ZIP file first.

**Comment by RockiesGuyBrickStore** [comment]
I can do everything except for pushing the add button to add parts.  It was working fine but now I can't add parts to any page

**Comment by RockiesGuyBrickStore** [comment]
I have uninstalled the program and reinstalled it and it still doesn't work to add parts.  Any ideas?

**Comment by ddotero3** [comment]
just wondering did you guys get this fix if so how
