### ISSUE TITLE
QML extension: PriceGuide missing properties

### ISSUE THREAD

**Issue by strawberrymetropolis** [rgriebl/brickstore#903]
**Describe the bug**
When receiving the `priceGuideUpdated` signal, the passed `priceGuide.item` is incomplete, for example missing the `id` property.

**To Reproduce**
```
function onPriceGuideUpdated(priceGuide) {
    if ([
        BrickLink.UpdateStatus.Ok,
        BrickLink.UpdateStatus.UpdateFailed
    ].includes(priceGuide.updateStatus)) {
        console.info(priceGuide.item)
        console.info(priceGuide.item.id)
    }
}
```

Output in the Developer Console:
```
INFO qml: QVariant(const BrickLink::Item*, 0x716cd386ee58)
INFO qml: undefined
```

**Expected behavior**
Receiving a complete item with all properties as documented [here](https://www.brickstore.dev/extensions/qml-bricklink-priceguide.html).

**System information**
Ubuntu 22.04.4 LTS
BrickStore 2024.5.2 (build: 1261)

**Comment by rgriebl** [comment]
The documentation is wrong here. The `item` and `color` properties are actually the raw C++ pointers and you have to convert them via `let item = BrickLink.item(pg.item)` to something QML/JS understands first (same for color).
It's a bit unfortunate, but I didn't want to sacrifice any performance and memory consumption by blindly wrapping everything, even if it's not used at all.
I leave this one open, so I don't forget to fix the docs.

**Comment by strawberrymetropolis** [comment]
Thanks for the super-fast response @rgriebl !
