### ISSUE TITLE
Minifig Item Id throwing error

### ISSUE THREAD

**Issue by adbookerfhsu** [rgriebl/brickstore#910]
**Describe the bug**
An import of my store inventory has errors for 8 of my minifigs. Item ID#sh0092 is correct on BL but when doing a search for that item, Brickstore appears to have dropped one of the zeros from the item#. This will not go back into BL as this item id# doesn't exist.

It appears to only affect the "sh" minifigs - "Super Heroes" category

![minifigbrickstoreproblem](https://github.com/user-attachments/assets/e9c8161a-6f2b-4337-a202-a871a0b0be04)

**Comment by ZZJHONS** [comment]
Click Extras -> Update database, Bricklink renamed the IDs to add a 0

**Comment by adbookerfhsu** [comment]
I had done that before importing but for some reason those minfigs did not update. Thank you!
