### ISSUE TITLE
Not letting me add parts 

### ISSUE THREAD

**Issue by ddotero3** [rgriebl/brickstore#916]
**Describe the bug**
A clear description of what the bug is.

**To Reproduce**
1. Go to --Add Items
2. Click on --- the item i want to add on
3. Scroll down to the item 
4. See error the add button does not work 

**Expected behavior**

**Screenshots**

**System information**
Please tell us which system you are running on and which BrickStore version you are using.
In BrickStore, just open `Help` > `System information...`, Click `Copy to clipboard` and then paste  here.

**Additional context**
You can also attach BSX files, but GitHub only accepts these if added to a ZIP file first.

**Comment by ZZJHONS** [comment]
You need to select also a color on the right to be able to add a part to a file.

**Comment by ddotero3** [comment]
ive tried that and it still doesn't work

**Comment by ZZJHONS** [comment]
A screenshot would help

**Comment by ddotero3** [comment]
![Bug](https://github.com/user-attachments/assets/6cf2a342-ae63-4b60-96ab-d24390e8410a)

So I used the camera, to take a picture of the head and select the color but the "add" button is greyed out.
I'm still able to input: Quantity, Bulk, etc. but the "add" button is still greyed out.

**Comment by ZZJHONS** [comment]
You can't have a value of 0% in the first tiered prices where you have an 8 quantity, put a percentage there or change the tiered quantity to 0 to not use it.

**Comment by ddotero3** [comment]
Thanks You ZZJHONS its now working
