### ISSUE TITLE
Always show a Tab even with a single document opened?

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#92]
I'd personnaly like to have a tab shown, even when a single document is opened.

It would:
* clearly shows the document name (as in a transparent app window task bar it's not very visible),
* shows the "*" of edited file,
* permits a quick close using the mouse, and not having search for the CTRL+F4 keys, or worse, the main menu to close this file.

This could be an option in settings, though, like "[x] Always show a Document Tab"...

![image](https://user-images.githubusercontent.com/32078594/104818695-6537ef00-5829-11eb-9675-5223d5e8abda.png)

What do the others prefer?

**Comment by legobanker** [comment]
I agree.  When working with one window, the tab doesn't show.  Only until you open multiple tabs can you see the "original" or "first" tab you opened.

**Comment by chiminirc** [comment]
I agree, it would be nice to display the tab always, even when it is just a single document.

**Comment by rgriebl** [comment]
Try the newest build a see if that works for you. I've also add a "Home" button to switch back to the starting screen at any time.

**Comment by paramecie** [comment]
VERY nice! And the home also! Thanks!

**Comment by paramecie** [comment]
PS: could we have an option button like here?

![image](https://user-images.githubusercontent.com/32078594/104970293-3a959400-59eb-11eb-8f89-8b1e0522fc51.png)

**Comment by rgriebl** [comment]
You mean moving the button to the toolbar? why?

**Comment by paramecie** [comment]
Sorry - I mean, please add a shortcut to Settings in the button bar.
