### ISSUE TITLE
Unable to update to 2024.11.1

### ISSUE THREAD

**Issue by teddywsb** [rgriebl/brickstore#925]
**Describe the bug**
Unable to update to 2024.11.1

**To Reproduce**
1. Go to update 
2. Click on install
4. See error like in screen

**Screenshots**

![image](https://github.com/user-attachments/assets/1aaf4654-3740-47f2-8156-cb6acb558a09)

**System information**
### BrickStore 2024.5.2 (build: 1261)

* **brickstore.edition**: desktop
* **brickstore.ldraw**: 26 Nov 2024 17:48:44 +0100
* **brickstore.locale**: pl
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930154)
* **build.date**: 2024-05-02T09:26:17.000
* **build.host**: fv-az522-729
* **build.number**: 1261
* **build.qt.version**: 6.6.3
* **hw.cpu**: AMD Ryzen 5 4500 6-Core Processor
* **hw.cpu.arch**: x86_64
* **hw.gpu**: NVIDIA GeForce RTX 3050
* **hw.gpu.arch**: nvidia
* **hw.memory.gb**: 15.9
* **os.arch**: x86_64
* **os.productname**: Windows 6.2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.6.3
* **windows.tabletmode**: false

**Comment by rgriebl** [comment]
You are running Windows 8 which is not supported by BrickStore (Win 10 18.09 is the minimum).
Older versions of BrickStore did not enforce this minimum, but this led to very hard to debug problems: see #846

**Comment by teddywsb** [comment]
I am running windows 11 not windows 8

![image](https://github.com/user-attachments/assets/63e9457a-ab17-4bed-a9d1-3f936312fbec)

**Comment by rgriebl** [comment]
Now that's weird ... it "identifies" as `Windows 6.2` which is the internal Microsoft version number for Win 8. Let me check on my Win 11 machine...

**Comment by teddywsb** [comment]
Thanks for tips. I do not know why I have marked "Windows 8 compatibility mode"

**Comment by teddywsb** [comment]
Thanks for tips. I do not know why I have marked "Windows 8 compatibility mode"
