### ISSUE TITLE
Light Theme does not work

### ISSUE THREAD

**Issue by sbrunswig** [rgriebl/brickstore#926]
**Describe the bug**
After updating to version 2024.11.1, light theme no longer works.

**To Reproduce**
1. Go to extras
2. Go to settings
3. Go to interface
4. Change theme to light

**Expected behavior**
Light Theme

**Screenshots**

**System information**

brickstore.edition: desktop
brickstore.ldraw: 26 Nov 2024 16:40:02 -0600
brickstore.locale: en
build.arch: x86_64
build.compiler: Microsoft Visual-C++2019 (194234433)
build.date: 2024-11-25T22:51:25.000
build.host: fv-az1347-898
build.number: 1305
build.qt.version: 6.8.0
hw.cpu: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
hw.cpu.arch: x86_64
hw.gpu: Intel(R) Iris(R) Xe Graphics
hw.gpu.arch: intel
hw.memory.gb: 15.6
os.arch: x86_64
os.productname: Windows 11 Version 23H2
qt.debug: false
qt.platformname: windows
qt.version: 6.8.0
windows.tabletmode: false

**Additional context**
You can also attach BSX files, but GitHub only accepts these if added to a ZIP file first.

**Comment by sbrunswig** [comment]
Yep that fixed it, just so you are aware the light theme does not over ride windows dark mode as it did in the previous version of brickstore

**Comment by rgriebl** [comment]
Yes - that was an oversight on my part, when I switched to a different light theme on Windows 11 because of graphical glitches. Will be fixed in the next release
