### ISSUE TITLE
Update database not working

### ISSUE THREAD

**Issue by 77JR** [rgriebl/brickstore#927]
**Describe the bug**
When opening Brickstore it loads and says updating the bricklink database, then a message saying already up to date.
But at the bottom it says using a datbase that was generated 6 days ago.

**To Reproduce**
1. Go to '...' Open Brickstore
2. Click on '....' Update database

**Expected behavior**
I expected the database to update after opening. If it doesn't then I normally manually click the update database. But doing this it tells me it is already up to date. But says I am using one from 6 days ago.

**Screenshots**
![image](https://github.com/user-attachments/assets/1fcfe5c5-7af9-43c3-86c9-3870db102a95)
![image](https://github.com/user-attachments/assets/4cd63fbf-2bf5-483b-be80-e5932676da4e)

**System information**
Please tell us which system you are running on and which BrickStore version you are using.
In BrickStore, just open `Help` > `System information...`, Click `Copy to clipboard` and then paste  here.
### BrickStore 2024.11.1 (build: 1305)

* **brickstore.edition**: desktop
* **brickstore.ldraw**: 02 Dec 2024 10:23:08 +0000
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (194234433)
* **build.date**: 2024-11-25T22:51:25.000
* **build.host**: fv-az1347-898
* **build.number**: 1305
* **build.qt.version**: 6.8.0
* **hw.cpu**: AMD Ryzen 5 4500U with Radeon Graphics
* **hw.cpu.arch**: x86_64
* **hw.gpu**: AMD Radeon(TM) Graphics
* **hw.gpu.arch**: amd
* **hw.memory.gb**: 7.4
* **os.arch**: x86_64
* **os.productname**: Windows 11 Version 23H2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.8.0
* **windows.tabletmode**: false

**Additional context**
You can also attach BSX files, but GitHub only accepts these if added to a ZIP file first.

**Comment by rgriebl** [comment]
The problem is part 14769pb716 that was added to BrickLink on Nov 28th: https://www.bricklink.com/message.asp?ID=1497175
As soon as the problem is fixed on BrickLink, BrickStore's database re-generation will start working again.

**Comment by 77JR** [comment]
Thank you!! Working again

**Comment by 77JR** [comment]
Thank you. They have sorted the part issue. All working again
