### ISSUE TITLE
Part Out used sets as used parts

### ISSUE THREAD

**Issue by AllesMeins** [rgriebl/brickstore#93]
When parting out a used sets the resulting parts should be also marked as "used". Currently when parting out a used set all the parts get added as "new".

**Comment by uvt203** [comment]
The old programme has always parted out sets as new - and this one does too. Simple mark all lines - right hand click and change to used.

**Comment by AllesMeins** [comment]
> The old programme has always parted out sets as new - and this one does too. Simple mark all lines - right hand click and change to used.

Thanks, I get that it is possible to fix it - but why? I can't see any use-case where you have a used set in your inventory, take it apart and magically all parts transform into new ones...

**Comment by uvt203** [comment]
Sorry but you don't get the point. The programme be default parts out sets as new. In case you need to part out a used set you will have to change all parts to used after parting out. I agree the other way around would never be a valid option.

**Comment by paramecie** [comment]
Another solution would be to have a default Condition for Inventory AND part out, like here:

![image](https://user-images.githubusercontent.com/32078594/104850645-857eb100-58f0-11eb-841a-b554712a112b.png)

**Comment by AllesMeins** [comment]
> Sorry but you don't get the point. The programme be default parts out sets as new. In case you need to part out a used set you will have to change all parts to used after parting out. I agree the other way around would never be a valid option.

Yes, I get that - but the question is "why does it do this by default". I don't know the internal workings but it is probably a comparably small change to do a check "is this set used" and than query the database for used/new parts accordingly.

**Comment by paramecie** [comment]
Whatever it was, who cares. But people working on Used exclusively - do have to make some extra efforts.
CTRL+A or select the added lots, then right click, condition, Used... and every time.

A simple default condition for part out, but both in "Import Inventory" and "Part out item" would be great, IMO...

**Comment by paramecie** [comment]
Yes!

**Comment by paramecie** [comment]
Confirmed: it's working properly on Build 204:
https://github.com/rgriebl/brickstore/actions/runs/493640605

**Comment by paramecie** [comment]
Part out of a Used set works, but we don't have an option as above. Maybe one of these days?

**Comment by AllesMeins** [comment]
Great, thanks!
