### ISSUE TITLE
Known colors doesn't work properly

### ISSUE THREAD

**Issue by uvt203** [rgriebl/brickstore#94]
Version 21.1.4 on MACOS 10.13.6 in window add item when using known colors, most - but not all known colors - show in the color window. 
After selecting another item to add to the file, the known color field show all colors afterwards for the next couple of items. Suddenly without letting me know when and why it shows again some but not all known colors of one of the following items I am to enter to the file.

**Comment by paramecie** [comment]
If I remember well, Robert wrote it was a prototype feature...

**Comment by rgriebl** [comment]
There's no API to access the known colors list as shown on the BL web site. I try to work around that shortcoming right now by using the "item+color" to "lego partscode" mapping database that is downloadable from BL, but that doesn't have all the existing combinations.
I tried to start a dialog with the BL admins about API access in general, but haven't had much luck getting responses yet (back in the old days, I could have just told Dan what I need ;) ).

**Comment by paramecie** [comment]
Mmmmmh - you've got to wait for century expecting them for any change...
Why not "simply" downloading the PGuide page and parsing it?
I know... parsing won't be reliable and will need some update every once in a while, but maybe it's better than nothing?

**Comment by rgriebl** [comment]
I have discussed that with the BL devs and they are looking into giving me access to this information.
Until then, I'll leave the implementation as is ... screen-scraping the HTML pages is not an option.

**Comment by paramecie** [comment]
> screen-scraping the HTML pages is not an option.

Understand what it implies - however I parse the known colors in the catalog page for maybe 10 years with no problem ;-)
As you wish.
