### ISSUE TITLE
Part Out Function Causes Crash, Restart

### ISSUE THREAD

**Issue by legobanker** [rgriebl/brickstore#95]
Hello all,

Is anyone having issues with the "part out" function?  I try to part out a set, say 10 copies of #40358.  It won't part out 10 copies of the set in a new window (it only does it as one set).  The other issue is when you part out the set(s) and have BS overwrite the existing entry (the original set) it parts out the correct quantity, but then crashes and reboots?

**Comment by paramecie** [comment]
It's fixed. Let me find the build...

**Comment by paramecie** [comment]
It's here:
https://github.com/rgriebl/brickstore/actions/runs/489478507

It's a .mid file, that's a zip. Unzip and run.

**Comment by legobanker** [comment]
Perfect!  Problem solved.  Thanks for your help!
