### ISSUE TITLE
Part out function into new window not working

### ISSUE THREAD

**Issue by legobanker** [rgriebl/brickstore#96]
Here's what I have:

Open new set/kit
Add 10 as quantity
![image](https://user-images.githubusercontent.com/77599267/104869595-6e51ba80-5914-11eb-9af2-35beb238502d.png)

Get the following message:
![image](https://user-images.githubusercontent.com/77599267/104869635-81fd2100-5914-11eb-8cca-71044525f341.png)

Select "NO" to part out into new window
Only parts out "1" copy of the set, not 10

Is this a default setting I need to change?

**Comment by paramecie** [comment]
I confirm. Good catch!
It's a bug, as parting those out in the same document gives the proper amount.
For now, CTRL+A, CTRL+* to multiply by the number of sets...

**Comment by legobanker** [comment]
:-)  I can work around this issue, since #95 and #88 fixed the part out (in the same window) error.  It's one of those functions I was used to in BrickStock.  Thanks again!

**Comment by rgriebl** [comment]
Fixed with 085c7aeb8903d1458321cb6ef863b2a281548667

**Comment by legobanker** [comment]
Question:  is this an update to the software, or something I need to do to make it work ;-)  I am not sure about that spaghetti code lol

**Comment by paramecie** [comment]
It'll be included in next release.

However it may be already on this build (didn't have time to check):
https://github.com/rgriebl/brickstore/actions/runs/493640605

Just download the .mid file, unzip it, run the install.

**Comment by paramecie** [comment]
Confirmed: it's working properly on Build 204:
https://github.com/rgriebl/brickstore/actions/runs/493640605

**Comment by legobanker** [comment]
Confirmed as well.  Perfect :-)
