### ISSUE TITLE
Printing as "PDF"

### ISSUE THREAD

**Issue by legobanker** [rgriebl/brickstore#97]
I tried the "print to PDF" function and got the following error:

![image](https://user-images.githubusercontent.com/77599267/104874755-a90e1f80-5921-11eb-8ecd-11715e241545.png)

It prompted for the "Standard Print Template":

![image](https://user-images.githubusercontent.com/77599267/104874828-d5c23700-5921-11eb-9f32-c71d9b3e318f.png)

Once clicking ok populates the above error message.

**Comment by paramecie** [comment]
Must be related to the very recent JS way to make templates... It's just brand new ;-)

**Comment by rgriebl** [comment]
Yeah - I know exactly why this error would show, but then again the Windows installation shouldn't be able to trigger the conditions. I'll have to check this on another Windows machine here.
