### ISSUE TITLE
Export as "BrickLink Mass Update XML to Clipboard"

### ISSUE THREAD

**Issue by legobanker** [rgriebl/brickstore#98]
When attempting to perform a mass update (based on these options: Stock Room (A/B/C) or Reserved item (for a buyer), the XML code isn't populating.

Example of MASS update.  It appears BS will allow for quantity and price, but will not update: Sale, Stockroom or Reserved fields.  I downloaded my store inventory and tried to update all of these fields.  

![image](https://user-images.githubusercontent.com/77599267/104875303-fb9c0b80-5922-11eb-9779-f2b4b7b4b5cb.png)

The XML code shows up as follows:

![image](https://user-images.githubusercontent.com/77599267/104875366-225a4200-5923-11eb-9398-b32bf55ab8be.png)

**Comment by legobanker** [comment]
It appears this function is working now:

![image](https://user-images.githubusercontent.com/77599267/104923075-8bfd3f00-5969-11eb-9a35-6cf60cf56671.png)

Uploading inventory to BrickLink (via stockroom option)

![image](https://user-images.githubusercontent.com/77599267/104923156-acc59480-5969-11eb-8937-99c2497aca24.png)

Adding Inventory as reserved:

![image](https://user-images.githubusercontent.com/77599267/104923254-cebf1700-5969-11eb-9e67-d39720038dec.png)

BrickLink confirmation:

![image](https://user-images.githubusercontent.com/77599267/104923325-e5656e00-5969-11eb-8f84-ce212d83c57f.png)

I'm *assuming* by default, that you cannot reserve and place those items in a stock room, as they automatically are held for the buyer.

**Comment by legobanker** [comment]
Correction:  It still wont allow updates (using an existing file) to update BrickLink inventory: ie...using master store inventory file to update stockroom, reserve status.  It will still let you update Price and Quantity.  It's almost as if the other options: reserve, stockroom, sale won't work in combination with the others (if that makes sense).  Happily enjoying this testing 💯

**Comment by paramecie** [comment]
Related to #68 ?

**Comment by legobanker** [comment]
yeah, just like that

**Comment by paramecie** [comment]
See #43 also... it's an old snake we're chasing here ;-)

**Comment by legobanker** [comment]
Looks like it lol

**Comment by rgriebl** [comment]
Please see the latest comments on #68
