### ISSUE TITLE
Build 204, BrickStore database

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#99]
Just installed build 204.

1) It automatically updated the database, fine! But the max age was set up to 7 days, and the previous base was really recent. Is it normal?

2) The age of the database is shown as 3 hours, a few seconds after downloading it. Is it a question of timezone, or is it the age of the DB itself and not the dowload time? Maybe it's a bit confusing - but it's not a major point ;-)

![image](https://user-images.githubusercontent.com/32078594/104941809-d6a3a900-59b3-11eb-8d80-7812a46af097.png)

**Comment by legobanker** [comment]
I'm wondering the same thing.  Updated to the latest build and I did a manual DB update.  Maybe it's the last time the DB on BL was updated?  The DB update I just did was the same size as earlier this morning (6,153 or something like that).

![image](https://user-images.githubusercontent.com/77599267/104943041-2ddd5580-5983-11eb-8018-d0f1212fda5a.png)

**Comment by paramecie** [comment]
> Maybe it's the last time the DB on BL was updated?

Probably. That should/could be explained, maybe like:

Last Database download: 10 seconds ago
Last Database change: 3 hours ago

![image](https://user-images.githubusercontent.com/32078594/104943640-57fc3b00-59b6-11eb-941c-f92566a6b80c.png)

**Comment by legobanker** [comment]
Yeah, just a notification that some sort of DB update was done from BL's end.  I'll keep trying it out throughout the day and see if any thing changes (ie. size of DB update).

**Comment by paramecie** [comment]
If it's based on BrickLink it'll update every day on 6 am Paris time, that's about midnight USA East time.

**Comment by rgriebl** [comment]
This was the first download to get the new DB version which has a "generated at" date field. From now on, it will update every X  days. The new age of the DB is the *real* one (when it was generated on my server). Before it was just the timestamp of when you downloaded it last.

And it's not been generated at 6am, because I forced a regeneration to get the date field in.

**Comment by paramecie** [comment]
Maybe shorter: "Database generated: 10 hours ago"? 

![image](https://user-images.githubusercontent.com/32078594/104970464-d7f0c800-59eb-11eb-96bf-91d2fc311c49.png)

**Comment by paramecie** [comment]
Even shorter, no ":" 

BrickStore version **2222.01.02 (build 999)**     -     Database generated **10 hours ago**


![image](https://user-images.githubusercontent.com/32078594/104970535-1dad9080-59ec-11eb-8a4a-81bacdb97cfb.png)
